objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GP_Evento_General_Batch__c.object
<CustomObject>
    <fields>
        <fullName>ID_Suscriptor__c</fullName>
        <label>ID Suscriptor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Titular__c</fullName>
        <label>ID Titular</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JsonAtribute__c</fullName>
        <label>JsonAtribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GP Evento General Batch</label>
    <nameField>
        <label>GP Evento General Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Eventos General Batch</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GP_Socio__c.object
<CustomObject>
    <description>Socio Club Personal - Gestor de Puntos</description>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo_total__c</fullName>
        <label>Saldo total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GP Acumulador</label>
    <nameField>
        <label>Nombre de Socio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Acumuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GPEventoGeneralBatchTriggerTest.cls
@isTest
Global with sharing class GPEventoGeneralBatchTriggerTest {
    @isTest
    static void insertarGP_Evento_General_Batch() {
        List<Object> listMapAttr = new List<Object>();

        Map<String, Object> mapAux = new Map<String, Object>();
        mapAux.put('NombreDelAtributo', 'Tiene Canje');
        mapAux.put('TipoDeAtributo', 'Boolean');
        mapAux.put('Valor', True);
        listMapAttr.add(mapAux);

        mapAux = new Map<String, Object>();
        mapAux.put('NombreDelAtributo', 'Tipo De Cliente');
        mapAux.put('TipoDeAtributo', 'String');
        mapAux.put('Valor', 'DNI');
        listMapAttr.add(mapAux);

        mapAux = new Map<String, Object>();
        mapAux.put('NombreDelAtributo', 'Millas');
        mapAux.put('TipoDeAtributo', 'Integer');
        mapAux.put('Valor', 501);
        listMapAttr.add(mapAux);

        Map<String, Object> jsonAttr = new Map<String, Object>();
        jsonAttr.put('listaDeAtributos', listMapAttr);
        String jsonAttrSerialized = JSON.serialize(jsonAttr);

        //Cuenta
        Account cuenta = new Account();
        cuenta.name = 'cuenta1';
        cuenta.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        cuenta.AccountIntegrationId__c = '111111111111';
        //cuenta.vlocity_cmt__PrimaryContactId__c = pc.Id;
        insert cuenta;

        GP_Socio__c acum = new GP_Socio__c();
        acum.Activo__c = true;
        acum.Cuenta__c = cuenta.Id;
        acum.Saldo_total__c = 100;
        insert acum;

        GP_Evento_General_Batch__c evGralBatch = new GP_Evento_General_Batch__c();
        evGralBatch.ID_Suscriptor__c = '0';
        evGralBatch.ID_Titular__c = acum.Cuenta__c;
        evGralBatch.Tipo_de_evento__c = 'Canje por LanPass';
        evGralBatch.JsonAtribute__c = jsonAttrSerialized;

        insert evGralBatch;
    }
}