objects/Account.object
<CustomObject>
    <fields>
        <fullName>ClubMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>#MarketingTeam #Sprint08 
Defines if the account is a Club Personal member</description>
        <label>Club Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <label>DocumentNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>CUIT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PersonalClubCategory__c</fullName>
        <label>Personal Club Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Classic</fullName>
                </value>
                <value>
                    <fullName>Premium/Black</fullName>
                </value>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>Classic:Premium/Black:TRIAL</fullName>
                    <isActive>false</isActive>
                    <label>Classic:Premium/Black:TRIAL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <label>DocumentNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DocumentTypes</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/DocumentTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DNI</fullName>
        <default>true</default>
        <label>DNI</label>
    </customValue>
    <customValue>
        <fullName>CUIL</fullName>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Libreta de Enrolamiento</label>
    </customValue>
    <customValue>
        <fullName>LCV</fullName>
        <label>Libreta Civica</label>
    </customValue>
    <customValue>
        <fullName>PAS</fullName>
        <label>Pasaporte</label>
    </customValue>
    <customValue>
        <fullName>CID</fullName>
        <label>Cedula de Identidad</label>
    </customValue>
    <customValue>
        <fullName>CUIT</fullName>
        <isActive>false</isActive>
        <label>CUIT</label>
    </customValue>
    <description>DocumentTypes</description>
    <masterLabel>DocumentTypes</masterLabel>
</GlobalValueSet>

classes/Mkt_CPDataManagerTest.cls
@isTest
public class Mkt_CPDataManagerTest {

	static testmethod void invoquedMethodTest(){

		Contact contact = new Contact(FirstName = 'firstName', LastName = 'lastName', DocumentType__c = 'DNI', DocumentNumber__c = '44553333', Email = 'test@yopmail.com');
		insert contact;
		
		Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
	    Id businessRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Business' AND SobjectType = 'Account' LIMIT 1].Id;
	
	    Account ac = new Account (Name='New Test Consumer', RecordTypeId = consumerRecordTypeId, vlocity_cmt__PrimaryContactId__c = contact.Id, ClubMember__c = true, PersonalClubCategory__c = 'Classic');
	    Account ab = new Account (Name='New Test Business', RecordTypeId = businessRecordTypeId, vlocity_cmt__PrimaryContactId__c = contact.Id, ClubMember__c = true, PersonalClubCategory__c = 'Classic');
	    List<Account> accounts = new List<Account>();
	    accounts.add(ac);
	    accounts.add(ab);
		
		insert accounts;
		
	    Mkt_CPDataManager dataManager = new Mkt_CPDataManager();
	    Mkt_clubPersonalTab personalTab = new Mkt_clubPersonalTab();
	    Map<String,Object> inputMap = new Map<String,Object>();
	    Map<String,Object> outputMap = new Map<String,Object>();
	    Map<String,Object> options = new Map<String,Object>();
	    Map<String,Object> altaMap = new Map<String,Object>();
	    List<Map<String,Object>> accList = new List<Map<String,Object>>();
		List<Map<String,Object>> acbList = new List<Map<String,Object>>();
		Map<String,Object> consumer = new Map<String,Object>();
		Map<String,Object> business = new Map<String,Object>();

		consumer.put('Id',ac.Id);
		consumer.put('ClubCategory', 'Alta Reciente');
		accList.add(consumer);
		business.put('Id',ab.Id);
		business.put('ClubCategory', 'Alta Reciente');
		acbList.add(business);

	    inputMap.put('ContextId',ac.Id);
	    altaMap.put('businessAccounts', accList);
	    altaMap.put('consumerAccounts',acbList);
	    inputMap.put('AltaClubPersonal',altaMap);
	    inputMap.put('CPMembershipCancellation',altaMap);

	    Test.startTest();
	    dataManager.invokeMethod('getAccountsCP',inputMap,outputMap,options);
	    dataManager.invokeMethod('getUsersInfo',inputMap,outputMap,options);
	    dataManager.invokeMethod('createMembers',inputMap,outputMap,options);
	    personalTab.invokeMethod('getAccountHeader',inputMap,outputMap,options);
	    dataManager.invokeMethod('deleteMembers',inputMap,outputMap,options);
	    Test.stopTest();
	}
}