objects/Account.object
<CustomObject>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <label>DocumentNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>CUIT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>Field to descript the reason a status had been apply for an asset</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Fraude</fullName>
                </value>
                <value>
                    <fullName>Port-out</fullName>
                </value>
                <value>
                    <fullName>Mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por fraude</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida voluntariamente</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por siniestro</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por Dorma</fullName>
                </value>
                <value>
                    <fullName>Suspend-Operador</fullName>
                </value>
                <value>
                    <fullName>Resume-Operador</fullName>
                </value>
                <value>
                    <fullName>Baja-PortOut</fullName>
                </value>
                <value>
                    <fullName>Baja-Baja</fullName>
                </value>
                <value>
                    <fullName>Siniestro/Extravio</fullName>
                </value>
                <value>
                    <fullName>Administrativo</fullName>
                </value>
                <value>
                    <fullName>Suspend-PortOut</fullName>
                </value>
                <value>
                    <fullName>PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LineNumber__c</fullName>
        <description>Vlocity line number copied from the order which assists in sequencing the assets and organizing them into a hierarchy.</description>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SuspensionsAndRatings_test.cls
@IsTest
public class SuspensionsAndRatings_test {
	
    @IsTest static void invoke_getHistoric(){
    	String methodName = 'getHistoric';

    	Map<String, Object> input = new Map<String, Object>();
    	Map<String, Object> outMap = new Map<String, Object>();
    	Map<String, Object> options = new Map<String, Object>();
		
    	SuspensionsAndRatings suspAndReco = new SuspensionsAndRatings();
        
        Id consumerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        Account acc = new Account(RecordTypeId = consumerRecordTypeId, Name = 'Sample Account', AccountNumber = '1234', DocumentType__c = 'DNI', DocumentNumber__c = '12345678');
        insert acc;
        
        Asset asset = new Asset(Name = 'asset1', vlocity_cmt__LineNumber__c = '1234567890', AccountId = acc.Id, Sub_Status__c = 'Siniestro');
        insert asset;
        
        Transaction_History__c transHist = new Transaction_History__c(Account__c = acc.Id, Asset__c =asset.Id);
        insert transHist;
        
        input.put('assetId',asset.Id);
        input.put('accountId',acc.Id);
        input.put('processTransaction','Todos'); 
        input.put('motiveTransaction','Siniestro');
     
    
    	Test.startTest();
    	suspAndReco.invokeMethod(methodName, input, outMap, options);
		Test.stopTest();
        
        system.assertNotEquals(null,outMap.get('Result'));
    }
}