objects/Account.object
<CustomObject>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>#Marketing #Sprint15 Atributo de mayor ponderación aplicado a la cuenta que se visualizará en V360.</description>
        <label>Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <description>#Sprint16 #Marketing Account segment attributes</description>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Socio Club</fullName>
                </value>
                <value>
                    <fullName>Estratégico</fullName>
                </value>
                <value>
                    <fullName>Menor</fullName>
                </value>
                <value>
                    <fullName>Jubilado</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AttributesWeighing__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>#Sprint16 #Marketing Tabla de ponderación de atributos para Account y Contact</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>Attribute Name</description>
        <label>Attribute</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Salesforce Object</description>
        <label>Object</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weighing__c</fullName>
        <description>Attribute weighing</description>
        <label>Weighing</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ponderación de Atributos</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <description>#Sprint16 #Marketing Contact Attributes</description>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Prensa</fullName>
                </value>
                <value>
                    <fullName>Jubilado</fullName>
                </value>
                <value>
                    <fullName>Plan Social</fullName>
                </value>
                <value>
                    <fullName>Empleado Grupo</fullName>
                </value>
                <value>
                    <fullName>Ex Empleado Grupo</fullName>
                </value>
                <value>
                    <fullName>No Vidente</fullName>
                </value>
                <value>
                    <fullName>Hipoacúsico</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Menor</fullName>
                </value>
                <value>
                    <fullName>Estratégico</fullName>
                </value>
                <value>
                    <fullName>Socio Club</fullName>
                </value>
                <value>
                    <fullName>Atributo Z</fullName>
                </value>
                <value>
                    <fullName>Atributo B</fullName>
                </value>
                <value>
                    <fullName>aaaaaa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AttributesWeighingController.cls
public class AttributesWeighingController {
	
	public AttributesWeighing__c record {get;set;}
    public List<SelectOption> objectsList{get;set;}
    public List<AttributesWeighing__c> attributesList{get;set;}
    public String accountString = Label.Account;
    public String contactString = label.Contact;
    
    public AttributesWeighingController(){

        attributesList = new List<AttributesWeighing__c>();
    	objectsList = new List<SelectOption>();
    	record = new AttributesWeighing__c();

    	objectsList.add(new selectoption(accountString,accountString));
    	objectsList.add(new selectoption(contactString,contactString));
    	record.object__c = accountString;
    	attributesList = fillAttributesList(record.object__c);
   	}

    
   	public static List<AttributesWeighing__c> fillAttributesList(String inputObject){

   		List<String> schemaAttributes = new List<String>();
        List<AttributesWeighing__c> weighingList = new List<AttributesWeighing__c>();
   		Schema.DescribeFieldResult fieldResult;
        if(inputObject== Label.Account){
        	fieldResult = Account.Attributes__c.getDescribe();
        }
        if(inputObject == Label.Contact){
        	fieldResult = Contact.Attributes__c.getDescribe();
        }
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			String aux = pickListVal.getLabel();
			schemaAttributes.add(aux);
		}
		weighingList = [SELECT Id, Name, object__c, attribute__c, weighing__c
		 			      FROM AttributesWeighing__c
		 				 WHERE Attribute__c IN :schemaAttributes
		 				   AND object__c =:inputObject ORDER BY weighing__c DESC];
        
        if(schemaAttributes.size()!=weighingList.size()){
            //If the Multipicklist has a new value which is not into the custom settings
            for(String schema : schemaAttributes){
                Boolean exist = false;
                for(AttributesWeighing__c attribute : weighingList){
                    if(attribute.attribute__c == schema){
                        exist = true;
                        break;
                    }
                }
                if(!exist){
                    AttributesWeighing__c newRecord = new AttributesWeighing__c();
                    newRecord.Name = inputObject + '_' +schema;
                    newRecord.Object__c = inputObject;
                    newRecord.Attribute__c = schema;
                    newRecord.Weighing__c = 0;
                    weighingList.add(newRecord);
                }
            }
        }

        return weighingList;
    }

    public PageReference refillAttributesList(){
    	attributesList = new List<AttributesWeighing__c>();
        attributesList = fillAttributesList(record.object__c);
    	return null;
    }

    public Pagereference cancel(){
    	
        return Page.attributesLanding;
    }

    public Pagereference save(){
    	upsert attributesList;
    	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.confirm,Label.WeighingSave));
    	fillAttributesList(record.object__c);
    	return null;
    }
}