objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/GP_Saldo_por_vencimiento__c.object
<CustomObject>
    <description>Saldos de puntos según vencimiento - Gestor de Puntos</description>
    <fields>
        <fullName>Cuenta__c</fullName>
        <formula>Socio__r.Cuenta__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cuenta</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Puntos__c</fullName>
        <label>Puntos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socio__c</fullName>
        <label>Socio</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipLabel>GP Saldos por vencimiento</relationshipLabel>
        <relationshipName>GP_Saldos_por_vencimiento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vencimiento__c</fullName>
        <label>Vencimiento</label>
        <type>Date</type>
    </fields>
    <label>GP Saldo por vencimiento</label>
    <nameField>
        <label>Saldo por vencimiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Saldos por vencimiento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Socio__c.object
<CustomObject>
    <description>Socio Club Personal - Gestor de Puntos</description>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo_total__c</fullName>
        <label>Saldo total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GP Acumulador</label>
    <nameField>
        <label>Nombre de Socio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Acumuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GP_BatchSaldosVencidosTest.cls
@isTest
public with sharing class GP_BatchSaldosVencidosTest {

    static testMethod void testBatch() {
        Account a = new Account();
        a.name = 'cuenta1';
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        a.AccountIntegrationId__c = '111111111111';
        insert a;

        GP_Socio__c acum = new GP_Socio__c();
        acum.Cuenta__c = a.Id;
        acum.Saldo_total__c = 1000;
        insert acum;

        List<GP_Saldo_por_vencimiento__c> listSaldos = new List<GP_Saldo_por_vencimiento__c>();
        for(integer i = 0; i<10; i++) {
            GP_Saldo_por_vencimiento__c sv = new GP_Saldo_por_vencimiento__c();
            sv.Puntos__c = 100;
            sv.Socio__c = acum.Id;
            sv.Vencimiento__c = Date.Today().addDays((-4) + i); 
            //Los primeros 4 saldos deben eliminarse por estar vencidos.
            listSaldos.add(sv);
        }
        insert listSaldos;

        Test.StartTest();
        GP_BatchSaldosVencidos batchSaldosVencidos = new GP_BatchSaldosVencidos();
        ID batchprocessid = Database.executeBatch(batchSaldosVencidos);
        Test.StopTest();

        Integer cnt = [Select Count() From GP_Saldo_por_vencimiento__c];
        Double puntosSocio = [Select Saldo_total__c From GP_Socio__c Where Id = :acum.Id].Saldo_total__c;
        System.assertEquals(6, cnt);
        System.assertEquals(600, puntosSocio);
    }
}