objects/Account.object
<CustomObject>
    <fields>
        <fullName>BillingAddressStore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BillingAddressStore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Day__c</fullName>
        <description>Campo agregado para almacenar el ciclo de  facturación de la cuenta</description>
        <label>Billing Day</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClubMember__c</fullName>
        <defaultValue>false</defaultValue>
        <description>#MarketingTeam #Sprint08 
Defines if the account is a Club Personal member</description>
        <label>Club Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CuitNumber__c</fullName>
        <description>Campo para registrar el numero de Cuit</description>
        <label>CuitNumber</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CuitType__c</fullName>
        <description>Valid if cuit starts with 2 or 3</description>
        <formula>IF(  TEXT(DocumentType__c )= &apos;CUIT&apos; &amp;&amp;  BEGINS( DocumentNumber__c , &apos;3&apos;), &apos;3X&apos;, &apos;2X&apos;)</formula>
        <label>CuitType</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dunning__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mora</description>
        <label>Dunning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonalClubCategory__c</fullName>
        <label>Personal Club Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Classic</fullName>
                </value>
                <value>
                    <fullName>Premium/Black</fullName>
                </value>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>Classic:Premium/Black:TRIAL</fullName>
                    <isActive>false</isActive>
                    <label>Classic:Premium/Black:TRIAL</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PersonalClubPoints__c</fullName>
        <label>PersonalClubPoints</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShippingAddressStore__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ShippingAddressStore</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SocialPlan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>#MarketingTeam #Sprint08
Indicates if the account receives a social plan.</description>
        <label>Social Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserLevel__c</fullName>
        <label>User Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Mid</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValidatedBillingAddress__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Validated Billing Address</description>
        <inlineHelpText>Validated Billing Address</inlineHelpText>
        <label>Validated Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ValidatedShippingAddress__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Validated Shipping Address</description>
        <inlineHelpText>Validated Shipping Address</inlineHelpText>
        <label>Validated Shipping Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__BillDeliveryMethod__c</fullName>
        <label>Bill Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Paper Billing</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ContactPreferences__c</fullName>
        <description>The preferred method (or methods) of communications to the parties of this account such as mail, email or phone.</description>
        <label>Contact Preferences</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                    <label>Teléfono</label>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                    <label>Correo electrónico</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <description>The status of the customer&apos;s account such as active, inactive, suspended, pending or expired.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Dunning__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo Temporal</description>
        <label>Dunning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Inactivo</fullName>
                </value>
                <value>
                    <fullName>Potencial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensed Agent</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Associate Agent</fullName>
                </value>
                <value>
                    <fullName>Managing Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EmailsSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CantidadDeEmails__c</fullName>
        <label>Cantidad de Emails</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Emails Setting</label>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute value data.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ParentItemId__c</fullName>
        <label>ParentItemId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ServiceAccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account that identifies the service location or subscriber that is the user of the service.</description>
        <label>Service Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Products (Service Account)</relationshipLabel>
        <relationshipName>ServiceAccountOrderItems</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Gemalto</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>TELECOM PERSONAL</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>FixedLine</fullName>
                    <label>Línea Fija</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <label>Línea Móvil</label>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Servicio Valor Agregado</fullName>
                </value>
                <value>
                    <fullName>Plan Prepago</fullName>
                </value>
                <value>
                    <fullName>Plan Pospago</fullName>
                </value>
                <value>
                    <fullName>Plan Hibrido</fullName>
                </value>
                <value>
                    <fullName>Servicio GSM</fullName>
                </value>
                <value>
                    <fullName>Numeros Amigos</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Control Cuota Datos</fullName>
                </value>
                <value>
                    <fullName>Simcard</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Credito Adicional</fullName>
                </value>
                <value>
                    <fullName>Roaming</fullName>
                </value>
                <value>
                    <fullName>Dispositivo</fullName>
                </value>
                <value>
                    <fullName>Prestamo</fullName>
                </value>
                <value>
                    <fullName>Proteccion</fullName>
                </value>
                <value>
                    <fullName>Captura</fullName>
                </value>
                <value>
                    <fullName>Pack LDI</fullName>
                </value>
                <value>
                    <fullName>Pack Roaming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SaleManager.cls
global with sharing class SaleManager implements vlocity_cmt.VlocityOpenInterface
{
    static final String internetFamily = 'Internet';
    static final String voiceFamily = 'Fixed';
    
    global SaleManager() {}

    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        try
        {
            if (methodName.equals('GetOrderValidations')) {
              GetOrderValidations(inputMap, outMap, options);
            }

            if (methodName.equals('ReserveProducts')) {
              ReserveProducts(inputMap, outMap, options);
            }

            if (methodName.equals('GetCustomSetting')) {
              GetCustomSetting(inputMap, outMap, options);
            }

            if (methodName.equals('GetCustomSettingAtribute')) {
              GetCustomSettingAtribute(inputMap, outMap, options);
            }

            if (methodName.equals('AssingProductsToServiceAccount')) {
              AssingProductsToServiceAccount(inputMap, outMap, options);
            }

            if (methodName.equals('ValidateEmailSettings')) {
              ValidateEmailSettings(inputMap, outMap, options);
            }

            if (methodName.equals('SetStockMovementCodes')) {
              SetStockMovementCodes(inputMap, outMap, options);
            }

            if (methodName.equals('SendPickUpInformationEmail')) {
              SendPickUpInformationEmail(inputMap, outMap, options);
            }

            if(methodName.equals('GetAmountInfoRefillSOS')) {
                GetAmountInfoRefillSOS(inputMap, outMap, options);
            }

            if (methodName.equals('GetDeliveryMethodOptions')) {
                GetDeliveryMethodOptions(inputMap, outMap, options);
            }

            if (methodName.equals('GetNewGuid')) {
                GetNewGuid(inputMap, outMap, options);
            }

            result = false;
        }
        catch(Exception e)
        {
            System.debug('SaleManager:invokeMethod -> exception: ' + e);
            result = false;
        }
        return result;
    }

    void GetNewGuid(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String,Object> options){
        String idUnico = GuidUtil.NewGuid();
        outMap.put('X-Consumer-Transaction-ID', idUnico);
    }

    Boolean ValidateServicePlanExistence(String orderId) {
      List<OrderItem> items = [select Product2.Name from OrderItem where OrderId = :orderId and (Product2.Family = 'Service Plan' or Product2.Family = :internetFamily or Product2.Family = :voiceFamily)];
      Boolean serviceExists = false ;
      if (items.size() > 0)
        serviceExists = true;
      return serviceExists;
    }

    Boolean ValidateFamilyExistence(String orderId, String family) {
      List<OrderItem> items = [select Product2.Name from OrderItem where OrderId = :orderId and Product2.Family = :family];
      Boolean exists = false;
      if (items.size() > 0)
        exists = true;
      return exists;
    }

    String GetCategoryService(String orderId) {
      String categoryService;
      Boolean bafExists = ValidateFamilyExistence(orderId, internetFamily);
      Boolean voiceExists = ValidateFamilyExistence(orderId, voiceFamily);
      if (!bafExists && !voiceExists)
        categoryService = null;
      else if (bafExists)
        categoryService = internetFamily;
        else categoryService = 'Voz';
      return categoryService;
    }

    Boolean getAppointmentRequired(String idOrder) {
        System.debug('getAppointmentRequired');
        Boolean appointmentRequired = false;
        System.debug('idOrder: ' + idOrder);
        List<OrderItem> items = [SELECT Id, vlocity_cmt__JSONAttribute__c FROM OrderItem WHERE OrderId = :idOrder];
        Integer itemsCount = 0;
        while(!appointmentRequired && itemsCount < items.size())
        {
            if (items[itemsCount].vlocity_cmt__JSONAttribute__c != null)
            {
              Map<String, Object> mapa = (Map<String, Object>) JSON.deserializeUntyped(items[itemsCount].vlocity_cmt__JSONAttribute__c);
              List<Object> characteristics = (List<Object>) mapa.get('CHAR');
              if (characteristics != null)
              {
                Map<String, Object> susceptibleCita = (Map<String, Object>) characteristics[0];
                if(susceptibleCita.get('value__c') == 'Selected')
                {
                    appointmentRequired = true;
                } else {
                    appointmentRequired = false;
                }
              }
            }
            itemsCount++;
        }

        System.debug('appointmentRequired: ' + appointmentRequired);
        //outMap.put('appointmentRequired', appointmentRequired);
        return appointmentRequired;
    }

    public void GetOrderValidations(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String,Object> options) {
        /*
        * ─────────────────────────────────────────────────────────────────────────────────────────────────
        *   SaleManager.GetOrderValidations
        * ─────────────────────────────────────────────────────────────────────────────────────────────────
        * Description:  DEPRECATED - Method to get preliminary validations for delivery method change
        * Date:         2018-06-04
        * Params:       options.orderId
        * Return:       outMap.userChannel,
        *               outMap.hasTangibles
        */
        try {
            ta_sales_UserUtils userUtils = new ta_sales_UserUtils();
            options.put('userId', System.UserInfo.getUserId());
            userUtils.invokeMethod('getUserChannel', null, options, options);

            outMap.put('hasTangibles', taOrderController.ValidateTangibleExistence(String.ValueOf(options.get('orderId'))));
            outMap.put('userChannel', options.get('UserChannel'));
        }
        catch (Exception e) {
            System.debug('Exception Msg: ' + e.getMessage());
            System.debug('Exception Cause: ' + e.getCause());
            System.debug('Exception Stack Trace: ' + e.getStackTraceString());
            throw e;
        }
    }
  
    /*void GenerateJson(Map<String,Object> inputMap, Map<String, Object> outMap){
       String idOrder = (String) inputMap.get('IdOrder');
       List<OrderItem> plansCollection = [select Id, Product2.Name from OrderItem where Product2.ProductCode = 'PTNAC' and OrderId = :idOrder order by Product2.Name];
       List<Map<String, Object>>  plans = new List<Map<String,Object>>();
       List<Map<String, Object>> lines;
       //Empiezan los cambios
       String aux = '';
       for (OrderItem orderItem : plansCollection){
          if (aux != orderItem.Product2.Name){
              Map<String, Object> plan = new Map<String, Object>();
              lines = new List<Map<String,Object>>();
              plan.put('nombre', orderItem.Product2.Name);
              plan.put('isSelected', false);
              plan.put('lineas', lines);
              plans.add(plan);
              aux = orderItem.Product2.Name;
          }
          List<OrderItem> items = [select Product2.Name, Product2.ProductCode from OrderItem where Product2.Family = 'Simcard' and vlocity_cmt__ParentItemId__c = :orderItem.Id];
          for(OrderItem lineItem : items){
                  Map<String, Object> tempMapLine = new Map<String, Object>();
                  tempMapLine.put('isSelected', false);
                  tempMapLine.put('linea', null);
                  tempMapLine.put('validacionLinea', null);
                  tempMapLine.put('NMU', lineItem.Product2.ProductCode);
                  tempMapLine.put('serial', null);
                  tempMapLine.put('validacionSerial', null) ;

                  lines.add(tempMapLine);                                       
              }
        }

       Map<String, Object> principalNode = new Map<String, Object>();
               principalNode.put('lineasReservadas', false);
               principalNode.put('planes', plans);
               principalNode.put('serialesReservados', false); 

       List<Map<String, Object>>  returnList = new List<Map<String,Object>>();

        returnList.add(principalNode);
        outMap.put('options', returnList);
    }*/

    void GetCustomSetting(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        System.debug('GetCustomSetting');
        String csName = (String) options.get('CSName');
        List<Object> csFields = (List<Object>) options.get('CSFields');

        System.debug('csFields= ' + csFields);

        String QueryStr1 = 'SELECT ';
        Map<String,Object> mapField;
        String strField;

        for (Object objField:csFields){
            mapField = (Map<String,Object>) objField;
            strField = (String) mapField.get('field');
            QueryStr1 += strField+ ', ';
        }

        QueryStr1 = QueryStr1.substringBeforeLast(',');
        QueryStr1 +=' FROM ' + csName + ' LIMIT 1';

        System.debug('QueryStr1= ' + QueryStr1);

        List<Object> csValues = Database.query(QueryStr1);

        outMap.put('CSValues', csValues[0]);

    }
    
    void GetCustomSettingAtribute(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        /**
        * ─────────────────────────────────────────────────────────────────────────────────────────────────
        * @description Retrieve the fields listed in CSFields array from the Custom Setting Atribute CSAtribute 
        * in the Custom Setting CSName
        * ──────────────────────────────────────────────────────────────────────────────────────────────────
        * @author   Damian Avrij
        * @date     2018-01-12
        * @param    CSName the Custom Setting need you want to retrieve
        * @param    CSAtribute the CS atribute you want to retrieve
        * @param    CSFields the list of fields you want to retrieve
        * @return   CSValues a map wiht the field values
        */
        System.debug('GetCustomSettingInstance');
        String csName = (String) options.get('CSName');
        String csAtribute = (String) options.get('CSAtribute');
        List<Object> csFields = (List<Object>) options.get('CSFields');

        System.debug('csFields= ' + csFields);

        String QueryStr1 = 'SELECT ';
        Map<String,Object> mapField;
        String strField;

        for (Object objField:csFields){
            mapField = (Map<String,Object>) objField;
            strField = (String) mapField.get('field');
            QueryStr1 += strField+ ', ';
        }

        QueryStr1 = QueryStr1.substringBeforeLast(',');
        QueryStr1 +=' FROM ' + csName + ' WHERE Name =\''+ csAtribute +'\' LIMIT 1';

        System.debug('QueryStr1= ' + QueryStr1);

        List<Object> csValues = Database.query(QueryStr1);

        outMap.put('CSValues', csValues[0]);

    }

    void ReserveProducts(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {
        try
        {
            System.debug('ReserveProducts');
            String orderId = (String) options.get('IdOrder');
            Map<String,String> getPointOfSaleWarehouseResponse = taOrderController.GetPointOfSaleWarehouse(orderId);
            String codPuntoDeVenta = getPointOfSaleWarehouseResponse.get('codPuntoDeVenta');
            String codDeposito = getPointOfSaleWarehouseResponse.get('codDeposito');
            String codAplicacion = '2';

            List<Map<String, Object>>  plans = new List<Map<String,Object>>();
            List<Map<String, Object>>  returnList = new List<Map<String,Object>>();

            Set<Id> oiIds = new Set<Id>();

            Map<String, Object> billingOrder = (Map<String, Object>) inputMap.get('BillingOrder');
            Map<String, List<OrderItem>> itemsByProductName = new Map<String, List<OrderItem>>();
            Map<String, Integer> groupedNmus = new Map<String, Integer>();
            Map<String, Map<String, Object>> nmus = new Map<String, Map<String, Object>>();
            Map<String, Object> principalNode = new Map<String, Object>();
            Map<String, Object> plan = new Map<String, Object>();
            Map<String, String> planNames = new Map<String, String>();
            Map<String, String> itemParents = new Map<String, String>();

            //List<OrderItem> plansCollection = [SELECT Id, Product2.Name FROM OrderItem WHERE Product2.ProductCode = 'FAN_TSEG1' AND OrderId = :orderId ORDER BY Product2.Name];
            //Added By Venkatesh - PFTA-7872
            List<OrderItem> plansCollection = [SELECT Id, Product2.Name FROM OrderItem WHERE Product2.vlocity_cmt__Type__c = 'Plan Prepago' AND OrderId = :orderId ORDER BY Product2.Name];
            
            System.debug('PlansCollection: ' + plansCollection);

            for(OrderItem orderItem : plansCollection){
                oiIds.add(orderItem.Id);
                planNames.put(orderItem.Id, orderItem.Product2.Name);
            }

            //List<OrderItem> items = [select Product2.Name, Product2.ProductCode, Quantity, vlocity_cmt__ParentItemId__c from OrderItem where Product2.Family = 'Simcard' and vlocity_cmt__ParentItemId__c IN :oiIds];
            //List<OrderItem> items = [select Id, Product2.Name, Product2.ProductCode, Quantity, vlocity_cmt__ParentItemId__c from OrderItem where Product2.ProductCode = 'FAN_PSIM_STANDARD' and vlocity_cmt__ParentItemId__c IN :oiIds];
            List<OrderItem> items = [select Id, Product2.Name, Product2.ProductCode, Quantity, vlocity_cmt__ParentItemId__c from OrderItem where Product2.vlocity_cmt__Type__c = 'Simcard' and vlocity_cmt__ParentItemId__c IN :oiIds];
            for(OrderItem item: items){
                //List<OrderItem> children = itemsByProductName.get(item.Product2.Name);
                //if(planNames.contains(items.vlocity_cmt__ParentItemId__c))
                List<OrderItem> children = itemsByProductName.get(planNames.get(item.vlocity_cmt__ParentItemId__c));
                if(children == null){
                    children = new List<OrderItem>();
                }
                children.add(item);
                itemParents.put(item.Product2.Name, item.vlocity_cmt__ParentItemId__c);
                itemsByProductName.put(planNames.get(item.vlocity_cmt__ParentItemId__c), children);
            }

            System.debug('itemsByProductName'+itemsByProductName+'.keySet()'+itemsByProductName.keySet());
            for(String productName: itemsByProductName.keySet()){
                plan = new Map<String, Object>();
                List<Map<String, Object>> lines = new List<Map<String, Object>>();
                for(OrderItem item: (List<OrderItem>)itemsByProductName.get(productName)){
                    Map<String, Object> tempMapLine = new Map<String, Object>();
                    tempMapLine.put('isSelected', false);
                    tempMapLine.put('linea', null);
                    tempMapLine.put('validacionLinea', null);
                    tempMapLine.put('NMU', productName);
                    tempMapLine.put('serial', null);
                    tempMapLine.put('validacionSerial', null);
                    tempMapLine.put('orderItemId', item.Id) ;
                    tempMapLine.put('orderItemParentId', item.vlocity_cmt__ParentItemId__c) ;
                    lines.add(tempMapLine);
                }
                  
                //plan.put('nombre', planNames.get(itemParents.get(productName)));
                plan.put('nombre', productName);
                plan.put('isSelected', false);
                plan.put('lineas', lines);
                plans.add(plan);
                System.debug('Plan'+Plan);
            }

            for(OrderItem item: items){
                Integer i = groupedNmus.get(item.Product2.ProductCode);
                if(i == null){
                    i = 0;
                }
                i += (Integer)item.Quantity;
                groupedNmus.put(item.Product2.ProductCode, i);
            }

            for(String s: groupedNmus.keySet()){
                Map<String, Object> nmu = new Map<String, Object>();
                nmu.put('codNMU', s);
                nmu.put('codDeposito', codDeposito);
                nmu.put('cantidad', groupedNmus.get(s));
                nmus.put(s, nmu);
            }

            System.debug('nmus: ' + nmus);

            /* DA - 6/11/2017: PFTA-6749. Se quita el paso de reserva por NMU de las SIMCards.
            Cuando se realice reserva de otro tipo de producto hay que revisar el código.  
            */
            try
            {
                //PFTA - 10326 - Se envia siempre punto de venta 0
                String idUnicoTransaccion = GuidUtil.NewGuid();
                System.debug('SaleManager:idUnicoTransaccion: ' + idUnicoTransaccion);
                Map<String,Object> response = IFS_S101_reserveOrRelease.reserveOrRelease('R', codAplicacion, orderId, '0', idUnicoTransaccion, nmus);

                String httpResponseCode = (String) response.get('httpStatusCode');
                if (httpResponseCode != '200' && httpResponseCode != '201')
                    throw new FuncException('Error al invocar al servicio de reserva por NMU. ' + response);
            }
            catch(Exception e){}
          
            principalNode.put('lineasReservadas', false);
            principalNode.put('planes', plans);
            principalNode.put('serialesReservados', false);

            returnList.add(principalNode);
            outMap.put('options', returnList[0]);

            System.debug('Fin ReserveProducts' + returnList);
        }
        catch(Exception e){
            System.debug('SaleManager:invokeMethod -> exception: '+e);
        }
    }

    void AssingProductsToServiceAccount(Map<String,Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {
        try
        {
            System.debug('AssingLinesToDiferentUser');
            String orderId = (String) options.get('IdOrder');
            String accountId = (String) options.get('accountId');
            String serviceContactId = (String) options.get('serviceContactId');
            String userPermissionLevel = (String) options.get('userPermissionLevel');

            System.debug('userPermissionLevel: ' + userPermissionLevel);

            RecordType recordType = [SELECT Id from RecordType WHERE Name = 'Service' AND SobjectType = 'Account'];

            Account serviceAccount = [SELECT BillingAddress,BillingAddressStore__c,BillingLatitude,BillingLongitude,BillingPostalCode,
            Billing_Day__c,ClubMember__c,CuitNumber__c,CuitType__c,Dunning__c,vlocity_cmt__BillDeliveryMethod__c,Name,ParentId,PersonalClubCategory__c,
            PersonalClubPoints__c,ShippingAddress,ShippingAddressStore__c,ShippingLatitude,ShippingLongitude,SocialPlan__c,
            ValidatedBillingAddress__c,ValidatedShippingAddress__c,vlocity_cmt__Active__c,vlocity_cmt__ContactPreferences__c,
            vlocity_cmt__Status__c, UserLevel__c FROM Account WHERE Id = :accountId];
            serviceAccount.vlocity_cmt__PrimaryContactId__c = serviceContactId;
            serviceAccount.RecordTypeId = recordType.Id;
            serviceAccount.Id = null;
            serviceAccount.UserLevel__c = (userPermissionLevel <> '') ? userPermissionLevel : 'High';

            System.debug('userPermissionLevel: ' + userPermissionLevel);

            insert serviceAccount;

            List<OrderItem> itemsCollection = [SELECT Id FROM OrderItem WHERE OrderId = :orderId];
            for(OrderItem item : itemsCollection)
            {
                item.vlocity_cmt__ServiceAccountId__c = serviceAccount.Id;
            }
            update itemsCollection;
        }
        catch(Exception e){
            System.debug('SaleManager:invokeMethod -> exception: '+e);
        }
    }

    void ValidateEmailSettings(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        String fieldEmail = (String) options.get('FieldEmail');
        List<Map<String, Object>>  returnList = new List<Map<String,Object>>();
        Map<String, Object> principalNode = new Map<String, Object>();
        Boolean emailDomain = false;
        Boolean emailValidated = true;
        if (String.isBlank(fieldEmail) == false) {
            List<ValidEmailDomain__c> domainList = ValidEmailDomain__c.getall().values();
            String strDomain = fieldEmail.split('@').get(1);
            
            for (ValidEmailDomain__c mydomain : domainList) {
                if (mydomain.Name == '@' + strDomain) {
                    emailDomain = true;
                }
            }
            
            if (emailDomain == true) {
                List<AggregateResult> result  = [SELECT Count(Id) total FROM Contact WHERE Email =:fieldEmail];
                Decimal intExistingEmails = (Decimal) result[0].get('total');
                EmailsSetting__c mhc = EmailsSetting__c.getInstance();
                Decimal maxEmails = mhc.CantidadDeEmails__c;
                if ((intExistingEmails + 1 ) > maxEmails) {
                    emailValidated = false;
                }
            }
            
            principalNode.put('emailMax', emailValidated);
            principalNode.put('emailDomain', emailDomain);
            
            try{
                Map<String, Object> responseNode = IFS_S171_validateEMail.validateEMail(fieldEmail);
                principalNode.put('emailValidation', (String)responseNode.get('CodeEstado'));
                principalNode.put('emailHistoryValidation', fieldEmail);
    
            } catch(Exception ex){
                principalNode.put('emailValidation', 'ERROR');
                principalNode.put('emailHistoryValidation', 'N/A');
                throw ex;
            }
            
        }
        else {
            principalNode.put('emailMax', true);
            principalNode.put('emailDomain', true);
            principalNode.put('emailValidation', 1);
            principalNode.put('emailHistoryValidation', fieldEmail);
        }
        
        returnList.add(principalNode);
        outMap.put('options', returnList[0]);
        
    }
    
    void SetStockMovementCodes(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        String deliveryMethod = (String) options.get('DeliveryMethod');
        String orderId = (String) options.get('IdOrder');
        
        Map<string, Object> response = TaMatrixUtils.getStockMovementOperation('VTAN','ENTREGA', deliveryMethod, 'NOAPLICA');
        String codOperation =  (String) response.get('StockMovementOperation__OperationCode');
        String destinationDepositCode = (String) response.get('StockMovementOperation__DestinationDepositCode');
        
        if(destinationDepositCode == 'VICLIE')
            destinationDepositCode = 'VICLIE0001';
        
        //List<OrderItem> itemsCollection = [SELECT Id, Operation_Code__c, Deposit_Code__c FROM OrderItem WHERE OrderId = :orderId];
        List<OrderItem> itemsCollection = taOrderController.GetOrderSerials(orderId);
        for(OrderItem item : itemsCollection)
        {
            item.Operation_Code__c = codOperation;
            item.Deposit_Code__c = destinationDepositCode;
        }
        update itemsCollection;
    }

    void SendPickUpInformationEmail(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        System.debug('Send PickUp Information Email');
        String orderId = (String) options.get('IdOrder');
        String emailToSend = (String) options.get('EmailToSend');
        
        if (emailToSend != null && emailToSend != '') {
            RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'CrossObject__c' AND DeveloperName = 'EmailToSend'];
            
            CrossObject__c crossObj = new CrossObject__c(Email1__c = emailToSend, RecordTypeId = rt.Id, Picklist1__c = 'Detalles de Pickup', Order__c = orderId);
            insert crossObj;
        }
    }

    void GetAmountInfoRefillSOS(Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        System.debug('GetAmountInfoRefillSOS');
        String idOrder = (String) inputMap.get('IdOrder');
        Map<String,Object> result = new Map<String,Object>();
        System.debug('idOrder: ' + idOrder);
        List<OrderItem> items = [SELECT Id, vlocity_cmt__JSONAttribute__c FROM OrderItem WHERE OrderId = :idOrder];
        Integer itemsCount = 0;
        while(itemsCount < items.size())
        {
            System.debug('vlocity_cmt__JSONAttribute__c: ' + items[itemsCount].vlocity_cmt__JSONAttribute__c);
            if (items[itemsCount].vlocity_cmt__JSONAttribute__c != null)
            {

                result = AssetAttributesUtils.GetJSONAttribute(items[itemsCount].vlocity_cmt__JSONAttribute__c, 'Monto del Prestamo');

            }
            itemsCount++;
        }

        System.debug(result);

        outMap.put('RefillAmount',result);

    }

    void GetDeliveryMethodOptions(Map<String, Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {
        try {
            System.debug('GetDeliveryMethodOptions inputMap: ' + inputMap);
            System.debug('GetDeliveryMethodOptions outMap: ' + outMap);
            System.debug('GetDeliveryMethodOptions options: ' + options);
        }
        catch (Exception e) {
            System.debug('Exception Msg: ' + e.getMessage());
            System.debug('Exception Cause: ' + e.getCause());
            System.debug('Exception Stack Trace: ' + e.getStackTraceString());
            throw e;
        }
    }
}