objects/Account.object
<CustomObject>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <label>DocumentNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>CUIT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <label>DocumentNumber</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DocumentType__c</fullName>
        <label>DocumentType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DocumentTypes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Femenino</fullName>
                </value>
                <value>
                    <fullName>Masculino</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                    <isActive>false</isActive>
                    <label>U</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensed Agent</fullName>
                </value>
                <value>
                    <fullName>Broker</fullName>
                </value>
                <value>
                    <fullName>Associate Agent</fullName>
                </value>
                <value>
                    <fullName>Managing Agent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LinesSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CantidadDeLineas__c</fullName>
        <defaultValue>5</defaultValue>
        <label>Cantidad de Lineas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lines Setting</label>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Gemalto</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>TELECOM PERSONAL</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>FixedLine</fullName>
                    <label>Línea Fija</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <label>Línea Móvil</label>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Servicio Valor Agregado</fullName>
                </value>
                <value>
                    <fullName>Plan Prepago</fullName>
                </value>
                <value>
                    <fullName>Plan Pospago</fullName>
                </value>
                <value>
                    <fullName>Plan Hibrido</fullName>
                </value>
                <value>
                    <fullName>Servicio GSM</fullName>
                </value>
                <value>
                    <fullName>Numeros Amigos</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Control Cuota Datos</fullName>
                </value>
                <value>
                    <fullName>Simcard</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Credito Adicional</fullName>
                </value>
                <value>
                    <fullName>Roaming</fullName>
                </value>
                <value>
                    <fullName>Dispositivo</fullName>
                </value>
                <value>
                    <fullName>Prestamo</fullName>
                </value>
                <value>
                    <fullName>Proteccion</fullName>
                </value>
                <value>
                    <fullName>Captura</fullName>
                </value>
                <value>
                    <fullName>Pack LDI</fullName>
                </value>
                <value>
                    <fullName>Pack Roaming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/DocumentTypes.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DNI</fullName>
        <default>true</default>
        <label>DNI</label>
    </customValue>
    <customValue>
        <fullName>CUIL</fullName>
    </customValue>
    <customValue>
        <fullName>LEN</fullName>
        <label>Libreta de Enrolamiento</label>
    </customValue>
    <customValue>
        <fullName>LCV</fullName>
        <label>Libreta Civica</label>
    </customValue>
    <customValue>
        <fullName>PAS</fullName>
        <label>Pasaporte</label>
    </customValue>
    <customValue>
        <fullName>CID</fullName>
        <label>Cedula de Identidad</label>
    </customValue>
    <customValue>
        <fullName>CUIT</fullName>
        <isActive>false</isActive>
        <label>CUIT</label>
    </customValue>
    <description>DocumentTypes</description>
    <masterLabel>DocumentTypes</masterLabel>
</GlobalValueSet>

classes/IFS_S443_validateMaxLinesXDoc.cls
@RestResource(urlMapping='/v1/integrationprocedure/validateMaxLinesXDoc/*')
global with sharing class IFS_S443_validateMaxLinesXDoc {

    @HttpPost
    global static void getData() {
        FromJSON jsonBody;
        RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
        res.addHeader('Content-Type', 'application/json');
        system.debug('Inico de getData');
        try {
            try {
                jsonBody = (fromJSON)JSON.deserialize(req.requestBody.toString(),FromJSON.class);
            }
            catch (Exception e) {
                throw new CalloutException('Error al deserializar los parametros. Verifique la estructura del JSON. Error: ' + e.getMessage());
            }
            system.debug('json:'+ jsonBody);
            checkContrato (jsonBody); //-- Verifico que el contrato (IFS) se cumpla.

            String numeroDocumento = jsonBody.validateMaxLinesXDoc.numeroDocumento;
            String tipoDocumento = ((jsonBody.validateMaxLinesXDoc.tipoDocumento == null) ? '' : jsonBody.validateMaxLinesXDoc.tipoDocumento);


            res.statuscode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(getDatos(numeroDocumento,tipoDocumento,'')));
            
        }
        catch (CalloutException ce) {
            res.statuscode = 404;
            res.responseBody = Blob.valueOf(JSON.serialize(getRespuestaNoOk('417',ce.getMessage())));
        }
        catch(Exception e){
            res.statuscode = 404;
            res.responseBody = Blob.valueOf(JSON.serialize(getRespuestaNoOk('417',e.getMessage())));
        }

    }

    private static Map<String,Object> getDatos (String pnumeroDocumento, String ptipoDocumento, String pgenero) {
        
        System.debug('Validate Lines Qtty');
        //Get the number of lines assigned to a customer

        LinesSetting__c linesSetting = LinesSetting__c.getInstance();
        Integer maxLinesQtty = Integer.valueOf(linesSetting.CantidadDeLineas__c);

        Integer linesQttyAllAssets=0;

        System.debug('Valores Input');
        System.debug('pnumeroDocumento '+ pnumeroDocumento);
        System.debug('ptipoDocumento: ' + ptipoDocumento );
        System.debug('pgenero: '+ pgenero);
        
        if (ptipoDocumento.length() == 0 && pgenero.length() == 0) {
            System.debug('Consulta por '+ pnumeroDocumento);
            linesQttyAllAssets = [SELECT count() FROM Asset 
                                    WHERE Product2.Family = 'Movil' AND Product2.vlocity_cmt__Type__c  = 'Plan Prepago' AND 
                                    Account.vlocity_cmt__PrimaryContactId__r.DocumentNumber__c = :pnumeroDocumento
                                    And Account.RecordType.Name = 'Consumer'];
        } else {
            if (ptipoDocumento.length() > 0 && pgenero.length() > 0) {
                System.debug('Consulta por numero de Documento: '+ pnumeroDocumento);
                System.debug('tipo de documento: ' + ptipoDocumento );
                System.debug('genero: '+ pgenero);
                linesQttyAllAssets = [SELECT count() FROM Asset 
                                        WHERE Product2.Family = 'Movil' AND Product2.vlocity_cmt__Type__c  = 'Plan Prepago' AND 
                                        Account.vlocity_cmt__PrimaryContactId__r.DocumentNumber__c = :pnumeroDocumento
                                        AND Account.vlocity_cmt__PrimaryContactId__r.DocumentType__c= :ptipoDocumento 
                                        AND Account.vlocity_cmt__PrimaryContactId__r.Gender__c= : pgenero
                                        And Account.RecordType.Name = 'Consumer'];
            } else if (ptipoDocumento.length() > 0) {
                    System.debug('Consulta por numero de Documento: '+ pnumeroDocumento);
                    System.debug('tipo de documento: ' + ptipoDocumento );
                    linesQttyAllAssets = [SELECT count() FROM Asset 
                                            WHERE Product2.Family = 'Movil' AND Product2.vlocity_cmt__Type__c  = 'Plan Prepago' AND 
                                            Account.vlocity_cmt__PrimaryContactId__r.DocumentNumber__c = :pnumeroDocumento
                                            AND Account.vlocity_cmt__PrimaryContactId__r.DocumentType__c= :ptipoDocumento 
                                            And Account.RecordType.Name = 'Consumer'];
            } else {
                    System.debug('Consulta por numero de Documento: '+ pnumeroDocumento);
                    System.debug('genero: '+ pgenero);
                    linesQttyAllAssets = [SELECT count() FROM Asset 
                                            WHERE Product2.Family = 'Movil' AND Product2.vlocity_cmt__Type__c  = 'Plan Prepago' AND 
                                            Account.vlocity_cmt__PrimaryContactId__r.DocumentNumber__c = :pnumeroDocumento
                                            AND Account.vlocity_cmt__PrimaryContactId__r.Gender__c= : pgenero
                                            And Account.RecordType.Name = 'Consumer'];
            }
        }

        return getRespuestaOk(linesQttyAllAssets,maxLinesQtty);
    }

    private static List<Map<String, String>> getRespuestaNoOk(String pCodigo, String pDescripcion) {
        System.debug('Entre a getRespuestaNoOk()');
        Map<String, String> mapa = new Map<String, String>();
        List<Map<String, String>> lstErrors = new List<Map<String, String>>();
        mapa.put('errorCode', pcodigo);
        mapa.put('message', pDescripcion);
        lstErrors.add(mapa);
        return lstErrors;   
    }

    private static Map<String,Object> getRespuestaOk(integer pcantidadContratada, integer pcantOfertaLineas) {
        Map<String, Object> mapa = new Map<String, Object>();
        Map<String, Object> mapa1 = new Map<String, Object>();
        mapa1.put('cantOfertaLineas', pcantOfertaLineas);
        mapa1.put('cantidadContratada', pcantidadContratada);
        mapa.put('validateMaxLinesXDoc', mapa1);
        return mapa;
    }

    /**
     * Objetivo: Verificar que se cumpla el contrato.
     * Si lo cumple termina y sino dispara la excepción: CalloutException.
     */
    private static void checkContrato (FromJSON pJson) {
        System.debug('Entre a checkContrato()');
        final String K_TYPE_OF_DOCUMENT = 'CUIT,CUIL,DNI,LC,LE,CI,PASAPORTE,CIU,PAU';

        if (pJson.validateMaxLinesXDoc == null) {
            System.debug('Error en el JSON');
            throw new CalloutException('Error en la validacion del JSON');
        }

        String numeroDocumento = pJson.validateMaxLinesXDoc.numeroDocumento;
        String tipoDocumento = pJson.validateMaxLinesXDoc.tipoDocumento;

        if (String.isBlank(numeroDocumento)) {
            System.debug('numeroDocumento nulo o vacio');
            throw new CalloutException('Error en la validacion de los atributos del request. El numero de documento esta vacio');
        }
        if (!numeroDocumento.isnumeric()){
            System.debug('numeroDocumento no se corresponde con un valor del tipo numero');
            throw new CalloutException('Error en la validacion de los atributos del request. El numero de documento no se corresponde con un valor del tipo numero');
        }
        if (!(pJson.validateMaxLinesXDoc.tipoDocumento == null)) {
//            if (!String.isBlank(tipoDocumento)) {
                if (K_TYPE_OF_DOCUMENT.indexOf(tipoDocumento)==-1 || String.isBlank(tipoDocumento)) {
                    throw new CalloutException('Request invalido, Tipo de Documento invalido [' + 
                    tipoDocumento + '] - Tipos validos: [' + K_TYPE_OF_DOCUMENT + ']');
                }
//           }
        }

    }

    public class FromJSON {
        public validateMaxLinesXDocClass validateMaxLinesXDoc; 

    }

    public class validateMaxLinesXDocClass {
        public String numeroDocumento; 
        public String tipoDocumento;
    }
}