objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserRoleAPIName__c</fullName>
        <description>It is used to store the API name of the Salesfor Role assigned to the user based in the roles available for the work team in Work team permissions.</description>
        <externalId>true</externalId>
        <label>User Role API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Store the region that the store location belongs to.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to indicate the status of the point of sales or agency.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dado de baja</fullName>
                </value>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Pendiente activación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Work_Place__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the Work Team with the Agency or Point of Sales.</description>
        <label>Work Place</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Work Teams</relationshipLabel>
        <relationshipName>Work_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Físico</fullName>
    </customValue>
    <customValue>
        <fullName>MVNO</fullName>
    </customValue>
    <customValue>
        <fullName>Telefónico</fullName>
    </customValue>
    <description>Used to indicate the top level of the channels in the solution.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>LITO</fullName>
        <label>Litoral</label>
    </customValue>
    <customValue>
        <fullName>MEDI</fullName>
        <label>Mediterranea</label>
    </customValue>
    <customValue>
        <fullName>SUR</fullName>
        <label>Sur</label>
    </customValue>
    <customValue>
        <fullName>LISU</fullName>
        <isActive>false</isActive>
        <label>LISU</label>
    </customValue>
    <customValue>
        <fullName>NOA</fullName>
        <isActive>false</isActive>
        <label>NOA</label>
    </customValue>
    <customValue>
        <fullName>LINO</fullName>
        <isActive>false</isActive>
        <label>LINO</label>
    </customValue>
    <description>Store the region division used in Telecom Argentina</description>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/IFS_S474_activacionFOLTest.cls
@isTest
public class IFS_S474_activacionFOLTest {
    static final String K_ACCOUNT_NAME = 'TestS474Acc';
    static final String K_ACCOUNT_CODE = '1000000000110001';

    @isTest static void testResponseStatus200 () {
        FromJSON jsonObj = new FromJSON();

        jsonObj.activacionFOL.idCuenta=K_ACCOUNT_CODE;
        jsonObj.activacionFOL.operacion='A'; 
        jsonObj.activacionFOL.fechaDesde='2018-04-30 00:00:00';

        System.debug('jsonObj: ' + JSON.serialize(jsonObj));

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/Care_activacionFOL/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        // Account a = [SELECT Id, AccountIntegrationId__c FROM Account WHERE Name = :K_ACCOUNT_CODE];

        // System.debug('Valores Cuenta---> :' + a);
        IFS_S474_activacionFOL.getData();

        System.assertEquals(200, RestContext.response.statuscode); 
        Result resultado = (Result)JSON.deserialize(RestContext.response.responseBody.toString(), Result.class);
        System.assertNotEquals(null, resultado);
        System.assertEquals('0', resultado.codResultado);

        System.debug('Response: ' + RestContext.response.responseBody.toString());

        Test.stopTest();
    }


    @isTest static void testResponseStatus417 () {
        FromJSON jsonObj = new FromJSON();

        jsonObj.activacionFOL.idCuenta=K_ACCOUNT_CODE;
        jsonObj.activacionFOL.operacion='C'; 
        jsonObj.activacionFOL.fechaDesde='2018-04-30 00:00:00';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/Care_activacionFOL/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S474_activacionFOL.getData();

        System.assertEquals(417, RestContext.response.statuscode); 
        List<ErrorClass> lstErrors = (List<ErrorClass>)JSON.deserialize(RestContext.response.responseBody.toString(), List<ErrorClass>.class);
        System.assertNotEquals(null, lstErrors);

        System.debug('Response: ' + RestContext.response.responseBody.toString());

        Test.stopTest();
    }

    @isTest static void testResponseStatus400 () {
        FromJSON jsonObj = new FromJSON();

        jsonObj.activacionFOL.idCuenta=K_ACCOUNT_CODE;
        jsonObj.activacionFOL.operacion='A'; 
        jsonObj.activacionFOL.fechaDesde='2018-04-3 00:00:00';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/Care_activacionFOL/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S474_activacionFOL.getData();

        System.assertEquals(400, RestContext.response.statuscode); 
        List<ErrorClass> lstErrors = (List<ErrorClass>)JSON.deserialize(RestContext.response.responseBody.toString(), List<ErrorClass>.class);
        System.assertNotEquals(null, lstErrors);

        System.debug('Response: ' + RestContext.response.responseBody.toString());

        Test.stopTest();
    }

    @TestSetup
    static void crearDatosPrueba () {
        System.debug('----- Entre en crearDatosPrueba');
        //- Configuracion Usuario -
        vlocity_cmt__BusinessSite__c storeLocation = createStoreLocation ();
        WorkTeam__c workTeam = createWorkTeam (storeLocation.Id);
        createWorkTeamMember (workTeam.Id);
        System.debug('----- Sali de crearDatosPrueba');
    }


    static vlocity_cmt__BusinessSite__c createStoreLocation () {
        System.debug('---------- Entre en createStoreLocation()');

        System.debug('------------ Antes de crear el Account (Organization) ----');
        Account orgAcc = createOrganization();
        System.debug('------------ Despues de crear el Account (Organization) ----');
        
        vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(Name='Barrio Norte', 
            vlocity_cmt__OrganizationId__c=orgAcc.Id, Status__c='Activo', Type__c='POS', Channel__c='Físico',
             Channel_Type__c='Agentes', Channel_Type_2__c='Agentes', Channel_Type_3__c='Agentes',
             Region__c='AMBA');

        insert storeLocation;     
        return [SELECT Id FROM vlocity_cmt__BusinessSite__c WHERE Name='Barrio Norte'];     
    }


    static Account createOrganization () {

        System.debug('---------- Entre en createOrganization()');
        List<Account> lstAcc = new List<Account>();

        Account a = new Account(Name=K_ACCOUNT_NAME, AccountIntegrationId__c = K_ACCOUNT_CODE);
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        lstAcc.add(a);

        Account b = new Account(Name='TelecomTest', AccountIntegrationId__c=String.valueOf(10001));
        b.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing').getRecordTypeId();
        lstAcc.add(b);
        insert lstAcc;
        System.debug('---------- Salgo de createOrganization()');
        return [SELECT Id FROM Account WHERE Name = 'TelecomTest'];
    }

    static WorkTeam__c createWorkTeam (Id pStoreLocationId) {
        System.debug('---------- Entre en createWorkTeam()');
        WorkTeam__c wt = new WorkTeam__c(Name='Ventas', Team_Name__c='Ventas', Is_Active__c=true, Work_Place__c=pStoreLocationId);
        insert wt;
        return [SELECT Id FROM WorkTeam__c WHERE Name='Ventas'];
    }

    static void createWorkTeamMember (Id pWorkTemaId) {
        System.debug('---------- Entre en createWorkTeamMember()');
        Team_Member__c wtm = new Team_Member__c(User_member__c=UserInfo.getUserId(), Work_Team__c=pWorkTemaId);
        wtm.UserRoleAPIName__c='Care';
        insert wtm;
    }

    public class FromJSON {
        public FromJSON_1 activacionFOL; 
        public FromJSON() {
            activacionFOL = new FromJSON_1();
        }
    }

    public class FromJSON_1 {
        public String idCuenta; 
        public String operacion;
        public String fechaDesde;
    }

    public class Result {
        public String codResultado;
        public String descResultado;
    }

    public class ErrorClass {
        public String errorCode;
        public String message;
    }
}