objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CardHolderName__c</fullName>
        <label>Card Holder Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CardType__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Master Card</fullName>
                </value>
                <value>
                    <fullName>DISCOVER</fullName>
                </value>
                <value>
                    <fullName>UCB</fullName>
                </value>
                <value>
                    <fullName>MASTERCARD</fullName>
                </value>
                <value>
                    <fullName>377</fullName>
                    <label>VISA</label>
                </value>
                <value>
                    <fullName>CABAL</fullName>
                </value>
                <value>
                    <fullName>CREDENCIAL</fullName>
                </value>
                <value>
                    <fullName>AMERICAN EXPRESS</fullName>
                </value>
                <value>
                    <fullName>DINERS</fullName>
                </value>
                <value>
                    <fullName>NARANJA</fullName>
                </value>
                <value>
                    <fullName>KADICARD</fullName>
                </value>
                <value>
                    <fullName>TARJETA AZUL</fullName>
                </value>
                <value>
                    <fullName>TARJETA ARGENTA</fullName>
                </value>
                <value>
                    <fullName>NEVADA</fullName>
                </value>
                <value>
                    <fullName>VISA PROVENCRED</fullName>
                </value>
                <value>
                    <fullName>CARTA AUTOMATICA</fullName>
                </value>
                <value>
                    <fullName>TARJETA GRUPAR</fullName>
                </value>
                <value>
                    <fullName>CREDIMAS</fullName>
                </value>
                <value>
                    <fullName>TARJETA NATIVA</fullName>
                </value>
                <value>
                    <fullName>MIRA</fullName>
                </value>
                <value>
                    <fullName>TARJETA SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SIDECREER</fullName>
                </value>
                <value>
                    <fullName>NARANJA-VISA</fullName>
                </value>
                <value>
                    <fullName>COOPEPLUS</fullName>
                </value>
                <value>
                    <fullName>DATA 2000</fullName>
                </value>
                <value>
                    <fullName>TARJETA CREDICASH</fullName>
                </value>
                <value>
                    <fullName>TARJETA SOL</fullName>
                </value>
                <value>
                    <fullName>TARJETA TITANIO</fullName>
                </value>
                <value>
                    <fullName>TARJETA CMR</fullName>
                </value>
                <value>
                    <fullName>TARJETA MAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ExpirationMonth__c</fullName>
        <label>Expiration Month</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>07</fullName>
                </value>
                <value>
                    <fullName>08</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ExpirationYear__c</fullName>
        <label>Expiration Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Last4Numbers__c</fullName>
        <label>Last4Numbers</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IFS_S465_asociarTarjetaTest.cls
@isTest
public class IFS_S465_asociarTarjetaTest {
        //private static final String idCliAux = String.valueOf(10000);
       // private static final String idCliAux = '0016C000008fDM6QAM';
       private static final String idCliAux = '00';

    @isTest static void testResponseStatus200 () {
        FromJSON jsonObj = new FromJSON();

		//jsonObj.asociarTarjeta.idCliente='0016C000008fDM6QAM';
        // String idCliAux = String.valueOf(10000);
        jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='2';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('200'), RestContext.response.statuscode); 
        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }


    /**
     * @Objetivo: No mandar parametros obligatorios para forzar el status code 400.
     */
    @isTest static void testResponseAnotherStatus417_ID_CLIENTE () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente='';
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
    //    Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
    //    System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }    
        @isTest static void testResponseAnotherStatus417_CARD_NUMBER () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }    
        @isTest static void testResponseAnotherStatus417_EXPIRATION_YEAR () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }    

        @isTest static void testResponseAnotherStatus417_LAST_4_NUMBERS () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }    

        @isTest static void testResponseAnotherStatus417_EXPIRATION_MONTH () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    } 

       @isTest static void testASOCIAR_TRARJ_PRIM_NULL () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary= null;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
    //    Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
    //    System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    } 

       @isTest static void testVALIDAR_EXPIRATION_MONTH () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='17';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary= true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
 //       Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
 //       System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }

       @isTest static void testVALIDAR_EXPIRATION_YEAR () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='17';
		jsonObj.asociarTarjeta.expirationYear='2014';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary= true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }

      @isTest static void testVALIDAR_4_NUMBERS () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='MASTERCARD';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='22';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }

    @isTest static void testVALIDAR_CARD_TYPE () {
        FromJSON jsonObj = new FromJSON();

		jsonObj.asociarTarjeta.idCliente= idCliAux;
		jsonObj.asociarTarjeta.cardHolderName='Juan Perez';
		jsonObj.asociarTarjeta.cardNumber='XXXXXXXXXXXX2222';
		jsonObj.asociarTarjeta.cardType='TRUCHA';
		jsonObj.asociarTarjeta.expirationMonth='02';
		jsonObj.asociarTarjeta.expirationYear='2018';
		jsonObj.asociarTarjeta.last4Numbers='2222';
		jsonObj.asociarTarjeta.isPrimary=true;
		jsonObj.asociarTarjeta.securityCode='333';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure/asociarTarjeta/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S465_asociarTarjeta.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
//        Map<String, Object> resMap = (Map<String, Object>)JSON.deserializeUntyped(RestContext.response.responseBody.toString());
//        System.assertEquals('OK', resMap.get('resultado'));

        Test.stopTest();
    }

////////////////////////////////////////
    @TestSetup
    private static void crearDatosPrueba () {
        System.debug('----- Entre en crearDatosPrueba');
        Account account = createAccount();
        vlocity_cmt__PaymentMethod__c payMet = creaPayMet(account);
        //- Configuracion Usuario -
        // vlocity_cmt__BusinessSite__c storeLocation = createStoreLocation ();
        // WorkTeam__c workTeam = createWorkTeam (storeLocation.Id);
        // createWorkTeamMember (workTeam.Id);
        System.debug('----- Sali de crearDatosPrueba');
    }

   private static Account createAccount() {
        System.debug('---------- Entre en createAccount() id:' + String.valueOf(10000));
        List<Account> lstAcc = new List<Account>();
        Account a = new Account();
        a.Name='TestIFSS445Account';
        a.AccountIntegrationId__c= idCliAux;
	//	a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        lstAcc.add(a);
        insert lstAcc;
        a = getCreatedAccount('TestIFSS445Account');
        System.debug('---------- Sali de createAccount()');
        return a;
    }

    private static Account getCreatedAccount (String pName) {
        System.debug('-------------- Entre en getCreatedAccount()');
        Account a = [SELECT Id, AccountIntegrationId__c FROM Account WHERE Name = :pName];
        System.debug('-------------- Account Id: ' + a.Id);
        System.debug('-------------- AccountIntegrationId: ' + a.AccountIntegrationId__c);
        System.debug('-------------- Sali de getCreatedAccount()');
        return a;
    }

    private static vlocity_cmt__PaymentMethod__c creaPayMet(Account cuenta) {
        vlocity_cmt__PaymentMethod__c payMet = new vlocity_cmt__PaymentMethod__c();
        payMet.vlocity_cmt__AccountId__c = cuenta.Id;
        payMet.vlocity_cmt__IsActive__c = true;
        payMet.vlocity_cmt__CardHolderName__c = 'Juan Perez';
        payMet.vlocity_cmt__CardType__c = 'MASTERCARD';
        payMet.vlocity_cmt__ExpirationMonth__c = '02';
        payMet.vlocity_cmt__ExpirationYear__c = '2018';
        payMet.vlocity_cmt__Last4Numbers__c = '2222';
        insert payMet;
        return payMet;
    }
//////////////////////////////////////

    public class FromJSON {
        public FromJSON_1 asociarTarjeta; 
        public FromJSON() {
            asociarTarjeta = new FromJSON_1();
        }
    }
    public class FromJSON_1 {
        public String idCliente; 
        public String cardHolderName;
        public String cardNumber;
        public String cardType;
        public String expirationMonth;
        public String expirationYear;
        public String last4Numbers;
        public Boolean isPrimary;
        public String securityCode;
    }

}