objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>#Marketing #Sprint15 Atributo de mayor ponderación aplicado a la cuenta que se visualizará en V360.</description>
        <label>Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <description>#Sprint16 #Marketing Account segment attributes</description>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Socio Club</fullName>
                </value>
                <value>
                    <fullName>Estratégico</fullName>
                </value>
                <value>
                    <fullName>Menor</fullName>
                </value>
                <value>
                    <fullName>Jubilado</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomerIntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Integration Id</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SegmentLevel1__c</fullName>
        <label>Segment Level 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SegmentLevel1</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SegmentLevel2__c</fullName>
        <label>Segment Level 2</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SegmentLevel2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SegmentUniqueCode__c</fullName>
        <description>#MarketingTeam #Sprint08
Unique code identifier for segment level combination</description>
        <label>Segment Unique Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AttributesByProfile__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>#Sprint16 #Marketing Tabla de Atributos que puede asignar o desasignar cada perfil.</description>
    <fields>
        <fullName>AccountAttributes__c</fullName>
        <label>Account Attributes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactAttributes__c</fullName>
        <label>Contact Attributes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Atributos por Perfil</label>
</CustomObject>

objects/AttributesWeighing__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>#Sprint16 #Marketing Tabla de ponderación de atributos para Account y Contact</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>Attribute Name</description>
        <label>Attribute</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Salesforce Object</description>
        <label>Object</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weighing__c</fullName>
        <description>Attribute weighing</description>
        <label>Weighing</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ponderación de Atributos</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attributes__c</fullName>
        <description>#Sprint16 #Marketing Contact Attributes</description>
        <label>Attributes</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Prensa</fullName>
                </value>
                <value>
                    <fullName>Jubilado</fullName>
                </value>
                <value>
                    <fullName>Plan Social</fullName>
                </value>
                <value>
                    <fullName>Empleado Grupo</fullName>
                </value>
                <value>
                    <fullName>Ex Empleado Grupo</fullName>
                </value>
                <value>
                    <fullName>No Vidente</fullName>
                </value>
                <value>
                    <fullName>Hipoacúsico</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Menor</fullName>
                </value>
                <value>
                    <fullName>Estratégico</fullName>
                </value>
                <value>
                    <fullName>Socio Club</fullName>
                </value>
                <value>
                    <fullName>Atributo Z</fullName>
                </value>
                <value>
                    <fullName>Atributo B</fullName>
                </value>
                <value>
                    <fullName>aaaaaa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Segments__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>SegmentLevel1__c</fullName>
        <label>Segmentación Nivel 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SegmentLevel2__c</fullName>
        <label>Segmentación Nivel 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Category</label>
</CustomObject>

globalValueSets/SegmentLevel1.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Alta reciente</fullName>
        <default>true</default>
        <label>Alta reciente</label>
    </customValue>
    <customValue>
        <fullName>Altas Recientes</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Hogar</fullName>
    </customValue>
    <customValue>
        <fullName>Línea Prepago</fullName>
    </customValue>
    <customValue>
        <fullName>Percanta</fullName>
    </customValue>
    <customValue>
        <fullName>Premium/Black</fullName>
    </customValue>
    <customValue>
        <fullName>Prepago Línea</fullName>
    </customValue>
    <customValue>
        <fullName>Sólo Móvil</fullName>
    </customValue>
    <masterLabel>SegmentLevel1</masterLabel>
</GlobalValueSet>

globalValueSets/SegmentLevel2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Altas Recientes</fullName>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Black Conexion Total Libre 2XL</fullName>
    </customValue>
    <customValue>
        <fullName>Default</fullName>
    </customValue>
    <customValue>
        <fullName>Empleado</fullName>
    </customValue>
    <customValue>
        <fullName>Gold</fullName>
    </customValue>
    <customValue>
        <fullName>Marcanta</fullName>
    </customValue>
    <customValue>
        <fullName>Masivo</fullName>
    </customValue>
    <customValue>
        <fullName>Regular A</fullName>
    </customValue>
    <customValue>
        <fullName>Sólo Movil</fullName>
    </customValue>
    <customValue>
        <fullName>Menor</fullName>
    </customValue>
    <customValue>
        <fullName>SOHO</fullName>
    </customValue>
    <customValue>
        <fullName>Empresas</fullName>
    </customValue>
    <customValue>
        <fullName>PyME</fullName>
    </customValue>
    <masterLabel>SegmentLevel2</masterLabel>
</GlobalValueSet>

classes/AccountTriggersTest.cls
@isTest
public class AccountTriggersTest {

    static testMethod void TestAccountInsert(){

        // Test Custom Setting Data
        List<Segments__c> segments = new List<Segments__c>();
        Segments__c seg = new Segments__c(Name = 'Black',
                                          segmentLevel1__c = 'Hogar',
                                          segmentLevel2__c = '1 TV');
        Segments__c seg2 = new Segments__c(Name = 'Premium',
                                          segmentLevel1__c = 'Sólo Móvil',
                                          segmentLevel2__c = 'Black');
        segments.add(seg);
        segments.add(seg2);
        insert segments;
        // Test data setup
        // Create an account with Segment = Black
        Account acc = new Account (Name='Test Account Black1',
                                   SegmentLevel1__c = 'Hogar',
                                   SegmentLevel2__c = '1 TV');
        // Test Insert
        Test.startTest();
        Database.SaveResult result = Database.insert(acc,false);
        acc.SegmentLevel1__c = 'Sólo Móvil';
        acc.SegmentLevel2__c = 'Black';
        Database.SaveResult result2 = Database.update(acc,false);
        Test.stopTest();
                //List<Account> lstCuentas = [SELECT segmentUniqueCode__c FROM Account WHERE Id = :acc.Id LIMIT 1];
                //string strvalor1 = lstCuentas[0].segmentUniqueCode__c;
                //system.debug('lstCuentas ===> '+lstCuentas);
                //system.debug('strvalor1 ===> '+strvalor1);
        //System.assertEquals('Black',[SELECT segmentUniqueCode__c FROM Account WHERE Id = :acc.Id LIMIT 1][0].segmentUniqueCode__c);
    }

    static testMethod void checkInsertUniqueConsumerAccountTest() {
        MockupFactory.generate();
        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Contact contact = [SELECT Id FROM Contact LIMIT 1];

        Account acc = new Account (Name='New Test Account', RecordTypeId = consumerRecordTypeId, vlocity_cmt__PrimaryContactId__c = contact.Id);

        Test.startTest();
        try {
            insert acc;
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.ConsumerAccountNotUniqueError) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }

    static testMethod void checkUpdateUniqueConsumerAccountTest() {
        MockupFactory.generate();
        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Id businessRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Business' AND SobjectType = 'Account' LIMIT 1].Id;
        Contact contact = [SELECT Id FROM Contact LIMIT 1];

        Account acc = new Account (Name='New Test Account', RecordTypeId = businessRecordTypeId, vlocity_cmt__PrimaryContactId__c = contact.Id);
        insert acc;

        Test.startTest();
        try {
            acc.RecordTypeId = consumerRecordTypeId;
            update acc;
        } catch (Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.ConsumerAccountNotUniqueError) ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }

    static testMethod void setCustomerAccountIntegrationIdTest() {
        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Id businessRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Business' AND SobjectType = 'Account' LIMIT 1].Id;

        Account acc = new Account (Name='New Test Account', RecordTypeId = businessRecordTypeId);
        Account acc2 = new Account (Name='New Test Account2', RecordTypeId = consumerRecordTypeId);

        Test.startTest();
        insert acc;
        insert acc2;

        Account insertedAccount1 = [SELECT Id, CustomerIntegrationId__c FROM Account WHERE Id =: acc.Id LIMIT 1];
        System.assert(insertedAccount1.CustomerIntegrationId__c == Decimal.valueOf('10000000001'));
        Account insertedAccount2 = [SELECT Id, CustomerIntegrationId__c FROM Account WHERE Id =: acc2.Id LIMIT 1];
        //System.assert(insertedAccount2.CustomerIntegrationId__c == Decimal.valueOf('10000000002'));
        Test.stopTest();
    }

    static testMethod void setBillingAccountIntegrationIdTest() {
        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Id billingRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Billing' AND SobjectType = 'Account' LIMIT 1].Id;

        Account acc = new Account (Name='New Test Account', RecordTypeId = consumerRecordTypeId);
        insert acc;
        Account acc2 = new Account (Name='New Test Account2', RecordTypeId = billingRecordTypeId, ParentId = acc.Id);

        Test.startTest();
        insert acc2;

        Account acc3 = new Account (Name='New Test Account3', RecordTypeId = billingRecordTypeId, ParentId = acc.Id);
        insert acc3;

        Account insertedAccount1 = [SELECT Id, AccountIntegrationId__c FROM Account WHERE Id =: acc2.Id LIMIT 1];
        //System.assert(insertedAccount1.AccountIntegrationId__c == '1000000000110001');
        Account insertedAccount2 = [SELECT Id, AccountIntegrationId__c FROM Account WHERE Id =: acc3.Id LIMIT 1];
        //System.assert(insertedAccount2.AccountIntegrationId__c == '1000000000110002');
        Test.stopTest();
    }

    static testMethod void callIntegrationServicesTest() {
        Id billingRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Billing' AND SobjectType = 'Account' LIMIT 1].Id;
        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;

        Account customerAccount = new Account(Name = 'Customer Account Test', RecordTypeId = consumerRecordTypeId);
        Account billingAccount = new Account(Name = 'Billing Account Test', RecordTypeId = billingRecordTypeId);

        Test.startTest();
        insert customerAccount;

        billingAccount.ParentId = customerAccount.Id;
        insert billingAccount;
        Test.stopTest();
    }

    /**
     * @Author: Julia Carranza
     * @Description: This test tests the attributesWeighingValidation and the updateAttributeAccountField method consequently.
     */
    @isTest static void attributesWeighingValidation() {
        String jubilado = 'Jubilado';
        String estrategico = 'Estratégico';
        String menor = 'Menor';
        String vip = 'VIP';
        String prensa = 'Prensa';
        String account = 'Account';
        String contact = 'Contact';
        String socioClub = 'Socio Club';
 
        String userId = UserInfo.getUserId();
        Id userProfileId = Id.valueOf(UserInfo.getProfileId());
        Profile userProfile = [SELECT Name FROM Profile WHERE Id = :userProfileId];

        AttributesWeighing__c aw1 = new AttributesWeighing__c(Name = 'aw1', Attribute__c = jubilado, Object__c = account, Weighing__c = 1);
        AttributesWeighing__c aw2 = new AttributesWeighing__c(Name = 'aw2', Attribute__c = estrategico, Object__c = account, Weighing__c = 2);
        AttributesWeighing__c aw3 = new AttributesWeighing__c(Name = 'aw3', Attribute__c = menor, Object__c = account, Weighing__c = 3);
        AttributesWeighing__c aw4 = new AttributesWeighing__c(Name = 'aw4', Attribute__c = vip, Object__c = contact, Weighing__c = 4);
        AttributesWeighing__c aw5 = new AttributesWeighing__c(Name = 'aw5', Attribute__c = prensa, Object__c = contact, Weighing__c = 5);
        AttributesWeighing__c att1 = new AttributesWeighing__c(Name = '01', Object__c = account, Attribute__c = socioClub, Weighing__c = 1);
        AttributesByProfile__c ab1 = new AttributesByProfile__c(AccountAttributes__c = (jubilado + '; ' + estrategico + '; ' + menor + '; ' + socioClub), ContactAttributes__c = (vip + '; ' + prensa), SetupOwnerId = userProfile.Id);

        Test.startTest();

        Database.Insert(aw1);
        Database.Insert(aw2);
        Database.Insert(aw3);
        Database.Insert(aw4);
        Database.Insert(att1);
        Database.Insert(ab1);

        Contact contact1 = new Contact(LastName='Contact1', Attributes__c=vip);
        //Attribute__c autocompletes with VIP (Contact Trigger)
        Database.Insert(contact1);
        
        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing').getRecordTypeId();
        Account account1 = new Account(Name='current1', Attributes__c = jubilado, RecordTypeId = devRecordTypeId, vlocity_cmt__PrimaryContactId__c = Null);
        Account account2 = new Account(Name='current2', Attributes__c = jubilado, RecordTypeId = devRecordTypeId, vlocity_cmt__PrimaryContactId__c = contact1.Id);
        //Attribute__c from account1 autocompletes with jubilado because it has no contact.
        //Attribute__c from account2 autocompletes with VIP because of the contact.
        List<Account> listAcc = new List<Account>();
        listAcc.add(account1);
        listAcc.add(account2);
        insert account1;
        
        for(Account acc : listAcc){
            acc.Attributes__c = estrategico;
        }
        account1.Attributes__c = estrategico;
        update account1;

        contact1.Attributes__c = '';
        //listAcc[1].Attributes__c = menor;

        Database.update(contact1);
        //Database.update(listAcc[1]);

        account1.Attributes__c = '';
        //listAcc[1].Attributes__c = '';
        Database.update(listAcc[0]);
        //Database.update(listAcc[1]);

        account1.Attributes__c = (jubilado + ';' + estrategico);
        Database.update(listAcc[0]);

        Test.stopTest();
    }

    /**
     * @Author: Julia Carranza
     * @Description: This test tests the AttributesUsage Class for the Account Object.
     */
    @isTest static void checkObjectAttributesRules(){
        String jubilado = 'Jubilado';
        String estrategico = 'Estratégico';
        String menor = 'Menor';
        String vip = 'VIP';
        String prensa = 'Prensa';
        String account = 'Account';
        String contact = 'Contact';
        String socioClub = 'Socio Club';
        
        String userId = UserInfo.getUserId();
        Id userProfileId = Id.valueOf(UserInfo.getProfileId());
        Profile userProfile = [SELECT Name FROM Profile WHERE Id = :userProfileId];

        AttributesWeighing__c aw1 = new AttributesWeighing__c(Name = 'aw1', Attribute__c = jubilado, Object__c = account, Weighing__c = 1);
        AttributesWeighing__c aw2 = new AttributesWeighing__c(Name = 'aw2', Attribute__c = estrategico, Object__c = account, Weighing__c = 2);
        AttributesWeighing__c aw3 = new AttributesWeighing__c(Name = 'aw3', Attribute__c = menor, Object__c = account, Weighing__c = 3);
        AttributesWeighing__c aw4 = new AttributesWeighing__c(Name = 'aw4', Attribute__c = vip, Object__c = contact, Weighing__c = 4);
        AttributesWeighing__c aw5 = new AttributesWeighing__c(Name = 'aw5', Attribute__c = prensa, Object__c = contact, Weighing__c = 5);
        AttributesWeighing__c att1 = new AttributesWeighing__c(Name = '01', Object__c = account, Attribute__c = socioClub, Weighing__c = 6);
        AttributesWeighing__c aw6 = new AttributesWeighing__c(Name = 'aw6', Attribute__c = estrategico, Object__c = contact, Weighing__c = 7);
        AttributesByProfile__c ab1 = new AttributesByProfile__c(AccountAttributes__c = (jubilado + '; ' + estrategico + '; ' + menor + '; ' + socioClub), ContactAttributes__c = (vip + '; ' + estrategico + ';' + prensa), SetupOwnerId = userProfile.Id);
        
        Test.startTest();

        Database.Insert(aw1);
        Database.Insert(aw2);
        Database.Insert(aw3);
        Database.Insert(aw4);
        Database.Insert(att1);
        Database.Insert(aw5);
        Database.Insert(aw6);
        Database.Insert(ab1);

        Contact contact1 = new Contact(LastName='Contact1', Attributes__c = vip);
        Database.Insert(contact1);

        Id devRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing').getRecordTypeId();
        Account account1 = new Account(Name='current1', Attributes__c = jubilado, RecordTypeId = devRecordTypeId, vlocity_cmt__PrimaryContactId__c = Null);
        Database.Insert(account1);

        //contact1.Attributes__c = vip + ';' + estrategico;
        //account1.Attributes__c = jubilado + ';' + estrategico;
        //Database.update(contact1);
        //Database.update(account1);

        Test.stopTest();
    }
}