objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerIntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Integration Id</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PhoneValidated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Número de línea decisora validado.</description>
        <label>Phone Validated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Account object.</description>
        <inlineHelpText>this field determines the relationship with the Account object.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkbox1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>generic checkbox field type</description>
        <inlineHelpText>generic checkbox field type</inlineHelpText>
        <label>Checkbox1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DateTime3__c</fullName>
        <label>DateTime 3</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Integer1__c</fullName>
        <description>generic integer field type</description>
        <inlineHelpText>generic integer field type</inlineHelpText>
        <label>Integer 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Integer2__c</fullName>
        <description>generic integer field type</description>
        <inlineHelpText>generic integer field type</inlineHelpText>
        <label>Integer 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MarkForDeletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>field represent of mark for deletion record</description>
        <inlineHelpText>field represent of mark for deletion record</inlineHelpText>
        <label>Mark for deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cerrado</fullName>
                </value>
                <value>
                    <fullName>Confirmado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Fallo Envio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>String1__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>TrackingStatus__c</fullName>
        <label>Tracking status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de pago</fullName>
                </value>
                <value>
                    <fullName>Preparar pedido</fullName>
                </value>
                <value>
                    <fullName>Pendiente de entrega</fullName>
                </value>
                <value>
                    <fullName>Entregado</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Validacion de Identidad</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Validacion</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por fraude</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida voluntariamente</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por siniestro</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por Dorma</fullName>
                </value>
                <value>
                    <fullName>Línea de Baja</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Time Out Store PickUp</fullName>
                </value>
                <value>
                    <fullName>Cobrado</fullName>
                </value>
                <value>
                    <fullName>Pago No Concretado</fullName>
                </value>
                <value>
                    <fullName>Recargado</fullName>
                </value>
                <value>
                    <fullName>Recarga SOS exitosa</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulacion</fullName>
                </value>
                <value>
                    <fullName>Fraude</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Validacion Rechazada</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Caja</fullName>
                </value>
                <value>
                    <fullName>Anulado</fullName>
                </value>
                <value>
                    <fullName>Exitoso</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout</fullName>
                </value>
                <value>
                    <fullName>Inicial</fullName>
                </value>
                <value>
                    <fullName>Cerrada - No corresponde</fullName>
                </value>
                <value>
                    <fullName>Cerrada Exitosa - Reclamo</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago por Vencimiento de Plazo de Retiro</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago</fullName>
                </value>
                <value>
                    <fullName>Pago Fallido</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SMSSender__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sender__c</fullName>
        <label>Sender</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>SMS Sender</label>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taSalesSMSInteractionTest.cls
@isTest
private class taSalesSMSInteractionTest {

  String method = 'ReceiveMessage';
  
  Map<String,Object> input = new Map<String,Object>();
  Map<String,Object> outMap = new Map<String,Object>();
  Map<String,Object> options = new Map<String,Object>();
  
  //testClass.invokeMethod(method, input, outMap, options);

  @isTest
  static void invoke_ValidateClientResponse_OK(){
      String method = 'ValidateClientResponse';
      String testLine = '1234567890';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    Asset ast = TestDataFactory.createAssets(1, acc, testLine)[0];
    acc.Phone = '1234567890';
    update acc;
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    CrossObject__c trkCross = new CrossObject__c(
      String1__c = '1234567890',
      Status__c = 'Confirmado',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      DateTime3__c = Date.today(), 
      RecordTypeId = trkRecordType
    );
    insert trkCross;
    
    CrossObject__c templateCross =  new CrossObject__c(
      PickList1__c = 'Verificación de Línea Decisora',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    ); 
    insert templateCross;
    
    options.put('accountId', acc.Id);
    options.put('type', 'Verificación de Línea Decisora');
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest(); 
    
    System.assertEquals(true, (Boolean) outMap.get('IsValid'));
  } 

  @isTest
  static void invoke_CheckAndSaveDecisiveLine_Invalid(){
      String method = 'CheckAndSaveDecisiveLine';
      String testLine = '1234567890';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    insert new SMSSender__c(Name='S-Confirmacion-SMS', Sender__c='TestStress - SMS');
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    acc.CustomerIntegrationId__c = 5645647;
    update acc;
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    Asset ast = TestDataFactory.createAssets(1, acc, testLine)[0];
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    CrossObject__c templateCross =  new CrossObject__c(
      PickList1__c = 'Verificación de Línea Decisora',
      RecordTypeId = smsRecordType,
      String1__c = '{{Name}} - {{Phone}} - {{OK}} - {{KO}}'
    ); 
    insert templateCross;
    
    options.put('accountId', acc.Id);
    options.put('phone', 123456789);
    options.put('orderId',ord.Id);
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest();
    
    List<CrossObject__c> trkCross = [SELECT Id FROM CrossObject__c WHERE RecordTypeId = :trkRecordType];
    //PFTA-10979, ya no se hace insert en acc en el metodo
    //Account resultAcc = [SELECT PhoneValidated__c, Phone FROM Account WHERE Id = :acc.Id];
    
    System.assertEquals(1, trkCross.size());
    //System.assertEquals(false, resultAcc.PhoneValidated__c);
    //System.assertEquals('123456789', resultAcc.Phone);
    //System.assertEquals(resultAcc.Id, (String) outMap.get('RootAcount'));
  }

  @isTest
  static void invoke_CheckAndSaveDecisiveLine_Valid(){
      String method = 'CheckAndSaveDecisiveLine';
      String testLine = '1234567890';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    Asset ast = TestDataFactory.createAssets(1, acc, testLine)[0];
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    CrossObject__c templateCross =  new CrossObject__c(
      PickList1__c = 'Verificación de Línea Decisora',
      RecordTypeId = smsRecordType,
      String1__c = '{{Name}} - {{Phone}} - {{OK}} - {{KO}}'
    );
    insert templateCross;
    
    options.put('accountId', acc.Id);
    options.put('phone', testLine);
    options.put('orderId',ord.Id);
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest();
    
    List<CrossObject__c> trkCross = [SELECT Id FROM CrossObject__c WHERE RecordTypeId = :trkRecordType];
    //PFTA-10979, ya no se hace insert en acc en el metodo
    //Account resultAcc = [SELECT PhoneValidated__c, Phone FROM Account WHERE Id = :acc.Id];
    
    System.assertEquals(0, trkCross.size());
    //System.assertEquals(true, resultAcc.PhoneValidated__c);
    //System.assertEquals(testLine, resultAcc.Phone);
    //System.assertEquals(resultAcc.Id, (String) outMap.get('RootAcount'));
  }

  @isTest
  static void invoke_SendSMS_Valid(){
      String method = 'SendSMS';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String logRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    CrossObject__c trkCross = new CrossObject__c(
      String1__c = '1234567890',
      Status__c = 'Confirmado',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      DateTime3__c = Date.today(), 
      RecordTypeId = trkRecordType
    );
    insert trkCross;
    
    CrossObject__c templateCross =  new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    ); 
    insert templateCross;
    
    options.put('accountId', acc.Id);
    options.put('orderId', ord.Id);
    options.put('cellnumber', '1234567890');
    options.put('text', 'Test Message');
    options.put('type', 'Verificación de identidad en una orden de venta');
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest();
    
    CrossObject__c resTrkCross = [SELECT Status__c FROM CrossObject__c WHERE Id = :trkCross.Id];
    
    Map<String, Object> resp = (Map<String, Object>) outMap.get('ValidateSMS_Response');
    
    System.assertEquals('Cerrado', resTrkCross.Status__c);
    System.assertEquals(true, (Boolean) resp.get('IsValid'));
  }
  
  @isTest
  static void invoke_SendSMS_NotValid(){
      String method = 'SendSMS';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String logRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    CrossObject__c templateCross =  new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    ); 
    insert templateCross;

	SMSSender__c objSMS = new SMSSender__c();
	objSMS.Name = 'S-Confirmacion-SMS';
	objSMS.Sender__c = 'S-Confirmacion-SMS';
	insert objSMS;
    
    options.put('accountId', acc.Id);
    options.put('orderId', ord.Id);
    options.put('cellnumber', '1234567890');
    options.put('text', 'Test Message');
    options.put('type', 'Verificación de identidad en una orden de venta'); 
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    try {
    testClass.invokeMethod(method, input, outMap, options);
    } catch (exception e) {
        System.assertEquals('Error inesperado al enviar el SMS.',e.getMessage());
    }
    Test.stopTest();
  }

  @isTest
  static void invoke_receiveMessageTestOK(){
      String method = 'ReceiveMessage';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    acc.phone = '1234567890';
    update acc; 
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String logRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    insert new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    ); 
    
    insert new CrossObject__c(
      PickList1__c = 'Sms',
      Account__c = acc.Id, 
      Order__c = ord.Id,
      Checkbox1__c = false,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = logRecordType
    );
    
    insert new CrossObject__c(
      Account__c = acc.Id, 
      Order__c = ord.Id,
      String1__c = '1234567890',
      Status__c = 'Pendiente',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = trkRecordType
    );
    
    options.put('accountId', acc.Id);
    options.put('IdOrder', ord.Id);
    options.put('ResponseTypeSMS', 'OK');
	  options.put('mensaje', 'Prueba Mensaje Test');
    
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest();
    
    Order ord1 = [SELECT TrackingStatus__c FROM Order WHERE Id = :ord.Id];
    
    //System.assertEquals('Preparar pedido', ord1.TrackingStatus__c);
  }
  
  @isTest
  static void invoke_receiveMessageTest_NoOK(){
      String method = 'ReceiveMessage';
  
    Map<String,Object> input = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
    Map<String,Object> options = new Map<String,Object>();
    
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    acc.phone = '1234567890';
    update acc; 
    
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String logRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    insert new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType, 
      Integer1__c=300, Integer2__c=3
    ); 
    
    insert new CrossObject__c(
      PickList1__c = 'Sms',
      Account__c = acc.Id, 
      Order__c = ord.Id,
      Checkbox1__c = false,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = logRecordType
    );
    
    insert new CrossObject__c(
      Account__c = acc.Id, 
      Order__c = ord.Id,
      String1__c = '1234567890',
      Status__c = 'Pendiente',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = trkRecordType
    );
    
    options.put('accountId', acc.Id);
    options.put('IdOrder', ord.Id);
    options.put('ResponseTypeSMS', 'NOK');
    options.put('mensaje', 'Prueba Mensaje Test');
    Test.startTest();
    taSalesSMSInteraction testClass = new taSalesSMSInteraction();
    testClass.invokeMethod(method, input, outMap, options);
    Test.stopTest();
    
    Order ord1 = [SELECT TrackingStatus__c FROM Order WHERE Id = :ord.Id];
    
    System.assertEquals('Inicial', ord1.TrackingStatus__c);
  }
  
  @isTest
  static void SendSMSTemplateOK(){
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String logRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(300);
    
    String templateType = 'Recarga Exitosa';
    String msj = 'Hola';
    
    insert new CrossObject__c(
      PickList1__c = templateType,
      RecordTypeId = smsRecordType, 
      String1__c = msj
    );

    SMSSender__c objSMS = new SMSSender__c();
    objSMS.Name = 'S-Confirmacion-SMS';
    objSMS.Sender__c = 'S-Confirmacion-SMS';
    insert objSMS;
    
    Map<String, String> variables = new Map<String, String>();
    variables.put('Name', 'Nombre');
    
    Test.startTest();
    taSalesSMSInteraction.sendSMSTemplate('12345678', templateType, variables);
    Test.stopTest();
    
    List<CrossObject__c> retCross = [SELECT Id 
                       FROM CrossObject__c 
                      WHERE Picklist1__c = :templateType
                        AND Status__c = 'Pendiente'
                        AND MarkForDeletion__c = true];
     
     System.assertEquals(1, retCross.size());
  }

  @isTest
    static void ReceiveMessageTestOK() {
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String LogRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage(); 
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    
    insert new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    );
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(290);
    
    insert new CrossObject__c(
      Account__c = acc.Id, 
      Order__c = ord.Id,
      String1__c = '1234567890',
      Status__c = 'Pendiente',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = trkRecordType
    );
    
    insert new CrossObject__c(
      PickList1__c = 'Sms',
      Account__c = acc.Id, 
      Order__c = ord.Id,
      Checkbox1__c = false,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = LogRecordType
    );
    
    Test.startTest();
    taSalesSMSInteraction.ReceiveMessage('1234567890', 'OK');
    Test.stopTest();
    
    Order ord1 = [SELECT TrackingStatus__c FROM Order WHERE Id = :ord.Id];
    
    System.assertEquals('Preparar pedido', ord1.TrackingStatus__c);
    }
    
    @isTest
    static void ReceiveMessageTestNoOK() {
    String smsRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Template').getRecordTypeId();
    String LogRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('Log Identity Validation').getRecordTypeId();
    String trkRecordType = Schema.SObjectType.CrossObject__c.getRecordTypeInfosByName().get('SMS Tracking').getRecordTypeId();
    
    String orderRecordType = Schema.SObjectType.Order.getRecordTypeInfosByName().get('MobilePhoneOrder').getRecordTypeId();
    
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    TestDataFactory.createExpectedMessage();
    
    Account acc = TestDataFactory.createAccounts(1,'Business')[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];
    
    ord.RecordTypeId = orderRecordType;
    update ord;
    
    insert new CrossObject__c(
      PickList1__c = 'Verificación de identidad en una orden de venta',
      RecordTypeId = smsRecordType,
      Integer1__c=300, Integer2__c=3
    );
    
    DateTime fechaLimiteVencimiento = Datetime.Now().addMinutes(290);
    
    insert new CrossObject__c(
      Account__c = acc.Id, 
      Order__c = ord.Id,
      String1__c = '1234567890',
      Status__c = 'Pendiente',
      Integer1__c = 3,
      DateTime1__c = fechaLimiteVencimiento,
      RecordTypeId = trkRecordType
    );
    
    System.debug('order record type: ' + ord.RecordType.Name);
    
    Test.startTest();
    taSalesSMSInteraction.ReceiveMessage('1234567890', 'NOK');
    Test.stopTest();
    
    Order ord1 = [SELECT TrackingStatus__c FROM Order WHERE Id = :ord.Id];
    
    System.assertEquals('Cancelada - Validacion Rechazada', ord1.TrackingStatus__c);
    }
    
    @isTest
    static void ValidateClientResponseTest() {
    
    }
    
    @isTest
    static void SendSMSTest() {
    
    }
    
    @isTest
    static void CheckAndSaveDecisiveLineTest() {
    
    }
    
}