objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PrimaryContactId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The primary person to contact with any business related to this account. If the customer is a consumer, the primary contact may also be the customer but need not be. For example, the customer&apos;s assistant or spouse may be identified as the desired primary contact.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>MSISDN__c</fullName>
        <description>MSISDN Line number</description>
        <inlineHelpText>MSISDN Line number</inlineHelpText>
        <label>MSISDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription_Id__c</fullName>
        <label>Subscription Id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_ACCUMULATION_RECHARGE__c.object
<CustomObject>
    <fields>
        <fullName>Categoria__c</fullName>
        <label>Categoria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MSISDN__c</fullName>
        <label>MSISDN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Monto__c</fullName>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Suscripcion__c</fullName>
        <label>Suscripción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Cliente__c</fullName>
        <label>Tipo de Cliente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>GP ACCUMULATION RECHARGE</label>
    <nameField>
        <label>GP ACCUMULATION RECHARGE Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP ACCUMULATION RECHARGES</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GP_Condicional_logico__c.object
<CustomObject>
    <description>Condicional de regla - Gestor de Puntos</description>
    <fields>
        <fullName>Operador__c</fullName>
        <label>Operador</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Variable_a_comparar__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>=</fullName>
                </value>
                <value>
                    <fullName>!=</fullName>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>&gt;=</fullName>
                </value>
                <value>
                    <fullName>&lt;=</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regla__c</fullName>
        <label>Regla</label>
        <referenceTo>GP_Regla__c</referenceTo>
        <relationshipLabel>Condicionales logicos</relationshipLabel>
        <relationshipName>Condicionales_logicos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Valor_contra_el_que_se_compara__c</fullName>
        <label>Valor contra el que se compara</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Variable_a_comparar__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>BLACK</fullName>
                </value>
                <value>
                    <fullName>CLASSIC</fullName>
                </value>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS</fullName>
                </value>
                <value>
                    <fullName>GGCC</fullName>
                </value>
                <value>
                    <fullName>MOVIL-PREPAGO</fullName>
                </value>
                <value>
                    <fullName>MOVIL-ABONO</fullName>
                </value>
                <value>
                    <fullName>ARNET</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>PREPAGO-A-ABONO FIJO</fullName>
                </value>
                <value>
                    <fullName>ABONO FIJO-A-FACTURA</fullName>
                </value>
                <value>
                    <fullName>INTERNET-MAS-VELOCIDAD</fullName>
                </value>
                <value>
                    <fullName>CABLE-SUMAR FLOW</fullName>
                </value>
                <value>
                    <fullName>LOW</fullName>
                </value>
                <value>
                    <fullName>MID</fullName>
                </value>
                <value>
                    <fullName>MID HIGH</fullName>
                </value>
                <value>
                    <fullName>PREMIUM</fullName>
                </value>
                <value>
                    <fullName>integer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variable_a_comparar__c</fullName>
        <label>Variable a comparar</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Categoria De Socio</fullName>
                </value>
                <value>
                    <fullName>Tipo De Cliente</fullName>
                </value>
                <value>
                    <fullName>Tipo De Servicio</fullName>
                </value>
                <value>
                    <fullName>Tipo De Upselling</fullName>
                </value>
                <value>
                    <fullName>Equipo Categoria</fullName>
                </value>
                <value>
                    <fullName>Monto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GP Condicional logico</label>
    <nameField>
        <label>Condicional logico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condicionales logicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Lista_de_Asset__c.object
<CustomObject>
    <description>Assets del Socio - Gestor de Puntos</description>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>GP Lista de Assets</relationshipLabel>
        <relationshipName>GP_Lista_de_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MSISDN__c</fullName>
        <formula>Asset__r.MSISDN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSISDN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Puntos_acumulados_mes_0__c</fullName>
        <label>Puntos acumulados mes 0</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Puntos_acumulados_mes_1__c</fullName>
        <label>Puntos acumulados mes 1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Puntos_acumulados_mes_2__c</fullName>
        <label>Puntos acumulados mes 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Puntos_acumulados_mes_3__c</fullName>
        <label>Puntos acumulados mes 3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socio</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipLabel>GP Lista de Assets</relationshipLabel>
        <relationshipName>GP_Lista_de_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Puntos_Acumulados__c</fullName>
        <label>Total Puntos Acumulados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GP Lista de Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Lista de Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Regla__c.object
<CustomObject>
    <description>Reglas p/sumar o restar puntos - Gestor de Puntos</description>
    <fields>
        <fullName>Dias_vencimiento__c</fullName>
        <label>Dias para vencimiento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Operador_calculo__c</fullName>
        <label>Operador calculo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>+</fullName>
                </value>
                <value>
                    <fullName>-</fullName>
                </value>
                <value>
                    <fullName>*</fullName>
                </value>
                <value>
                    <fullName>/</fullName>
                </value>
                <value>
                    <fullName>%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Confiabilización</fullName>
                </value>
                <value>
                    <fullName>Premio Recarga 3M</fullName>
                </value>
                <value>
                    <fullName>Castigo Recarga</fullName>
                </value>
                <value>
                    <fullName>Recarga por Monto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cater</fullName>
                </value>
                <value>
                    <fullName>Antigüedad</fullName>
                </value>
                <value>
                    <fullName>Alta a FOL</fullName>
                </value>
                <value>
                    <fullName>Continuidad FOL</fullName>
                </value>
                <value>
                    <fullName>Alta a Débito Automatico</fullName>
                </value>
                <value>
                    <fullName>Descarga APP</fullName>
                </value>
                <value>
                    <fullName>Alta Nuevo Servicio Core</fullName>
                </value>
                <value>
                    <fullName>Referidos</fullName>
                </value>
                <value>
                    <fullName>Convergente Fiber</fullName>
                </value>
                <value>
                    <fullName>Convergente Arnet</fullName>
                </value>
                <value>
                    <fullName>Baja</fullName>
                </value>
                <value>
                    <fullName>Transferencia</fullName>
                </value>
                <value>
                    <fullName>Canje</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valor_calculo__c</fullName>
        <label>Valor calculo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variable_calculo__c</fullName>
        <label>Variable calculo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vigencia_desde__c</fullName>
        <label>Vigencia desde</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vigencia_hasta__c</fullName>
        <label>Vigencia hasta</label>
        <type>Date</type>
    </fields>
    <label>GP Regla</label>
    <nameField>
        <label>Nombre de Regla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Reglas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GP_Socio__c.object
<CustomObject>
    <description>Socio Club Personal - Gestor de Puntos</description>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo_total__c</fullName>
        <label>Saldo total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GP Acumulador</label>
    <nameField>
        <label>Nombre de Socio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Acumuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GP_AccumulationTriggerTest.cls
@isTest
Global with sharing class GP_AccumulationTriggerTest {
    @isTest
    static void testTriggerPremioOK() {
        //Contacto
        Contact pc = new Contact();
        pc.MobilePhone = '15304466';
        pc.Email = 'ns@salesforce.com';
        pc.FirstName = 'N';
        pc.LastName = 'S';
        insert pc;
        //Cuenta
        Account cuenta = new Account();
        cuenta.name = 'cuenta1';
        cuenta.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        cuenta.AccountIntegrationId__c = '111111111111';
        cuenta.vlocity_cmt__PrimaryContactId__c = pc.Id;
        insert cuenta;
        //Asset
        Asset a = new Asset(AccountId = cuenta.Id);
        a.Name = 'Asset Test';
        a.MSISDN__c = '2222';
        a.Subscription_Id__c = 'S2222';
        insert a;

        GP_Regla__c regla = new GP_Regla__c();
        regla.Tipo_de_evento__c = 'Premio Recarga 3M';
        regla.Dias_vencimiento__c = 90;
        regla.Variable_calculo__c = 'Monto';
        regla.Operador_calculo__c = '*';
        regla.Valor_calculo__c = 1;
        regla.Vigencia_desde__c = Date.Today() - 7;
        regla.Vigencia_hasta__c = Date.Today() + 7;
        insert regla;

        GP_Condicional_logico__c cond1 = new GP_Condicional_logico__c();
        cond1.Regla__c = regla.Id;
        cond1.Variable_a_comparar__c = 'Tipo De Cliente';
        cond1.Operador__c = '=';
        cond1.Valor_contra_el_que_se_compara__c = 'DNI';
        insert cond1;

        GP_Socio__c acum = new GP_Socio__c();
        acum.Activo__c = true;
        acum.Cuenta__c = cuenta.Id;
        acum.Saldo_total__c = 100;
        insert acum;

        GP_Lista_de_asset__c assetAcum = new GP_Lista_de_asset__c();
        assetAcum.Asset__c = a.Id;
        assetAcum.Socio__c = acum.Id;
        assetAcum.Puntos_acumulados_mes_0__c = 10;
        assetAcum.Puntos_acumulados_mes_1__c = 10;
        assetAcum.Puntos_acumulados_mes_2__c = 10;
        assetAcum.Puntos_acumulados_mes_3__c = 10;
        assetAcum.Total_Puntos_Acumulados__c = 40;
        insert assetAcum;
        
        GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
        accRecharge.Categoria__c = 'BLACK';
        accRecharge.Monto__c = 102;
        accRecharge.MSISDN__c = '2222';
        accRecharge.Suscripcion__c = 'S2222';
        accRecharge.Tipo_de_cliente__c = 'DNI';

        Test.StartTest();
        insert accRecharge;
        Test.StopTest();
        System.assertEquals(202, [ Select Saldo_total__c From GP_Socio__c Limit 1 ].Saldo_total__c );
    }

    @isTest
    static void testTriggerMes3Null() {
        //Contacto
        Contact pc = new Contact();
        pc.MobilePhone = '15304466';
        pc.Email = 'ns@salesforce.com';
        pc.FirstName = 'N';
        pc.LastName = 'S';
        insert pc;
        //Cuenta
        Account cuenta = new Account();
        cuenta.name = 'cuenta1';
        cuenta.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        cuenta.AccountIntegrationId__c = '111111111111';
        cuenta.vlocity_cmt__PrimaryContactId__c = pc.Id;
        insert cuenta;
        //Asset
        Asset a = new Asset(AccountId = cuenta.Id);
        a.Name = 'Asset Test';
        a.MSISDN__c = '2222';
        a.Subscription_Id__c = 'S2222';
        insert a;

        GP_Regla__c regla = new GP_Regla__c();
        regla.Tipo_de_evento__c = 'Recarga por Monto';
        regla.Dias_vencimiento__c = 90;
        regla.Variable_calculo__c = 'Monto';
        regla.Operador_calculo__c = '*';
        regla.Valor_calculo__c = 1;
        regla.Vigencia_desde__c = Date.Today() - 7;
        regla.Vigencia_hasta__c = Date.Today() + 7;
        insert regla;

        GP_Condicional_logico__c cond1 = new GP_Condicional_logico__c();
        cond1.Regla__c = regla.Id;
        cond1.Variable_a_comparar__c = 'Tipo De Cliente';
        cond1.Operador__c = '=';
        cond1.Valor_contra_el_que_se_compara__c = 'DNI';
        insert cond1;

        GP_Socio__c acum = new GP_Socio__c();
        acum.Activo__c = true;
        acum.Cuenta__c = cuenta.Id;
        acum.Saldo_total__c = 100;
        insert acum;

        GP_Lista_de_asset__c assetAcum = new GP_Lista_de_asset__c();
        assetAcum.Asset__c = a.Id;
        assetAcum.Socio__c = acum.Id;
        assetAcum.Puntos_acumulados_mes_0__c = 0;
        assetAcum.Puntos_acumulados_mes_1__c = 0;
        assetAcum.Puntos_acumulados_mes_2__c = 0;
        assetAcum.Puntos_acumulados_mes_3__c = 0;
        assetAcum.Total_Puntos_Acumulados__c = 0;
        insert assetAcum;
        
        GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
        accRecharge.Categoria__c = 'BLACK';
        accRecharge.Monto__c = 0;
        accRecharge.MSISDN__c = '2222';
        accRecharge.Suscripcion__c = 'S2222';
        accRecharge.Tipo_de_cliente__c = 'DNI';

        Test.StartTest();
        insert accRecharge;
        Test.StopTest();
        //System.assertEquals(202, [ Select Saldo_total__c From GP_Socio__c Limit 1 ].Saldo_total__c );
    }

    @isTest
    static void testTriggerExceptionSinMonto() {
        try{
            GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
            accRecharge.Categoria__c = 'BLACK';
            accRecharge.MSISDN__c = '2222';
            accRecharge.Suscripcion__c = 'S2222';
            accRecharge.Tipo_de_cliente__c = 'DNI';

            Test.StartTest();
            insert accRecharge;
            Test.StopTest();
        } catch(Exception ex) {
            //System.assertEquals('Error: ** El campo Monto__c es obligatorio.',ex.getMessage());
        }
    }

    @isTest
    static void testTriggerExceptionSinCategoria() {
        try{
            GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
            accRecharge.Monto__c = 0;
            accRecharge.MSISDN__c = '2222';
            accRecharge.Suscripcion__c = 'S2222';
            accRecharge.Tipo_de_cliente__c = 'DNI';

            Test.StartTest();
            insert accRecharge;
            Test.StopTest();
        } catch(Exception ex) {
            //
        }
    }

    @isTest
    static void testTriggerExceptionSinSuscripcion() {
        try{
            GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
            accRecharge.Categoria__c = 'BLACK';
            accRecharge.Monto__c = 0;
            accRecharge.MSISDN__c = '2222';
            accRecharge.Tipo_de_cliente__c = 'DNI';

            Test.StartTest();
            insert accRecharge;
            Test.StopTest();
        } catch(Exception ex) {
            //
        }
    }

    @isTest
    static void testTriggerExceptionSinTipoDeCliente() {
        try{
            GP_ACCUMULATION_RECHARGE__c accRecharge = new GP_ACCUMULATION_RECHARGE__c();
            accRecharge.Categoria__c = 'BLACK';
            accRecharge.Monto__c = 0;
            accRecharge.MSISDN__c = '2222';
            accRecharge.Suscripcion__c = 'S2222';

            Test.StartTest();
            insert accRecharge;
            Test.StopTest();
        } catch(Exception ex) {
            //
        }
    }
}