objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <description>Formula: Value of the AccountId field.</description>
        <formula>AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentAdjustment__c.object
<CustomObject>
    <description>Payment adjustments allow a Customer Service Rep to request an adjustment to a customer&apos;s billing statement. For example, this could occur as the result of a case that was registered to dispute a prior billing or product issue. Once the adjustment is approved, it can then be fed to the client&apos;s billing system for processing. This object can also be used to register a client&apos;s payment independent of any dispute.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship that establishes the means or means of payment that were configured as intention to use for the payment of the order.</description>
        <inlineHelpText>Relationship that establishes the means or means of payment that were configured as intention to use for the payment of the order</inlineHelpText>
        <label>Sale Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payment Adjustments</relationshipLabel>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments/Adjustments</relationshipLabel>
        <relationshipName>PaymentAdjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IFS_S031_Test.cls
@isTest 
public class IFS_S031_Test {
    @isTest static  void testGetCallout() {
        IFS_S031 service31 = new IFS_S031();
        Order ordenTest = new Order();
        Account accountTest = new Account();
        String accountIntID = '0026D000000tAmdPER';
        accountTest.AccountIntegrationId__c = accountTest.id;
        accountTest.Name = 'Juan Perez';
        insert accountTest;
        ordenTest.AccountId = accountTest.id;
        ordenTest.EffectiveDate = Date.today();
        ordenTest.status = 'Draft';
        insert ordenTest;
        map<String,Object> input = new map<String,Object>();
        map<String,Object> output = new map<String,Object>();
        map<String,Object> options = new map<String,Object>();
        input.put('IdOrder',ordenTest.id);
        vlocity_cmt__PaymentAdjustment__c payment = new vlocity_cmt__PaymentAdjustment__c();
        payment.Order__c=ordenTest.id;
        payment.vlocity_cmt__AccountId__c = accountTest.id;
        insert payment;
        service31.invokeMethod('test',input,output,options);
        system.assertEquals(1,1);
    }
    
}