objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/TriggeredSendNotificationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>It&apos;s used to map the Id of the Triggered Send of Marketing Cloud with the SF Service</description>
    <fields>
        <fullName>TriggeredSendMCId__c</fullName>
        <label>TriggeredSendMCId</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Triggered Send Notification Settings</label>
</CustomObject>

classes/TriggeredSendNotificationServiceTest.cls
@isTest
public class TriggeredSendNotificationServiceTest {

  @isTest static void testTriggeredSendMethods(){
    Map<String,Object> inputMap = new Map<String,Object>();
    Map<String,Object> outMap = new Map<String,Object>();
	Map<String,Object> options = new Map<String,Object>();
    
    Account account = TestDataFactory.createAccounts(1, 'Consumer')[0];
    account.AccountIntegrationId__c = '10000000564';

    List <Order> order = TestDataFactory.createOrders(2, account);
    options.put('orderId', order[0].Id);
    options.put('oldOrderId', order[1].Id);
    options.put('trackingStatus', 'Anulado');
    options.put('orderApprovalStatus', null);
    options.put('trackingStatusAnnulment', 'Exitoso');
        
    insert new TriggeredSendNotificationSettings__c(Name = 'CloseAnnulmentOrder', TriggeredSendMCId__c = 'CloseAnnulmentOrder');
    
    List<object> obj = new List<Object>();
    Map<String, Object> toMap = new Map<String, Object>();
    toMap.put('Address', '003temail@tes.com');
    toMap.put('SubscriberKey', '003temail@tes.com');
    toMap.put('Options', 'Options');
    toMap.put('Channel', 'Email');
    toMap.put('processName', 'CloseAnnulmentOrder');
    obj.add(toMap);
    inputMap.put('To', toMap);
    
    List<Object> toSendList = VlocityOpenInterfaceHelper.getListObjectsFromMap(inputMap, 'To');
    toMap = (Map<String, Object>)toSendList[0];
    
    Test.startTest();     
    TriggeredSendNotificationService tts = new TriggeredSendNotificationService();
    Map<String, Object> mapt = tts.validateParameters(toMap);  
    tts.invokeMethod('sendMessage', inputMap, outMap, options);
    tts.sendMessage(inputMap, outMap, 'typeSend');
    Test.stopTest();
  }
}