objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerIntegrationId__c</fullName>
        <externalId>true</externalId>
        <label>Customer Integration Id</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/FinancialPromotion__c.object
<CustomObject>
    <description>Financial Promotions #SalesTeam #Sprint17

In the framework of the #Fan project, it is requested to be able to configure in the CRM financial promotions that include promotions with banks, with credit cards and all means of payment available.

The financial promotions that are set up may have different application rules depending on the context in which a sale is being made, such as on the basis of specific offers or specific promotions for an area or force of sale. The promotion could also be made available based on the characteristics of the products, services or bundles configured or even characteristics of the customer who is making the purchase.</description>
    <fields>
        <fullName>Percentage__c</fullName>
        <formula>(Interest__c - 1 ) * 100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Porcentaje</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Financial Promotion</label>
    <nameField>
        <displayFormat>PF-{0000000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HW_Charge_Code_Taxes_CFT__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Charge_Code__c</fullName>
        <label>Charge Code</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>HW Charge Code Taxes CFT</label>
</CustomObject>

objects/Location__c.object
<CustomObject>
    <description>Locations</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>BillingMode__c</fullName>
        <label>BillingMode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BillingMode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PickUpStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pick Up Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Pick Up Store Location)</relationshipLabel>
        <relationshipName>OrdersForPickUp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveOneTimeTotal__c</fullName>
        <label>Effective Total: One Time Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__EffectiveOneTimeTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveRecurringTotal__c</fullName>
        <label>Effective Total: Monthly Charges</label>
        <summarizedField>OrderItem.vlocity_cmt__EffectiveRecurringTotal__c</summarizedField>
        <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrderTotal__c</fullName>
        <formula>vlocity_cmt__OneTimeTotal__c +  vlocity_cmt__Tax__c  +( vlocity_cmt__RecurringTotal__c *  vlocity_cmt__NumberOfContractedMonths__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Alicuota__c</fullName>
        <description>Overall Tax Rate applicable to the Product</description>
        <label>Alicuota</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveOneTimeTotal__c</fullName>
        <label>Effective One Time Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EffectiveRecurringTotal__c</fullName>
        <label>Effective Recurring Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute value data.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PricingLogData__c</fullName>
        <description>Detailed pricing log information for this line item stored as a JSON structure.</description>
        <label>Pricing Log</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Alicuota__c</fullName>
        <description>Overall Tax Rate applicable to the Product</description>
        <label>Alicuota</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0.105</fullName>
                </value>
                <value>
                    <fullName>0.21</fullName>
                    <default>true</default>
                    <label>0.21</label>
                </value>
                <value>
                    <fullName>0.262632</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>BillingMode__c</fullName>
        <label>Billing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BillingMode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location</description>
        <inlineHelpText>Location</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Store_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OrderPriceAdjustment__c.object
<CustomObject>
    <description>Represents a specific discount, fee, override price or charge applied to the overall order or to a specific line item. Used for write-in overrides, adjustments added through an applied promotion or any price, charge or fee identified for the order or line item. The price or adjustment indicates the action and sub-action requested such as adding or removing the price or adjustment as well as the date the change is requested to be applied. It also indicates the expected dates for any recurring but limited-time pricing.</description>
    <fields>
        <fullName>vlocity_cmt__Amount__c</fullName>
        <description>For write-in prices, the new or overriding amount. For example, $100 USD. This value is null for pricing using a selected pricing element since the pricing amount is defined by the selected pricing element.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order Pricing</label>
    <nameField>
        <label>Reference Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Pricing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentAdjustment__c.object
<CustomObject>
    <description>Payment adjustments allow a Customer Service Rep to request an adjustment to a customer&apos;s billing statement. For example, this could occur as the result of a case that was registered to dispute a prior billing or product issue. Once the adjustment is approved, it can then be fed to the client&apos;s billing system for processing. This object can also be used to register a client&apos;s payment independent of any dispute.</description>
    <fields>
        <fullName>Financial_Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Financial Promotion</description>
        <inlineHelpText>Financial Promotion</inlineHelpText>
        <label>Financial Promotion</label>
        <referenceTo>FinancialPromotion__c</referenceTo>
        <relationshipLabel>Payment Adjustments</relationshipLabel>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/BillingMode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Electronico</fullName>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
    </customValue>
    <masterLabel>Billing Mode</masterLabel>
</GlobalValueSet>

classes/KAL_integrationGetTaxes.cls
global with sharing class KAL_integrationGetTaxes implements vlocity_cmt.VlocityOpenInterface{
	
	global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
		Boolean result=false;
		if (methodName.equals('GetCalculatedTaxes')){
			GetCalculatedTaxes(inputMap, options);
			result = true;
		}
		return result;
	}
	
	public static Map<String, Object> GetCalculatedTaxes(Map<String,Object> inputMap, Map<String,Object> options){
		String orderId = (String)(options.get('OrderId'));
        String domicilio = (String)inputMap.get('delivery');
		System.debug(orderId);
		System.debug(domicilio);        		
        Map<String, Object> request = IntegrationS013Request(orderId, domicilio);
	    System.debug('request s013: '+JSON.serialize(request));
	    Map<String, Object> output = new Map<String, Object>();
	    Map<String, Object> options2 = new Map<String, Object>();	   
	    try{

    		vlocity_cmt.IntegrationProcedureService integProcService = new vlocity_cmt.IntegrationProcedureService();
	    	integProcService.invokeMethod('IFS_S013', request, output, options2);
	
    	}catch(Exception ex){
            System.debug('KAL_integrationGetTaxes:GetCalculatedTaxes -> exception: '+ex);
        	throw ex; 
		}

        if(output.isEmpty()){            
            throw new FuncException('Respuesta incorrecta en el servicio S013');            
        }                
        System.debug('response s013: ' + JSON.serialize(output));
        Map<String, Object> response = (Map<String, Object>)output.get('IPResult');               
	    return response;	    
	}
    	
	private static Map<String, Object> IntegrationS013Request(String orderId, String domicilio) {		
		Order order = [SELECT  OrderNumber, 
                Account.AccountIntegrationId__c, 
                Account.CustomerIntegrationId__c,
                CreatedDate,
                BillingMode__c,
                vlocity_cmt__OrderTotal__c,
                OriginStoreLocation__c,
                OriginStoreLocation__r.PointOfSaleId__c,
                OriginStoreLocation__r.Location__r.Name,
                OriginStoreLocation__r.vlocity_cmt__State__c,
                PickUpStoreLocation__c,
                PickUpStoreLocation__r.PointOfSaleId__c,
                PickUpStoreLocation__r.Location__r.Name,
                PickUpStoreLocation__r.vlocity_cmt__State__c
            FROM Order 
            WHERE Id = :orderId
        ];
            
        List<OrderItem> orderItems = taOrderController.GetOrderItemsBillable(orderId);
        Map<String, Object> request = new Map<String, Object>();
        Map<String, Object> calculoImpuestosPeticion = new Map<String, Object>();
        //calculoImpuestosPeticion.put('nivel', 'Cliente');
        //calculoImpuestosPeticion.put('idCliente', order.Account.CustomerIntegrationId__c);        
        Map<String, Object> infoPetCalculoImpuestos = new Map<String, Object>();
        List<Map<String, Object>> listaCantidadCargos = new List<Map<String, Object>>();

        // Obtengo todos los descuentos para luego aplicarlos en el order item que corresponde
        // y se ponen en una estructura tipo hashtable para poder acceder directamente luego
        Map<String, List<vlocity_cmt__OrderPriceAdjustment__c>> hashDescuentos = taOrderController.GetPriceAdjustmentsGroupByOrderItem(orderId);
        
        // // Total  sin impuestos
        Decimal totalBasePrice = 0;
        Integer i = 1;
        	for (OrderItem orderItem : orderItems){
        		String codCargo = '';
            	
            	Map<String, Object> chargeCode = AssetAttributesUtils.ObtenerChargeCode(orderItem.vlocity_cmt__Product2Id__r.vlocity_cmt__JSONAttribute__c);
            	if(chargeCode != null){
                codCargo = String.valueOf(chargeCode.get('value__c'));
            	}
            	
            	for(Integer j = 1 ; j <= orderItem.Quantity; j++){
	                Integer indice = (i*j)-1;
	                Map<String, Object> infoCargo = new Map<String, Object>();
	                Map<String, Object> cargo = new Map<String, Object>();

	                Decimal price = GetBasePrice(orderItem);
	                totalBasePrice = totalBasePrice + price;

	                String origenProducto = 'NAC';
	                Map<String, Object> attrbFabricacion = AssetAttributesUtils.GetJSONAttribute(orderItem.vlocity_cmt__Product2Id__r.vlocity_cmt__JSONAttribute__c, 'Fabricacion');
	                if(attrbFabricacion != null){
	                    // System.debug('despacho: ' + attrbFabricacion.get('value__c'));
	                    String despacho = String.valueOf(attrbFabricacion.get('value__c'));
	                    if(despacho != null){
	                        origenProducto = IntegrationUtils.ParseFabricacion(despacho);
	                    }
	                }            
	                cargo.put('codCargo', codCargo);
	                cargo.put('secuenciaProductoAdquirido', indice + 1);
	                cargo.put('precioBase', IntegrationUtils.ParseAmount(price));
	                cargo.put('cantUnidadesProdAdquiridas', '1');
	                cargo.put('codMoneda', 'ARS');
	                cargo.put('origenProducto', origenProducto);
	                cargo.put('bienUso', false);

	                /* aca hago todo lo de descuentos					
	                if(hashDescuentos != null && hashDescuentos.size() > 0){	                    
	                        cargo.put('listaDescuentos', listaDescuentos);
	                    }
	                }*/
	                // fin descuentos
	                infoCargo.put('infoCargo',cargo);
	                listaCantidadCargos.add(infoCargo);
            	}
            	i = i + 1;
            }
			
			// agrego los cargos de CFT
        if(order.vlocity_cmt__OrderTotal__c > 0){
            List<vlocity_cmt__PaymentAdjustment__c> payments = taOrderController.GetPaymentAdjustmentsWithCFT(OrderId);
            HW_Charge_Code_Taxes_CFT__c taxCFT = HW_Charge_Code_Taxes_CFT__c.getInstance('Default');
            String codCargo = taxCFT.Charge_Code__c;
            for (vlocity_cmt__PaymentAdjustment__c payment : payments){
                // System.debug('ENTROOO');
                Integer indice = i - 1;
                Map<String, Object> infoCargo = new Map<String, Object>();
                Map<String, Object> cargo = new Map<String, Object>();
    
                Decimal price = 0;
    
                // necesitamos pasar a HW el porcentaje del CFT del total de la orden sin impuestos.
                // si hubiese mas de un metodo de pago, tenemos q calcular primero el porcentaje que representa ese pago en el total de la orden y luego seguir con los calculos
                // asumo que el campo payment.vlocity_cmt__Amount__c viene sin el CFT calculado.
    
                // Ejemplo, si algo vale $8.000 (impuestos incluidos) y paga una tarjeta con $5.000 y otra $3.000 y ambas tienen un CFT del %5
                // buscamos el porcentaje que representa $3000 en el total de la orden
                // 3000 * 100 / 5000 = 37,5%
                
                System.debug('totalBasePrice: ' + totalBasePrice);

                Decimal percentaje = payment.vlocity_cmt__Amount__c * 100 / order.vlocity_cmt__OrderTotal__c;
                System.debug('payment.vlocity_cmt__Amount__c: ' + payment.vlocity_cmt__Amount__c);
                System.debug('order.vlocity_cmt__OrderTotal__c: ' + order.vlocity_cmt__OrderTotal__c);
                System.debug('porcentaje: ' + percentaje);
                // ahora obtengo el bruto con el porcentaje obtenido
                // 37,5% * $6611,5702 (total de la orden sin impuestos) / 100 = $2479,3388
                Decimal basePrice = percentaje * totalBasePrice / 100;
                System.debug('basePrice: ' + basePrice);
                // por ultimo calculo el CFT del bruto recien calculado
                // $2479,3388 * 0,05 / 100 = $123,9669 esto le tengo q mandar a HW para que calcule los impuestos del CFT aplicado
                price = basePrice * payment.Financial_Promotion__r.Percentage__c / 100;           
                System.debug('price: ' + price);

                cargo.put('codCargo', codCargo);
                cargo.put('secuenciaProductoAdquirido', indice + 1);
                cargo.put('precioBase', IntegrationUtils.ParseAmount(price));
                cargo.put('cantUnidadesProdAdquiridas', '1');
                cargo.put('codMoneda', 'ARS');
                cargo.put('origenProducto', 'NAC');
                cargo.put('bienUso', true);
                infoCargo.put('infoCargo',cargo);
                listaCantidadCargos.add(infoCargo);
    
                i = i + 1;
            }
        }

        infoPetCalculoImpuestos.put('listaCantidadCargos', listaCantidadCargos);
        Map<String, Object> infoVentas = new Map<String, Object>();
        infoVentas.put('fechaVenta', IntegrationUtils.ParseDateTime(DateTime.now()));

        //Obtener localidad y provincia        
        Map<String, Object> locationCodes = getCodProvincia(domicilio);
        infoVentas.put('codLocalidad', locationCodes.get('codLocalidad'));
        infoVentas.put('codMunicipio', 'string');
        infoVentas.put('codProvincia', locationCodes.get('codProvincia'));
        
        infoPetCalculoImpuestos.put('infoVentas', infoVentas);

        calculoImpuestosPeticion.put('infoPetCalculoImpuestos', infoPetCalculoImpuestos);
        calculoImpuestosPeticion.put('nivel', 'Cliente');
        calculoImpuestosPeticion.put('idCliente', order.Account.CustomerIntegrationId__c);        
        Map<String, Object> body = new Map<String, Object>();
        body.put('calculoImpuestosPeticion', calculoImpuestosPeticion);
     
        request.put('body', body);		
        System.debug('body' + JSON.serialize(body));
		return request;

    }

    private static Map<String, Object> getCodProvincia(String delivery){        
        Map<String, Object> locationCodes = new Map<String, Object>();
        System.debug('getCodProvincia');
            if(delivery.contains('Ciudad Autónoma de Buenos Aires')) {
                locationCodes.put('codLocalidad', 'Ciudad Autonoma de Buenos Aires');
                locationCodes.put('codProvincia', 'C');
                return locationCodes;    
            }
            else if(delivery.contains('Tierra del Fuego')) {                
                locationCodes.put('codLocalidad', 'Tierra del Fuego');
                locationCodes.put('codProvincia', 'V');
                return locationCodes;
            }
            else if(delivery.contains('Santa Cruz')){                
                locationCodes.put('codLocalidad', 'Santa Cruz');
                locationCodes.put('codProvincia', 'Z');
                return locationCodes;      
            }
            else if(delivery.contains('La Pampa')) {                
                locationCodes.put('codLocalidad', 'La Pampa');
                locationCodes.put('codProvincia', 'L');
                return locationCodes;
            }
            else if(delivery.contains('La Rioja')) {                
                locationCodes.put('codLocalidad', 'La Rioja');
                locationCodes.put('codProvincia', 'F');
                return locationCodes;
            }
            else if(delivery.contains('Catamarca')) {                
                locationCodes.put('codLocalidad', 'Catamarca');
                locationCodes.put('codProvincia', 'K');
                return locationCodes;
            }
            else if(delivery.contains('San Luis')) {                
                locationCodes.put('codLocalidad', 'San Luis');
                locationCodes.put('codProvincia', 'D');
                return locationCodes;
            }
            else if(delivery.contains('Chubut')){                
                locationCodes.put('codLocalidad', 'Chubut');
                locationCodes.put('codProvincia', 'U');
                return locationCodes;
            }
            else if(delivery.contains('Neuquén')) {                
                locationCodes.put('codLocalidad', 'Neuquen');
                locationCodes.put('codProvincia', 'Q');
                return locationCodes;
            }
            else if(delivery.contains('Formosa')){                
                locationCodes.put('codLocalidad', 'Formosa');
                locationCodes.put('codProvincia', 'P');
                return locationCodes;
            }
            else if(delivery.contains('Río Negro')) {                
                locationCodes.put('codLocalidad', 'Rio Negro');
                locationCodes.put('codProvincia', 'R');
                return locationCodes;
            }
            else if(delivery.contains('San Juan')){                
                locationCodes.put('codLocalidad', 'San Juan');
                locationCodes.put('codProvincia', 'J');
                return locationCodes;
            }
            else if(delivery.contains('Jujuy')) {                
                locationCodes.put('codLocalidad', 'Jujuy');
                locationCodes.put('codProvincia', 'Y');
                return locationCodes;
            }
            else if(delivery.contains('Sargento del Estero')){                
                locationCodes.put('codLocalidad', 'Sargento del Estero');
                locationCodes.put('codProvincia', 'G');
                return locationCodes;
            }
            else if(delivery.contains('Corrientes')) {                
                locationCodes.put('codLocalidad', 'Corrientes');
                locationCodes.put('codProvincia', 'W');
                return locationCodes;
            }
         return locationCodes;           
        }

	// el epc tiene los precios con IVA
    // por lo tanto vamos a buscar la alicuota aplicada a un nodo particular del jsonAttribute
    public static Decimal GetBasePrice(OrderItem orderItem){
        Decimal alicuota = 0;
        if(orderItem.vlocity_cmt__Product2Id__r.Alicuota__c != null){
            alicuota = Decimal.valueOf(orderItem.vlocity_cmt__Product2Id__r.Alicuota__c);
            alicuota = alicuota+1;
        } else {
            Map<String, Object> attrbAlicuota = AssetAttributesUtils.GetJSONAttribute(orderItem.vlocity_cmt__Product2Id__r.vlocity_cmt__JSONAttribute__c, 'Alicuota');
            if(attrbAlicuota != null){
                // System.debug('alicuota: ' + attrbAlicuota.get('value__c'));
                alicuota = Decimal.valueOf(String.valueOf(attrbAlicuota.get('value__c')));
                // convierto el 21 a 1.21 para poder dividirlo luego
                alicuota = (alicuota / 100) + 1;
            }
        }
        /*AM Sacar else donde se busca el attributo*/

        //System.debug('GetBasePrice:alicuota -> ' + alicuota);

        Decimal basePrice = getPrice(orderItem);
        if(alicuota > 0){
            basePrice = basePrice / alicuota;
        }        
        return basePrice;
    }	


 	private static Decimal getPrice(OrderItem orderItem){
        Decimal ret = 0;
        Map<String, Object> attribute = null;
        System.debug('pricinglogdata: ' + JSON.serialize(orderItem.vlocity_cmt__PricingLogData__c));
        if(orderItem.vlocity_cmt__PricingLogData__c == null){
            System.debug('orderItem.vlocity_cmt__EffectiveRecurringTotal__c: ' + orderItem.vlocity_cmt__EffectiveRecurringTotal__c);
            if(orderItem.vlocity_cmt__EffectiveOneTimeTotal__c != null){
                ret = orderItem.vlocity_cmt__EffectiveOneTimeTotal__c;
            }
            if(orderItem.vlocity_cmt__EffectiveRecurringTotal__c != null){
                ret += orderItem.vlocity_cmt__EffectiveRecurringTotal__c;
            }
        } else {
            Map<String, Object> priceLog = (Map<String, Object>)JSON.deserializeUntyped(orderItem.vlocity_cmt__PricingLogData__c);
            System.debug('vlocity_cmt__PricingLogData__c: ' + orderItem.vlocity_cmt__PricingLogData__c);
            Map<String,Object> logData = (Map<String,Object>)priceLog.get('LogData');
            List<Object> ot_std_prc = (List<Object>)logData.get('OT_STD_PRC');
            if(ot_std_prc == null){
                throw new FuncException('No se pudo obtener el precio del producto \'' + orderItem.vlocity_cmt__Product2Id__r.Name + '\'.');
            }           
            Map<String, Object> aux = (Map<String, Object>)ot_std_prc[0];
            ret = Decimal.valueOf(String.valueOf(aux.get('BaseValue')));
        }
        System.debug('getPrice:alicuota -> ' + ret);
        return ret;
    }

    public static Decimal GetBaseDiscount(String orderItemAlicuota, String jsonAttribute, String priceLog, String priceListEntryId){
        Decimal alicuota = 0;
        if(orderItemAlicuota != null){
            alicuota = Decimal.valueOf(orderItemAlicuota);
            alicuota = alicuota+1;
        } else {
            Map<String, Object> attrbAlicuota = AssetAttributesUtils.GetJSONAttribute(jsonAttribute, 'Alicuota');
            if(attrbAlicuota != null){
                // System.debug('alicuota: ' + attrbAlicuota.get('value__c'));
                alicuota = Decimal.valueOf(String.valueOf(attrbAlicuota.get('value__c')));
                // convierto el 21 a 1.21 para poder dividirlo luego
                alicuota = (alicuota / 100) + 1;
            }
        }
        System.debug('GetBaseDiscount:alicuota -> ' + alicuota);
        /*AM Sacar else donde se busca por json attribute */
        Decimal baseDiscount = getDiscount(priceLog, priceListEntryId);
        if(alicuota > 0){
            baseDiscount = baseDiscount / alicuota;
        }

        return baseDiscount;
    }
    
    private static Decimal getDiscount(String stringPriceLog, String priceListEntryId){
        Decimal ret = null;
        Map<String, Object> attribute = null;
        if(stringPriceLog != null){
            Map<String, Object> priceLog = (Map<String, Object>)JSON.deserializeUntyped(stringPriceLog);
            Map<String,Object> logData = (Map<String,Object>)priceLog.get('LogData');
            List<Object> ot_std_prc = (List<Object>)logData.get('OT_STD_PRC');

            for (Object element : ot_std_prc){
                Map<String, Object> aux = (Map<String, Object>)element;
                if(aux.get('PriceListEntryId') == priceListEntryId){
                    ret = Decimal.valueOf(String.valueOf(aux.get('BaseAdjustment'))) * -1;
                    break;
                }
            }
        }
        return ret;
    }
     
}