objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountIntegrationId__c</fullName>
        <description>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</description>
        <externalId>true</externalId>
        <inlineHelpText>Account Integration Id (concatena 11 digitos del Customer Integration Id y 5 del Billing Integration Id)</inlineHelpText>
        <label>Account Integration Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>MSISDN__c</fullName>
        <description>MSISDN Line number</description>
        <inlineHelpText>MSISDN Line number</inlineHelpText>
        <label>MSISDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Assets Using This Price List</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Orders Using This Price List</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Store the region that the store location belongs to.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to indicate the status of the point of sales or agency.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dado de baja</fullName>
                </value>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Pendiente activación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__Catalog__c.object
<CustomObject>
    <description>A catalog is a container of one or more items such as products. Catalogs can be contained within other catalogs forming a hierarchical structure for organizing the contained items.</description>
    <fields>
        <fullName>vlocity_cmt__Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Catalog</label>
    <nameField>
        <label>Catalog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__CatalogProductRelationship__c.object
<CustomObject>
    <description>Associates a product with a catalog or catalog category.</description>
    <fields>
        <fullName>vlocity_cmt__CatalogId__c</fullName>
        <label>Catalog</label>
        <referenceTo>vlocity_cmt__Catalog__c</referenceTo>
        <relationshipLabel>Catalog Product Relationships</relationshipLabel>
        <relationshipName>CatalogProductRelationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Catalog Product Relationships</relationshipLabel>
        <relationshipName>CatalogProductRelationships2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Catalog Product Relationship</label>
    <nameField>
        <label>Catalog Product Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Product Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <description>A price list represents the pricing for the products and services that your company offers. A base price list defines the baseline pricing for your products and services. A child price list inherits all the pricing from the base price list and contains exceptions to the baseline pricing.</description>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Pricebook2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Work_Place__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relates the Work Team with the Agency or Point of Sales.</description>
        <label>Work Place</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Work Teams</relationshipLabel>
        <relationshipName>Work_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Físico</fullName>
    </customValue>
    <customValue>
        <fullName>MVNO</fullName>
    </customValue>
    <customValue>
        <fullName>Telefónico</fullName>
    </customValue>
    <description>Used to indicate the top level of the channels in the solution.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>LITO</fullName>
        <label>Litoral</label>
    </customValue>
    <customValue>
        <fullName>MEDI</fullName>
        <label>Mediterranea</label>
    </customValue>
    <customValue>
        <fullName>SUR</fullName>
        <label>Sur</label>
    </customValue>
    <customValue>
        <fullName>LISU</fullName>
        <isActive>false</isActive>
        <label>LISU</label>
    </customValue>
    <customValue>
        <fullName>NOA</fullName>
        <isActive>false</isActive>
        <label>NOA</label>
    </customValue>
    <customValue>
        <fullName>LINO</fullName>
        <isActive>false</isActive>
        <label>LINO</label>
    </customValue>
    <description>Store the region division used in Telecom Argentina</description>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/IFS_S224_invoiceAndPaymentNotiTest.cls
@isTest
public class IFS_S224_invoiceAndPaymentNotiTest {
    static final String K_TIPO_DOCUMENTO_OK = 'DNI';
    static final String K_NMRO_DOCUMENTO_OK = '32987652';
    static final String K_NMRO_LINEA_OK = '1138305305';
    static final String K_ACCOUNT_NAME = 'TestS224Acc';

    private static final String K_MSISDN_OK  = '47774777';
    private static final String K_MSISDN_NOK = '49994999';
    private static final String K_CANAL_OK = 'IVR';
    private static final String K_CANAL_NOK = 'Presencial';
    private static final String K_ORDER_NAME = 'TestOrderS224';
    private static final String K_CATALOGO_NAME = 'IVR';


    @isTest static void testResponseStatus200 () {
        FromJSON jsonObj = new FromJSON();

        Account account = getAccountId ();
        Order order = [SELECT Id FROM Order WHERE AccountId = :account.Id];
        jsonObj.invoiceAndPaymentNotification.LegalInvoiceNumber='A0001-48484848';
        jsonObj.invoiceAndPaymentNotification.SalesOrderId=order.Id; 
        jsonObj.invoiceAndPaymentNotification.Status='Payment succeed';
        jsonObj.invoiceAndPaymentNotification.StatusInvoice='Invoice succeed';

        jsonObj.invoiceAndPaymentNotification.ReasonCode='Reason';
        jsonObj.invoiceAndPaymentNotification.ReasonCodeName='Reason';
        jsonObj.invoiceAndPaymentNotification.TotalInvoiceAmount=0;
        jsonObj.invoiceAndPaymentNotification.LegalInvoiceNumber='';

        System.debug('jsonObj: ' + JSON.serialize(jsonObj));

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure//Sales_CollectionAndBilling_invoiceAndPaymentNotification/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S224_invoiceAndPaymentNotification.getData();

        System.assertEquals(Integer.valueOf('200'), RestContext.response.statuscode); 
        Result resultado = (Result)JSON.deserialize(RestContext.response.responseBody.toString(), Result.class);
        System.assertNotEquals(null, resultado);
        System.assertEquals(0, resultado.resultCode);

        System.debug('Response: ' + RestContext.response.responseBody.toString());

        Test.stopTest();
    }


    @isTest static void testResponseStatus417 () {
        FromJSON jsonObj = new FromJSON();

        Account account = getAccountId ();
        Order order = [SELECT Id FROM Order WHERE AccountId = :account.Id];
        jsonObj.invoiceAndPaymentNotification.SalesOrderId=''; 
        jsonObj.invoiceAndPaymentNotification.Status='Payment succeed';
        jsonObj.invoiceAndPaymentNotification.StatusInvoice='';
        jsonObj.invoiceAndPaymentNotification.ReasonCode='';
        jsonObj.invoiceAndPaymentNotification.Comments='';
        jsonObj.invoiceAndPaymentNotification.ReasonCodeName='';
        jsonObj.invoiceAndPaymentNotification.TotalInvoiceAmount=0;
        jsonObj.invoiceAndPaymentNotification.LegalInvoiceNumber='';

        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/v1/integrationprocedure//Sales_CollectionAndBilling_invoiceAndPaymentNotification/';  
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(JSON.serialize(jsonObj));
        req.headers.put('Authorization', 'Bearer ' + UserInfo.getSessionID());
        req.headers.put('Content-Type', 'application/json');
        RestContext.request = req;
        RestContext.response = res;

        IFS_S224_invoiceAndPaymentNotification.getData();

        System.assertEquals(Integer.valueOf('417'), RestContext.response.statuscode); 
        List<ErrorClass> lstErrors = (List<ErrorClass>)JSON.deserialize(RestContext.response.responseBody.toString(), List<ErrorClass>.class);
        System.assertNotEquals(null, lstErrors);

        System.debug('Response: ' + RestContext.response.responseBody.toString());

        Test.stopTest();
    }


    ///////////////// Metodos de Creacion datos de Prueba //////////////////////

    @TestSetup
    private static void crearDatosPrueba () {
        System.debug('----- Entre en crearDatosPrueba');
        Account account = createAccount();
        //-- Perfiles del usuario --//
        vlocity_cmt__BusinessSite__c storeLocation = createStoreLocation ();
        WorkTeam__c workTeam = createWorkTeam (storeLocation.Id);
        createWorkTeamMember (workTeam.Id);
        //-- Datos de la prueba
        Pricebook2 priceBook = createPriceBook();
        Product2 product = createProduct();
        vlocity_cmt__PriceList__c priceList = createPriceList(priceBook.Id);
        PricebookEntry priceBookEntry = createPriceBookEntry(product, priceBook);
        vlocity_cmt__Catalog__c catalogo = createCatalog ();
        vlocity_cmt__CatalogProductRelationship__c relCatalogProd = createProductCatalogRelationship (catalogo, product);
        Asset rootAsset = createAssetRoot(account);

        createOrder(priceList, account);

        System.debug('----- Sali de crearDatosPrueba');
    }

    static Account getAccountId () {
        return [SELECT Id FROM Account WHERE Name = :K_ACCOUNT_NAME];
    }


    private static Account createAccount() {
        System.debug('---------- Entre en createAccount()');
        List<Account> lstAcc = new List<Account>();
        Account a = new Account(Name=K_ACCOUNT_NAME, AccountIntegrationId__c=String.valueOf(10000));
        a.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        lstAcc.add(a);
        Account b = new Account(Name='TelecomTest', AccountIntegrationId__c=String.valueOf(10001));
        b.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Billing').getRecordTypeId();
        lstAcc.add(b);
        insert lstAcc;
        return getCreatedAccount(K_ACCOUNT_NAME);
    }

    private static Account getCreatedAccount (String pName) {
        System.debug('-------------- Entre en getCreatedAccount()');
        Account a = [SELECT Id FROM Account WHERE Name = :pName];
        System.debug('-------------- Account Id: ' + a.Id);
        System.debug('-------------- Sali de getCreatedAccount()');
        return a;
    }

    private static vlocity_cmt__PriceList__c createPriceList(Id priceBookId){
        System.debug('---------- Entre en createPriceList()');
        vlocity_cmt__PriceList__c taPriceList = new vlocity_cmt__PriceList__c(Name='Telecom Price List', vlocity_cmt__Code__c='PRL_TELCOM',
            vlocity_cmt__Description__c='Create for IFS_S445 Testing', vlocity_cmt__Pricebook2Id__c=priceBookId);

        insert taPriceList;
        return  [SELECT id FROM vlocity_cmt__PriceList__c WHERE vlocity_cmt__Code__c = 'PRL_TELCOM'];
    }
    
    private static Product2 createProduct() {
        System.debug('---------- Entre en createProduct()');
        Product2 prod = new Product2(Name='TestProduct');
        insert prod;
        return  [SELECT Id FROM Product2 WHERE Name = 'TestProduct'];
    }

    private static Pricebook2 createPriceBook(){
        System.debug('---------- Entre en createPriceBook()');
        Pricebook2 priceBook = new Pricebook2(Name='PriceBook for IFS_S224 Testing');
        insert priceBook;
        return  [SELECT Id FROM Pricebook2 WHERE Name = 'PriceBook for IFS_S224 Testing'];
    }

    private static PricebookEntry createPriceBookEntry(Product2 pProd, Pricebook2 pPriceBook2) {
        System.debug('---------- Entre en createPriceBookEntry()');
        Id standardPBId = Test.getStandardPricebookId();
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = standardPBId,
            Product2Id = pProd.Id, UnitPrice = 111.85, IsActive = true);

        insert standardPrice;
        return  [SELECT Id FROM PricebookEntry WHERE Product2Id = :pProd.Id AND IsActive = true AND Pricebook2Id = :standardPBId];
    }    

    private static vlocity_cmt__Catalog__c createCatalog () {
      System.debug('---------- Entre en createCatalog()');  
      vlocity_cmt__Catalog__c catalogo = new vlocity_cmt__Catalog__c(
          Name=K_CATALOGO_NAME, vlocity_cmt__Description__c='Catalog for IFS_S224 Testing', vlocity_cmt__IsActive__c=true);  
        insert catalogo;
        return  [SELECT Id, Name FROM vlocity_cmt__Catalog__c WHERE Name = :catalogo.Name ];
    }

    private static vlocity_cmt__CatalogProductRelationship__c createProductCatalogRelationship (vlocity_cmt__Catalog__c pCatalogo, Product2 pProd) {
        System.debug('---------- Entre en createProductCatalogRelationship()'); 
        vlocity_cmt__CatalogProductRelationship__c prodCatalogRel = new vlocity_cmt__CatalogProductRelationship__c(
            Name=pCatalogo.Name, vlocity_cmt__CatalogId__c=pCatalogo.Id, vlocity_cmt__IsActive__c=true, vlocity_cmt__Product2Id__c=pProd.Id );

        insert prodCatalogRel;
        return  [SELECT Id, vlocity_cmt__Product2Id__c FROM vlocity_cmt__CatalogProductRelationship__c WHERE Name=:pCatalogo.Name];
    }

    public static Asset createAssetRoot(Account pAcc){
        System.debug('---------- Entre en createAssetRoot()'); 
        Asset a = new Asset();
        a.Product2Id = createPlan().Id;
        a.Accountid = pAcc.Id;
        a.name = 'RootAsset-Test';
        a.MSISDN__c = K_MSISDN_OK;
        insert a;
        return  [SELECT Id FROM Asset WHERE Accountid = :pAcc.Id AND Name = 'RootAsset-Test'];
    }

    private static Product2 createPlan (){
        System.debug('---------- Entre en createPlan()'); 
        Product2 service = new Product2(Name='Plan - Test', Family='Movil');
        insert service;
        return  [SELECT Id FROM Product2 WHERE Name = 'Plan - Test' AND Family = 'Movil'];
    }


    static void createOrder(vlocity_cmt__PriceList__c pTAPriceList, Account pAccount) {
        Order order = new Order(Name=K_ORDER_NAME, AccountId=pAccount.Id, EffectiveDate=Date.today(),
                                    Status='Draft', Pricebook2Id =Test.getStandardPricebookId(),
                                        vlocity_cmt__PriceListId__c=pTAPriceList.Id, Delivery_Method__c='Delivery',
                                                    vlocity_cmt__OriginatingChannel__c='Agentes');

        insert order;
    }


    static Id getPricebookId () {
        vlocity_cmt__CatalogProductRelationship__c prodCatalogRel = [SELECT Id, vlocity_cmt__Product2Id__c FROM vlocity_cmt__CatalogProductRelationship__c WHERE Name=:K_CATALOGO_NAME];
        Id productId = prodCatalogRel.vlocity_cmt__Product2Id__c;
        PricebookEntry priceBookEntry = [SELECT Id FROM PricebookEntry WHERE Product2Id = :productId AND IsActive = true AND Pricebook2Id = :Test.getStandardPricebookId()];
        return priceBookEntry.Id;
    }

    private static vlocity_cmt__BusinessSite__c createStoreLocation () {
        System.debug('---------- Entre en createStoreLocation()');

        System.debug('------------ Antes de crear el Account (Organization) ----');
        Account orgAcc = getCreatedAccount('TelecomTest');
        System.debug('------------ Despues de crear el Account (Organization) ----');
        vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(Name='Centro de Servicio Santa Fe', 
            vlocity_cmt__OrganizationId__c=orgAcc.Id, Status__c='Activo', Type__c='POS', Channel__c='Físico',
             Channel_Type__c='Oficinas Comerciales', Channel_Type_2__c='Oficinas Comerciales', Channel_Type_3__c='Oficinas Comerciales',
             Region__c='AMBA', RecordTypeId=Schema.SObjectType.vlocity_cmt__BusinessSite__c.getRecordTypeInfosByName().get('Punto de venta OC').getRecordTypeId());
        insert storeLocation;     
        return [SELECT Id FROM vlocity_cmt__BusinessSite__c WHERE Name='Centro de Servicio Santa Fe'];     

/*        vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(Name='Barrio Norte', 
            vlocity_cmt__OrganizationId__c=orgAcc.Id, Status__c='Activo', Type__c='POS', Channel__c='Físico',
             Channel_Type__c='Agentes', Channel_Type_2__c='Agentes', Channel_Type_3__c='Agentes',
             Region__c='AMBA');
        insert storeLocation;     
        return [SELECT Id FROM vlocity_cmt__BusinessSite__c WHERE Name='Barrio Norte'];    */
}

    private static WorkTeam__c createWorkTeam (Id pStoreLocationId) {
        System.debug('---------- Entre en createWorkTeam()');
        WorkTeam__c wt = new WorkTeam__c(Name='Ventas', Team_Name__c='Ventas', Is_Active__c=true, Work_Place__c=pStoreLocationId);
        insert wt;
        return [SELECT Id FROM WorkTeam__c WHERE Name='Ventas'];
    }

    private static void createWorkTeamMember (Id pWorkTemaId) {
        System.debug('---------- Entre en createWorkTeamMember()');
        Team_Member__c wtm = new Team_Member__c(User_member__c=UserInfo.getUserId(), Work_Team__c=pWorkTemaId);
        wtm.UserRoleAPIName__c='Care';

        insert wtm;
    }


    public class FromJSON {
        public FromJSON_1 invoiceAndPaymentNotification; 
        public FromJSON() {
            invoiceAndPaymentNotification = new FromJSON_1();
        }
    }

    public class FromJSON_1 {
        public String SalesOrderId; 
        public String Status;
        public String StatusInvoice;
        public String ReasonCode;
        public String Comments;
        public String ReasonCodeName;
        public Decimal TotalInvoiceAmount;
        public String LegalInvoiceNumber;
    }

    public class Result {
        public Integer resultCode=-1;
        public String message;
    }

    public class ErrorClass {
        public String errorCode;
        public String message;
    }

    public class FromBadJSON2 {
        public String dummy1; 
        public String dummy2; 
    }


}