objects/Account.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AutoPaymentAmount__c</fullName>
        <label>Auto Payment Amount</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Full Balance</fullName>
                </value>
                <value>
                    <fullName>Minimum Due</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__EnableAutopay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Autopay</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__OrderProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Product from which this asset was created or most recently updated.</description>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/AssetsMinimalDateFilter__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Set for minimal assets date used in range selection</description>
    <fields>
        <fullName>AssetMinDate__c</fullName>
        <description>Asset minimal date</description>
        <label>Asset Min Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Assets Minimal Date Filter</label>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>DeliveryDate__c</fullName>
        <description>Delivery Date - xOM</description>
        <inlineHelpText>Delivery Date - xOM</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/AssetUtilsTest.cls
@isTest
public class AssetUtilsTest {
    
    @testSetup private static void gerenateData() {
        
        AssetsMinimalDateFilter__c assetMin = new AssetsMinimalDateFilter__c(Name = 'FilterDate', AssetMinDate__c = Date.today());
        insert assetMin;
        
        Account acc = new Account(Name = 'Customer', vlocity_cmt__EnableAutopay__c = true, vlocity_cmt__AutoPaymentAmount__c  = 'Full Balance', Phone = '123245');
        insert acc;
        
        // Asset asst = new Asset(Name = 'Asset', AccountId = acc.Id);
        // insert asst;
        List<Order> listOrder = TestDataFactory.createOrders(1,acc);
        Order order = listOrder[0];
        List<Product2> product = TestDataFactory.createProduct(1);
        List<Asset> assets = TestDataFactory.createAssets(1,product.get(0),acc);
        List<OrderItem> orderItems = TestDataFactory.createOrderItemsWithAsset(1,order,assets.get(0));
        assets[0].vlocity_cmt__OrderProductId__c = orderItems[0].Id;
        update assets;

        Case c = new Case(AssetId = assets[0].Id);
        insert c;

        Asset assetaux = [SELECT vlocity_cmt__OrderProductId__r.OrderId FROM Asset WHERE Id = :assets[0].Id LIMIT 1];
        System.debug(assetaux);
        Order orderaux = [SELECT Id, OriginStoreLocation__c, CreatedDate, DeliveryDate__c, Delivery_Method__c, vlocity_cmt__OriginatingChannel__c
                         FROM Order
                        WHERE Id = : assetaux.vlocity_cmt__OrderProductId__r.OrderId];
        System.debug(orderaux);
    }
    
    @isTest private static void testInvoke() {
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options;
        
        Id assId = [SELECT Id FROM Asset LIMIT 1].Id;
        inputMap.put('Id', assId);

        AssetUtils au = new AssetUtils();

        Test.startTest();
        	au.invokeMethod('getNegotiations', inputMap, outMap, options);
        Test.stopTest();
    }

    @isTest private static void testInvoke2() {
        Map<String,Object> inputMap = new Map<String,Object>();
        Map<String,Object> outMap = new Map<String,Object>();
        Map<String,Object> options;
        
        Id assId = [SELECT Id FROM Asset LIMIT 1].Id;
        inputMap.put('Id', assId);

        AssetUtils au = new AssetUtils();

        Test.startTest();
        	au.invokeMethod(null, inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest private static void testNegotiation(){       
        AssetUtils.Negotiation assUtil = new AssetUtils.Negotiation();
        
        assUtil.Name = '';
        assUtil.negDate = Date.today();
        assUtil.negNumber = '';
        assUtil.negType = '';
        assUtil.status = '';
    }

    @isTest private static void getOrdersByAsset(){
        Id assetId = [SELECT Id FROM Asset LIMIT 1].Id;
        AssetUtils utils = new AssetUtils();
        List<OrderItem> orders = utils.getOrdersByAsset(assetId);
    }

    @isTest private static void getOrderByAsset(){
        Id assetId = [SELECT Id FROM Asset LIMIT 1].Id;
        Order order = AssetUtils.getOrderByAsset(assetId);
    }

    @isTest private static void getCasesByAsset(){
        Id assetId = [SELECT Id FROM Asset LIMIT 1].Id;
        AssetUtils utils = new AssetUtils();
        List<Case> cases = utils.getCasesByAsset(assetId);
    }
}