objects/Account.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__ContactPreferences__c</fullName>
        <description>The preferred method (or methods) of communications to the parties of this account such as mail, email or phone.</description>
        <label>Contact Preferences</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                    <label>Teléfono</label>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>eMail</fullName>
                    <label>Correo electrónico</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PermanencyDueDate__c</fullName>
        <description>Permanency Due Date</description>
        <inlineHelpText>Permanency Due Date</inlineHelpText>
        <label>Permanency Due Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Email1__c</fullName>
        <description>generic email field type</description>
        <inlineHelpText>generic email field type</inlineHelpText>
        <label>Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Cerrado</fullName>
                </value>
                <value>
                    <fullName>Confirmado</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
                <value>
                    <fullName>Fallo Envio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>String1__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>String2__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <recordTypes>
        <fullName>EmailToSend</fullName>
        <active>true</active>
        <label>Email to send</label>
    </recordTypes>
    <recordTypes>
        <fullName>SMSTracking</fullName>
        <active>true</active>
        <label>SMS Tracking</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MessagingConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>DaysBeforeExpiration__c</fullName>
        <label>Days Before Expiration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Messaging Configuration</label>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_sales_notifyIncomingExpirations.cls
global with sharing class ta_sales_notifyIncomingExpirations implements Database.Batchable<sObject>, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        MessagingConfig__c msgCon = MessagingConfig__c.getInstance('Default');
        DateTime daysto = Date.Today().addDays((Integer)(msgCon.DaysBeforeExpiration__c + 1));
        String query = 'SELECT Id, Email, Account.vlocity_cmt__ContactPreferences__c, Phone FROM Contact WHERE PermanencyDueDate__c = ' + daysto.format('YYYY-MM-dd');
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Contact> contacts = (List<Contact>) scope;
        List<CrossObject__c> crossObjects = new List<CrossObject__c>();
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'CrossObject__c' AND DeveloperName = 'EmailToSend'];

        RecordType trackingrt = [SELECT Id FROM RecordType WHERE SObjectType = 'CrossObject__c' AND DeveloperName = 'SMSTracking'];

        CrossObject__c smsTemplateConfig = [SELECT Id, String1__c FROM CrossObject__c WHERE Picklist1__c = 'Vencimiento de plazo de permanencia' AND RecordType.Name = 'SMS Template' LIMIT 1];
        

        for(Contact c: contacts){
            if(c.Account.vlocity_cmt__ContactPreferences__c != null){
                if(c.Account.vlocity_cmt__ContactPreferences__c.indexOf('eMail') != -1){
                    crossObjects.add(new CrossObject__c(Email1__c = c.Email, RecordTypeId = rt.Id, Picklist1__c = 'Vencimiento de plazo de permanencia'));
                }else if(c.Account.vlocity_cmt__ContactPreferences__c.indexOf('SMS') != -1){
                    /*String body = '{"body": {"request": {"Target": {"User": {"Celnumber": "'+ cellnumber +'"}}},"communicationText": "'+ text +'"}}';
                    Map<String, Object> input = (Map<String, Object>) JSON.deserializeUntyped(body);
                    Map<String, Object> output = new Map<String, Object>();
                    Map<String, Object> options2 = new Map<String, Object>();
                    vlocity_cmt.IntegrationProcedureService integProcServ = new vlocity_cmt.IntegrationProcedureService();
                    integProcServ.invokeMethod('IFS_S159', input, output, options2);*/
                    crossObjects.add(new CrossObject__c(String1__c = c.Phone, String2__c = smsTemplateConfig.String1__c, RecordTypeId = trackingrt.Id, DateTime1__c = System.now(), Picklist1__c = 'Vencimiento de plazo de permanencia', Status__c = 'Pendiente'));
                }
            }
        }

        insert crossObjects;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }

    public void execute(Schedulablecontext ctx){
        ta_sales_notifyIncomingExpirations batch = new ta_sales_notifyIncomingExpirations ();
        Database.executeBatch(batch);
    }
}