objects/Account.object
<CustomObject>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>#Marketing #Sprint15 Atributo de mayor ponderación aplicado a la cuenta que se visualizará en V360.</description>
        <label>Attribute</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/AttributesWeighing__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>#Sprint16 #Marketing Tabla de ponderación de atributos para Account y Contact</description>
    <fields>
        <fullName>Attribute__c</fullName>
        <description>Attribute Name</description>
        <label>Attribute</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Salesforce Object</description>
        <label>Object</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weighing__c</fullName>
        <description>Attribute weighing</description>
        <label>Weighing</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ponderación de Atributos</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Attribute__c</fullName>
        <label>Attribute</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AttributesWeighingControllerTest.cls
/**
 * @Author: Julia Carranza
 * @Description: This test tests the AttributesWeighingController Class.
 */
@isTest
public class AttributesWeighingControllerTest {

		static testMethod void myUnitTest(){
		String jubilado = 'Jubilado';
		String estrategico = 'Estratégico';
		String menor = 'Menor';
		String vip = 'VIP';
        String prensa = 'Prensa';
		String account = 'Account';
        String contact = 'Contact';

		AttributesWeighing__c aw1 = new AttributesWeighing__c(Name = 'aw1', Attribute__c = jubilado, Object__c = account, Weighing__c = 1);
		AttributesWeighing__c aw2 = new AttributesWeighing__c(Name = 'aw2', Attribute__c = estrategico, Object__c = account, Weighing__c = 2);
		AttributesWeighing__c aw3 = new AttributesWeighing__c(Name = 'aw3', Attribute__c = menor, Object__c = account, Weighing__c = 3);
		AttributesWeighing__c aw4 = new AttributesWeighing__c(Name = 'aw4', Attribute__c = vip, Object__c = contact, Weighing__c = 4);
        AttributesWeighing__c aw5 = new AttributesWeighing__c(Name = 'aw5', Attribute__c = prensa, Object__c = contact, Weighing__c = 5);

		Test.StartTest(); 

		Database.Insert(aw1);
		Database.Insert(aw2);
		Database.Insert(aw3);
		Database.Insert(aw4);
	    
	    PageReference pageRef1 = Page.AttributesWeighing; 
	    attributesWeighingController cont1 = new attributesWeighingController();

	    cont1.refillAttributesList();
	    cont1.cancel();
	    cont1.save();

	    Test.StopTest();
	}

    //PageReference pageRef3 = Page.AttributesByProfile;
    //PageReference pageRef4 = Page.AttributeRulesCreation;
    /*attributesWeighingController cont2 = new attributesWeighingController();
    cont2.refillAttributesList();
    cont2.cancel();
    cont2.save();*/
}