objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Subscription_Id__c</fullName>
        <label>Subscription Id</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Case</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CantidadAjuste__c</fullName>
        <description>Este campo es necesario para guardar en el caso la cantidad (monto en peso, tiempo, Megas) en base a la unidad seleccionada</description>
        <label>Cantidad Ajuste</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Store the team that is working in the case, it is updated each time that the case is resigned to handle the RAV.</description>
        <label>Owner Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TipoOperacionAjuste__c</fullName>
        <description>Campo necesario en ajustes para guardar si es Debito o Credito.</description>
        <label>TipoOperacionAjuste</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TipoSeleccion__c</fullName>
        <description>Field dependiente que me permite seleccionar si se trata de una cuenta o un servicio para mostrar el Tipo Concepto, Tipo Cargo, Tipo Item.</description>
        <label>TipoSeleccion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cuenta</fullName>
                </value>
                <value>
                    <fullName>Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UnidadAjuste__c</fullName>
        <description>Este campo es necesario para guardar en el caso la unidad de ajuste correspondiente.</description>
        <label>Unidad Ajuste</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Datos(Mb)</fullName>
                </value>
                <value>
                    <fullName>Voz</fullName>
                </value>
                <value>
                    <fullName>Credito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ServiceId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the service Asset which is the subject of this Case.</description>
        <label>Service ID</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2 OR 3</booleanFilter>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Asset.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Asset.vlocity_cmt__BillingAccountId__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Asset.vlocity_cmt__ServiceAccountId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>BillingMode__c</fullName>
        <label>BillingMode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BillingMode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderApprovalStatus__c</fullName>
        <description>Order Status when approval needed from Administración de Ventas profile.</description>
        <label>OrderApprovalStatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de aprobación</fullName>
                </value>
                <value>
                    <fullName>Aprobado por ADV</fullName>
                </value>
                <value>
                    <fullName>Rechazada por ADV</fullName>
                </value>
                <value>
                    <fullName>Aprobada automáticamente</fullName>
                </value>
                <value>
                    <fullName>Devuelto al Vendedor</fullName>
                </value>
                <value>
                    <fullName>Rechazado por Cliente</fullName>
                </value>
                <value>
                    <fullName>Aprobado por Cliente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>approver__c</fullName>
        <label>Approver</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>true</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>BillingMode__c</fullName>
        <label>Billing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BillingMode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <recordTypes>
        <fullName>Digital</fullName>
        <active>true</active>
        <description>Store the information of the store locations responsible of digital channel.</description>
        <label>Digital</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the manager of the workplace</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/BillingMode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Electronico</fullName>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
    </customValue>
    <masterLabel>Billing Mode</masterLabel>
</GlobalValueSet>

globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Físico</fullName>
    </customValue>
    <customValue>
        <fullName>MVNO</fullName>
    </customValue>
    <customValue>
        <fullName>Telefónico</fullName>
    </customValue>
    <description>Used to indicate the top level of the channels in the solution.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/CaseTriggerHandlerTest.cls
@isTest
public class CaseTriggerHandlerTest {

    @testSetup
    public static void createDataTest() {
        List<Account> accounts = TestDataFactory.createAccounts(1);
        List<Asset> assets = TestDataFactory.createAssets(1, accounts.get(0));
    }


    @isTest
    public static void updateCaseDataOnInsertTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        WorkTeam__c wt = TestDataFactory.createWorkTeam('WorkTeamTestCase');
        Team_Member__c tm = TestDataFactory.setTeamMember('TeamMemberTestCase', UserInfo.getUserId(), wt);

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');

        //WHEN
        CaseTriggerHandler.updateCaseDataOnInsert(cases);

        //THEN
        System.assert(true);


    }

    @isTest
    public static void updateCaseOnUpdateTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');

        //WHEN
        CaseTriggerHandler.updateCaseOnUpdate(cases);

        //THEN
        System.assert(true);


    }

    @isTest
    public static void checkUserProfileOnDeleteTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');

        //WHEN
        CaseTriggerHandler.checkUserProfileOnDelete(cases);

        //THEN
        System.assert(true);


    }

    @isTest
    public static void updateChildonMassiveTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');
        Map<Id, Case> casesMap = new Map<Id, Case>(cases);

        for (Case c: cases) {
            c.Status = 'Resuelta Masiva';
        }

        //WHEN
        CaseTriggerHandler.updateChildonMassive(cases, casesMap);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void escalarCasoTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        Profile profile = [SELECT Name FROM Profile LIMIT 1];

        User u = TestDataFactory.createUser(profile.Name);

        WorkTeam__c wtParent = new WorkTeam__c(
            Name = 'WorkTeamTestCaseParent',
            Team_Name__c = 'WorkTeamTestCaseParent',
            Is_Active__c = true,
            Manager__c = u.Id
        );
        insert wtParent;



        WorkTeam__c wt = TestDataFactory.createWorkTeam('WorkTeamTestCase');
        wt.Manager__c = UserInfo.getUserId();
        wt.Parent_Team__c = wtParent.id;
        update wt;

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');

        for (Case c: cases) {
            c.Status = 'Expirada';
            c.Subject = 'Inconvenientes con cargos tasados y facturados';
            c.Approver__c = UserInfo.getUserId();
            c.vlocity_cmt__Amount__c = 400;
        }

        //WHEN
        CaseTriggerHandler.escalarCaso(cases);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void validateSplitAmountTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        Profile profile = [SELECT Name FROM Profile LIMIT 1];

        User u = TestDataFactory.createUser(profile.Name);

        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');
        Map<Id, Case> casesMap = new Map<Id, Case>();

        for (Case c: cases) {
            c.Subject = 'Inconvenientes con cargos tasados y facturados';
            c.OwnerId = u.Id;
            c.vlocity_cmt__Amount__c = 400;

            casesMap.put(c.Id, new Case(
                                Subject = c.Subject,
                                AccountId = c.AccountId,
                                AssetId = c.AssetId,
                                OwnerId = UserInfo.getUserId())
            );
        }

        //WHEN
        CaseTriggerHandler.validateSplitAmount(cases, casesMap);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void submitApprovalProcessTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        List<Case> cases = TestDataFactory.createCases(1, account.Id, asset.Id, 'Subject');

        String escalamiento = 'RAV_Escalamiento_a_Equipo';
        String caseId = cases.get(0).Id;

        //WHEN
        CaseTriggerHandler.submitApprovalProcess(escalamiento, caseId);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void setAdjustment9Test () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        asset.Subscription_Id__c = 'Subscription_Id__c';
        update asset;
        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Servicio',
                                UnidadAjuste__c = 'Credito',
                                TipoOperacionAjuste__c = 'DEBITO',
                                vlocity_cmt__Amount__c = 400,
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Set<Id> casesId = new Set<Id>();
        casesId.add(c.Id);

        //WHEN
        CaseTriggerHandler.setAdjustment(casesId);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void setAdjustment1Test () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        asset.Subscription_Id__c = 'Subscription_Id__c';
        update asset;
        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Servicio',
                                UnidadAjuste__c = 'Credito',
                                TipoOperacionAjuste__c = 'CREDITO',
                                vlocity_cmt__Amount__c = 400,
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Set<Id> casesId = new Set<Id>();
        casesId.add(c.Id);

        //WHEN
        CaseTriggerHandler.setAdjustment(casesId);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void setAdjustment2Test () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Servicio',
                                TipoOperacionAjuste__c = 'NC - Libre',
                                UnidadAjuste__c = 'VOZ',
                                vlocity_cmt__Amount__c = 400,
                                CantidadAjuste__c = '10:10:10',
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Set<Id> casesId = new Set<Id>();
        casesId.add(c.Id);

        //WHEN
        CaseTriggerHandler.setAdjustment(casesId);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void setAdjustment3Test () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];

        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Cuenta',
                                TipoOperacionAjuste__c = 'NC - Libre',
                                UnidadAjuste__c = 'VOZ',
                                vlocity_cmt__Amount__c = 400,
                                CantidadAjuste__c = '10:10:10',
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Set<Id> casesId = new Set<Id>();
        casesId.add(c.Id);

        //WHEN
        CaseTriggerHandler.setAdjustment(casesId);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void callToIntegrationS479Test () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Servicio',
                                UnidadAjuste__c = 'Credito',
                                TipoOperacionAjuste__c = 'CREDITO',
                                vlocity_cmt__Amount__c = 400,
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Map<String, Object> output = new Map<String, Object>();

        //WHEN
        CaseTriggerHandler.callToIntegrationS479(c, output);

        //THEN
        System.assert(true);
    }

    @isTest
    public static void getTotalItemsForVouchersTest () {
        //GIVE
        Account account = [SELECT Id FROM Account LIMIT 1];
        Asset asset = [SELECT Id FROM Asset LIMIT 1];
        Case c = new Case(
                                Subject='Inconvenientes con cargos tasados y facturados',
                                AccountId = account.Id,
                                AssetId = asset.Id,
                                TipoSeleccion__c = 'Servicio',
                                UnidadAjuste__c = 'Credito',
                                TipoOperacionAjuste__c = 'CREDITO',
                                vlocity_cmt__Amount__c = 400,
                                vlocity_cmt__ServiceId__c = asset.Id);
        insert c;

        Map<String, Object> response = new Map<String, Object>();
        Map<String, Object> listaDetalle = new Map<String, Object>();
        List<Object> elementoDetalle = new List<Object>();
        Map<String, Object> elemento = new Map<String, Object>();
        elemento.put('montoNetoAjuste', 200.00);
        Map<String, Object> importeFacturaFinal = new Map<String, Object>();
        importeFacturaFinal.put('importeItemComprobanteSinImp', 400.00);
        elemento.put('importeFacturaFinal', importeFacturaFinal);
        elemento.put('codCargo','codCargo');
        Map<String, Object> idItemCorreccion = new Map<String, Object>();
        idItemCorreccion.put('nroItemComprobante', 'nroItemComprobante');
        idItemCorreccion.put('montoNetoAjuste', 'montoNetoAjuste');
        elemento.put('idItemCorreccion',idItemCorreccion);
        elementoDetalle.add(elemento);
        listaDetalle.put('elementoDetalle', elementoDetalle);
        Map<String, Object> solicitudCorreccionInformacion = new Map<String, Object>();
        solicitudCorreccionInformacion.put('listaDetalle', listaDetalle);
        response.put('solicitudCorreccionInformacion', solicitudCorreccionInformacion);

        //WHEN
        CaseTriggerHandler.getTotalItemsForVouchers(c, account, response);

        //THEN
        System.assert(true);
    }
    
    @IsTest static void Test_updateCaseTechServiceCriteria(){

        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accountObj = new Account (
            Name='Account Test', 
            RecordTypeId = businessRecordTypeId
        );
        insert accountObj;
 
       /* Entitlement entitleTest = New Entitlement(
            Name= 'TechCare-OrderAcceptance',
            AccountId = accountObj.id
        );
        insert entitleTest;   */    
        
        List<Order> testOrder = TestDataFactory.createOrders(1,accountObj);
        testOrder[0].OrderApprovalStatus__c = 'Pendiente de aprobación';
        update testOrder;
        /*Order orderTest = New Order(
             AccountId =accountObj.Id,
             Status = 'Draft',
             OrderApprovalStatus__c = 'Pendiente de aprobación',
             Delivery_Method__c='Delivery',
             EffectiveDate = date.today()
         );
        
        insert orderTest;*/
        
        Id techServiceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical Service').getRecordTypeId();
        Case caseObj2 = New Case(
            Origin = 'Personalizado',
            AccountId = accountObj.Id,
            RecordTypeId = techServiceRecordTypeId,
            Subject = 'Gestión de Servicio Técnico',
            Order__c = testOrder[0].Id
            );
        insert caseObj2;
        
        
        Test.startTest();
        caseObj2.Status = 'En espera del cliente';
        Update caseObj2;            
        Test.stopTest();
        Case finalCase = [SELECT Id,AccountId,EntitlementId FROM Case WHERE AccountId =: accountObj.Id LIMIT 1];
        system.AssertNotEquals(null,finalCase.EntitlementId);
        
    }
    
    @IsTest static void Test_updateCaseTechServiceCriteria_Derivada(){
        /*MilestoneType miles = New MilestoneType();
        miles.Name = 'TechCare10Days';
        miles.RecurrenceType = 'recursChained';
        insert miles;*/
        
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accountObj = new Account (
            Name='Account Test', 
            RecordTypeId = businessRecordTypeId
        );
        insert accountObj;      
        
        /*Order orderTest = New Order(
             AccountId =accountObj.Id,
             Status = 'Draft',
             OrderApprovalStatus__c = 'Pendiente de aprobación',
             Delivery_Method__c='Delivery',
             EffectiveDate = date.today()
         );
         insert orderTest;*/
         
         
        List<Order> testOrder = TestDataFactory.createOrders(1,accountObj);
        testOrder[0].OrderApprovalStatus__c = 'Pendiente de aprobación';
        update testOrder;
        
        Id techServiceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical Service').getRecordTypeId();
        Case caseObj2 = New Case(
            Origin = 'Personalizado',
            AccountId = accountObj.Id,
            RecordTypeId = techServiceRecordTypeId,
            Subject = 'Gestión de Servicio Técnico',
            Order__c = testOrder[0].Id
            );
        insert caseObj2;
        
        CaseHistory testHistory = New CaseHistory();
        testHistory.Field = 'Owner';
        testHistory.CaseId = caseObj2.Id;
        insert testHistory;
        
        
        User testUser = TestDataFactory.createUser('System Administrator');
        Map<id,id> idQueueMap = New Map<Id,Id>();
        idQueueMap.put(caseObj2.Id,testUser.Id);
        Map<id,String> casesMap = New Map<id,String>();
        String caseString = Json.serialize(caseObj2);
        casesMap.put(caseObj2.Id,caseString);
        
        
        Test.startTest();
        caseObj2.Status = 'Derivada';
        Update caseObj2;
        CaseTriggerHandler.setFirstBackOfficeQueueFuture(casesMap,idQueueMap);
        Test.stopTest();
        
    }
    
    /*@IsTest static void setFirstBackOfficeQueueFuture_test(){
        MilestoneType miles = New MilestoneType();
        miles.Name = 'TechCare10Days';
        miles.RecurrenceType = 'recursChained';
        insert miles;
        
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accountObj = new Account (
            Name='Account Test', 
            RecordTypeId = businessRecordTypeId
        );
        insert accountObj;
        
        User testUser = TestDataFactory.createUser('Vlocity_Developer');
        
        Id techServiceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical Service').getRecordTypeId();
        Case caseObj2 = New Case(
            Origin = 'Personalizado',
            AccountId = accountObj.Id,
            RecordTypeId = techServiceRecordTypeId,
            Subject = 'Gestión de Servicio Técnico'
            );
        insert caseObj2;
        
        CaseMilestone csMiles = New CaseMilestone();
        csMiles.CaseId = caseObj2.Id;
        csMiles.MilestoneTypeId = miles.Id;
        csMiles.TargetDate = datetime.now();
        insert csMiles;
        
        Map<id,id> idQueueMap = New Map<Id,Id>();
        idQueueMap.put(caseObj2.Id,testUser.Id);
        Map<id,String> casesMap = New Map<id,String>();
        String caseString = Json.serialize(caseObj2);
        casesMap.put(caseObj2.Id,caseString);
        
    }*/
    
    @IsTest static void SetOwnerTeam_Test(){
        List<Account> accountTest = TestDataFactory.createAccounts(1,'Business');
        //vlocity_cmt__BusinessSite__c storeLoc = TestDataFactory.createStoreLocation('Test location',accountTest[0].Id);
        vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c();
        storeLocation.Name = 'test name';
        storeLocation.BillingMode__c = 'Fiscal';
        storeLocation.Channel__c = 'Digital';
        storeLocation.Channel_Type__c = 'SMS';
        storeLocation.Channel_Type_2__c = 'SMS';
        storeLocation.Channel_Type_3__c = 'SMS';
        storeLocation.Vlocity_cmt__OrganizationId__c = accountTest[0].Id;
        insert storeLocation;
        
        WorkTeam__c workTeam = TestDataFactory.createWorkTeam('wt Test',storeLocation);
        User userTest = TestDataFactory.createUser('System Administrator');
        Team_Member__c tmTest = TestDataFactory.setTeamMember('testwk',userTest.Id,workTeam);
        List<Case> caseTest = TestDataFactory.createCases(1,accountTest[0].Id,'test');
        
        Test.startTest();
        caseTest[0].OwnerId = userTest.Id;
        update caseTest;
        Test.stopTest();
        
        Case caseDummy = [SELECT id,OwnerId,Owner_Team__c FROM Case WHERE Id =: caseTest[0].Id];
        System.assertNotEquals(null, caseDummy.Owner_Team__c);
    }

}