objects/Asset.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>The current provisioning, or fulfillment, status of the asset with values such as New, Active, Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RootItemId__c</fullName>
        <label>RootItemId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Codigo_Movimiento_Inventario__c</fullName>
        <label>Codigo Movimiento Inventario</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Suspend</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Modify</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                    <isActive>false</isActive>
                    <label>Nominacion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset that this Order Product was pushed to by Order To Asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Product</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Product2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>(NOTE: The functionality of this field is replaced by the Action, Sub-Action and Fulfilment Status fields.) The desired provisioning action for the asset identified on this line item. Values include New (add), Active (no change), Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RootItemId__c</fullName>
        <label>RootItemId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubAction__c</fullName>
        <description>The sub-action requested for this line item typically used for moves of service from one location to another with values of Move-Add and Move-Delete. Move-Add means this item is being added as part of the move and usually should be added before the previous service is disconnected. Move-Delete means this item is the service to be disconnected after the service is activated at the new location.</description>
        <label>Sub Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Suspend-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Suspend-Fraude</fullName>
                </value>
                <value>
                    <fullName>Suspend-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Resume-Fraude</fullName>
                </value>
                <value>
                    <fullName>Resume-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Full suspend</fullName>
                </value>
                <value>
                    <fullName>Baja-Baja</fullName>
                </value>
                <value>
                    <fullName>Baja-PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Codigo_Movimiento_Inventario__c</fullName>
        <label>Codigo Movimiento Inventario</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tangible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indica si un producto es tangible o no</description>
        <label>Tangible</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>sinister_type__c</fullName>
        <label>Tipo Siniestro</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Robo</fullName>
                </value>
                <value>
                    <fullName>Hurto</fullName>
                </value>
                <value>
                    <fullName>Extravio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrderItems.cls
public class OrderItems extends ApplicationDomain {
    public OrderItems(List<OrderItem> orderItems) {
        Super(orderItems);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain Construct(List<SObject> sObjectList) {
            return new OrderItems(sObjectList);
        } 
    }

    public void SetActionsForSuspension(fflib_ISObjectUnitOfWork unitOfWork, SuspensionReason suspReason) {
        for (OrderItem orderItem : (List<OrderItem>) this.Records) {
            orderItem.Vlocity_cmt__Action__c = OrderItemAction.Change.Name();
            orderItem.Vlocity_cmt__ProvisioningStatus__c = OrderItemProvisioningStatus.Suspend.Name();

            if (suspReason == SuspensionReason.Administrativa)
                orderItem.Vlocity_cmt__SubAction__c = 'Suspend-Fraude';
            else
                orderItem.Vlocity_cmt__SubAction__c = 'Suspend-Siniestro';

            if (orderItem.vlocity_cmt__Product2Id__r.Tangible__c == true)
                orderItem.Codigo_Movimiento_Inventario__c = this.GetStockMovementCode(OrderType.Suspension, suspReason.Name());

            unitOfWork.RegisterDirty(orderItem);
        }
    }

    public void SetActionsForResume(fflib_ISObjectUnitOfWork unitOfWork, Map<Id, Asset> assetsWithActiveSuspension) {
        for (OrderItem orderItem : (List<OrderItem>) this.Records) {
            orderItem.Vlocity_cmt__Action__c = OrderItemAction.Change.Name();
            orderItem.Vlocity_cmt__ProvisioningStatus__c = OrderItemProvisioningStatus.Resume.Name();

            if (orderItem.vlocity_cmt__Product2Id__r.Tangible__c == true) {
                Asset orderItemAsset;

                if (orderItem.Vlocity_cmt__AssetId__r.Vlocity_cmt__RootItemId__c != null)
                    orderItemAsset = (Asset) assetsWithActiveSuspension.Get(orderItem.Vlocity_cmt__AssetId__r.Vlocity_cmt__RootItemId__c);
                else 
                    orderItemAsset = (Asset) assetsWithActiveSuspension.Get(orderItem.Vlocity_cmt__AssetId__c);

                if (orderItemAsset.Transaction_History_Entries__r != null && orderItemAsset.Transaction_History_Entries__r.Size() > 0) {
                    String suspensionReason = orderItemAsset.Transaction_History_Entries__r[0].Sinister_type__c;            
                    orderItem.Codigo_Movimiento_Inventario__c = this.GetStockMovementCode(OrderType.Resume, suspensionReason);
                }
            }

            unitOfWork.RegisterDirty(orderItem);
        }
    }

     private String GetStockMovementCode(OrderType orderGestion, String suspReason) {
        String stockMovementCode;

        if (orderGestion == OrderType.Suspension) {
            if (suspReason == SuspensionReason.Robo.Name())
                stockMovementCode = 'STCR';
            else if (suspReason == SuspensionReason.Hurto.Name() || suspReason == SuspensionReason.Administrativa.Name())
                stockMovementCode = 'STCH';
            else if (suspReason == SuspensionReason.Extravio.Name())
                stockMovementCode = 'STCE';
        }
        else if (orderGestion == OrderType.Resume) {
            if (suspReason == SuspensionReason.Robo.Name())
                stockMovementCode = 'RTCR';
            else if (suspReason == SuspensionReason.Hurto.Name() || suspReason == SuspensionReason.Administrativa.Name())
                stockMovementCode = 'RTCH';
            else if (suspReason == SuspensionReason.Extravio.Name())
                stockMovementCode = 'RTCE';
        }
        
        return stockMovementCode;
    }
}