objects/Asset.object
<CustomObject>
    <fields>
        <fullName>MSISDN__c</fullName>
        <description>MSISDN Line number</description>
        <inlineHelpText>MSISDN Line number</inlineHelpText>
        <label>MSISDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Assets Using This Price List</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>MSISDN__c</fullName>
        <formula>Asset.MSISDN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSISDN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Price list used by contracts</description>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TrackingStatus__c</fullName>
        <label>Tracking status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de pago</fullName>
                </value>
                <value>
                    <fullName>Preparar pedido</fullName>
                </value>
                <value>
                    <fullName>Pendiente de entrega</fullName>
                </value>
                <value>
                    <fullName>Entregado</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Validacion de Identidad</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Validacion</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por mora</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por fraude</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida voluntariamente</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por siniestro</fullName>
                </value>
                <value>
                    <fullName>Línea suspendida por Dorma</fullName>
                </value>
                <value>
                    <fullName>Línea de Baja</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Time Out Store PickUp</fullName>
                </value>
                <value>
                    <fullName>Cobrado</fullName>
                </value>
                <value>
                    <fullName>Pago No Concretado</fullName>
                </value>
                <value>
                    <fullName>Recargado</fullName>
                </value>
                <value>
                    <fullName>Recarga SOS exitosa</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulacion</fullName>
                </value>
                <value>
                    <fullName>Fraude</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Validacion Rechazada</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout Caja</fullName>
                </value>
                <value>
                    <fullName>Anulado</fullName>
                </value>
                <value>
                    <fullName>Exitoso</fullName>
                </value>
                <value>
                    <fullName>Cancelada - Timeout</fullName>
                </value>
                <value>
                    <fullName>Inicial</fullName>
                </value>
                <value>
                    <fullName>Cerrada - No corresponde</fullName>
                </value>
                <value>
                    <fullName>Cerrada Exitosa - Reclamo</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago por Vencimiento de Plazo de Retiro</fullName>
                </value>
                <value>
                    <fullName>Pendiente de Anulación de Pago</fullName>
                </value>
                <value>
                    <fullName>Pago Fallido</fullName>
                </value>
                <value>
                    <fullName>READY_WC</fullName>
                    <label>Conciliada Ok</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Orders Using This Price List</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <description>A price list represents the pricing for the products and services that your company offers. A base price list defines the baseline pricing for your products and services. A child price list inherits all the pricing from the base price list and contains exceptions to the baseline pricing.</description>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Pricebook2Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>PriceLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/AssetConciliatorTriggerTest.cls
@isTest
private class AssetConciliatorTriggerTest {
	
	@isTest static void TestCaseUpdate() {
		
		 Map<String,Object> inputMap = new Map<String,Object>();
      Map<String,Object> outMap = new Map<String,Object>();
      Map<String,Object> options = new Map<String,Object>();

      AssetConciliator assetConciliator = new AssetConciliator();

      Case getCase = createCase ();
     
  		String orderId =  getCase.Order__c;
        Order orderTest = [SELECT Id, Gestion__c, Status, TrackingStatus__c FROM Order where Id = :orderId];

      Test.startTest();
       
        orderTest.TrackingStatus__c = 'READY_WC';
      
        Database.SaveResult result2 = Database.update(orderTest,false);
      Test.stopTest();


	}
	
  public static Account createAccount (){

      Account newAccountExample = new Account();
      newAccountExample.Name='New Account Test Conciliator';

      insert newAccountExample;
      return newAccountExample;
    }

    public static Asset createAsset(){

      Account accountExample = createAccount();
      Product2 prod = createProduct(1)[0];
      Contact contactExample = createContacts(accountExample);

      Asset newAssetExample = new Asset(Name='New Asset Test', Product2Id=prod.Id, AccountId=accountExample.Id, ContactId=contactExample.Id, MSISDN__c='1123568749');

      insert newAssetExample;
      return newAssetExample;
    }

    public static Case createCase(){

     Asset getAsset = createAsset();
     Order getOrder = createOrder(getAsset);


     Case newCaseExample = new Case(
      Subject='New Case Test Conciliator',
      AccountId = getAsset.AccountId,
      AssetId = getAsset.Id,
      Order__c = getOrder.Id,
      Status = 'Informada');

     insert newCaseExample;


     return newCaseExample;
   }

   public static Order createOrder (Asset assetTest){


    Contract contractExample = new Contract(Name='New Order Test Conciliator',StartDate=Date.Today(),Status = 'Draft', AccountId = assetTest.AccountId,  ContractTerm = 4);
    insert contractExample;

    vlocity_cmt__PriceList__c taPriceList = createPriceList('Telecom Price List');

    Order orderExample = new Order();
    orderExample.Name = 'test order conciliator';
    orderExample.AccountId = assetTest.AccountId;
    orderExample.ContractId = contractExample.Id;
    orderExample.Pricebook2Id =Test.getStandardPricebookId();
    orderExample.EffectiveDate = Date.Today();
    orderExample.Status = 'Draft';
    orderExample.vlocity_cmt__PriceListId__c=taPriceList.Id;
    orderExample.Delivery_Method__c = 'Presencial';
    orderExample.vlocity_cmt__OriginatingChannel__c='Agentes';   
    orderExample.TrackingStatus__c ='Inicial';
	orderExample.Gestion__c = 'Conciliate'; 

    insert orderExample;

    createOrderItem(2, orderExample);

    return orderExample;

  }


  public static vlocity_cmt__PriceList__c createPriceList(String name){
    String priceBookId = createPriceBook('TA Price Book').Id;

    vlocity_cmt__PriceList__c taPriceList =
    new vlocity_cmt__PriceList__c(Name=name,
      vlocity_cmt__Code__c='1',
      vlocity_cmt__Pricebook2Id__c=priceBookId);

    insert taPriceList;

    return taPriceList;
  }

  public static Pricebook2 createPriceBook(String name){
    Pricebook2 priceBook = new Pricebook2(Name=name);

    insert priceBook;

    return priceBook;
  }

  public static void createOrderItem(Integer numOrders, Order Ord) {

     List<OrderItem> OIList = new List<OrderItem>();
     List<product2>Prod=createProduct(1);
     PricebookEntry standardPrice = new PricebookEntry(
      Pricebook2Id =Test.getStandardPricebookId(),
      Product2Id = prod[0].Id,
      UnitPrice = 10000, IsActive = true);

     insert standardPrice;

     for(Integer i=0;i<numOrders;i++) {
       OrderItem oi = new OrderItem(OrderId=Ord.id,Quantity=decimal.valueof('1'),UnitPrice=1,PricebookEntryId=standardPrice.id);

       OIList.add(oi);
     }

     insert OIList;

  }

   public static List<Product2> createProduct(Integer numProd) {
      List<Product2> prods = new List<Product2>();

      for(Integer i=0;i<numProd;i++) {
        Product2 a = new Product2(Name='TestProduct '+i, ProductCode='TestProductCode');
        prods.add(a);
      }

      insert prods;

      return prods;
  }


  public static Contact createContacts(Account acc){

   Contact newContact = new Contact(FirstName='firstNameTest',
                                    LastName='lastNameTest',
                                    AccountId=acc.Id);

    insert newContact;
   return newContact;

  }
	
}