objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Linked_Product_Family__c</fullName>
        <formula>TEXT(Product2.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Linked Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Producto__c</fullName>
        <formula>TEXT( Product2.vlocity_cmt__Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tipo de Producto</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>imei__c</fullName>
        <label>Imei</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Define el  subtipo de un caso por ejemplo Siebel , Negocio Net, Negocio 2000 ( , campo agregado a solicitud de Telecom )</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Siebel</fullName>
                </value>
                <value>
                    <fullName>Negocio Net</fullName>
                </value>
                <value>
                    <fullName>Negocio 2000</fullName>
                </value>
                <value>
                    <fullName>Web de gestión móvil</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Paginas externas</fullName>
                </value>
                <value>
                    <fullName>Avaya  CMS Supervisor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Internet Monitor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitos Online</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitor Reportes</fullName>
                </value>
                <value>
                    <fullName>Avaya APC (Agente)</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC / ONE X</fullName>
                </value>
                <value>
                    <fullName>Avaya IC Manager</fullName>
                </value>
                <value>
                    <fullName>Avaya IN - Caída Total</fullName>
                </value>
                <value>
                    <fullName>Avaya ONE X</fullName>
                </value>
                <value>
                    <fullName>Banner de Productividad</fullName>
                </value>
                <value>
                    <fullName>Herramientas de Gestión/ Atencion</fullName>
                </value>
                <value>
                    <fullName>Inconveniente con las llamadas</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con correo</fullName>
                </value>
                <value>
                    <fullName>Página de Niveles</fullName>
                </value>
                <value>
                    <fullName>Social Media - WebLogueo</fullName>
                </value>
                <value>
                    <fullName>Trans Routing</fullName>
                </value>
                <value>
                    <fullName>TUID</fullName>
                </value>
                <value>
                    <fullName>Grabador NICE</fullName>
                </value>
                <value>
                    <fullName>Epiron (Redes Sociales)</fullName>
                </value>
                <value>
                    <fullName>Novedad Informativa</fullName>
                </value>
                <value>
                    <fullName>SNAP</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Descripción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Imei__c</fullName>
        <description>Representa el valor del Imei de un equipo o dispositivo para el cual existe una transacción de suspension o habilitación</description>
        <label>Imei</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Campo utilizado para identificar si es una suspensión de siniestro o administrativa</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Administrativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sinister_type__c</fullName>
        <label>Tipo Siniestro</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Robo</fullName>
                </value>
                <value>
                    <fullName>Hurto</fullName>
                </value>
                <value>
                    <fullName>Extravio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TaCareSuspensionsAndReconnections.cls
global class TaCareSuspensionsAndReconnections implements vlocity_cmt.VlocityOpenInterface {
    private Map<String, Object> input;
    private Map<String, Object> output;
    private Map<String, Object> options;

    global Boolean invokeMethod(String methodName, Map<String, Object> input, Map<String, Object> output, Map<String, Object> options) {
        try {
            this.input = input;
            this.output = output;
            this.options = options;

            switch on methodName {
                when 'SuspendAssets' {
                    this.SuspendAssets();
                }
                when 'ResumeAssets' {
                    this.ResumeAssets();
                }
                when 'SubmitOrders' {
                    this.SubmitOrders();
                }
                when 'createListChildCasesUnfraudBA' {
                    this.createListChildCasesUnfraudBA();
                }
                when 'SuspencreateListChildCasesFraudBAdAssets' {
                    this.createListChildCasesFraudBA();
                }
                when 'createListChildCasesAssets' {
                    this.createListChildCasesAssets();
                }
                when 'getSuspendedDevicesByAccountId' {
                    this.getSuspendedDevicesByAccountId();
                }
                when 'createTrasactionHistory' {
                    this.createTrasactionHistory();
                }
                when 'GetAssetByIMEI' {
                    this.GetAssetByIMEI();
                }
                when 'GetNewGuid' {
                    this.GetNewGuid();
                }                
            }

            return true;
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private void SuspendAssets() {
        try {
            Id accountId = (Id) this.options.get('AccountId');
            String suspensionReason = (String) this.options.get('SuspensionReason');
            String deviceAssetIdToSuspend = (String) this.options.get('DeviceAssetIdToSuspend');
            String prepaidAssetIdToSuspend = (String) this.options.get('PrepaidAssetIdToSuspend');
            Set<Id> assetToSuspendIds = new Set<Id>();

            if (String.IsNotEmpty(deviceAssetIdToSuspend))
                assetToSuspendIds.Add(deviceAssetIdToSuspend);
            
            if (String.IsNotEmpty(prepaidAssetIdToSuspend))
                assetToSuspendIds.Add(prepaidAssetIdToSuspend);

            Id orderId = AssetService.Suspend(accountId, assetToSuspendIds, this.GetSuspensionReasonType(suspensionReason));
            this.output.put('OrderId', orderId);
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private void ResumeAssets() {
        try {
            Id accountId = (Id) this.options.get('AccountId');
            String deviceAssetIdToResume = (String) this.options.get('DeviceAssetIdToResume');
            String prepaidAssetIdToResume = (String) this.options.get('PrepaidAssetIdToResume');
            Set<Id> assetToResumeIds = new Set<Id>();

            if (String.IsNotEmpty(deviceAssetIdToResume))
                assetToResumeIds.Add(deviceAssetIdToResume);
            
            if (String.IsNotEmpty(prepaidAssetIdToResume))
                assetToResumeIds.Add(prepaidAssetIdToResume);

            Id orderId = AssetService.Resume(accountId, assetToResumeIds);
            this.output.put('OrderId', orderId);
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private void GetAssetByIMEI() {
        try {
            AssetsSelector assetsSelector = (AssetsSelector) Application.Selector.NewInstance(Asset.SObjectType);
            String IMEI = (String) this.options.get('IMEI');

            List<Asset> assets = assetsSelector.SelectByIMEI(new Set<String> { IMEI });

            if (!assets.IsEmpty()) {     
                this.output.put('AccountId', assets[0].AccountId);
                this.output.put('Status', assets[0].Status);
                this.output.put('AssetId', assets[0].Id);
            }
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private void SubmitOrders() {
        try {
            String orderId = (String) this.options.get('OrderId');
            Set<Id> orderToSubmitIds = new Set<Id>();

            if (String.IsNotEmpty(orderId))
                orderToSubmitIds.Add(orderId);

            OrderService.Submit(orderToSubmitIds);
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private SuspensionReason GetSuspensionReasonType(String strSuspensionReason) {
        try {
            for (SuspensionReason suspReason : SuspensionReason.values()) {
                if (suspReason.Name() == strSuspensionReason)
                    return suspReason;
            }

            return null;
        }
        catch (Exception ex) {
            throw ex;
        }
    }

    private void createListChildCasesUnfraudBA() {
        Id parentId = (Id) input.get('DRId_Case');
        // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('BillingAccs');
        
        List<Case> listChildCases = new List<Case>();

        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            Id accId =  (Id) baMap.get('Id');
            Case myCase = new Case();
            myCase.ParentId = parentId;
            myCase.AccountId = accId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativo';
            myCase.Status = 'Cerrado';
            listChildCases.add(myCase);
        }
        insert listChildCases;
        output.put('Cases',listChildCases);
    }

    private void createListChildCasesFraudBA() {
        Id parentId = (Id)input.get('DRId_Case');
       // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('FraudBillingAccs');

        List<Case> listChildCases = new List<Case>();
        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            Id accId =  (Id) baMap.get('Id');
            Case myCase = new Case();
            myCase.ParentId = parentId;
            myCase.AccountId = accId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativo';
            myCase.Status = 'Cerrado';
            listChildCases.add(myCase);
        }
        insert listChildCases;
        output.put('Cases',listChildCases);
    }
    
    private void createListChildCasesAssets() {
        Id parentId = (Id)input.get('DRId_Case');
        Id orderId = (Id) input.get('OrderId');
        Id recordTypeId = (Id) options.get('RecordTypeId');
        Id subtype = (String) options.get('SubType');
       // Map<String, Object> clientInformation = (Map<String, Object>) inputMap.get('ClientInformation');
        List<Object> billingAccs = (List<Object>)options.get('AssetsM');

        List<Case> listChildCases = new List<Case>();
        for(Object ba : billingAccs){
            Map<String, Object> baMap = (Map<String, Object>) ba; 
            System.debug('baMap: ' + baMap);
            Id assetId =  (Id) baMap.get('AssetId');
            Case myCase = new Case();
            myCase.ParentId = parentId;
            System.debug('Asset id: ' + assetId);
            myCase.AssetId = assetId;
            myCase.Subject = 'Suspension/Habilitacion por Administrativo';
            myCase.Status = 'En espera de ejecución';
            myCase.Order__c = orderId;
            myCase.RecordTypeId = recordTypeId;
            myCase.Type = 'Suspensiones y reconexiones';
            myCase.SubType__c = subtype;
            listChildCases.add(myCase);
        }
        insert listChildCases;
        output.put('Cases',listChildCases);
    }
    
    private void getSuspendedDevicesByAccountId ()
    {
        try {
            Id accountId = (Id) this.input.get('ContextId');
            Map<String, Object> recordType = (Map<String, Object>) this.input.get('RecordType');
            Id recordTypeId = (Id) recordType.get('Id');
            List<Map<String, object>> listClientSuspensions = new List<Map<String, object>>();
            
            Map<String, Object> clientSuspensionsMap;
            List<transaction_history__c> clientSuspensions = [SELECT Id, Asset__r.AccountId, Asset__c, Asset__r.id, Asset__r.Name, asset__r.imei__c, imei__c FROM transaction_history__c where new_status__c = 'Active' AND Account__c = :accountId AND RecordTypeId = :recordTypeId AND Description__c = 'Suspensión' AND Type__c = 'Siniestro' AND ((asset__r.tipo_de_producto__c = 'dispositivo' and asset__R.Linked_Product_Family__c = 'Movil') OR (imei__c <> null ))];
            System.debug('clientSuspensions: ' + clientSuspensions);
            for(transaction_history__c susp : clientSuspensions){
                clientSuspensionsMap = new Map<String, String>();
                If(susp.Asset__c != null){
                    clientSuspensionsMap.put('Id', (String) susp.Asset__r.id); 
                    clientSuspensionsMap.put('TransactionId', (String) susp.Id); 
                    clientSuspensionsMap.put('assetName', (String) susp.Asset__r.Name);
                    clientSuspensionsMap.put('Imei', (String) susp.asset__r.imei__c);
                    clientSuspensionsMap.put('AccountId', (String) susp.Asset__r.AccountId);
                }
                else {
                    clientSuspensionsMap.put('TransactionId', (String) susp.Id);
                    clientSuspensionsMap.put('Imei', (String) susp.Imei__c);
                }
                listClientSuspensions.add(clientSuspensionsMap);
            }
            
            
            
            
            System.debug(listClientSuspensions);
            output.put('listClientSuspensions',listClientSuspensions);
        }
        catch (Exception ex) {
            throw ex;
        }
    }
    
    private void createTrasactionHistory() {
            
            //List<transaction_history__c> listTransactionHis = new List<transaction_history__c>();
            Map<String, Object> trasactionData = (Map<String, Object>) this.options.get('transactionHistory'); 
            System.debug('trasactionData: ' + trasactionData);
            transaction_history__c myTransactionHis = new transaction_history__c();
            
            if( trasactionData.get('Id') == null ){
                myTransactionHis.sinister_type__c = (String)trasactionData.get('SinisterType');
                myTransactionHis.Type__c = (String)trasactionData.get('Type');
                myTransactionHis.RecordTypeId = (Id)trasactionData.get('RecordType');
                myTransactionHis.New_Status__c = (String)trasactionData.get('NewStatus');
                myTransactionHis.Imei__c = (String)trasactionData.get('Imei');
                myTransactionHis.Description__c = (string)trasactionData.get('Description');
                myTransactionHis.Account__c = (Id)trasactionData.get('AccountId');
            }else{
                myTransactionHis.Id = (Id)trasactionData.get('Id');
                myTransactionHis.New_Status__c = (String)trasactionData.get('NewStatus');
            }
            
    
        System.debug('myTransactionHis: ' + myTransactionHis);
        upsert myTransactionHis;
        output.put('TransactionHistoryCreate',myTransactionHis);
    }

    //Norwill Gutierrez - To Get unique id for transaction
    private void GetNewGuid(){
        String idUnico = GuidUtil.NewGuid();
        this.output.put('UniqueTransactionID', idUnico);
    }     
}