objects/Asset.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>The current provisioning, or fulfillment, status of the asset with values such as New, Active, Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Attributes_Binding__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Attribute_Category__c</fullName>
        <label>Attribute Category</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attributes Binding</label>
</CustomObject>

classes/Attribute_Binding_Class.cls
public class Attribute_Binding_Class {
  static List<Attributes_Binding__c> parameters =  [Select id,Name,Field__c,Attribute_Name__c,Object__c,Attribute_Category__c from Attributes_Binding__c WHERE Object__c = 'Asset' and Active__c = true];
  
    public static void ins(List<Asset> newMap){
        try{
            Attribute_Binding_Class.getAttributesAndReplace(newMap);
        }
        catch(Exception ex){
            System.debug(ex);
        }
    } 

    public static void getAttributesAndReplace(List<Asset> assetsToUpdate){
        if(Attribute_Binding_Class.parameters != null && Attribute_Binding_Class.parameters.size() > 0){
            XOMUtilities getspecificAttribute = new XOMUtilities();
            for (Asset asset : assetsToUpdate){
                List<Asset> listaDeAssets = new List<Asset>();
                listaDeAssets.add(asset);
                List<Map<String, Object>> assetAttributes = getspecificAttribute.getJsonAttributesFromAnyObject(listaDeAssets , 'Asset');
                if(assetAttributes != null){
                    for(Attributes_Binding__c parameter: Attribute_Binding_Class.parameters){
                        string n = getspecificAttribute.getValueFromAttrs(assetAttributes, parameter.Attribute_Name__c);      
                        
                        if(n!= null && n!= '')
                            asset.put(parameter.Field__c, n);
                    }
                    //asset.put('Status', asset.vlocity_cmt__ProvisioningStatus__c);
                }
            }
        }
    }

    public static void upd(Map<Id, Asset> oldMap, List<Asset> newMap){
        try{
            Attribute_Binding_Class.getAttributesAndReplace(newMap);
        }
        catch(Exception ex){
            system.debug('exception on: ' + ex.getLineNumber() + ex);
            //throw ex;
        }
    }
}