objects/Asset.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetReferenceId__c</fullName>
        <description>Unique identifier of the asset. Used by Vlocity CPQ to track the asset across various objects in the asset-based ordering lifecycle. Populate this field with some globally unique identifier if the asset is created/mastered in an external system. When created initially within Salesforce, Vlocity assigns a value based on the Salesforce ID.</description>
        <label>Asset Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute data for the asset.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>The current provisioning, or fulfillment, status of the asset with values such as New, Active, Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__Action__c</fullName>
        <description>The action desired for this line item with values of Add, Change, Existing or Disconnect. Existing means no change is requested. Add is a request to add the item, Change is a request to change it. Disconnect is a request to remove it.</description>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Add</fullName>
                </value>
                <value>
                    <fullName>Change</fullName>
                </value>
                <value>
                    <fullName>Disconnect</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
                <value>
                    <fullName>Suspend</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Modify</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                    <isActive>false</isActive>
                    <label>Nominacion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset that this Order Product was pushed to by Order To Asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Product</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetReferenceId__c</fullName>
        <description>Unique identifier of the asset refereced by this line item. Used by Vlocity CPQ to track the asset across various objects in the asset-based ordering lifecycle.</description>
        <label>Asset Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute value data.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProvisioningStatus__c</fullName>
        <description>(NOTE: The functionality of this field is replaced by the Action, Sub-Action and Fulfilment Status fields.) The desired provisioning action for the asset identified on this line item. Values include New (add), Active (no change), Changed or Deleted.</description>
        <label>Provisioning Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SerialNumber__c</fullName>
        <label>Serial Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__SubAction__c</fullName>
        <description>The sub-action requested for this line item typically used for moves of service from one location to another with values of Move-Add and Move-Delete. Move-Add means this item is being added as part of the move and usually should be added before the previous service is disconnected. Move-Delete means this item is the service to be disconnected after the service is activated at the new location.</description>
        <label>Sub Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Move</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Suspend-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Suspend-Fraude</fullName>
                </value>
                <value>
                    <fullName>Suspend-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Suspend-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Voluntaria</fullName>
                </value>
                <value>
                    <fullName>Resume-Fraude</fullName>
                </value>
                <value>
                    <fullName>Resume-Siniestro</fullName>
                </value>
                <value>
                    <fullName>Resume-Portabilidad</fullName>
                </value>
                <value>
                    <fullName>Full suspend</fullName>
                </value>
                <value>
                    <fullName>Baja-Baja</fullName>
                </value>
                <value>
                    <fullName>Baja-PortOut</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Gemalto</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>TELECOM PERSONAL</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>FixedLine</fullName>
                    <label>Línea Fija</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <label>Línea Móvil</label>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Servicio Valor Agregado</fullName>
                </value>
                <value>
                    <fullName>Plan Prepago</fullName>
                </value>
                <value>
                    <fullName>Plan Pospago</fullName>
                </value>
                <value>
                    <fullName>Plan Hibrido</fullName>
                </value>
                <value>
                    <fullName>Servicio GSM</fullName>
                </value>
                <value>
                    <fullName>Numeros Amigos</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Control Cuota Datos</fullName>
                </value>
                <value>
                    <fullName>Simcard</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Credito Adicional</fullName>
                </value>
                <value>
                    <fullName>Roaming</fullName>
                </value>
                <value>
                    <fullName>Dispositivo</fullName>
                </value>
                <value>
                    <fullName>Prestamo</fullName>
                </value>
                <value>
                    <fullName>Proteccion</fullName>
                </value>
                <value>
                    <fullName>Captura</fullName>
                </value>
                <value>
                    <fullName>Pack LDI</fullName>
                </value>
                <value>
                    <fullName>Pack Roaming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Venkat_DeltaOrder.cls
global with sharing class Venkat_DeltaOrder implements vlocity_cmt.VlocityOpenInterface {


    /**
    *  DeltaOrder
    *  Author: Bill Coppens
    *  Method: CompareLineItems
    *  MethodDescription: Compare the line items. of an OrderId sent in.  It returns lists of new / deleted / change 
    **/
    global Boolean invokeMethod(String methodName, Map<String, Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {
        Boolean retval = false;

        if (methodName == 'CompareLineItems') {
            return compareLineItems(inputMap,outMap,options);
        }

        return retval;
    }

    /**
    * Compare and update the line items
    * Select the line items and the associated products.
    * use the product details to determine if there is a change is product, if they are the same products
    **/

    public Boolean CompareLineItems(Map<String, Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {

        Boolean retval = false;

        List<String> oiFields = vlocity_cmt.DBHelper.getFields('OrderItem');
        List<String> prodFields = vlocity_cmt.DBHelper.getFields('Product2');
        String orderId = (String)inputMap.get('OrderId');

        // Build the query for order items and ite product details for the order
        String soql = 'select ' + String.join(oiFields,',') + ', PricebookEntry.Product2.' 
                        + String.join(prodFields,',PricebookEntry.Product2.') 
                        + ' from OrderItem where orderId = :orderId';


        
        // set up the processing structure definition.
        List<OrderItem> newOI = new List<OrderItem>();
        List<OrderItem> oldOI = new List<OrderItem>();
        List<Map<String,OrderItem>> deltaOI = new List<Map<String,OrderItem>>();
        List<Map<String,OrderItem>> sameOI = new List<Map<String,OrderItem>>();
        List<OrderItem> removeOI = new List<OrderItem>();

       

        //outMap.put('soql',soql);  // A degug if needed.

        // Execute the query
        List<OrderItem> ois = database.query(soql);

        outmap.put('itemSize',ois.size());
        outMap.put('orderId',orderId);
        retval = true;

        // determine if the line item is net new in the order or if it was moved from assets.
        for (OrderItem oi : ois) {
            if (isNew(oi)) {
                newOI.add(oi);
            } else {
                oldOI.add(oi);      
//              oi.vlocity_cmt__Action__c       = 'Disconnect';
                // assume they will change as the default measure.
                oi.vlocity_cmt__SubAction__c    = 'Change';
            }
        }


        // perform a check to see if the line item should replace a previous OrderItem, or change the old OrderItem 
        for (OrderItem noi: newOI) {
            for (OrderItem ooi: oldOI) {
                if (compareLike(noi,ooi)) {

                    if (compareChange(noi,ooi)) {
                        Map<String,OrderItem> temp = new Map<String,OrderItem>();
                        temp.put('new',noi);
                        temp.put('old',ooi);
                        deltaOI.add(temp);
                        ooi.vlocity_cmt__ProvisioningStatus__c  = 'Deleted';
                        noi.vlocity_cmt__SubAction__c           = 'Change';
                    }

                    if (compareSame(noi,ooi)) {
                        Map<String,OrderItem> temp = new Map<String,OrderItem>();
                        temp.put('new',noi);
                        temp.put('old',ooi);
                        sameOI.add(temp);
                        ooi.vlocity_cmt__ProvisioningStatus__c  = 'Deleted';
                        noi.vlocity_cmt__SubAction__c           = 'Move';
                        noi.vlocity_cmt__AssetReferenceId__c    = ooi.vlocity_cmt__AssetReferenceId__c;
                        noi.vlocity_cmt__AssetId__c             = ooi.vlocity_cmt__AssetId__c;
                        noi.vlocity_cmt__JSONAttribute__c       = ooi.vlocity_cmt__JSONAttribute__c;
                        noi.vlocity_cmt__SerialNumber__c        = ooi.vlocity_cmt__SerialNumber__c;
                    }
                    break;
                }
            }
        }

        for (OrderItem ooi: oldOI) {
            for (OrderItem noi: newOI) {
                if (!compareChange(noi,ooi) && !compareSame(noi,ooi)) {
                    removeOI.add(ooi);
                }
            }
        }

        update ois;
        
         // Set up the return structure
        outmap.put('deltaItems',deltaOI);
        outmap.put('sameItems',sameOI);
        outmap.put('removeItems',removeOI);

        return retval;
        
        // If the same child product of the source plan is not present, then we need to delete that child product in the cart.
        // 
    }

    /**
    *  Check to see is the order item is new
    **/
    public Boolean isNew(OrderItem oi) {
        Boolean retval = false;

        if (oi.vlocity_cmt__Action__c != 'Existing') {
            retval = true;
        }

        return retval;
    }

    /**
    *  Compare the 2 orderItems.  Return true if it appears that they ar alike
    **/

    public Boolean comparelike(OrderItem newOI, OrderItem oldOI) {
        Boolean retval = false;
        if ((newOI.PricebookEntry.Product2.vlocity_cmt__Type__c == oldOI.PricebookEntry.Product2.vlocity_cmt__Type__c)
            && (newOI.PricebookEntry.Product2.Family == oldOI.PricebookEntry.Product2.Family)
        ) {
            retval = true;
        }
        return retval;
    }
    /**
    *  Compare the 2 orderItems.  Return true if it appears that the the new order item should
    *  replace the old order item.
    **/

    public Boolean compareChange(OrderItem newOI, OrderItem oldOI) {
        Boolean retval = false;
        if ((newOI.PricebookEntry.Product2.vlocity_cmt__Type__c == oldOI.PricebookEntry.Product2.vlocity_cmt__Type__c)
            && (newOI.PricebookEntry.Product2.Family == oldOI.PricebookEntry.Product2.Family)
            && (newOI.PricebookEntry.Product2.ProductCode != oldOI.PricebookEntry.Product2.ProductCode)
        ) {
            retval = true;
        }
        return retval;
    }

    /**
    *   Compare and see if the new order item is the same as the old and simply needs to 
    *   move the asset identifiers from the old order item to the new order item. 
    **/
    public Boolean compareSame(OrderItem newOI, OrderItem oldOI) {
        Boolean retval = false;
        if ((newOI.PricebookEntry.Product2.vlocity_cmt__Type__c == oldOI.PricebookEntry.Product2.vlocity_cmt__Type__c)
            && (newOI.PricebookEntry.Product2.Family == oldOI.PricebookEntry.Product2.Family)
            && (newOI.PricebookEntry.Product2.ProductCode == oldOI.PricebookEntry.Product2.ProductCode)
        ) {
            retval = true;
        }
        return retval;
    }
}