objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Migrated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicador de si el asset fue migrado desde legado; cuando está valuado a TRUE indica de manera inequívoca que el contacto se migró de legado</description>
        <label>Migrated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AttributeSelectedValues__c</fullName>
        <label>Attribute Selected Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/update2AssetJSONAttributeTrigerTest.cls
global class update2AssetJSONAttributeTrigerTest {
    public static void testUpdateConMiniJson()
    {
        Asset a = new Asset();
        a.AccountId = '0016C000009OLhhQAG';
        a.Product2ID = '01t6C000000ZudJQAS';
        a.Name = 'Simcard_Json_Test';
        a.Migrated__c = true;
        a.vlocity_cmt__AttributeSelectedValues__c = '{"MSISDN":"1144447363"}';
        insert a;
      }
    
}