objects/Asset.object
<CustomObject>
    <fields>
        <fullName>MSISDN__c</fullName>
        <description>MSISDN Line number</description>
        <inlineHelpText>MSISDN Line number</inlineHelpText>
        <label>MSISDN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute data for the asset.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LineNumber__c</fullName>
        <description>Vlocity line number copied from the order which assists in sequencing the assets and organizing them into a hierarchy.</description>
        <label>Line Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>String1__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Operation_Code__c</fullName>
        <description>Field used to describe the operation being performed. Used to retake the order in any step.</description>
        <label>Operation Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Received224_Date__c</fullName>
        <description>A date field to store the date when the response of the 224 integration service is received. The 224 service is a callback response from Payment, indicating if payment was successful or why did it fail. This is needed for later validations on the order.</description>
        <label>Received224_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order_Failed_Payment_Messages__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Order Failed Payment Messages</label>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Operation_Code__c</fullName>
        <description>This field is used to store Operation Code for Orders with delivery method as Delivery. This will be consumed by OM. This comes from US PFTA-7934</description>
        <label>Operation Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AssetId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The asset that this Order Product was pushed to by Order To Asset</description>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Order Product</relationshipLabel>
        <relationshipName>OrderProducts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing Vlocity Attribute value data.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__LineNumber__c</fullName>
        <description>Vlocity line number generated by code which serves to sequence the line items and organize them into a hierarchy.</description>
        <label>LineNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SMSSender__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Sender__c</fullName>
        <label>Sender</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>SMS Sender</label>
</CustomObject>

objects/TASalesCodeValue__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>TA Sales General Custom Settings for conversion from a Code to a Value. This is a general conversion CS when you need to translate a given code into a given description.</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TASalesCodeValue</label>
</CustomObject>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/BillingResponseHandlerTest.cls
@isTest
public with sharing class BillingResponseHandlerTest {
    
    @testSetup static void createDataTest(){
        //List<Account> accounts = TestDataFactory.createAccounts(1,'Consumer');
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        /*
        List<Order> orders = new List<Order>();
        for (Account a: accounts) {
            orders.addAll(TestDataFactory.createOrders(1,a));
        }
        */
        MockUpFactory.generate();
    }
    
    @isTest
    static void BillingResponse_Handler() {
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, String>();
        options.put('ContactFirstName', 'Contact First Name');
        options.put('ContactLastName', 'Contact LastName');
        options.put('AccountName', 'Sample Account');
        options.put('DocumentType', 'DNI');
        options.put('DocumentNumber', '12345678');
        options.put('AccountNumber', '1234');
        options.put('Email', 'test@yopmail.com');
        options.put('PhoneNumber', '1234567890');
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod('callBackService224', inputMap, outMap, options);
        BResp.invokeMethod('testGetSystemURL', inputMap, outMap, options);
        //BResp.invokeMethod('callNominationCheckout', inputMap, outMap, options);
        BResp.invokeMethod('getNominationAssets', inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest static void callBackService224_OKWithOrderStatusSucced() {
        //GIVEN
        String methodName = 'callBackService224';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id, OrderNumber FROM Order LIMIT 1];
        
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","Status":"payment succeed","StatusInvoice":"invoice succeed","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest static void callBackService224_OKWithOrderStatusSuccedRecarga() {
        //GIVEN
        String methodName = 'callBackService224';
        
        String mockResponse = '{"txId":"12345"}';
        VlocityIntegrationProcedureTestUtility.mockIntegrationProcedure('IFS_S143', mockResponse);

        mockResponse = '{"IPResult":{"executionCode":"OK"}}';
        VlocityIntegrationProcedureTestUtility.mockIntegrationProcedure('IFS_S159', mockResponse);
        
        Id recordType = [SELECT Id FROM RecordType WHERE Name = 'SMS Template'].Id;
        CrossObject__c template = new CrossObject__c(String1__c = 'pepe', RecordTypeId = recordType, Picklist1__c = 'Recarga Exitosa');
        insert template;
        insert new SMSSender__c(Name='S-Confirmacion-SMS',Sender__c='S-Confirmacion-SMS');
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        /*Order order = [SELECT Id, Gestion__c, OriginStoreLocation__c, OrderNumber FROM Order LIMIT 1];
        order.Gestion__c = 'Recarga';
        update order;*/
        Account account = [SELECT Id FROM Account LIMIT 1];
        Id pricebookId = Test.getStandardPricebookId();
        Order orderNew = new Order(AccountId = account.Id, Status = 'Draft', Gestion__c = 'Recarga', Operation_Code__c = 'VTNLCE', EffectiveDate = Date.today(), Pricebook2Id = pricebookId,vlocity_cmt__OriginatingChannel__c ='Agentes',Delivery_Method__c ='Presencial', Received224_Date__c = Date.Today());
        insert orderNew;
        
        Order order = [SELECT Id, Gestion__c, OriginStoreLocation__c, OrderNumber FROM Order WHERE Id=:orderNew.Id];

        System.debug('callBackService224_OKWithOrderStatusSuccedRecarga: ' + order);
        
        List<Product2> product = TestDataFactory.createProduct(1);
        List<Asset> assets = TestDataFactory.createAssets(1,account,'453343636363');
        List<OrderItem> orderItems = TestDataFactory.createOrderItemsWithAsset(1,order,assets.get(0));
        String MSISDN = '{"MSISDN":[{"attributedisplayname__c":"MSISDN","attributeRunTimeInfo":{"value":"nroLinea"}}]}';
        orderItems.get(0).vlocity_cmt__JSONAttribute__c = MSISDN;
        update orderItems.get(0);
        
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","Status":"payment succeed","StatusInvoice":"invoice succeed","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest static void callBackService224_OKWithOrderIdNull() {
        //GIVEN
        String methodName = 'callBackService224';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id, OrderNumber FROM Order LIMIT 1];
        
        String ReasonCode = 'ReasonCode';
        
        insert new Order_Failed_Payment_Messages__c(Name = 'Error_Code__c', Error_Code__c=ReasonCode);
                
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","ReasonCode":"'+ReasonCode+'","Status":"Draft","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }
    @isTest static void callBackService224_Error001() {
        //GIVEN
        String methodName = 'callBackService224';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id, OrderNumber FROM Order LIMIT 1];
        
        TASalesCodeValue__c cod2 = new TASalesCodeValue__c();
        cod2.Name= 'IF224ReasonAnulada';
        cod2.Value__c = '2';
        insert cod2;
        
        String ReasonCode = '2';
        insert new Order_Failed_Payment_Messages__c(Name = 'Error_Code__c', Error_Code__c=ReasonCode);
                
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","ReasonCode":"'+ReasonCode+'","Status":"payment failed","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }

    @isTest static void callBackService224_Error002() {
        //GIVEN
        String methodName = 'callBackService224';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id, OrderNumber FROM Order LIMIT 1];
        
        TASalesCodeValue__c cod3 = new TASalesCodeValue__c();
        cod3.Name= 'IF224ReasonCancelada';
        cod3.Value__c = '3';
        insert cod3;
        
        String ReasonCode = '3';
        insert new Order_Failed_Payment_Messages__c(Name = 'Error_Code__c', Error_Code__c=ReasonCode);
                
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","ReasonCode":"'+ReasonCode+'","Status":"payment failed","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }

    @isTest static void callBackService224_OKWithOrderDeliveryMethodStorePickUp() {
        //GIVEN
        String methodName = 'callBackService224';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id, OrderNumber FROM Order LIMIT 1];
        order.Delivery_Method__c = 'Store Pick Up';
        update order;
        
        String ReasonCode = 'ReasonCode';
        insert new Order_Failed_Payment_Messages__c(Name = 'Error_Code__c', Error_Code__c=ReasonCode);
                
        String JSONResponse = '{"invoiceAndPaymentNotification":{"SalesOrderId":"'+order.OrderNumber+'","Status":"payment succeed","StatusInvoice":"invoice succeed","LegalInvoiceNumber":"LegalInvoiceNumber"}}';
        
        options.put('JSONResponse',JSONResponse);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest static void callNominationCheckoutOK() {
        //GIVEN
        String methodName = 'callNominationCheckout';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id FROM Order LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        List<Product2> product = TestDataFactory.createProduct(1);
        List<Asset> assets = TestDataFactory.createAssets(1,product.get(0),account);
        List<OrderItem> orderItems = TestDataFactory.createOrderItemsWithAsset(1,order,assets.get(0));
        
        options.put('orderId', order.Id);
        options.put('accountId', account.Id);
        options.put('assetId', assets.get(0).Id);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }
    
    @isTest static void prepareOrderForOM() {
        //GIVEN
        String methodName = 'prepareOrderForOM';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Order order = [SELECT Id FROM Order LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        List<Product2> product = TestDataFactory.createProduct(1);
        List<Asset> assets = TestDataFactory.createAssets(1,product.get(0),account);
        List<OrderItem> orderItems = TestDataFactory.createOrderItemsWithAsset(1,order,assets.get(0));
        
        options.put('orderId', order.Id);
        options.put('accountId', account.Id);
        options.put('assetId', assets.get(0).Id);
        
        //WHEN
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }

    @isTest
    static void SendSuccesfulOrderClientNotification() {
        Test.startTest();
        Order order = [SELECT Id FROM Order LIMIT 1];
        BillingResponseHandler.SendSuccesfulOrderClientNotification(order.Id);
        Test.stopTest();
    }

    @isTest
    static void SendSuccesfulPaymentClientNotification() {
        Test.startTest();
        Order order = [SELECT Id FROM Order LIMIT 1];
        BillingResponseHandler.SendSuccesfulPaymentClientNotification(order.Id);
        Test.stopTest();
    }
    
    @isTest static void callBackService224_NullException() {
       
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        try
        {
            BResp.invokeMethod(null, inputMap, outMap, options);
        }
        catch (Exception ex)
        {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Attempt to de-reference a null object') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }

    @isTest static void callNominationCheckout_Exception() {
        String methodName = 'callNominationCheckout';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        BResp.invokeMethod(methodName, inputMap, outMap, options);
        Test.stopTest();
    }

    @isTest static void getNominationAssets_Exception() {
        String methodName = 'getNominationAssets';
        
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = null;
        Map<String, Object> options = new Map<String, Object>();
        
        Test.startTest();
        BillingResponseHandler BResp = new BillingResponseHandler();
        try
        {
            BResp.invokeMethod(methodName, inputMap, outMap, options);
        }
        catch (Exception ex)
        {
            Boolean expectedExceptionThrown =  ex.getMessage().contains('Attempt to de-reference a null object') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        Test.stopTest();
    }
    
    @isTest static void processInternetPackReset_Test() {
        String methodName = 'processInternetPackReset_Test';

        String nroLinea = 'NroLinea';
        //TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        Account account = [SELECT Id FROM Account LIMIT 1];
        TestDataFactory.createAssets(1,account);
        
        Asset asset = [SELECT vlocity_cmt__LineNumber__c, AccountId FROM Asset LIMIT 1];
        asset.vlocity_cmt__LineNumber__c = nroLinea;
        asset.MSISDN__c = nroLinea;
        update asset;
        
        Product2 product = TestDataFactory.createProduct(1).get(0);
        product.vlocity_cmt__JSONAttribute__c = '{"attributes":[{"attributedisplayname__c":"Unidad de Medida de Vigencia","attributeRunTimeInfo":{"default":[{"value":"W"}]}},{"attributedisplayname__c":"Vigencia Activacion","attributeRunTimeInfo":{"default":"24"}},{"attributedisplayname__c":"ID Sistema Origen","attributeRunTimeInfo":{"default":"FAN_PRDA_00003"}}]}';                                                                                         
        product.ProductCode = 'FAN_PRDA_00003'; // OJO CON ESTE VALOR, ESTÁ HARD CODE EN EL SOURCE
        update product;
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id =Test.getStandardPricebookId(),
            Product2Id = product.Id,
            UnitPrice = 10000, IsActive = true
        );

        insert standardPrice;
        
        Order orderOBJ = TestDataFactory.createOrders(1,account).get(0);
        String idOrder = (String) orderOBJ.Id;

        TestDataFactory.createPaymentAdjustments(1, account, orderOBJ);

        Id recordType = [SELECT Id FROM RecordType WHERE Name = 'SMS Template'].Id;
        CrossObject__c template = new CrossObject__c(String1__c = 'Se renovó tu cuota de datos exitosamente!', RecordTypeId = recordType, Picklist1__c = 'Renovacion de datos Exitosa');
        insert template;
        insert new SMSSender__c(Name='S-Confirmacion-SMS',Sender__c='S-Confirmacion-SMS');

        List<OrderItem> ordItemList = new List<OrderItem>();
        ordItemList.add(new OrderItem(OrderId = orderOBJ.Id, vlocity_cmt__AssetId__c = asset.Id, Product2Id = product.Id, Quantity = 10, PricebookEntryId = standardPrice.Id, UnitPrice = 100));
        insert ordItemList;
        
        Test.startTest();
        BillingResponseHandler.processInternetPackReset(orderOBJ);
        Test.stopTest();
    }
 }