objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>MessageID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#Mkt #Sprint18 SMS Administrator</description>
        <label>Message ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Crossobject__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>SMS Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Crossobject__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>CampaignMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MobilePhoneSend__c</fullName>
        <description>The mobile phone to send the message</description>
        <label>MobilePhoneSend</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>TextArea__c</fullName>
        <label>Text Area</label>
        <type>TextArea</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MktSMSOnlineSender.cls
public class MktSMSOnlineSender {
    
    @InvocableMethod(label='SMS Online Sender' description='Sends SMS Online')
    public static void sendSMSOnline(List<CampaignMember> campaignMembers) {
        
    	Set<Id> idSet = new Set<Id>();
    	List<CrossObject__c> messagesList = new List<CrossObject__c>();

    	for(CampaignMember campaignMember : campaignMembers ){
    		idSet.add(campaignMember.MessageId__c);
    	}

    	messagesList = [SELECT Id, TextArea__c FROM CrossObject__c WHERE Id IN :idSet];

        for(CampaignMember campaignMember : campaignMembers ){

        	for(CrossObject__c message : messagesList){

        		if(message.Id == campaignMember.MessageId__c){
        			String body = '{"params": { "nroLinea": "'+ campaignMember.MobilePhoneSend__c +'"}, "body": {"communicationText": "'+ message.TextArea__c +'"}}';
		        	Map<String, Object> input = (Map<String, Object>) JSON.deserializeUntyped(body);
		            Map<String, Object> output = new Map<String, Object>();
		            Map<String, Object> options = new Map<String, Object>();
		            vlocity_cmt.IntegrationProcedureService integProcServ = new vlocity_cmt.IntegrationProcedureService();
		            integProcServ.invokeMethod('IFS_S159', input, output, options);		
        			break;
        		}
        	}               
        }
    }
}