objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SubtypeL2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>OUT</fullName>
                </value>
                <value>
                    <fullName>IN/OUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>RRSS</fullName>
                </value>
                <value>
                    <fullName>ISMS</fullName>
                </value>
                <value>
                    <fullName>E-Mail</fullName>
                </value>
                <value>
                    <fullName>Sat Push</fullName>
                </value>
                <value>
                    <fullName>APP Push</fullName>
                </value>
                <value>
                    <fullName>Web Push</fullName>
                </value>
                <value>
                    <fullName>Discador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masivo</fullName>
                </value>
                <value>
                    <fullName>Empresa</fullName>
                </value>
                <value>
                    <fullName>Masivo y Empresa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubtypeL1__c</fullName>
        <label>Subtype L1</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alta/Portin Nuevo Cliente  (Nuevo DNI/CUIT)</fullName>
                </value>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Activ. Comercial</fullName>
                </value>
                <value>
                    <fullName>Fidelización</fullName>
                </value>
                <value>
                    <fullName>Comunicación/Educativa</fullName>
                </value>
                <value>
                    <fullName>Encuesta</fullName>
                </value>
                <value>
                    <fullName>Conversión</fullName>
                </value>
                <value>
                    <fullName>Relacionamiento</fullName>
                </value>
                <value>
                    <fullName>Transaccional</fullName>
                </value>
                <value>
                    <fullName>Retención</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubtypeL2__c</fullName>
        <label>Subtype L2</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SubtypeL1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alta/Portin (DNI/CUIT existente)</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Nuevo Servicio OTT/VAS</fullName>
                </value>
                <value>
                    <fullName>Cambio de Producto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cash-in (recargas)</fullName>
                </value>
                <value>
                    <fullName>Cash-Out (contenidos, packs, etc)</fullName>
                </value>
                <value>
                    <fullName>Alianzas</fullName>
                </value>
                <value>
                    <fullName>Club Personal</fullName>
                </value>
                <value>
                    <fullName>Configuración de servicios</fullName>
                </value>
                <value>
                    <fullName>Confiabilización de Datos</fullName>
                </value>
                <value>
                    <fullName>Morosidad</fullName>
                </value>
                <value>
                    <fullName>Modificaciones en los servicios</fullName>
                </value>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Testing ad hoc, NPS</fullName>
                </value>
                <value>
                    <fullName>Cart View</fullName>
                </value>
                <value>
                    <fullName>Cart Abandon</fullName>
                </value>
                <value>
                    <fullName>Promotional</fullName>
                </value>
                <value>
                    <fullName>Cross Sell</fullName>
                </value>
                <value>
                    <fullName>Educacional</fullName>
                </value>
                <value>
                    <fullName>Saludos especial</fullName>
                </value>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Soporte</fullName>
                </value>
                <value>
                    <fullName>Factura</fullName>
                </value>
                <value>
                    <fullName>Detalle de consumo</fullName>
                </value>
                <value>
                    <fullName>Churn Mitigation</fullName>
                </value>
                <value>
                    <fullName>Recupero</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NAWinback</fullName>
                    <label>N/A.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/MktgCloudAPISettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the configuration values to call Mktg Cloud API</description>
    <fields>
        <fullName>ClientId__c</fullName>
        <label>Client Id</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>Client Secret</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MktgAuthURL__c</fullName>
        <label>Mktg Auth URL</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Mktg Cloud API Settings</label>
</CustomObject>

classes/CampaignTriggersTest.cls
@isTest
public class CampaignTriggersTest {

    static testMethod void testUpdateCampaignMemberStatus() {
        
        MktgCloudAPISettings__c mktgCloudAPISettings = new MktgCloudAPISettings__c ();
        mktgCloudAPISettings.Name = 'Mktg Cloud API';
        mktgCloudAPISettings.ClientId__c = '1234';
        mktgCloudAPISettings.ClientSecret__c = '4567';
        mktgCloudAPISettings.MktgAuthURL__c = 'https://auth.exacttargetapis.com/v1/requestToken';
        mktgCloudAPISettings = getMktgCloudAPISettings();
        insert mktgCloudAPISettings;
        
        Test.setMock(HttpCalloutMock.class, new MktgCloudCalloutMock2()); 
        
        SingleRequestMock fakeTokenResponse = MarketingCloudAPIUtilTest.accessTokenResponse();
        SingleRequestMock fakeCampaignResponse = MarketingCloudAPIUtilTest.mktgCloudCampaignResponse();
        
        List<Campaign> campaignList = new List<Campaign>();
        for(Integer i = 0; i < 50 ; i++) {
            Campaign cp = new Campaign(Name = 'Test Campaign ' + i, Campaign_Type__c = 'Desarrollo',
                                       Campaign_Subtype__c = 'Fidelización', Campaign_Subtype_2__c = 'Club Personal', 
                                       Channel_Type__c  = 'OUT', Channel__c  = 'SMS', Campaign_Destiny__c = 'Masivo', Type = 'Desarrollo',
                                       Destination__c = 'Masivo',SubtypeL1__c = 'Fidelización', SubtypeL2__c = 'Club Personal');
            campaignList.add(cp);
        }
        
        Map<String, SingleRequestMock> endpoint2TestResp = new Map<String,SingleRequestMock>();
        
        endpoint2TestResp.put('https://auth.exacttargetapis.com/v1/requestToken', fakeTokenResponse);
        endpoint2TestResp.put('https://www.exacttargetapis.com/hub/v1/campaigns', fakeCampaignResponse);

        HttpCalloutMock multiCalloutMock = new MktgCloudMultiCalloutMock(endpoint2TestResp);
 		Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        
        Test.startTest();        
        Test.setMock(HttpCalloutMock.class, new MktgCloudCalloutCreateCampaignMock2());         
        insert campaignList;
        Test.stopTest();
    }
    
    public class MktgCloudCalloutCreateCampaignMock2 implements HttpCalloutMock{
        
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"id":"1234"}');
            res.setStatusCode(200);
            return res; 
        }
    }

 public class MktgCloudCalloutMock2 implements HttpCalloutMock{
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"accessToken":"1234567", "expiresIn": 3479}');
            res.setStatusCode(200);
            return res; 
        }
    }    
    
    public static SingleRequestMock mktgCloudCampaignResponse (){
    	SingleRequestMock fakeCampaignResponse = new SingleRequestMock(200,
                                                         'Complete',
                                                         '{"id":"1234"}',
                                                         null);

        return fakeCampaignResponse;
    }
    
    public static SingleRequestMock accessTokenResponse () {
        SingleRequestMock fakeTokenResponse = new SingleRequestMock(200,
                                                         'Complete',
                                                         '{"accessToken":"1234567"}',
                                                         null);

        return fakeTokenResponse;
    }
    
    public static MktgCloudAPISettings__c getMktgCloudAPISettings() {
        MktgCloudAPISettings__c mktgCloudAPISettings = new MktgCloudAPISettings__c ();
        mktgCloudAPISettings.Name = 'Mktg Cloud API';
        mktgCloudAPISettings.ClientId__c = '1234';
        mktgCloudAPISettings.ClientSecret__c = '4567';
        mktgCloudAPISettings.MktgAuthURL__c = 'https://auth.exacttargetapis.com/v1/requestToken';
        
        return mktgCloudAPISettings;
    } 
    
}