objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>MessageID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#Mkt #Sprint18 SMS Administrator</description>
        <label>Message ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Crossobject__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>SMS Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Crossobject__c</referenceTo>
        <relationshipLabel>Campaign Members</relationshipLabel>
        <relationshipName>CampaignMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isSMSOnline__c</fullName>
        <defaultValue>false</defaultValue>
        <description>#MKT #Sprint18 SMS Administrator</description>
        <label>Is SMS Online</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>TextArea__c</fullName>
        <label>Text Area</label>
        <type>TextArea</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <recordTypes>
        <fullName>SMSAdministrator</fullName>
        <active>true</active>
        <description>Mensajes para Marketing Cloud</description>
        <label>SMS Administrator</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/MktgCloudAPISettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the configuration values to call Mktg Cloud API</description>
    <fields>
        <fullName>MCAPIAccessToken__c</fullName>
        <label>MC API Access Token</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenCreationDate__c</fullName>
        <label>Token Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TokenDuration__c</fullName>
        <label>Token Duration</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mktg Cloud API Settings</label>
</CustomObject>

classes/MktSMSOnlineSenderTest.cls
@isTest
public class MktSMSOnlineSenderTest{

    static testMethod void testSend(){ 
        
        MarketingCloudAPIUtil.skipAPICall = true;

        MktgCloudAPISettings__c mktgCloudAPISettings = MarketingCloudAPIUtilTest.getMktgCloudAPISettings();
        mktgCloudAPISettings.TokenDuration__c = 3400;
        mktgCloudAPISettings.TokenCreationDate__c = Datetime.now();
        mktgCloudAPISettings.MCAPIAccessToken__c = '12345';
        insert mktgCloudAPISettings;

        Id crossObjectRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'SMSAdministrator' AND SobjectType = 'Crossobject__c' LIMIT 1].Id;
        List<Campaign> campaignList = TestDataFactory.createCampaigns(1);
        //insert campaignList;

        List<CrossObject__c> coList = new List<CrossObject__c>();
        CrossObject__c message = new CrossObject__c(RecordTypeId = crossObjectRecordTypeId,
                                                 TextArea__c = 'Mensaje de test');
        coList.add(message);
        insert coList;
            
        Contact contact1 = new Contact(LastName='Contact1');
        Database.Insert(contact1);

        Id campId = campaignList.get(0).Id;
        List<CampaignMember> cmList = new List<CampaignMember>();
        CampaignMember cm = new CampaignMember(CampaignId = campId,
                                               ContactId  = contact1.Id,
                                               MessageId__c   = message.Id,
                                               IsSMSOnline__c = true);
        cmList.add(cm);
        //insert cmList;

        Test.startTest();
        MktSMSOnlineSender.sendSMSOnline(cmList);   
        Test.stopTest();
    }
}