objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SubtypeL2__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>OUT</fullName>
                </value>
                <value>
                    <fullName>IN/OUT</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
                <value>
                    <fullName>CRM</fullName>
                </value>
                <value>
                    <fullName>RRSS</fullName>
                </value>
                <value>
                    <fullName>ISMS</fullName>
                </value>
                <value>
                    <fullName>E-Mail</fullName>
                </value>
                <value>
                    <fullName>Sat Push</fullName>
                </value>
                <value>
                    <fullName>APP Push</fullName>
                </value>
                <value>
                    <fullName>Web Push</fullName>
                </value>
                <value>
                    <fullName>Discador</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Masivo</fullName>
                </value>
                <value>
                    <fullName>Empresa</fullName>
                </value>
                <value>
                    <fullName>Masivo y Empresa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubtypeL1__c</fullName>
        <label>Subtype L1</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alta/Portin Nuevo Cliente  (Nuevo DNI/CUIT)</fullName>
                </value>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Activ. Comercial</fullName>
                </value>
                <value>
                    <fullName>Fidelización</fullName>
                </value>
                <value>
                    <fullName>Comunicación/Educativa</fullName>
                </value>
                <value>
                    <fullName>Encuesta</fullName>
                </value>
                <value>
                    <fullName>Conversión</fullName>
                </value>
                <value>
                    <fullName>Relacionamiento</fullName>
                </value>
                <value>
                    <fullName>Transaccional</fullName>
                </value>
                <value>
                    <fullName>Retención</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubtypeL2__c</fullName>
        <label>Subtype L2</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SubtypeL1__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alta/Portin (DNI/CUIT existente)</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Nuevo Servicio OTT/VAS</fullName>
                </value>
                <value>
                    <fullName>Cambio de Producto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cash-in (recargas)</fullName>
                </value>
                <value>
                    <fullName>Cash-Out (contenidos, packs, etc)</fullName>
                </value>
                <value>
                    <fullName>Alianzas</fullName>
                </value>
                <value>
                    <fullName>Club Personal</fullName>
                </value>
                <value>
                    <fullName>Configuración de servicios</fullName>
                </value>
                <value>
                    <fullName>Confiabilización de Datos</fullName>
                </value>
                <value>
                    <fullName>Morosidad</fullName>
                </value>
                <value>
                    <fullName>Modificaciones en los servicios</fullName>
                </value>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Testing ad hoc, NPS</fullName>
                </value>
                <value>
                    <fullName>Cart View</fullName>
                </value>
                <value>
                    <fullName>Cart Abandon</fullName>
                </value>
                <value>
                    <fullName>Promotional</fullName>
                </value>
                <value>
                    <fullName>Cross Sell</fullName>
                </value>
                <value>
                    <fullName>Educacional</fullName>
                </value>
                <value>
                    <fullName>Saludos especial</fullName>
                </value>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Soporte</fullName>
                </value>
                <value>
                    <fullName>Factura</fullName>
                </value>
                <value>
                    <fullName>Detalle de consumo</fullName>
                </value>
                <value>
                    <fullName>Churn Mitigation</fullName>
                </value>
                <value>
                    <fullName>Recupero</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>NAWinback</fullName>
                    <label>N/A.</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/MktgCloudAPISettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the configuration values to call Mktg Cloud API</description>
    <fields>
        <fullName>MCAPIAccessToken__c</fullName>
        <label>MC API Access Token</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenCreationDate__c</fullName>
        <label>Token Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TokenDuration__c</fullName>
        <label>Token Duration</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mktg Cloud API Settings</label>
</CustomObject>

classes/MktgMCSyncTest.cls
@isTest
public class MktgMCSyncTest {
    static testMethod void testSincronizeCampaignWithMC () {
        SingleRequestMock fakeTokenResponse = MarketingCloudAPIUtilTest.accessTokenResponse();
        SingleRequestMock fakeCampaignResponse = MarketingCloudAPIUtilTest.mktgCloudCampaignResponse();
        
        MarketingCloudAPIUtil.skipAPICall = true;

        //List<Campaign> campaignList = TestDataFactory.createCampaigns(1);
        List<Campaign> campaignList = new List<Campaign>();
        for(Integer i = 0; i < 50 ; i++) {
            Campaign cp = new Campaign(Name = 'Test Campaign ' + i, Campaign_Type__c = 'Desarrollo',
                                       Campaign_Subtype__c = 'Fidelización', Campaign_Subtype_2__c = 'Club Personal', 
                                       Channel_Type__c  = 'OUT', Channel__c  = 'SMS', Campaign_Destiny__c = 'Masivo', Type = 'Desarrollo',
                                       Destination__c = 'Masivo',SubtypeL1__c = 'Activ. Comercial', SubtypeL2__c = 'Cambio de Terminal');
            campaignList.add(cp);
        }
       

        Map<String, SingleRequestMock> endpoint2TestResp = new Map<String,SingleRequestMock>();
        
        endpoint2TestResp.put('https://auth.exacttargetapis.com/v1/requestToken', fakeTokenResponse);
        endpoint2TestResp.put('https://www.exacttargetapis.com/hub/v1/campaigns', fakeCampaignResponse);

        HttpCalloutMock multiCalloutMock = new MktgCloudMultiCalloutMock(endpoint2TestResp);
        
        MktgCloudAPISettings__c mktgCloudAPISettings = MarketingCloudAPIUtilTest.getMktgCloudAPISettings();
        mktgCloudAPISettings.TokenDuration__c = 3400;
        mktgCloudAPISettings.TokenCreationDate__c = Datetime.now();
        mktgCloudAPISettings.MCAPIAccessToken__c = '12345';
        insert mktgCloudAPISettings;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        insert campaignList;
            
        Test.stopTest();
    }
}