objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MarketingCloudCampaignId__c</fullName>
        <externalId>true</externalId>
        <label>Marketing Cloud Campaign Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

objects/MktgCloudAPISettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the configuration values to call Mktg Cloud API</description>
    <fields>
        <fullName>MCAPIAccessToken__c</fullName>
        <label>MC API Access Token</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenCreationDate__c</fullName>
        <label>Token Creation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TokenDuration__c</fullName>
        <label>Token Duration</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mktg Cloud API Settings</label>
</CustomObject>

classes/MktgMCCampaignUpdateTest.cls
@isTest (seeAllData = false)
public with sharing class MktgMCCampaignUpdateTest {
    static testMethod void testSincronizeCampaignWithMC () {
        SingleRequestMock fakeTokenResponse = MarketingCloudAPIUtilTest.accessTokenResponse();
        SingleRequestMock fakeCampaignResponse = MarketingCloudAPIUtilTest.mktgCloudCampaignResponse();
        
        MarketingCloudAPIUtil.skipAPICall = true;
        
        MktgCloudAPISettings__c mktgCloudAPISettings = MarketingCloudAPIUtilTest.getMktgCloudAPISettings();
        mktgCloudAPISettings.TokenDuration__c = 3400;
        mktgCloudAPISettings.TokenCreationDate__c = Datetime.now();
        mktgCloudAPISettings.MCAPIAccessToken__c = '12345';
        
        insert mktgCloudAPISettings;

        List<Campaign> campaignList = TestDataFactory.createCampaigns(1);
        
        Map<String, SingleRequestMock> endpoint2TestResp = new Map<String,SingleRequestMock>();
        
        endpoint2TestResp.put('https://auth.exacttargetapis.com/v1/requestToken', fakeTokenResponse);
        endpoint2TestResp.put('https://www.exacttargetapis.com/hub/v1/campaigns/123', fakeCampaignResponse);

        HttpCalloutMock multiCalloutMock = new MktgCloudMultiCalloutMock(endpoint2TestResp);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, multiCalloutMock);
        
        campaignList.get(0).MarketingCloudCampaignId__c = '123';
        
        MktgMCCampaignUpdate.updateCampaignWithMC(campaignList);

        Test.stopTest();
    }
}