objects/Case.object
<CustomObject>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Case</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserRoleAPIName__c</fullName>
        <description>It is used to store the API name of the Salesfor Role assigned to the user based in the roles available for the work team in Work team permissions.</description>
        <externalId>true</externalId>
        <label>User Role API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>Stores the name of the work team that the user belongs to. It is loaded by development to control the vlocity actions available for a user.</description>
        <externalId>true</externalId>
        <label>Work Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>approver__c</fullName>
        <label>Approver</label>
        <relationshipName>Users</relationshipName>
        <restrictedAdminField>true</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the manager of the workplace</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InactivateTeamMebersWhenInactiveUserTest.cls
@isTest
public class InactivateTeamMebersWhenInactiveUserTest {    
     
      static testMethod void getWorkTeamsByKeyNameTest() {
    
        //GIVEN
        String NameTest = 'TestgetWorkTeamsByKeyNameTest';
        
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test 0002', Name = 'Test 002', Is_Active__c = true );
        
        System.debug('Insertando work team ' + workTeam );
        insert workTeam;
        
        User u = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
        
        Team_Member__c member = new Team_Member__c(Work_Team__c = workTeam.Id, Is_Active__c = true, UserRoleAPIName__c = NameTest, User_member__c = u.Id );
        insert member;
        
        Group g = new Group(Name = NameTest, developerName = 'InactivateTeamMebersWhenInactiveUserTest');
        insert g;
                
        List<User> myList = new List<User>();
        myList.add(u);        
        
        Map<String, Object> newMp = new Map<String, Object>();
        newMp.put('usersInactive',myList);
                
        //WHEN
        Test.startTest();
        System.enqueueJob(new InactivateTeamMebersWhenInactiveUsers('inactivateTeamMebers',newMp ));
        Test.stopTest();         
        
        //THEN
        System.assert(true);        
    }
    
    @isTest static void inactivateUserTeamManager(){
    	
    	// Creating a * Parent Team *
    	String ParentTeamName = 'TestinactivateUserTeamManager';
    	
    	User u = [SELECT Id FROM User WHERE IsActive = true LIMIT 1];
    	
    	WorkTeam__c workTeamParent = new WorkTeam__c(Team_Name__c = ParentTeamName, Name = ParentTeamName, Manager__c = u.Id, Is_Active__c = true );
        insert workTeamParent;
        
        // Creating a * User Team * with a Manager 
        String TeamName = 'TestinactivateUserTeamManager2';
               
        User manager_ui = [SELECT Id FROM User WHERE IsActive = true AND Id != : u.Id LIMIT 1];
        
        WorkTeam__c workUserTeam = new WorkTeam__c(Team_Name__c = TeamName, Name = TeamName, Manager__c = manager_ui.Id, Parent_Team__c = workTeamParent.Id, Is_Active__c = true );
        insert workUserTeam;
        
        // Adding a Team Member to the * User Team *
        User user_team = [SELECT Id FROM User WHERE IsActive = true AND (Id != : u.Id AND Id != : manager_ui.Id) LIMIT 1];
        
        Team_Member__c teamMember = new Team_Member__c(Work_Team__c = workUserTeam.Id, Is_Active__c = true, UserRoleAPIName__c = TeamName, User_member__c = user_team.Id );
        insert teamMember;
        
        // Creating a Case for testing
        Case newCase = new Case(subject='Inconvenientes con cargos tasados y facturados', Origin='Email', Status='Nueva', Approver__c = manager_ui.Id);
        insert newCase;
   
        // Creating a New Parent Work team to assign it to a Work Team Without Manager
    	String ParentTeamName2 = 'ParentTeam_WOM';
    	
    	User Manager2 = [SELECT Id FROM User WHERE IsActive = true AND (Id != :user_team.Id AND Id != :manager_ui.Id AND Id != :u.Id) LIMIT 1];
    	
    	WorkTeam__c workTeamParent2 = new WorkTeam__c(Team_Name__c = ParentTeamName2, Name = ParentTeamName2, Manager__c = Manager2.Id, Is_Active__c = true );
        insert workTeamParent2;
        
        // Creating a New Work Team Without Manager
        String TeamNameWithOutManager = 'WorkTeamWithoutManager';     
                
        WorkTeam__c workUserTeam2 = new WorkTeam__c(Team_Name__c = TeamNameWithOutManager, Name = TeamNameWithOutManager, Parent_Team__c = workTeamParent2.Id, Is_Active__c = true );
        insert workUserTeam2;
        
         // Adding a Team Member to the New Work Team Without Manager
        User user_team2 = [SELECT Id FROM User WHERE IsActive = true AND (Id != : u.Id AND Id != : manager_ui.Id AND Id != :user_team.Id AND Id != :Manager2.Id) LIMIT 1];
        
        Team_Member__c teamMember2 = new Team_Member__c(Work_Team__c = workUserTeam2.Id, Is_Active__c = true, UserRoleAPIName__c = TeamNameWithOutManager, User_member__c = user_team2.Id );
        insert teamMember2;        
        
        // Creating a Case for testing
        Case newCase2 = new Case(subject='Inconvenientes con cargos tasados y facturados', Origin='Email', Status='Nueva', Approver__c = Manager2.Id);
        insert newCase2;        
        // 
        
        // * * * * * * * * * * 
        
        // Creating a New Parent Work team to assign it to a Work Team Without Manager
    	String ParentTeamName4 = 'ParentTeam_WOM_4';
    	
    	User Manager4 = [SELECT Id FROM User WHERE IsActive = true AND (Id != :user_team.Id AND  Id != :manager_ui.Id AND Id != :u.Id AND Id != :Manager2.Id AND Id != :teamMember2.Id) LIMIT 1];
    	
    	WorkTeam__c workTeamParent4 = new WorkTeam__c(Team_Name__c = ParentTeamName4, Name = ParentTeamName4, Manager__c = Manager4.Id, Is_Active__c = true );
        insert workTeamParent4;
        
        // Creating a New Work Sub Team Without Manager
        String ParentTeamName3 = 'ParentTeam_WOM_3';
    	    	
    	WorkTeam__c workTeamParent3 = new WorkTeam__c(Team_Name__c = ParentTeamName3, Name = ParentTeamName3, Parent_Team__c = workTeamParent4.Id, Is_Active__c = true );
        insert workTeamParent3;             
        
        // Creating a New Work Team Without Manager
        String TeamNameWithOutManager2 = 'WorkTemaWithoutManager2';     
                
        WorkTeam__c workUserTeam3 = new WorkTeam__c(Team_Name__c = TeamNameWithOutManager2, Name = TeamNameWithOutManager2, Parent_Team__c = workTeamParent3.Id, Is_Active__c = true );
        insert workUserTeam3;            
        
         // Adding a Team Member to the New Work Team Without Manager
        User user_team3 = [SELECT Id FROM User WHERE IsActive = true AND (Id != : u.Id AND Id != :user_team.Id AND Id != :manager_ui.Id AND Id != :u.Id AND Id != :Manager2.Id AND Id != :teamMember2.Id AND Id != :Manager4.Id) LIMIT 1];
        
        Team_Member__c teamMember3 = new Team_Member__c(Work_Team__c = workUserTeam3.Id, Is_Active__c = true, UserRoleAPIName__c = TeamNameWithOutManager2, User_member__c = user_team3.Id );
        insert teamMember3;        
        
        // Creating a Case for testing
        Case newCase3 = new Case(subject='Inconvenientes con cargos tasados y facturados', Origin='Email', Status='Nueva', Approver__c = Manager4.Id);
        insert newCase3;        
        // 
             
        Test.startTest();
            // Changing case owner to the users created above
            newCase.OwnerId = user_team.Id;
            update newCase;
            
            newCase2.OwnerId = user_team2.Id;
            update newCase2;
            
            newCase3.OwnerId = user_team3.Id;
            update newCase3;
         
            // List "Pending" Approval processes 
            List<processInstanceWorkItem> processWorkItem = [SELECT Id, ActorId, ProcessInstance.Status FROM ProcessInstanceWorkitem WHERE ( ActorId =: user_team.Id OR ActorId =: user_team2.Id OR ActorId =: user_team3.Id ) AND Isdeleted = false];
              
            for(ProcessInstanceWorkitem lpIWI :processWorkItem){
    		    	
    		    lpIWI.ProcessInstance.Status = 'Pending';
    		}   
         
            update processWorkItem;
         
            List<User> myList = new List<User>();
            myList.add(user_team);  
            myList.add(user_team2); 
            myList.add(user_team3);      
        
            Map<String, Object> newMp = new Map<String, Object>();
            newMp.put('usersInactive',myList);
                                
            System.enqueueJob(new InactivateTeamMebersWhenInactiveUsers('inactivateTeamMebers',newMp ));  
            
        Test.stopTest();        
    }
}