objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <description>Describe el incidente del caso por ejemplo Sin Acceso ,Lentitud, Errores en consultas y/o gestiones,Varios</description>
        <label>Incident</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SubType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Sin Acceso</fullName>
                </value>
                <value>
                    <fullName>Lentitud</fullName>
                </value>
                <value>
                    <fullName>Errores en consultas y/o gestiones</fullName>
                </value>
                <value>
                    <fullName>Varios</fullName>
                </value>
                <value>
                    <fullName>Problemas de acceso</fullName>
                </value>
                <value>
                    <fullName>Faltante de datos</fullName>
                </value>
                <value>
                    <fullName>Andreani</fullName>
                </value>
                <value>
                    <fullName>Seprit</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con envio de informacion</fullName>
                </value>
                <value>
                    <fullName>Backend - Sin acceso</fullName>
                </value>
                <value>
                    <fullName>Backend - Lentitud </fullName>
                </value>
                <value>
                    <fullName>Backend - errores en consultas/ gestiones</fullName>
                </value>
                <value>
                    <fullName>Frontend - Sin acceso</fullName>
                </value>
                <value>
                    <fullName>Frontend - Lentitud </fullName>
                </value>
                <value>
                    <fullName>Frontend - errores en consultas/ gestiones</fullName>
                </value>
                <value>
                    <fullName>Canjes</fullName>
                </value>
                <value>
                    <fullName>Categorías</fullName>
                </value>
                <value>
                    <fullName>Puntos</fullName>
                </value>
                <value>
                    <fullName>Voz y Datos 2/3/4G</fullName>
                </value>
                <value>
                    <fullName>Voz y Datos 2/3G</fullName>
                </value>
                <value>
                    <fullName>Voz y Datos 2G</fullName>
                </value>
                <value>
                    <fullName>Voz y Datos 3G</fullName>
                </value>
                <value>
                    <fullName>Datos 4G</fullName>
                </value>
                <value>
                    <fullName>Datos 2G</fullName>
                </value>
                <value>
                    <fullName>Datos 3G</fullName>
                </value>
                <value>
                    <fullName>Voz 2G</fullName>
                </value>
                <value>
                    <fullName>Voz 3G</fullName>
                </value>
                <value>
                    <fullName>Voz 2/3G</fullName>
                </value>
                <value>
                    <fullName>Demoras en el impacto de comandos en el sistema de Gestion</fullName>
                </value>
                <value>
                    <fullName>Demoras en el impacto en la red (no se visualizan en HLR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RepeatedCalls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rellamados</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Define el  subtipo de un caso por ejemplo Siebel , Negocio Net, Negocio 2000 ( , campo agregado a solicitud de Telecom )</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Siebel</fullName>
                </value>
                <value>
                    <fullName>Negocio Net</fullName>
                </value>
                <value>
                    <fullName>Negocio 2000</fullName>
                </value>
                <value>
                    <fullName>Web de gestión móvil</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Paginas externas</fullName>
                </value>
                <value>
                    <fullName>Avaya  CMS Supervisor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Internet Monitor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitos Online</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitor Reportes</fullName>
                </value>
                <value>
                    <fullName>Avaya APC (Agente)</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC / ONE X</fullName>
                </value>
                <value>
                    <fullName>Avaya IC Manager</fullName>
                </value>
                <value>
                    <fullName>Avaya IN - Caída Total</fullName>
                </value>
                <value>
                    <fullName>Avaya ONE X</fullName>
                </value>
                <value>
                    <fullName>Banner de Productividad</fullName>
                </value>
                <value>
                    <fullName>Herramientas de Gestión/ Atencion</fullName>
                </value>
                <value>
                    <fullName>Inconveniente con las llamadas</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con correo</fullName>
                </value>
                <value>
                    <fullName>Página de Niveles</fullName>
                </value>
                <value>
                    <fullName>Social Media - WebLogueo</fullName>
                </value>
                <value>
                    <fullName>Trans Routing</fullName>
                </value>
                <value>
                    <fullName>TUID</fullName>
                </value>
                <value>
                    <fullName>Grabador NICE</fullName>
                </value>
                <value>
                    <fullName>Epiron (Redes Sociales)</fullName>
                </value>
                <value>
                    <fullName>Novedad Informativa</fullName>
                </value>
                <value>
                    <fullName>SNAP</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
                <value>
                    <fullName>*150 (saldo)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RepeatedCallsTest.cls
@isTest
public class RepeatedCallsTest {
    @isTest public static void simpleTest() {
        Case testCase = new Case(
            RecordTypeId=Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical Service').getRecordTypeId(),
            Type='Asteriscos TP',
            SubType__c='*150 (saldo)',
            Incident__c='La caracteristica No existe',
            Status='New'
        );
        
        insert testCase;
        
        List<Task> testTasks = new List<Task>{
            new Task(WhatId=testCase.Id, Subject='RepeatedCall', Type='Call'),
            new Task(WhatId=testCase.Id, Subject='RepeatedCall', Type='Call')
                };
        
        insert testTasks;
        
        Case c = [SELECT Id, RepeatedCalls__c  FROM Case WHERE Id = :testCase.Id];
        
        System.assertEquals(2, c.RepeatedCalls__c);
    }
}