objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Define el  subtipo de un caso por ejemplo Siebel , Negocio Net, Negocio 2000 ( , campo agregado a solicitud de Telecom )</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Siebel</fullName>
                </value>
                <value>
                    <fullName>Negocio Net</fullName>
                </value>
                <value>
                    <fullName>Negocio 2000</fullName>
                </value>
                <value>
                    <fullName>Web de gestión móvil</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Paginas externas</fullName>
                </value>
                <value>
                    <fullName>Avaya  CMS Supervisor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Internet Monitor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitos Online</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitor Reportes</fullName>
                </value>
                <value>
                    <fullName>Avaya APC (Agente)</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC / ONE X</fullName>
                </value>
                <value>
                    <fullName>Avaya IC Manager</fullName>
                </value>
                <value>
                    <fullName>Avaya IN - Caída Total</fullName>
                </value>
                <value>
                    <fullName>Avaya ONE X</fullName>
                </value>
                <value>
                    <fullName>Banner de Productividad</fullName>
                </value>
                <value>
                    <fullName>Herramientas de Gestión/ Atencion</fullName>
                </value>
                <value>
                    <fullName>Inconveniente con las llamadas</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con correo</fullName>
                </value>
                <value>
                    <fullName>Página de Niveles</fullName>
                </value>
                <value>
                    <fullName>Social Media - WebLogueo</fullName>
                </value>
                <value>
                    <fullName>Trans Routing</fullName>
                </value>
                <value>
                    <fullName>TUID</fullName>
                </value>
                <value>
                    <fullName>Grabador NICE</fullName>
                </value>
                <value>
                    <fullName>Epiron (Redes Sociales)</fullName>
                </value>
                <value>
                    <fullName>Novedad Informativa</fullName>
                </value>
                <value>
                    <fullName>SNAP</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
                <value>
                    <fullName>Suspensión siniestro</fullName>
                </value>
                <value>
                    <fullName>Reconexión siniestro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Descripción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Campo utilizado para identificar si es una suspensión de siniestro o administrativa</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Administrativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>sinister_type__c</fullName>
        <label>Tipo Siniestro</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Robo</fullName>
                </value>
                <value>
                    <fullName>Hurto</fullName>
                </value>
                <value>
                    <fullName>Extravio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Orders.cls
public class Orders extends ApplicationDomain {
    public Orders(List<Order> orders) {
        Super(orders);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain Construct(List<SObject> sObjectList) {
            return new Orders(sObjectList);
        } 
    }

    public override void OnAfterUpdate(Map<Id, SObject> existingOrders) {
        fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.NewInstance();
        Set<Id> suspensionAndReconnectionsOrdersActivated = new Set<Id>();

        for (Order order : (List<Order>) this.Records) {
            if (this.IsActivated(order.Status, ((Order) existingOrders.Get(order.Id)).Status)) {
                if (order.Gestion__c == OrderType.Suspension.Name() || order.Gestion__c == OrderType.Resume.Name()) {
                    suspensionAndReconnectionsOrdersActivated.add(order.Id);
                }
            }
        }

        if (!suspensionAndReconnectionsOrdersActivated.IsEmpty())
            this.RegisterTransactionEntry(unitOfWork, suspensionAndReconnectionsOrdersActivated, existingOrders);

        unitOfWork.CommitWork();
    }

    public void ComposeSuspension(fflib_ISObjectUnitOfWork unitOfWork, SuspensionReason suspensionReason) {
        for (Order order : (List<Order>) this.Records) {
            order.Gestion__c = OrderType.Suspension.Name();

            OrderItems orderItems = (OrderItems) Application.Domain.NewInstance(order.OrderItems);
            orderItems.SetActionsForSuspension(unitOfWork, suspensionReason);

            unitOfWork.RegisterDirty(order);
        }
    }

    public void ComposeReconnection(fflib_ISObjectUnitOfWork unitOfWork, Map<Id, Asset> assetsWithActiveSuspension) {
        for (Order order : (List<Order>) this.Records) {
            order.Gestion__c = OrderType.Resume.Name();

            OrderItems orderItems = (OrderItems) Application.Domain.NewInstance(order.OrderItems);
            orderItems.SetActionsForResume(unitOfWork, assetsWithActiveSuspension);

            unitOfWork.RegisterDirty(order);
        }
    }

    private Boolean IsActivated(String currentOrderStatus, String oldOrderStatus) {
        return (currentOrderStatus != oldOrderStatus && currentOrderStatus == 'Activated');
    }

    private void RegisterTransactionEntry(fflib_ISObjectUnitOfWork unitOfWork,
        Set<Id> suspensionAndReconnectionsOrdersActivated, Map<Id, SObject> existingOrders) {
        CasesSelector casesSelector = (CasesSelector) Application.Selector.NewInstance(Case.SObjectType);
        Set<Id> suspensionAndReconnectionsParentCaseIds = new Set<Id>();
        List<Case> suspensionAndReconnectionCases = casesSelector.SelectByOrderIdWithAsset(suspensionAndReconnectionsOrdersActivated);

        for (Case caseObj : suspensionAndReconnectionCases)
            suspensionAndReconnectionsParentCaseIds.Add(caseObj.ParentId);
        
        Map<Id, Case> suspensionAndReconnectionsParentCases = new Map<Id, Case>(casesSelector.SelectById(suspensionAndReconnectionsParentCaseIds));
       
        Id assetTransactionRecordTypeId = Schema.SObjectType.Transaction_History__c
            .GetRecordTypeInfosByName().Get('Asset Transaction History').GetRecordTypeId();

        for (Case caseObj : suspensionAndReconnectionCases) {
            caseObj.Status = 'Realizada exitosa';

            if (caseObj.ParentId != null) {
                Case parentCase = suspensionAndReconnectionsParentCases.Get(caseObj.ParentId);
                Order order = (Order) existingOrders.Get(caseObj.Order__c);

                Transaction_History__c suspensionToRegister = new Transaction_History__c();
                suspensionToRegister.Account__c = parentCase.AccountId;
                suspensionToRegister.Asset__c = caseObj.AssetId;
                suspensionToRegister.RecordTypeId = assetTransactionRecordTypeId;

                if (parentCase.SubType__c == 'Suspensión siniestro') {
                    suspensionToRegister.Description__c = 'Suspensión';
                    suspensionToRegister.Type__c = 'Siniestro';
                    suspensionToRegister.Sinister_type__c = parentCase.Reason;
                    suspensionToRegister.New_Status__c = 'Active';
                }
                else if (parentCase.SubType__c == 'Reconexión siniestro') {
                    suspensionToRegister.Type__c = 'Siniestro';
                    suspensionToRegister.Description__c = 'Reconexión';
                }
                else if (parentCase.SubType__c == 'Suspensión administrativa') {
                    suspensionToRegister.Description__c = 'Suspensión';
                    suspensionToRegister.Type__c = 'Administrativa';
                    suspensionToRegister.New_Status__c = 'Active';
                }
                else if (parentCase.SubType__c == 'Reconexión administrativa') {
                    suspensionToRegister.Type__c = 'Administrativa';
                    suspensionToRegister.Description__c = 'Reconexión';
                }

                unitOfWork.RegisterNew(suspensionToRegister);
            }

            unitOfWork.RegisterDirty(caseObj);
        }
    }
}