objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Define el  subtipo de un caso por ejemplo Siebel , Negocio Net, Negocio 2000 ( , campo agregado a solicitud de Telecom )</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Siebel</fullName>
                </value>
                <value>
                    <fullName>Negocio Net</fullName>
                </value>
                <value>
                    <fullName>Negocio 2000</fullName>
                </value>
                <value>
                    <fullName>Web de gestión móvil</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Paginas externas</fullName>
                </value>
                <value>
                    <fullName>Avaya  CMS Supervisor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Internet Monitor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitos Online</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitor Reportes</fullName>
                </value>
                <value>
                    <fullName>Avaya APC (Agente)</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC / ONE X</fullName>
                </value>
                <value>
                    <fullName>Avaya IC Manager</fullName>
                </value>
                <value>
                    <fullName>Avaya IN - Caída Total</fullName>
                </value>
                <value>
                    <fullName>Avaya ONE X</fullName>
                </value>
                <value>
                    <fullName>Banner de Productividad</fullName>
                </value>
                <value>
                    <fullName>Herramientas de Gestión/ Atencion</fullName>
                </value>
                <value>
                    <fullName>Inconveniente con las llamadas</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con correo</fullName>
                </value>
                <value>
                    <fullName>Página de Niveles</fullName>
                </value>
                <value>
                    <fullName>Social Media - WebLogueo</fullName>
                </value>
                <value>
                    <fullName>Trans Routing</fullName>
                </value>
                <value>
                    <fullName>TUID</fullName>
                </value>
                <value>
                    <fullName>Grabador NICE</fullName>
                </value>
                <value>
                    <fullName>Epiron (Redes Sociales)</fullName>
                </value>
                <value>
                    <fullName>Novedad Informativa</fullName>
                </value>
                <value>
                    <fullName>SNAP</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
                <value>
                    <fullName>Suspensión siniestro</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Descripción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Campo utilizado para identificar si es una suspensión de siniestro o administrativa</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Administrativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrdersTest.cls
@IsTest
private class OrdersTest {
    @IsTest
    private static void WhenComposeSuspensionCallsDomainAndUowRegisterDirty() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        
        // Given
        fflib_SObjectUnitOfWork mockUow = (fflib_SObjectUnitOfWork) mocks.Mock(fflib_SObjectUnitOfWork.Class);
        OrderItems mockOrderItems = (OrderItems) mocks.Mock(OrderItems.Class);

        Id orderId = fflib_IDGenerator.Generate(Order.SObjectType);
        Id orderItemId = fflib_IDGenerator.Generate(OrderItem.SObjectType);
        List<Order> testOrders = (List<Order>) fflib_ApexMocksUtils.MakeRelationship(
            List<Order>.Class,
            new List<Order> { new Order(Id = orderId) },
            OrderItem.OrderId,
            new List<List<OrderItem>> { 
                new List<OrderItem> { new OrderItem(Id = orderItemId) }
            }
        );

        mocks.StartStubbing();
        mocks.When(mockOrderItems.SObjectType()).ThenReturn(OrderItem.SObjectType);
        mocks.StopStubbing();

        Application.UnitOfWork.SetMock(mockUow);
        Application.Domain.SetMock(mockOrderItems);                    

        // When
        Orders orders = new Orders(testOrders);
        orders.ComposeSuspension(mockUow, SuspensionReason.Robo);
        
        // Then
        ((fflib_SObjectUnitOfWork) 
            mocks.Verify(mockUow, 1)).RegisterDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object> { 
                        Order.Id => orderId,
                        Order.Gestion__c => OrderType.Suspension.Name()
                    }));
        ((OrderItems) mocks.Verify(mockOrderItems, 1)).SetActionsForSuspension(mockUow, SuspensionReason.Robo);
    }

    @IsTest
    private static void WhenComposeReconnectionCallsDomainAndUowRegisterDirty() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        
        // Given
        fflib_SObjectUnitOfWork mockUow = (fflib_SObjectUnitOfWork) mocks.Mock(fflib_SObjectUnitOfWork.Class);
        OrderItems mockOrderItems = (OrderItems) mocks.Mock(OrderItems.Class);

        Id orderId = fflib_IDGenerator.Generate(Order.SObjectType);
        Id orderItemId = fflib_IDGenerator.Generate(OrderItem.SObjectType);
        List<Order> testOrders = (List<Order>) fflib_ApexMocksUtils.MakeRelationship(
            List<Order>.Class,
            new List<Order> { new Order(Id = orderId) },
            OrderItem.OrderId,
            new List<List<OrderItem>> { 
                new List<OrderItem> { new OrderItem(Id = orderItemId) }
            }
        );

        mocks.StartStubbing();
        mocks.When(mockOrderItems.SObjectType()).ThenReturn(OrderItem.SObjectType);
        mocks.StopStubbing();

        Application.UnitOfWork.SetMock(mockUow);
        Application.Domain.SetMock(mockOrderItems);                    

        // When
        Orders orders = new Orders(testOrders);
        orders.ComposeReconnection(mockUow, null);
        
        // Then
        ((fflib_SObjectUnitOfWork) 
            mocks.Verify(mockUow, 1)).RegisterDirty(
                fflib_Match.sObjectWith(
                    new Map<SObjectField, Object> { 
                        Order.Id => orderId,
                        Order.Gestion__c => OrderType.Resume.Name()
                    }));
        ((OrderItems) mocks.Verify(mockOrderItems, 1)).SetActionsForResume(mockUow, null);
    }

    @IsTest
    private static void WhenOnAfterUpdateSinisterSuspensionOrderTransactionHistoryMustBeCreated() {
        //Given
        Integer ordersQuantityToCreate = 1;
        Account account = TestDataFactory.CreateAccounts(1)[0];
        List<Order> orders = TestDataFactory.CreateOrders(ordersQuantityToCreate, account);
        Asset asset = TestDataFactory.CreateAssets(1, account)[0];
        List<Case> expectedCases = TestDataFactory.CreateCases(2, account.Id, asset.Id, 'TestSubject');
        TestDataFactory.CreateOrderItemsWithAsset(1, orders[0], asset);
        Set<Id> expectedOrderIds = new Map<Id, Order>(orders).KeySet();

        //When
        Test.StartTest();        
        for (Case caseObj : expectedCases) {
            caseObj.Order__c = orders[0].Id;
            caseObj.SubType__c = 'Suspensión siniestro';
        }

        expectedCases[1].ParentId = expectedCases[0].Id;

        update expectedCases;

        for (Order order : orders) {
            order.Status = 'Activated';
            order.Gestion__c = 'Suspension';
        }

        update orders;

        List<Transaction_History__c> suspensions = [
            SELECT Description__c, Type__c, New_Status__c
            FROM Transaction_History__c
            WHERE Asset__c = :asset.Id
        ];
        Test.StopTest();

        //Then
        System.AssertEquals('Suspensión', suspensions[0].Description__c);
        System.AssertEquals('Siniestro', suspensions[0].Type__c);
        System.AssertEquals('Active', suspensions[0].New_Status__c);
    }
}