objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>OrderApprovalStatus__c</fullName>
        <description>Order Status when approval needed from Administración de Ventas profile.</description>
        <label>OrderApprovalStatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente de aprobación</fullName>
                </value>
                <value>
                    <fullName>Aprobado por ADV</fullName>
                </value>
                <value>
                    <fullName>Rechazada por ADV</fullName>
                </value>
                <value>
                    <fullName>Aprobada automáticamente</fullName>
                </value>
                <value>
                    <fullName>Devuelto al Vendedor</fullName>
                </value>
                <value>
                    <fullName>Rechazado por Cliente</fullName>
                </value>
                <value>
                    <fullName>Aprobado por Cliente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EntitlementManagerTest.cls
@isTest

public class EntitlementManagerTest {
	
    @isTest static void CreateEntitlementAndGetExistentEntitlementMap_Test (){
    	
    Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account accountObj = new Account (
            Name='Account Test', 
            RecordTypeId = businessRecordTypeId
        );
        insert accountObj;  
        
        List<Order> testOrder = TestDataFactory.createOrders(1,accountObj);
        testOrder[0].OrderApprovalStatus__c = 'Pendiente de aprobación';
        update testOrder;
        
        Id techServiceRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Technical Service').getRecordTypeId();
        Case caseObj2 = New Case(
            Origin = 'Personalizado',
            AccountId = accountObj.Id,
            RecordTypeId = techServiceRecordTypeId,
            Subject = 'Gestión de Servicio Técnico',
            Order__c = testOrder[0].Id
            );
        insert caseObj2;
        
        Test.startTest();
        caseObj2.Status = 'En espera del cliente';
        Update caseObj2;            
        Test.stopTest();
        Case finalCase = [SELECT Id,AccountId,EntitlementId FROM Case WHERE AccountId =: accountObj.Id LIMIT 1];
        system.AssertNotEquals(null,finalCase.EntitlementId);
        
    }
    
}