objects/Case.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Orden</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <description>Define el  subtipo de un caso por ejemplo Siebel , Negocio Net, Negocio 2000 ( , campo agregado a solicitud de Telecom )</description>
        <label>SubType</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Siebel</fullName>
                </value>
                <value>
                    <fullName>Negocio Net</fullName>
                </value>
                <value>
                    <fullName>Negocio 2000</fullName>
                </value>
                <value>
                    <fullName>Web de gestión móvil</fullName>
                </value>
                <value>
                    <fullName>NPS</fullName>
                </value>
                <value>
                    <fullName>Click</fullName>
                </value>
                <value>
                    <fullName>Paginas externas</fullName>
                </value>
                <value>
                    <fullName>Avaya  CMS Supervisor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Internet Monitor</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitos Online</fullName>
                </value>
                <value>
                    <fullName>Avaya APC - Monitor Reportes</fullName>
                </value>
                <value>
                    <fullName>Avaya APC (Agente)</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC</fullName>
                </value>
                <value>
                    <fullName>Avaya Barra AIC / ONE X</fullName>
                </value>
                <value>
                    <fullName>Avaya IC Manager</fullName>
                </value>
                <value>
                    <fullName>Avaya IN - Caída Total</fullName>
                </value>
                <value>
                    <fullName>Avaya ONE X</fullName>
                </value>
                <value>
                    <fullName>Banner de Productividad</fullName>
                </value>
                <value>
                    <fullName>Herramientas de Gestión/ Atencion</fullName>
                </value>
                <value>
                    <fullName>Inconveniente con las llamadas</fullName>
                </value>
                <value>
                    <fullName>Inconvenientes con correo</fullName>
                </value>
                <value>
                    <fullName>Página de Niveles</fullName>
                </value>
                <value>
                    <fullName>Social Media - WebLogueo</fullName>
                </value>
                <value>
                    <fullName>Trans Routing</fullName>
                </value>
                <value>
                    <fullName>TUID</fullName>
                </value>
                <value>
                    <fullName>Grabador NICE</fullName>
                </value>
                <value>
                    <fullName>Epiron (Redes Sociales)</fullName>
                </value>
                <value>
                    <fullName>Novedad Informativa</fullName>
                </value>
                <value>
                    <fullName>SNAP</fullName>
                </value>
                <value>
                    <fullName>Sender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CasesSelector.cls
public class CasesSelector extends ApplicationSelector {
    public Schema.SObjectType GetSObjectType() {
        return Case.SObjectType;
    }

    public List<Schema.SObjectField> GetSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Case.Id,
            Case.Status,
            Case.Type,
            Case.SubType__c,
            Case.Reason,
            Case.ParentId,
            Case.AccountId,
            Case.Order__c
        };
    }

    public List<Case> SelectById(Set<Id> caseIds) {
        return (List<Case>) this.SelectSObjectsById(caseIds);
    }

    public List<Case> SelectByOrderId(Set<Id> orderIds) {
        return (List<Case>) Database.Query(
            this.NewQueryFactory().SetCondition('Order__c IN :orderIds').ToSOQL()
        );
    }

    public List<Case> SelectByOrderIdWithAsset(Set<Id> orderIds) {
        fflib_QueryFactory casesQueryFactory = this.NewQueryFactory();
       
        new AssetsSelector().ConfigureQueryFactoryFields(
            casesQueryFactory,
            Case.AssetId.GetDescribe().GetRelationshipName());

        return (List<Case>) Database.Query(
            casesQueryFactory.SetCondition('Order__c IN :orderIds').ToSOQL()
        );
    }
}