objects/CreditCardsBins__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting  para registrar bins de  las tarjetas de credito</description>
    <fields>
        <fullName>CredicardTypeId__c</fullName>
        <label>CredicardTypeId</label>
        <length>55</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CreditCardsBins</label>
</CustomObject>

objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>Cbu__c</fullName>
        <label>Cbu</label>
        <length>22</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>alias__c</fullName>
        <description>Campo para indicar el alias para una cuenta bancaria</description>
        <label>Alias</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CardNumber__c</fullName>
        <label>Card Number</label>
        <length>16</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CardType__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Master Card</fullName>
                </value>
                <value>
                    <fullName>DISCOVER</fullName>
                </value>
                <value>
                    <fullName>UCB</fullName>
                </value>
                <value>
                    <fullName>MASTERCARD</fullName>
                </value>
                <value>
                    <fullName>377</fullName>
                    <label>VISA</label>
                </value>
                <value>
                    <fullName>CABAL</fullName>
                </value>
                <value>
                    <fullName>CREDENCIAL</fullName>
                </value>
                <value>
                    <fullName>AMERICAN EXPRESS</fullName>
                </value>
                <value>
                    <fullName>DINERS</fullName>
                </value>
                <value>
                    <fullName>NARANJA</fullName>
                </value>
                <value>
                    <fullName>KADICARD</fullName>
                </value>
                <value>
                    <fullName>TARJETA AZUL</fullName>
                </value>
                <value>
                    <fullName>TARJETA ARGENTA</fullName>
                </value>
                <value>
                    <fullName>NEVADA</fullName>
                </value>
                <value>
                    <fullName>VISA PROVENCRED</fullName>
                </value>
                <value>
                    <fullName>CARTA AUTOMATICA</fullName>
                </value>
                <value>
                    <fullName>TARJETA GRUPAR</fullName>
                </value>
                <value>
                    <fullName>CREDIMAS</fullName>
                </value>
                <value>
                    <fullName>TARJETA NATIVA</fullName>
                </value>
                <value>
                    <fullName>MIRA</fullName>
                </value>
                <value>
                    <fullName>TARJETA SHOPPING</fullName>
                </value>
                <value>
                    <fullName>SIDECREER</fullName>
                </value>
                <value>
                    <fullName>NARANJA-VISA</fullName>
                </value>
                <value>
                    <fullName>COOPEPLUS</fullName>
                </value>
                <value>
                    <fullName>DATA 2000</fullName>
                </value>
                <value>
                    <fullName>TARJETA CREDICASH</fullName>
                </value>
                <value>
                    <fullName>TARJETA SOL</fullName>
                </value>
                <value>
                    <fullName>TARJETA TITANIO</fullName>
                </value>
                <value>
                    <fullName>TARJETA CMR</fullName>
                </value>
                <value>
                    <fullName>TARJETA MAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Last4Numbers__c</fullName>
        <label>Last4Numbers</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__MethodType__c</fullName>
        <label>Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <default>true</default>
                    <label>Efectivo</label>
                </value>
                <value>
                    <fullName>1201</fullName>
                    <label>Debito a Proxima Factura</label>
                </value>
                <value>
                    <fullName>2001</fullName>
                    <label>Tarjeta de Credito</label>
                </value>
                <value>
                    <fullName>Transferencia Bancaria</fullName>
                </value>
                <value>
                    <fullName>4002</fullName>
                    <label>Tarjeta de Debito</label>
                </value>
                <value>
                    <fullName>9998</fullName>
                    <label>Descuento de Saldo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PaymentMethodTriggerHandler.cls
/**
 * Created by Alex on 14/9/2017.
 */
public class PaymentMethodTriggerHandler {

    public static void processPaymentMethodUpdates(List<vlocity_cmt__PaymentMethod__c> triggerNew) {

        System.debug('Inside of processPaymentMethodUpdates');
        System.debug('Trigger Data: ' + triggerNew);
        // Process logic for each paymentMethod
        for(vlocity_cmt__PaymentMethod__c payment : triggerNew){
            System.debug('Payment Data: ' + payment );
            System.debug('Payment.MethodType Data: ' + payment.vlocity_cmt__MethodType__c);
            System.debug('Payment.CardNumber Data: ' + payment.vlocity_cmt__CardNumber__c);
            if(payment.vlocity_cmt__MethodType__c=='Credit Card' || payment.vlocity_cmt__MethodType__c=='Bank Account' &&
            payment.alias__c == null){
                // Parsing the ccNumber to grab the last 4 digits
                String methodNumber = null;
                if(payment.vlocity_cmt__MethodType__c=='Credit Card'){ methodNumber = payment.vlocity_cmt__CardNumber__c; }
                if(payment.vlocity_cmt__MethodType__c=='Bank Account' && payment.Cbu__c != null){ methodNumber = payment.Cbu__c; }
                String last4digits = PaymentMethodTriggerHandler.extractLast4(methodNumber);
                // Changing the trigger.new data of the last4Numbers field
                payment.vlocity_cmt__Last4Numbers__c = last4digits;
            }

            if(payment.vlocity_cmt__MethodType__c=='Credit Card') {
                // Grabbing the CardType by Bins matching
                String cardTypeName = PaymentMethodTriggerHandler.extractCardTypebyMatchingWithBines(
                        payment.vlocity_cmt__CardNumber__c);
                // Changing the trigger.new data of cardType field
                payment.vlocity_cmt__CardType__c = cardTypeName;
            }

        }
        System.debug('End of Trigger Processing: ' + triggerNew);

    }

    public static String extractLast4(String ccNumber){

        // Grabbing total length
        Integer length = ccNumber.length();
        // returning the last 4 digits
        return ccNumber.substring(length-4,length);
    }

    public static String extractCardTypebyMatchingWithBines(String ccNumber) {
        // Getting al the bines from the custom setting
        List<CreditCardsBins__c> ccBins = CreditCardsBins__c.getall().values();
        // setting isvalidbin to false
        Boolean isBin = false;
        String cardType;

        for (CreditCardsBins__c ccb : ccBins){
        System.debug('CCBin: ' + ccb);
            // Only checking against the ccnumbers that are the same length as the bin
            String ccNumberAccordingtoBinLength = ccNumber.substring(0,ccb.CredicardTypeId__c.length());
        System.debug('ccNumberAccordingtoBinLength : ' + ccNumberAccordingtoBinLength);
            // Check if the bin is part of the cc
            isBin = ccNumberAccordingtoBinLength.contains(ccb.CredicardTypeId__c);
        System.debug('isBin: ' + isBin);
            if(isBin){
                // if true assign the string the cardtypename
                cardType = ccb.Name;
                break;
            }
        }
        return cardType;
    }

}