objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Account object.</description>
        <inlineHelpText>this field determines the relationship with the Account object.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkbox1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>generic checkbox field type</description>
        <inlineHelpText>generic checkbox field type</inlineHelpText>
        <label>Checkbox1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentAdjustment__c.object
<CustomObject>
    <description>Payment adjustments allow a Customer Service Rep to request an adjustment to a customer&apos;s billing statement. For example, this could occur as the result of a case that was registered to dispute a prior billing or product issue. Once the adjustment is approved, it can then be fed to the client&apos;s billing system for processing. This object can also be used to register a client&apos;s payment independent of any dispute.</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship that establishes the means or means of payment that were configured as intention to use for the payment of the order.</description>
        <inlineHelpText>Relationship that establishes the means or means of payment that were configured as intention to use for the payment of the order</inlineHelpText>
        <label>Sale Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Payment Adjustments</relationshipLabel>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PaymentMethodId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>vlocity_cmt__PaymentMethod__c.vlocity_cmt__IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.vlocity_cmt__AccountId__c</field>
                <operation>equals</operation>
                <valueField>vlocity_cmt__PaymentMethod__c.vlocity_cmt__AccountId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>vlocity_cmt__PaymentMethod__c</referenceTo>
        <relationshipLabel>Payment Adjustments</relationshipLabel>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>vlocity_cmt__MethodType__c</fullName>
        <label>Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <default>true</default>
                    <label>Efectivo</label>
                </value>
                <value>
                    <fullName>1201</fullName>
                    <label>Debito a Proxima Factura</label>
                </value>
                <value>
                    <fullName>2001</fullName>
                    <label>Tarjeta de Credito</label>
                </value>
                <value>
                    <fullName>Transferencia Bancaria</fullName>
                </value>
                <value>
                    <fullName>4002</fullName>
                    <label>Tarjeta de Debito</label>
                </value>
                <value>
                    <fullName>9998</fullName>
                    <label>Descuento de Saldo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/taSalesLogValidationIdentityExtension.cls
public with sharing class taSalesLogValidationIdentityExtension {

    public List<Crossobject__c> logs{get;set;}

    public taSalesLogValidationIdentityExtension(ApexPages.StandardController controller){
        Id orderId = controller.getId();
        RecordType recordTypeLog = [SELECT Id, Name FROM RecordType WHERE name = 'Log Identity Validation'];
        // paymentMethods = [SELECT vlocity_cmt__PaymentMethodId__r.vlocity_cmt__MethodType__c , vlocity_cmt__Amount__c FROM vlocity_cmt__PaymentAdjustment__c WHERE Order__c =: orderId];
        logs = [SELECT PickList1__c, DateTime1__c, Account__c, Account__r.Name, Checkbox1__c
                FROM Crossobject__c 
                WHERE Order__c =: orderId
                AND RecordTypeId = :recordTypeLog.Id
                ORDER BY DateTime1__c DESC];
    }
}