objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Email1__c</fullName>
        <description>generic email field type</description>
        <inlineHelpText>generic email field type</inlineHelpText>
        <label>Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <recordTypes>
        <fullName>EmailToSend</fullName>
        <active>true</active>
        <label>Email to send</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PickUpStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pick Up Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Pick Up Store Location)</relationshipLabel>
        <relationshipName>OrdersForPickUp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Orders Using This Price List</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>PointOfSaleAddressNumber__c</fullName>
        <description>Point Of Sale Address Number</description>
        <inlineHelpText>Point Of Sale Address Number</inlineHelpText>
        <label>Address Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PointOfSaleType__c</fullName>
        <description>PFTA-8812 - Stores the type of facility that the store location has.</description>
        <label>Type of facility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PointOfSaleTypesSet</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__StreetAddress__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <description>A price list represents the pricing for the products and services that your company offers. A base price list defines the baseline pricing for your products and services. A child price list inherits all the pricing from the base price list and contains exceptions to the baseline pricing.</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/ta_sales_DetallesDePickupControllerTest.cls
@isTest
public class ta_sales_DetallesDePickupControllerTest {

    @isTest static void loadValuesTest() {
        //GIVEN
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        
        Account account = [SELECT Id FROM Account LIMIT 1];
        vlocity_cmt__PriceList__c taPriceList = TestDataFactory.createPriceList('Telecom Price List');
        Order order = new Order(Name='TestOrder',
                                AccountId=account.Id,
                                EffectiveDate=Date.today(),
                                Status='Draft',
                                Pricebook2Id =Test.getStandardPricebookId(),
                                vlocity_cmt__PriceListId__c=taPriceList.Id,
                                Delivery_Method__c='Delivery',
                                vlocity_cmt__OriginatingChannel__c='Agentes'
                                );
        
        insert order;        
        
        vlocity_cmt__BusinessSite__c site = new vlocity_cmt__BusinessSite__c (
          vlocity_cmt__City__c = 'Tigre',
          PointOfSaleId__c = 1, 
          vlocity_cmt__StreetAddress__c = 'Test',
          PointOfSaleAddressNumber__c = '1',
          vlocity_cmt__OrganizationId__c = account.Id,
          PointOfSaleType__c  = 'LE',
          vlocity_cmt__State__c = '',
          vlocity_cmt__Country__c = '');
    insert site;
        
        order.PickUpStoreLocation__c = site.Id;
        update order;
        
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'CrossObject__c' AND DeveloperName = 'EmailToSend'];
        CrossObject__c cross = new CrossObject__c(Email1__c = 'test@test.com', Picklist1__c = 'Detalles de Pickup', RecordTypeId = rt.Id, Order__c = order.Id);
        insert cross;
                
        ta_sales_DetallesDePickupController DetallesDePickupController = new ta_sales_DetallesDePickupController();
        DetallesDePickupController.crossId = cross.Id;
        
        //WHEN
        Test.startTest();
        CrossObject__c crossObj = DetallesDePickupController.loadedCro;
        Test.stopTest();
        
        //THEN
        System.assert(true);
        
    }
    
    @isTest static void loadValuesExceptionTest() {
        //GIVEN
        ta_sales_DetallesDePickupController DetallesDePickupController = new ta_sales_DetallesDePickupController();
        
        //WHEN
        DetallesDePickupController.loadValues();
        
        
        //THEN
        System.assert(true);
        
    }
}