objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>String2__c</fullName>
        <description>generic string field type</description>
        <inlineHelpText>generic string field type</inlineHelpText>
        <label>String 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <recordTypes>
        <fullName>Account_Attribute</fullName>
        <active>false</active>
        <description>Account Attribute</description>
        <label>Account Attribute</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AttributeCrossObjectExtension.cls
public class AttributeCrossObjectExtension {
    
    public CrossObject__c record {get;set;}
    public List<SelectOption> RecordTypePicklist {get;set;}    
    public List<SelectOption> RecordTypeAdded {get;set;}    
    
    public AttributeCrossObjectExtension(ApexPages.StandardController stdCon){
        RecordTypePicklist = new list <SelectOption>();    
        RecordTypeAdded = new list <SelectOption>();    
        List<RecordType> RecordTypeList = new list <RecordType>();
        RecordTypeList = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Account'];
    
        for(RecordType type : RecordTypeList){
            RecordTypePicklist.add(new selectoption(type.Id,type.DeveloperName));
        }
    }
    
    public pageReference save(){
        List<RecordType> RecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'CrossObject__c'
                                                                 AND DeveloperName = 'Account_Attribute'];
        record.RecordTypeId = RecordType[0].Id;
        for(SelectOption so : RecordTypeAdded){
            record.String2__c = record.String2__c + so.getValue() + ';';
        }
        System.Debug('Yamil ' + record.String2__c);
        return null;
    }
}