objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Account object.</description>
        <inlineHelpText>this field determines the relationship with the Account object.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkbox1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>generic checkbox field type</description>
        <inlineHelpText>generic checkbox field type</inlineHelpText>
        <label>Checkbox1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Picklist1__c</fullName>
        <description>field of type list that is related and filtered with the record type of the object</description>
        <inlineHelpText>field of type list that is related and filtered with the record type of the object</inlineHelpText>
        <label>Picklist 1</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verificación de Línea Decisora</fullName>
                </value>
                <value>
                    <fullName>Verificación de identidad en una orden de venta</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de plazo de permanencia</fullName>
                </value>
                <value>
                    <fullName>Q&amp;A</fullName>
                </value>
                <value>
                    <fullName>Sms</fullName>
                </value>
                <value>
                    <fullName>Document</fullName>
                </value>
                <value>
                    <fullName>Vencimiento de Pickup</fullName>
                </value>
                <value>
                    <fullName>Detalles de Pickup</fullName>
                </value>
                <value>
                    <fullName>Error de nominacion</fullName>
                </value>
                <value>
                    <fullName>Nominacion exitosa</fullName>
                </value>
                <value>
                    <fullName>Recarga Exitosa</fullName>
                </value>
                <value>
                    <fullName>Cambio Numeros Amigos Ok</fullName>
                </value>
                <value>
                    <fullName>Renovacion de datos Exitosa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taSalesLogValidationIdentityExtTest.cls
@isTest
public class taSalesLogValidationIdentityExtTest {
    
    @isTest static void constructorTest(){
    	Account acc = TestDataFactory.createAccounts(1,'Consumer')[0];
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        Order ord = TestDataFactory.createOrders(1, acc)[0];
        Date newDate = Date.today();
        
        Crossobject__c crossObjectTest = new Crossobject__c( 
            PickList1__c = 'Document',
          	DateTime1__c = newDate, 
            Account__c = acc.Id,  
            Checkbox1__c = true,
            RecordTypeId = '0126C0000000AKJQA2',
            Order__c = ord.Id
        );
        insert crossObjectTest;
        
        System.debug(crossObjectTest + 'here testing1');
        
		ApexPages.StandardController stdLead = new ApexPages.StandardController(ord);  
        taSalesLogValidationIdentityExtension testClass = new taSalesLogValidationIdentityExtension(stdLead);

		System.assertEquals(testClass.logs[0].Id, crossObjectTest.Id);
        
    }
}