objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>this field determines the relationship with the Order object.</description>
        <inlineHelpText>this field determines the relationship with the Order object.</inlineHelpText>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Cross Objects</relationshipLabel>
        <relationshipName>Cross_Objects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>PickUpStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pick Up Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Pick Up Store Location)</relationshipLabel>
        <relationshipName>OrdersForPickUp</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OperatingHoursId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operating Hours</label>
        <referenceTo>vlocity_cmt__OperatingHours__c</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__StreetAddress__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OperatingHours__c.object
<CustomObject>
    <fields>
        <fullName>HoraEntrada__c</fullName>
        <label>Hora entrada</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HoraSalida__c</fullName>
        <label>Hora salida</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Operating Hours</label>
    <nameField>
        <label>Operating Hours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Operating Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_sales_DetallesDePickupController.cls
public class ta_sales_DetallesDePickupController{

    public boolean loaded = false;
    public Id crossId{get; set;}
    public String address{get;set;}
    public String horas{get;set;}
    
    public CrossObject__c loadedCro{ get{
        if(!loaded){
            loadValues();
            loaded = true;
        }
        return loadedCro;
        }  set;
    }
     
    public void loadValues() {
        loaded = true;
        try{
            loadedCro = [SELECT Id, Order__c, Order__r.PickUpStoreLocation__c FROM CrossObject__c WHERE Id = :crossId];
            Id storeId = loadedCro.Order__r.PickUpStoreLocation__c;
            vlocity_cmt__BusinessSite__c store = [SELECT Id, vlocity_cmt__StreetAddress__c, vlocity_cmt__State__c, vlocity_cmt__City__c, vlocity_cmt__Country__c, vlocity_cmt__OperatingHoursId__r.HoraEntrada__c, vlocity_cmt__OperatingHoursId__r.HoraSalida__c FROM vlocity_cmt__BusinessSite__c WHERE Id = :storeId];
            address = store.vlocity_cmt__StreetAddress__c + ', ' + store.vlocity_cmt__City__c + ', ' + store.vlocity_cmt__State__c + ', ' + store.vlocity_cmt__Country__c;
            horas = 'Horario de ' + store.vlocity_cmt__OperatingHoursId__r.HoraEntrada__c + 'hs a ' + store.vlocity_cmt__OperatingHoursId__r.HoraSalida__c + 'hs';
            //vlocity_cmt__OperatingHours__c
        }catch(Exception e){}
    }
}