objects/Crossobject__c.object
<CustomObject>
    <description>#Sales #Sprint12

multi-purpose object that allows you to configure templates of particular use such as content configurations of SMS, EMAILS, etc. and also allows you to track the sending and reply transactions of SMS, EMAILs, etc.

It has generic fields of type text, number and date which are added to several types of record types which are complemented with two fields of type pick list, thus a record type of type SMS can be combined with a sub value of type &quot;decision line&quot;</description>
    <fields>
        <fullName>DateTime1__c</fullName>
        <label>DateTime 1</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MarkForDeletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>field represent of mark for deletion record</description>
        <inlineHelpText>field represent of mark for deletion record</inlineHelpText>
        <label>Mark for deletion</label>
        <type>Checkbox</type>
    </fields>
    <label>Cross Object</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Crossobject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cross Objects</pluralLabel>
    <recordTypes>
        <fullName>SMSTracking</fullName>
        <active>true</active>
        <label>SMS Tracking</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_sales_purgeCrossObjects.cls
global class ta_sales_purgeCrossObjects implements Database.Batchable<sObject>, Schedulable {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, DateTime1__c FROM CrossObject__c WHERE MarkForDeletion__c = TRUE OR (RecordType.DeveloperName = \'SMSTracking\' AND DateTime1__c < TODAY)';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }

    public void execute(Schedulablecontext ctx){
        ta_sales_purgeCrossObjects batch = new ta_sales_purgeCrossObjects ();
        Database.executeBatch(batch);
    }
}