objects/DebugInfo__c.object
<CustomObject>
    <fields>
        <fullName>DebugData__c</fullName>
        <label>DebugData</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DebugLabel__c</fullName>
        <label>DebugLabel</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Info</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>MethodName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessName__c</fullName>
        <label>ProcessName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DebugLog</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>DebugInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DebugLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DebugInfo.cls
public with sharing class DebugInfo {
    
    public static void AddDebugInfoEntry(String processName, String methodName, String debugData) {
        AddDebugEntry(processName, methodName, debugData, 'Info');
    }

    public static void AddDebugWarningEntry(String processName, String methodName, String debugData) {
        AddDebugEntry(processName, methodName, debugData, 'Warning');
    }

    public static void AddDebugErrorEntry(String processName, String methodName, String debugData) {
        AddDebugEntry(processName, methodName, debugData, 'Error');
    }

    private static void AddDebugEntry(String processName, String methodName, String debugData, String debugType) {
        DebugInfo__c debugInfo = new DebugInfo__c(
            ProcessName__c = processName,
            MethodName__c = methodName,
            DebugData__c = String.valueOf(debugData),
            DebugLabel__c = debugType
        );

        insert debugInfo;
    }
}