objects/FinancialPromotions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Bank_Code__c</fullName>
        <label>Bank Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CFT__c</fullName>
        <label>CFT</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Creditcard_Type__c</fullName>
        <label>Creditcard Type Id</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instalments__c</fullName>
        <label>Instalments</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>FinancialPromotions</label>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentMethodType__c</fullName>
        <label>Payment Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethodType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PickUpStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pick Up Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Pick Up Store Location)</relationshipLabel>
        <relationshipName>OrdersForPickUp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PaymentMethodType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Method Type</label>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>AssociatedWarehouseDefault__c</fullName>
        <label>Associated Warehouse Default</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/taOrderBillingUpdateProcessTest.cls
@isTest
public class taOrderBillingUpdateProcessTest
{
  static testMethod void Test1()
  {
    List<Order> lstOrder = new List<Order>();
    List<Account> AccList = TestDataFactory.createAccounts(1, 'Consumer');
    vlocity_cmt__BusinessSite__c StoreLocations = new vlocity_cmt__BusinessSite__c(vlocity_cmt__OrganizationId__c=AccList[0].id ,PointOfSaleId__c=1.0, AssociatedWarehouseDefault__c='Default');
    insert StoreLocations;
    FinancialPromotions__c Promo1 = new FinancialPromotions__c(Name='Promo1',Creditcard_Type__c='403', Bank_Code__c='1', Instalments__c='1', CFT__c='test');
    insert Promo1;
    TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
    List<Order>OrdList = TestDataFactory.createOrders(2,AccList[0]);
    OrdList[0].PaymentMethodType__c ='1001';
    OrdList[0].vlocity_cmt__OriginatingChannel__c ='Presencial Oficina Comercial';
    OrdList[0].PickUpStoreLocation__c = StoreLocations.id;
    OrdList[1].vlocity_cmt__OriginatingChannel__c ='Presencial Oficina Comercial';
    OrdList[1].PickUpStoreLocation__c = StoreLocations.id;
    update OrdList;
    List<OrderItem>OIList =TestDataFactory.createOrderItem(2,OrdList[0]);
    List<OrderItem>OIList1 =TestDataFactory.createOrderItem(2,OrdList[1]);
    //generateMockupData();
    Test.startTest();
      Test.setMock(HttpCalloutMock.class, new IFS121NoLineMockHttpResponseGeneretor());
      taOrderBillingUpdateProcess.BillUpdateOrder(OrdList[0].Id);
    Test.stopTest();
  }
    static testMethod void Test2()
    {
      List<Order> lstOrder = new List<Order>();
      List<Account> AccList = TestDataFactory.createAccounts(1, 'Consumer');
      vlocity_cmt__BusinessSite__c StoreLocations = new vlocity_cmt__BusinessSite__c(vlocity_cmt__OrganizationId__c=AccList[0].id ,PointOfSaleId__c=1.0, AssociatedWarehouseDefault__c='Default');
      insert StoreLocations;
      StoreLocations.Channel_Type_3__c = 'Agentes';
      StoreLocations.Channel_Type_2__c = 'Agentes';
      StoreLocations.Channel_Type__c = 'Agentes';
      update StoreLocations;
      FinancialPromotions__c Promo1 = new FinancialPromotions__c(Name='Promo1',Creditcard_Type__c='403', Bank_Code__c='1', Instalments__c='1', CFT__c='test');
      insert Promo1;
      TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
      List<Order>OrdList = TestDataFactory.createOrders(2,AccList[0]);
      OrdList[0].PaymentMethodType__c ='1001';
      OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
      OrdList[0].OriginStoreLocation__c = StoreLocations.id;
      OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
      OrdList[1].OriginStoreLocation__c = StoreLocations.id;
      update OrdList;
      List<OrderItem>OIList =TestDataFactory.createOrderItem(2,OrdList[0]);
      List<OrderItem>OIList1 =TestDataFactory.createOrderItem(2,OrdList[1]);
      //generateMockupData();
      Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IFS121NoLineMockHttpResponseGeneretor());
        taOrderBillingUpdateProcess.BillUpdateOrder(OrdList[0].Id);
      Test.stopTest();
      }
      static testMethod void Test3()
      {
        List<Order> lstOrder = new List<Order>();
        List<Account> AccList = TestDataFactory.createAccounts(1, 'Consumer');
        vlocity_cmt__BusinessSite__c StoreLocations = new vlocity_cmt__BusinessSite__c(vlocity_cmt__OrganizationId__c=AccList[0].id ,PointOfSaleId__c=1.0, AssociatedWarehouseDefault__c='Default');
        insert StoreLocations;
        StoreLocations.Channel_Type_3__c = 'Agentes';
        StoreLocations.Channel_Type_2__c = 'Agentes';
        StoreLocations.Channel_Type__c = 'Agentes';
        update StoreLocations;
        FinancialPromotions__c Promo1 = new FinancialPromotions__c(Name='Promo1',Creditcard_Type__c='403', Bank_Code__c='1', Instalments__c='1', CFT__c='test');
        insert Promo1;
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        List<Order>OrdList = TestDataFactory.createOrders(2,AccList[0]);
        OrdList[0].PaymentMethodType__c ='1001';
        OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
        OrdList[0].OriginStoreLocation__c = StoreLocations.id;
        OrdList[0].Delivery_Method__c = 'Store Pick Up';
        OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
        OrdList[1].OriginStoreLocation__c = StoreLocations.id;
        OrdList[1].Delivery_Method__c = 'Store Pick Up';
        update OrdList;
        List<OrderItem>OIList =TestDataFactory.createOrderItem(2,OrdList[0]);
        List<OrderItem>OIList1 =TestDataFactory.createOrderItem(2,OrdList[1]);
        //generateMockupData();
        Test.startTest();
          Test.setMock(HttpCalloutMock.class, new IFS121NoLineMockHttpResponseGeneretor());
          taOrderBillingUpdateProcess.BillUpdateOrder(OrdList[0].Id);
        Test.stopTest();
      }
}