objects/GP_Condicional_logico__c.object
<CustomObject>
    <description>Condicional de regla - Gestor de Puntos</description>
    <fields>
        <fullName>Regla__c</fullName>
        <label>Regla</label>
        <referenceTo>GP_Regla__c</referenceTo>
        <relationshipLabel>Condicionales logicos</relationshipLabel>
        <relationshipName>Condicionales_logicos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SeComparaContraElValorFijo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SeComparaContraElValorFijo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variable_a_comparar__c</fullName>
        <label>Variable a comparar</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Categoria De Socio</fullName>
                </value>
                <value>
                    <fullName>Tipo De Cliente</fullName>
                </value>
                <value>
                    <fullName>Tipo De Servicio</fullName>
                </value>
                <value>
                    <fullName>Tipo De Upselling</fullName>
                </value>
                <value>
                    <fullName>Equipo Categoria</fullName>
                </value>
                <value>
                    <fullName>Monto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GP Condicional logico</label>
    <nameField>
        <label>Condicional logico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condicionales logicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Regla__c.object
<CustomObject>
    <description>Reglas p/sumar o restar puntos - Gestor de Puntos</description>
    <fields>
        <fullName>Dias_vencimiento__c</fullName>
        <label>Dias para vencimiento</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fecha_vencimiento__c</fullName>
        <label>Fecha de vencimiento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SeComparaContraElValorFijo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SeComparaContraElValorFijo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Confiabilización</fullName>
                </value>
                <value>
                    <fullName>Premio Recarga 3M</fullName>
                </value>
                <value>
                    <fullName>Castigo Recarga</fullName>
                </value>
                <value>
                    <fullName>Recarga por Monto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cater</fullName>
                </value>
                <value>
                    <fullName>Antigüedad</fullName>
                </value>
                <value>
                    <fullName>Alta a FOL</fullName>
                </value>
                <value>
                    <fullName>Continuidad FOL</fullName>
                </value>
                <value>
                    <fullName>Alta a Débito Automatico</fullName>
                </value>
                <value>
                    <fullName>Descarga APP</fullName>
                </value>
                <value>
                    <fullName>Alta Nuevo Servicio Core</fullName>
                </value>
                <value>
                    <fullName>Referidos</fullName>
                </value>
                <value>
                    <fullName>Convergente Fiber</fullName>
                </value>
                <value>
                    <fullName>Convergente Arnet</fullName>
                </value>
                <value>
                    <fullName>Baja</fullName>
                </value>
                <value>
                    <fullName>Transferencia</fullName>
                </value>
                <value>
                    <fullName>Canje</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vencimiento_fecha_fija__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True : Vence en una fecha determinada.
False : Vence luego de la cantidad de días que se especifique.</description>
        <label>Vencimiento en fecha fija</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vigencia_desde__c</fullName>
        <label>Vigencia desde</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vigencia_hasta__c</fullName>
        <label>Vigencia hasta</label>
        <type>Date</type>
    </fields>
    <label>GP Regla</label>
    <nameField>
        <label>Nombre de Regla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Reglas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GP_Condicionales_ControllerTest.cls
@isTest
public with sharing class GP_Condicionales_ControllerTest {
        
    public static testMethod void testCtrlVariable() {
        GP_Regla__c regla = new GP_Regla__c();
        regla.Vigencia_desde__c = Date.Today() - 7;
        regla.Vigencia_hasta__c = Date.Today() + 365;
        regla.Dias_vencimiento__c = 10;
        regla.Fecha_vencimiento__c = Date.Today() + 60;
        regla.Tipo_de_evento__c = 'Recarga por Monto';
        insert regla;

        GP_Condicional_logico__c cond = new GP_Condicional_logico__c();
        cond.Regla__c = regla.Id;
        cond.Variable_a_comparar__c = 'Monto';
        insert cond;

        PageReference pageRef = Page.GP_Upsert_Reglas;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',regla.Id);
    
        GP_Condicionales_Controller controller = new GP_Condicionales_Controller();

        //Pruebo getCondicional() con Id de condicion creada
        controller.IdCond = cond.Id;
        controller.getCondicional();
        //Pruebo saveCondicional() cambiando la variable a comparar
        controller.selectedVar = 'Tipo De Servicio';
        controller.saveCondicional();
        //Pruebo insertarCondicion() con una nueva cond
        controller.GP_Condicional_logico = new GP_Condicional_logico__c();
        controller.GP_Condicional_logico.Regla__c = regla.Id;
        controller.GP_Condicional_logico.Variable_a_comparar__c = 'Monto';
        controller.insertarCondicion();
        //Pruebo eliminar
        controller.deleteCond();
        //Pruebo doNothing(), usado para crear actionFunctions y poder reRenderizar componentes de la VF
        controller.doNothing();

        controller.saveAndReturnToList();
    }

    public static testMethod void testCtrlFijo() {
        GP_Regla__c regla = new GP_Regla__c();
        regla.Vigencia_desde__c = Date.Today() - 7;
        regla.Vigencia_hasta__c = Date.Today() + 365;
        regla.Dias_vencimiento__c = 10;
        regla.Fecha_vencimiento__c = Date.Today() + 60;
        regla.Tipo_de_evento__c = 'Upselling';
        //Para pasar por todos los casos del metodo principal
        regla.SeComparaContraElValorFijo__c = true;
        regla.Vencimiento_fecha_fija__c = true;
        insert regla;

        PageReference pageRef = Page.GP_Upsert_Reglas;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id',regla.Id);
        System.debug('Parametro ID: ' + ApexPages.currentPage().getParameters().get('id'));
    
        GP_Condicionales_Controller controller = new GP_Condicionales_Controller();
    }

    public static testMethod void testCtrlNuevaRegla() {
        PageReference pageRef = Page.GP_Upsert_Reglas;
        Test.setCurrentPage(pageRef);
        //ApexPages.currentPage().getParameters().put('id',regla.Id);
        System.debug('Parametro ID: ' + ApexPages.currentPage().getParameters().get('id'));
    
        GP_Condicionales_Controller controller = new GP_Condicionales_Controller();

        //Pruebo insertar una condicion en una regla nueva
        controller.GP_Condicional_logico = new GP_Condicional_logico__c();
        controller.GP_Condicional_logico.Variable_a_comparar__c = 'Monto';
        controller.insertarCondicion();
    }
}