objects/GP_Condicional_logico__c.object
<CustomObject>
    <description>Condicional de regla - Gestor de Puntos</description>
    <fields>
        <fullName>Operador__c</fullName>
        <label>Operador</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Variable_a_comparar__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>=</fullName>
                </value>
                <value>
                    <fullName>!=</fullName>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>&gt;=</fullName>
                </value>
                <value>
                    <fullName>&lt;=</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Regla__c</fullName>
        <label>Regla</label>
        <referenceTo>GP_Regla__c</referenceTo>
        <relationshipLabel>Condicionales logicos</relationshipLabel>
        <relationshipName>Condicionales_logicos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SeComparaContraElValorFijo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SeComparaContraElValorFijo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valor_contra_el_que_se_compara__c</fullName>
        <label>Valor contra el que se compara</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Variable_a_comparar__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>TRIAL</fullName>
                </value>
                <value>
                    <fullName>BLACK</fullName>
                </value>
                <value>
                    <fullName>CLASSIC</fullName>
                </value>
                <value>
                    <fullName>DNI</fullName>
                </value>
                <value>
                    <fullName>SOHO</fullName>
                </value>
                <value>
                    <fullName>EMPRESAS</fullName>
                </value>
                <value>
                    <fullName>GGCC</fullName>
                </value>
                <value>
                    <fullName>MOVIL-PREPAGO</fullName>
                </value>
                <value>
                    <fullName>MOVIL-ABONO</fullName>
                </value>
                <value>
                    <fullName>ARNET</fullName>
                </value>
                <value>
                    <fullName>TV</fullName>
                </value>
                <value>
                    <fullName>PREPAGO-A-ABONO FIJO</fullName>
                </value>
                <value>
                    <fullName>ABONO FIJO-A-FACTURA</fullName>
                </value>
                <value>
                    <fullName>INTERNET-MAS-VELOCIDAD</fullName>
                </value>
                <value>
                    <fullName>CABLE-SUMAR FLOW</fullName>
                </value>
                <value>
                    <fullName>LOW</fullName>
                </value>
                <value>
                    <fullName>MID</fullName>
                </value>
                <value>
                    <fullName>MID HIGH</fullName>
                </value>
                <value>
                    <fullName>PREMIUM</fullName>
                </value>
                <value>
                    <fullName>integer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GP Condicional logico</label>
    <nameField>
        <label>Condicional logico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condicionales logicos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Historia_transaccion__c.object
<CustomObject>
    <description>Historial de transacciones de Socio - Gestor de Puntos</description>
    <fields>
        <fullName>Numero_de_orden__c</fullName>
        <label>Numero de orden</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Puntos__c</fullName>
        <label>Puntos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socio</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipLabel>GP Historia transacciones</relationshipLabel>
        <relationshipName>GP_Historia_transacciones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suma_o_resta__c</fullName>
        <label>Suma o resta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suma</fullName>
                </value>
                <value>
                    <fullName>Resta</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Confiabilización</fullName>
                </value>
                <value>
                    <fullName>Premio Recarga 3M</fullName>
                </value>
                <value>
                    <fullName>Castigo Recarga</fullName>
                </value>
                <value>
                    <fullName>Recarga por Monto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cater</fullName>
                </value>
                <value>
                    <fullName>Antigüedad</fullName>
                </value>
                <value>
                    <fullName>Alta a FOL</fullName>
                </value>
                <value>
                    <fullName>Continuidad FOL</fullName>
                </value>
                <value>
                    <fullName>Alta a Débito Automatico</fullName>
                </value>
                <value>
                    <fullName>Descarga APP</fullName>
                </value>
                <value>
                    <fullName>Alta Nuevo Servicio Core</fullName>
                </value>
                <value>
                    <fullName>Referidos</fullName>
                </value>
                <value>
                    <fullName>Convergente Fiber</fullName>
                </value>
                <value>
                    <fullName>Convergente Arnet</fullName>
                </value>
                <value>
                    <fullName>Baja</fullName>
                </value>
                <value>
                    <fullName>Transferencia</fullName>
                </value>
                <value>
                    <fullName>Canje</fullName>
                </value>
                <value>
                    <fullName>Migracion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vencimiento__c</fullName>
        <label>Vencimiento</label>
        <type>Date</type>
    </fields>
    <label>GP Historia transaccion</label>
    <nameField>
        <label>Historia transaccion</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Historia transacciones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GP_Regla__c.object
<CustomObject>
    <description>Reglas p/sumar o restar puntos - Gestor de Puntos</description>
    <fields>
        <fullName>Fecha_vencimiento__c</fullName>
        <label>Fecha de vencimiento</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SeComparaContraElValorFijo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SeComparaContraElValorFijo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Confiabilización</fullName>
                </value>
                <value>
                    <fullName>Premio Recarga 3M</fullName>
                </value>
                <value>
                    <fullName>Castigo Recarga</fullName>
                </value>
                <value>
                    <fullName>Recarga por Monto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cater</fullName>
                </value>
                <value>
                    <fullName>Antigüedad</fullName>
                </value>
                <value>
                    <fullName>Alta a FOL</fullName>
                </value>
                <value>
                    <fullName>Continuidad FOL</fullName>
                </value>
                <value>
                    <fullName>Alta a Débito Automatico</fullName>
                </value>
                <value>
                    <fullName>Descarga APP</fullName>
                </value>
                <value>
                    <fullName>Alta Nuevo Servicio Core</fullName>
                </value>
                <value>
                    <fullName>Referidos</fullName>
                </value>
                <value>
                    <fullName>Convergente Fiber</fullName>
                </value>
                <value>
                    <fullName>Convergente Arnet</fullName>
                </value>
                <value>
                    <fullName>Baja</fullName>
                </value>
                <value>
                    <fullName>Transferencia</fullName>
                </value>
                <value>
                    <fullName>Canje</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valor_resultado_fijo__c</fullName>
        <label>Valor resultado fijo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vencimiento_fecha_fija__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True : Vence en una fecha determinada.
False : Vence luego de la cantidad de días que se especifique.</description>
        <label>Vencimiento en fecha fija</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vigencia_desde__c</fullName>
        <label>Vigencia desde</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vigencia_hasta__c</fullName>
        <label>Vigencia hasta</label>
        <type>Date</type>
    </fields>
    <label>GP Regla</label>
    <nameField>
        <label>Nombre de Regla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Reglas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/GP_Saldo_por_vencimiento__c.object
<CustomObject>
    <description>Saldos de puntos según vencimiento - Gestor de Puntos</description>
    <fields>
        <fullName>Cuenta__c</fullName>
        <formula>Socio__r.Cuenta__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cuenta</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Puntos__c</fullName>
        <label>Puntos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socio__c</fullName>
        <label>Socio</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipLabel>GP Saldos por vencimiento</relationshipLabel>
        <relationshipName>GP_Saldos_por_vencimiento</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vencimiento__c</fullName>
        <label>Vencimiento</label>
        <type>Date</type>
    </fields>
    <label>GP Saldo por vencimiento</label>
    <nameField>
        <label>Saldo por vencimiento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Saldos por vencimiento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Socio__c.object
<CustomObject>
    <description>Socio Club Personal - Gestor de Puntos</description>
    <fields>
        <fullName>Activo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Permiso__c</fullName>
        <label>Permiso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valor1</fullName>
                </value>
                <value>
                    <fullName>Valor2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Saldo_total__c</fullName>
        <label>Saldo total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tipo_de_socio__c</fullName>
        <label>Tipo de socio</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>GP Acumulador</label>
    <nameField>
        <label>Nombre de Socio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Acumuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GP_APITest.cls
@isTest
public with sharing class GP_APITest {
    
    /*
    Test
    static testMethod void adherirUnSocioBulk() {

        Account cuenta = new Account();
        cuenta.name = 'unaCuenta';

        insert cuenta;

        GP_socioAAdherir socioAAdherir = new GP_socioAAdherir(cuenta.id, 'black', 'Low');

        List<GP_socioAAdherir> sociosAAdherir = new List<GP_socioAAdherir>();
        sociosAAdherir.add(socioAAdherir);

        String resultado = GP_Api.adherirSocio(sociosAAdherir);

        system.assertEquals(1, [select id from GP_Socio__c where activo__c = true].size());
    }

    static testMethod void adherirUnSocioQueYaExistiaAnteriorMente() {
        Account cuenta = new Account();
        cuenta.name = 'unaCuenta';

        insert cuenta;

        GP_Socio__c socio = new GP_Socio__c();
        socio.Activo__c = false;
        socio.Cuenta__c = cuenta.id;

        insert socio;

        GP_socioAAdherir socioAAdherir = new GP_socioAAdherir(cuenta.id, 'black', 'Low');

        List<GP_socioAAdherir> sociosAAdherir = new List<GP_socioAAdherir>();
        sociosAAdherir.add(socioAAdherir);

        String resultado = GP_Api.adherirSocio(sociosAAdherir);

        system.assertEquals(1, [select id from GP_Socio__c where activo__c = true].size());
    }

    static testMethod void consultarUnaTransaccion(){

        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;

        GP_Historia_transaccion__c transaccion = new GP_Historia_transaccion__c();
        transaccion.Socio__c = socio.id;
        insert transaccion;

        System.assertEquals(1, Gp_api.consultarTransacciones(socio.id, Date.today().addDays(-1), Date.today().addDays(+1)).size());

    }

    static testMethod void consultarEstadoSocio(){
        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;

        system.assertEquals(socio.id, Gp_api.consultarEstadoSocio(socio.id).id);
    }

    static testMethod void eliminarSocio(){
        
        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;

        GP_Saldo_por_vencimiento__c saldo = new GP_Saldo_por_vencimiento__c();
        saldo.Socio__c = socio.id;
        saldo.puntos__c = 10;
        insert saldo;

        List<String> listaDeIds = new List<String>();
        listaDeIds.add(socio.id);

        gp_api.eliminarSocios(listaDeIds);

        System.assertEquals(1, [select id, activo__c from gp_socio__c].size());
        System.assertEquals(false, [select id, activo__c from gp_socio__c].activo__c);
        System.assertEquals(1, [select id from GP_Historia_transaccion__c].size());        
    }

    static testMethod void transferirPuntos(){

        GP_Socio__c socio = new GP_Socio__c();
        socio.saldo_total__c = 10;
        socio.activo__c = true;
        insert socio;

        GP_Saldo_por_vencimiento__c saldo = new GP_Saldo_por_vencimiento__c();
        saldo.Socio__c = socio.id;
        saldo.puntos__c = 10;
        saldo.vencimiento__c = Date.today().addDays(2);   
        insert saldo;

        GP_Socio__c socio2 = new GP_Socio__c();
        socio2.activo__c = true;
        insert socio2;

        gp_api.transferirPuntos(socio.id, socio2.id, 9);

        System.assertEquals(1,[select id, puntos__c from GP_Saldo_por_vencimiento__c where socio__c =: socio.id].puntos__c);  
        System.assertEquals(9,[select id, puntos__c from GP_Saldo_por_vencimiento__c where socio__c =: socio2.id].puntos__c);
        System.assertEquals(1, [select id, saldo_total__c from GP_Socio__c where id =: socio.id].saldo_total__c);
        System.assertEquals(9, [select id, saldo_total__c from GP_Socio__c where id =: socio2.id].saldo_total__c);

    }

    static testMethod void seGeneranVariasTransaccionesDeAltaSiSeConsumenVariosPuntosDeDistintasFechas(){
        GP_Socio__c socio = new GP_Socio__c();
        socio.saldo_total__c = 15;
        socio.activo__c = true;
        insert socio;

        GP_Saldo_por_vencimiento__c saldo = new GP_Saldo_por_vencimiento__c();
        saldo.Socio__c = socio.id;
        saldo.puntos__c = 10;
        saldo.vencimiento__c = Date.today().addDays(2);   
        insert saldo;

        GP_Saldo_por_vencimiento__c saldo2 = new GP_Saldo_por_vencimiento__c();
        saldo2.Socio__c = socio.id;
        saldo2.puntos__c = 5;
        saldo2.vencimiento__c = Date.today().addDays(3);   
        insert saldo2;

        GP_Socio__c socio2 = new GP_Socio__c();
        socio2.activo__c = true;
        socio2.saldo_total__c = 0;
        insert socio2;

        gp_api.transferirPuntos(socio.id, socio2.id, 11);

        system.debug([select id, puntos__c from GP_Historia_transaccion__c where socio__c =: socio2.id]);
        system.debug([select id, puntos__c from GP_Historia_transaccion__c where socio__c =: socio.id]);

        System.assertEquals(2,[select id, puntos__c from GP_Historia_transaccion__c where socio__c =: socio2.id].size());  
        System.assertEquals(4, [select id, saldo_total__c from GP_Socio__c where id =: socio.id].saldo_total__c);
        System.assertEquals(11, [select id, saldo_total__c from GP_Socio__c where id =: socio2.id].saldo_total__c); 
    }


    static testMethod void anularCanje(){
        
        GP_Socio__c socio = new GP_Socio__c();
        socio.saldo_total__c = 10;
        socio.activo__c = true;
        insert socio;

        GP_Historia_transaccion__c transaccion = new GP_Historia_transaccion__c();
        transaccion.socio__c = socio.id;
        transaccion.numero_de_orden__c = 1;
        transaccion.puntos__c = 12;
        transaccion.vencimiento__c = Date.today().addDays(2);
        transaccion.Suma_o_resta__c = 'Resta';

        insert transaccion;

        gp_api.anularCanje(socio.id, 1);

        system.assertEquals(22, [select id, saldo_total__c from gp_socio__c ].saldo_total__c);
        system.assertEquals(12, [select id, puntos__c, vencimiento__c from GP_Saldo_por_vencimiento__c].puntos__c);
        system.assertEquals(Date.today().addDays(2), [select id, puntos__c, vencimiento__c from GP_Saldo_por_vencimiento__c].vencimiento__c);
    }

    //Realizar 
    static testMethod void siElCanjeGeneroVariasTransaccionesDeRestaAnulaTodasLasTransaccionesDeRestaYPorCadaUnaGeneraUnaDeAlta(){}

    static testMethod void modificarPermisoSocio(){
        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;

        gp_api.ModificarPermisoSocio(socio.id, 'Low');

        system.assertEquals('Low', [select id, permiso__c from gp_socio__c].permiso__c);
    }

    static testMethod void modificarTipoDeSocio(){
        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;

        gp_api.ModificarTipoDeSocio(socio.id, 'Black');

        system.assertEquals('Black', [select id, Tipo_de_socio__c from gp_socio__c].Tipo_de_socio__c);
    }

    static testMethod void sumarRestarPuntos(){
        
        GP_Socio__c socio = new GP_Socio__c();
        socio.activo__c = true;
        insert socio;


        List<GP_AtributoValorDeUnEvento> atributos = new List<GP_AtributoValorDeUnEvento>();
        atributos.add(new GP_AtributoValorDeUnEvento('Tipo De Cliente', 'String', 'DNI'));

        List<GP_sumarRestarPuntosItem> items = new List<GP_sumarRestarPuntosItem>();
        items.add(new GP_sumarRestarPuntosItem(socio.id, 'Bienvenida', 1, atributos));

        GP_Regla__c regla = new GP_Regla__c();
        regla.Fecha_vencimiento__c = Date.today().addDays(2);
        regla.Tipo_de_evento__c = 'Bienvenida';
        regla.Valor_resultado_fijo__c = 10;
        regla.Vigencia_desde__c = Date.today().addDays(-1);
        regla.Vigencia_hasta__c = Date.today().addDays(2);
        regla.vencimiento_fecha_fija__c = true;
        regla.SeComparaContraElValorFijo__c = true;

        insert regla;

        GP_Condicional_logico__c condicional = new GP_Condicional_logico__c();
        condicional.Operador__c = '=';
        condicional.Regla__c = regla.id;
        condicional.Valor_contra_el_que_se_compara__c = 'DNI';
        condicional.Variable_a_comparar__c = 'Tipo De Cliente';
        condicional.Variable_contra_la_que_se_compara__c = 'Tipo De Cliente';

        insert condicional;

        gp_api.sumarRestarPuntos(items);

        System.assertEquals(10,[select id, puntos__c from GP_Saldo_por_vencimiento__c where socio__c =: socio.id].puntos__c);
        System.assertEquals(10, [select id, saldo_total__c from GP_Socio__c where id =: socio.id].saldo_total__c);
        System.assertEquals(1, [select id from GP_Historia_transaccion__c].size());
        System.assertEquals(regla.id,[select id, Generado_por__c from GP_Historia_transaccion__c where socio__c =: socio.id].Generado_por__c);  
        
    }*/


}