objects/GP_Lista_de_Asset__c.object
<CustomObject>
    <description>Assets del Socio - Gestor de Puntos</description>
    <fields>
        <fullName>MSISDN__c</fullName>
        <formula>Asset__r.MSISDN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MSISDN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Socio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Socio</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipLabel>GP Lista de Assets</relationshipLabel>
        <relationshipName>GP_Lista_de_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>suscriber_id__c</fullName>
        <formula>Asset__r.Subscription_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>suscriber id</label>
        <type>Text</type>
    </fields>
    <label>GP Lista de Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Lista de Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/GP_Socio__c.object
<CustomObject>
    <description>Socio Club Personal - Gestor de Puntos</description>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Saldo_total__c</fullName>
        <label>Saldo total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Socio_padre__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Acumulador Padre</label>
        <referenceTo>GP_Socio__c</referenceTo>
        <relationshipName>GP_Socios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GP Acumulador</label>
    <nameField>
        <label>Nombre de Socio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Acumuladores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IFS_S461.cls
@RestResource(urlMapping='/v1/integrationprocedure/getLoyaltyPoints/*')
global with sharing class IFS_S461 {
    
    @HttpPost
    global static Response getLoyaltyPoints(Request getLoyaltyPoints) {
        
        List<GP_Lista_de_Asset__c> listaDeAssets = new List<GP_Lista_de_Asset__c>();
        if(!String.isBlank(getLoyaltyPoints.choiceId.subscriberId)){
             
             listaDeAssets = [select id, Socio__r.cuenta__c, Socio__r.Socio_padre__c, Socio__r.Socio_padre__r.cuenta__c,
                              Socio__r.Socio_padre__r.Saldo_total__c, socio__r.Saldo_total__c 
                              from GP_Lista_de_Asset__c 
                              where suscriber_id__c =: getLoyaltyPoints.choiceId.subscriberId limit 1];
        }else{
            if(!String.isBlank(getLoyaltyPoints.choiceId.numeroLinea)){
                
                 listaDeAssets = [select id, Socio__r.cuenta__c, Socio__r.Socio_padre__c, Socio__r.Socio_padre__r.cuenta__c,
                                  Socio__r.Socio_padre__r.Saldo_total__c, socio__r.Saldo_total__c 
                                  from GP_Lista_de_Asset__c 
                                  where MSISDN__c =: getLoyaltyPoints.choiceId.numeroLinea limit 1];
            }
        }
        
         Response respuesta = new Response();
         if(listaDeAssets.size()>0){
             if(listaDeAssets[0].socio__r.socio_padre__c == null){
                 respuesta.pointsBalance = String.valueOf(listaDeAssets[0].socio__r.Saldo_total__c);
             }else{
                respuesta.pointsBalance = String.valueOf((Double) gp_api.consultarPuntos(listaDeAssets[0].Socio__r.Socio_padre__r.cuenta__c,listaDeAssets[0].socio__r.cuenta__c).get('totalPuntosDisponibles'));
             }
         }
         
         return respuesta; 
    }

    global class Request {
        global choice choiceId {get;set;}

    }
    
    global class choice {
        global String subscriberId {get;set;}
        global String numeroLinea {get;set;}
    }
    
    global class Response {
        global String pointsBalance { get; set; }
        
    }
    
}