objects/GP_Regla__c.object
<CustomObject>
    <description>Reglas p/sumar o restar puntos - Gestor de Puntos</description>
    <fields>
        <fullName>Activa__c</fullName>
        <description>La regla estará Activa si la fecha actual esta entre Vigencia desde y Vigencia Hasta.</description>
        <formula>AND(TODAY() &gt; Vigencia_desde__c, TODAY() &lt; Vigencia_hasta__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Activa</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Descripcion_regla__c</fullName>
        <label>Descripcion regla</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Metodo_a_ejecutar__c</fullName>
        <label>Metodo a ejecutar</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SeComparaContraElValorFijo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SeComparaContraElValorFijo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tipo_de_evento__c</fullName>
        <label>Tipo de evento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bienvenida</fullName>
                </value>
                <value>
                    <fullName>Confiabilización</fullName>
                </value>
                <value>
                    <fullName>Premio Recarga 3M</fullName>
                </value>
                <value>
                    <fullName>Castigo Recarga</fullName>
                </value>
                <value>
                    <fullName>Recarga por Monto</fullName>
                </value>
                <value>
                    <fullName>Upselling</fullName>
                </value>
                <value>
                    <fullName>Cater</fullName>
                </value>
                <value>
                    <fullName>Antigüedad</fullName>
                </value>
                <value>
                    <fullName>Alta a FOL</fullName>
                </value>
                <value>
                    <fullName>Continuidad FOL</fullName>
                </value>
                <value>
                    <fullName>Alta a Débito Automatico</fullName>
                </value>
                <value>
                    <fullName>Descarga APP</fullName>
                </value>
                <value>
                    <fullName>Alta Nuevo Servicio Core</fullName>
                </value>
                <value>
                    <fullName>Referidos</fullName>
                </value>
                <value>
                    <fullName>Convergente Fiber</fullName>
                </value>
                <value>
                    <fullName>Convergente Arnet</fullName>
                </value>
                <value>
                    <fullName>Baja</fullName>
                </value>
                <value>
                    <fullName>Transferencia</fullName>
                </value>
                <value>
                    <fullName>Canje</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valor_resultado_fijo__c</fullName>
        <label>Valor resultado fijo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valor_resultado_variable__c</fullName>
        <label>Valor calculo variable</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>GP Regla</label>
    <nameField>
        <label>Nombre de Regla</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GP Reglas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GP_Reglas_ListController.cls
public class GP_Reglas_ListController{
    public List<GP_Regla__c> listaReglas{get;set;}
    private ApexPages.StandardController controller;
    public Id IdRegla{get;set;}

    public GP_Reglas_ListController(ApexPages.StandardController stdController){
        getReglas();
    }

    public void borrarRegla() {
        GP_Regla__c regla = [SELECT Id FROM GP_Regla__c WHERE Id = :IdRegla];
        delete regla;
        getReglas();
    }

    public void getReglas() {
        listaReglas = new List<GP_Regla__c>();
        listaReglas = [SELECT   Descripcion_regla__c,Id, Activa__c, Metodo_a_ejecutar__c,Name,Tipo_de_evento__c,Valor_resultado_fijo__c,Valor_resultado_variable__c,SeComparaContraElValorFijo__c 
                       FROM GP_Regla__c];
    }

}