objects/IntegrationLog__c.object
<CustomObject>
    <description>Save a log containing the request or response of each integration procedure call to an external system.</description>
    <fields>
        <fullName>Adittional_Info__c</fullName>
        <label>Additional Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Indicative__c</fullName>
        <label>Indicative</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Paramts__c</fullName>
        <label>Paramts</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction-ID</label>
        <length>24</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IFS_LogRecord.cls
global with sharing class  IFS_LogRecord
{
    /**
     * Objetivo: Recibe los datos necesarios para crear un registro en el objeto custom Log
     * Parametros: 
     * String timestamp: string con formato 'yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'
     * String tipoLog: indica el tipo de log que se registra, para los servicios es 'SERVICIO'
     * String origen: indica quien genera el Log, para los servicios se informa el código del servicio. Ej 'S125'
     * String idUnico: contiene el identificador único de transacción
     * String reqResp: 'REQ'indica que es un registro de un request. 'RES' indica que es un registro de un response
     * String params: Si se ha informado atributos en params del request se informa aquí
     * String infoAdicional: cuando se registra un request va vacío. Si es un response se coloca el código de estado, la
     * descripción del estado separados por ';'. Si el servicio ha obtenido un response no se registra nada más, si no se ha obtenido
     * un response se agrega, también separado por  el separador anteriormente indiado, 'request to DPW  FAIL ; request body = ' + el body del request
     */
    public Static void record(String timestamp, String tipoLog, String origen,String reqRes, String idUnico, String params, String infoAdicional)
    { 
        System.debug('------------- Auto number seID : ' + 0);
        System.debug('--------------timesamp         : ' + timestamp);
        System.debug('--------------tipoLog          : ' + tipoLog);
        System.debug('--------------origen           : ' + origen );
        System.debug('--------------idUnico          : ' + idUnico );
        System.debug('--------------reqRes           : ' + reqRes );
        System.debug('--------------params           : ' + params );
        System.debug('--------------infoAdicional    : ' + infoAdicional ); 

        IntegrationLog__c logRec = new IntegrationLog__c();
        logRec.Adittional_Info__c = infoAdicional;
        logRec.Indicative__c = reqRes;
        logRec.Log_Type__c = tipoLog;
        logRec.Origin__c = origen;
        logRec.Paramts__c = params;
        logRec.Timestamp__c = timestamp; 
        logRec.Transaction_ID__c = idUnico;

        //Savepoint sp = Database.setSavepoint();  
         System.debug('--------------Antes de insert ' );
        try{
            insert logRec;
        } catch (Exception e) {
            throw(e);    
        }
        System.debug('--------------AL FINAL ' );
    }
    
}