objects/KB_Article__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Único tipo de artículo para cargar todo tipo de contenido.</description>
    <fields>
        <fullName>KB_ArticleType__c</fullName>
        <label>Tipo de Artículo</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contenido Libre</fullName>
                    <default>true</default>
                    <label>Contenido Libre</label>
                </value>
                <value>
                    <fullName>Pregunta y Respuesta</fullName>
                </value>
                <value>
                    <fullName>Paso a Paso</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Adjunto</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>KB_AssignedCategory__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo &quot;read only&quot; utilizado para las validaciones en la publicación de artículos.</description>
        <label>Assigned Category</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KB_Body__c</fullName>
        <label>Contenido HTML</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Contenido</label>
    <pluralLabel>Contenidos</pluralLabel>
</CustomObject>

classes/KB_Article_validateCategories.cls
public class KB_Article_validateCategories {
    
    @InvocableMethod(label='KB_validateCategories' description='Validate categories to publish articles.')
    public static void validateUpdateCategories(List<String> kbArticleId ){ 
        System.debug('validateUpdateCategories ArticleId: ' +kbArticleId); 
        if(!kbArticleId.isEmpty()){       
            String artId=kbArticleId.get(0);
            List <KB_Article__kav> articlesList= [Select Id, PublishStatus, KB_AssignedCategory__c, KnowledgeArticleId, KB_ArticleType__c, KB_Body__c  from KB_Article__kav where UrlName =: artId and PublishStatus ='Draft'];
            
            for(KB_Article__kav article: articlesList){
                List <KB_Article__DataCategorySelection> dataCategoriList =[Select DataCategoryName from KB_Article__DataCategorySelection where ParentId =: article.Id];            
                System.debug('dataCategoriList: ' +dataCategoriList);
                //if(article.PublishStatus.equalsIgnoreCase('Draft')){
                    article.KB_AssignedCategory__c =(dataCategoriList.size()>=1);
                //  article.KB_RunValidations__c=false;
               // }
                if(String.isEmpty(article.KB_Body__c)){
                    if(!String.isEmpty(article.KB_ArticleType__c)){
                        String articleType;
                        if(article.KB_ArticleType__c.equalsIgnoreCase('Contenido Libre')){
                            articleType='KB_Contenido_libre_template';
                        }
                        else if(article.KB_ArticleType__c.equalsIgnoreCase('Paso a Paso')){
                            articleType='KB_Paso_a_paso_template';
                        }
                        else if(article.KB_ArticleType__c.equalsIgnoreCase('Pregunta y Respuesta')){
                            articleType='KB_Preguntas_y_respuestas_template';
                        }
                        else if(article.KB_ArticleType__c.equalsIgnoreCase('Video')){
                            articleType='KB_Video_template';
                        }
                        else if(article.KB_ArticleType__c.equalsIgnoreCase('Adjunto')){
                            articleType='KB_Adjunto_template';
                        }

                        for(StaticResource staticR:[select id, name, Body from StaticResource where name =:articleType]){
                            System.debug('staticR.Body: ' +staticR.Body.toString());
                            article.KB_Body__c=staticR.Body.toString();
                        }
                    }   
                }
            }
            update articlesList;
        }
    }
}