objects/Location__c.object
<CustomObject>
    <description>Locations</description>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Status</description>
        <label>Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location</description>
        <inlineHelpText>Location</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Store_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PointOfSaleAddressNumber__c</fullName>
        <description>Point Of Sale Address Number</description>
        <inlineHelpText>Point Of Sale Address Number</inlineHelpText>
        <label>Address Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointOfSaleChannel__c</fullName>
        <description>Point Of Sale Channel</description>
        <inlineHelpText>Point Of Sale Channel</inlineHelpText>
        <label>Point Of Sale Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Presencial - Oficinas comerciales</fullName>
                </value>
                <value>
                    <fullName>Presencial - Agentes</fullName>
                </value>
                <value>
                    <fullName>Ecommerce</fullName>
                </value>
                <value>
                    <fullName>Telefónico</fullName>
                </value>
                <value>
                    <fullName>Televentas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos Pymes</fullName>
                </value>
                <value>
                    <fullName>Grandes Clientes</fullName>
                </value>
                <value>
                    <fullName>Gobierno y Empresas</fullName>
                </value>
                <value>
                    <fullName>VIP</fullName>
                </value>
                <value>
                    <fullName>Telefónico PyMEs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PointOfSaleStorePickupEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Point Of Sale Store Pickup Enabled</description>
        <inlineHelpText>Point Of Sale Store Pickup Enabled</inlineHelpText>
        <label>Point Of Sale Store Pickup Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PostOfficeCode__c</fullName>
        <description>Post Office Code</description>
        <inlineHelpText>Codigo o Numero de Sucursal</inlineHelpText>
        <label>Post Office Code</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to indicate the status of the point of sales or agency.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dado de baja</fullName>
                </value>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Pendiente activación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__StreetAddress__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/taSalesSearchBusinessSites.cls
global with sharing class taSalesSearchBusinessSites implements vlocity_cmt.VlocityOpenInterface{
    
    public Boolean invokeMethod(String methodName, Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options){
        
        if(methodName.equals('getBusinessSitesByCity')){
            getBusinessSitesByCity(outMap);
        }
        
        if(methodName.equals('getStorePickUpBusinessSitesByCity')){
            getStorePickUpBusinessSitesByCity(outMap);
        }
        
        if(methodName.equals('getPostOfficesByCity')){
            getPostOfficesByCity(outMap);
        }
        //INI - GS - PFTA-3595
        if(methodName.equals('getStorePickUpBusinessSitesByCityLookup')){
            getStorePickUpBusinessSitesByCityLookup(input, outMap, options);
        }
        //FIN - GS - PFTA-3595
        
        return true;
    }

    public void getBusinessSitesByCity(Map<String, Object> outMap){
        Map<String, List<Map<String, String>>> businessSitesDependency = new Map<String,List<Map<String, String>>>();

        for (vlocity_cmt__BusinessSite__c stores : [SELECT PointOfSaleId__c, vlocity_cmt__City__c, vlocity_cmt__StreetAddress__c, PointOfSaleAddressNumber__c FROM vlocity_cmt__BusinessSite__c ORDER BY vlocity_cmt__StreetAddress__c]){
            if (!businessSitesDependency.containsKey(stores.vlocity_cmt__City__c)){
                businessSitesDependency.put(stores.vlocity_cmt__City__c, new List<Map<String, String>>());
            }

            Map<String, String> tempMap = new Map<String, String>();
            
            tempMap.put('name', String.valueOf(stores.PointOfSaleId__c));
            tempMap.put('value', stores.vlocity_cmt__StreetAddress__c + ' ' + stores.PointOfSaleAddressNumber__c);
            
            businessSitesDependency.get(stores.vlocity_cmt__City__c).add(tempMap);
        }
        outMap.put('dependency', businessSitesDependency);
    }
    
    public void getStorePickUpBusinessSitesByCity(Map<String, Object> outMap){
        System.debug('paso 1 >>>>>>>>>>>>>>>');    
        Map<String, List<Map<String, String>>> businessSitesDependency = new Map<String,List<Map<String, String>>>();
        System.debug('paso 1 ');
        for (vlocity_cmt__BusinessSite__c store : [SELECT Name, PointOfSaleId__c, vlocity_cmt__City__c, vlocity_cmt__StreetAddress__c, PointOfSaleAddressNumber__c FROM vlocity_cmt__BusinessSite__c WHERE PointOfSaleStorePickupEnabled__c = true AND Type__c = 'POS' ORDER BY vlocity_cmt__StreetAddress__c]){
            if (!businessSitesDependency.containsKey(store.vlocity_cmt__City__c)){
                businessSitesDependency.put(store.vlocity_cmt__City__c, new List<Map<String, String>>());
            }
            
            Map<String, String> tempMap = new Map<String, String>();
            
            tempMap.put('name', store.Id);
            tempMap.put('value', store.Name + ' - ' + store.vlocity_cmt__StreetAddress__c + ' ' + store.PointOfSaleAddressNumber__c);
            
            businessSitesDependency.get(store.vlocity_cmt__City__c).add(tempMap);
        }
        System.debug('paso 1.1 ->'+ businessSitesDependency);
        outMap.put('dependency', businessSitesDependency);
    }
    
    public void getPostOfficesByCity(Map<String, Object> outMap) {
        try {
            Map<String, List<Map<String, String>>> businessSitesDependency = new Map<String,List<Map<String, String>>>();
            System.debug('paso 1.1' );
            List<vlocity_cmt__BusinessSite__c> storeLocations = [SELECT Name, Id, PostOfficeCode__c, vlocity_cmt__City__c, vlocity_cmt__StreetAddress__c, PointOfSaleAddressNumber__c
                                           FROM vlocity_cmt__BusinessSite__c
                                          WHERE RecordTypeId IN (SELECT Id
                                                                  FROM RecordType
                                                                 WHERE SobjectType = 'vlocity_cmt__BusinessSite__c'
                                                                   AND Name = 'Sucursales de Correo')
                                            AND Status__c = 'Activo'
                                          ORDER BY vlocity_cmt__StreetAddress__c];
                        
            for (vlocity_cmt__BusinessSite__c store : storeLocations){
                if (!businessSitesDependency.containsKey(store.vlocity_cmt__City__c)){
                    businessSitesDependency.put(store.vlocity_cmt__City__c, new List<Map<String, String>>());
                }
                
                Map<String, String> tempMap = new Map<String, String>();
                
                tempMap.put('name', String.valueOf(store.Id));
                tempMap.put('value', store.PostOfficeCode__c + ' - ' + store.Name);
                
                businessSitesDependency.get(store.vlocity_cmt__City__c).add(tempMap);
            }
            outMap.put('dependency', businessSitesDependency);
        }
        catch(Exception e) {
            System.debug('Exception Msg: ' + e.getMessage());
            System.debug('Exception Cause: ' + e.getCause());
            System.debug('Exception Stack Trace: ' + e.getStackTraceString());
            throw e;
        }
    }

    public void getStorePickUpBusinessSitesByCityLookup(Map<String, Object> inputMap, Map<String, Object> outMap, Map<String, Object> options) {
        try {
            String orderId = (String) inputMap.get('orderId');
            String location = (String) ((Map<String, Object>) inputMap.get('SalesChannelConfiguration')).get('City');
            System.debug('location: ' + location);

            Order order = [SELECT Id, OriginStoreLocation__c, vlocity_cmt__OriginatingChannel__c
                            FROM Order
                            WHERE Id = :orderId];

            vlocity_cmt__BusinessSite__c storeOrigin = [SELECT Name, vlocity_cmt__City__c
                                                        FROM vlocity_cmt__BusinessSite__c
                                                        WHERE Id = :order.OriginStoreLocation__c];

            List<Map<String, String>> tempList = new List<Map<String, String>>();
            List<vlocity_cmt__BusinessSite__c> storeLocations = [SELECT Name,
                                                                        PointOfSaleId__c,
                                                                        vlocity_cmt__City__c,
                                                                        vlocity_cmt__StreetAddress__c,
                                                                        PointOfSaleAddressNumber__c,
                                                                        PointOfSaleChannel__c
                                                                FROM vlocity_cmt__BusinessSite__c
                                                                WHERE PointOfSaleStorePickupEnabled__c = true
                                                                    AND Type__c = 'POS'
                                                                    AND Location__c = :location
                                                                ORDER BY vlocity_cmt__StreetAddress__c];

            for (vlocity_cmt__BusinessSite__c store : storeLocations) {
                Map<String, String> tempMap = new Map<String, String>();
                tempMap.put('name', store.Id);
                tempMap.put('value', store.Name + ' - ' + store.vlocity_cmt__StreetAddress__c + ' ' + store.PointOfSaleAddressNumber__c);

                if (orderId == '' || orderId == 'null')
                    tempList.add(tempMap);
                else {
                    if (order.vlocity_cmt__OriginatingChannel__c == 'Presencial Agente') {
                        if (store.Name.contains(storeOrigin.name))
                            tempList.add(tempMap);
                        else {
                            String aux = String.valueOf(store.PointOfSaleChannel__c);
                            if (aux == 'Presencial Oficina Comercial')
                                tempList.add(tempMap);
                        }
                    }
                    else
                        tempList.add(tempMap);
                }
            }

            outMap.put('options', tempList);
        }
        catch(Exception e) {
            System.debug('getStorePickUpBusinessSitesByCityLookup Exception Msg: ' + e.getMessage());
            System.debug('getStorePickUpBusinessSitesByCityLookup Exception Cause: ' + e.getCause());
            System.debug('getStorePickUpBusinessSitesByCityLookup Exception Stack Trace: ' + e.getStackTraceString());
            throw e;
        }
    }
}