objects/Location__c.object
<CustomObject>
    <description>Locations</description>
    <fields>
        <fullName>LocationCode__c</fullName>
        <description>Location Code</description>
        <externalId>true</externalId>
        <label>LocationCode</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code of the Location</description>
        <externalId>true</externalId>
        <label>Postal Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StateCode__c</fullName>
        <label>StateCode</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Street__c.object
<CustomObject>
    <description>Streets of Callejero Service</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location</description>
        <inlineHelpText>Localidad</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Streets</relationshipLabel>
        <relationshipName>Streets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Argentina CPA Postal Code</description>
        <label>Postal Code</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range_From__c</fullName>
        <description>Starting Address Number for the Range</description>
        <label>Range From</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_To__c</fullName>
        <description>Address Number Range End</description>
        <label>Range To</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StreetCode__c</fullName>
        <description>Callejero Street Reference / External ID / Código de Refencia de la Calle en Callejero</description>
        <externalId>true</externalId>
        <label>StreetCode</label>
        <length>12</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Street</label>
    <nameField>
        <label>Street Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streets</pluralLabel>
    <recordTypes>
        <fullName>Range</fullName>
        <active>true</active>
        <description>Range Record sub-type</description>
        <label>Range</label>
    </recordTypes>
    <recordTypes>
        <fullName>Street</fullName>
        <active>true</active>
        <description>Street Record Type</description>
        <label>Street</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zones__c.object
<CustomObject>
    <description>Object to store Zones (Industrial Parks, Gated Communities, Working-class Communities) from Callejero in SFDC.</description>
    <fields>
        <fullName>AddressNumber__c</fullName>
        <description>Main Street Number of Zone / Altura de Calle Principal de la Zona</description>
        <label>Address Number</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location to which the Zone belongs / Localidad a la que pertenece la Zona</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Zones</relationshipLabel>
        <relationshipName>Zones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone Main Street / Calle Principal de la Zona</description>
        <label>Street</label>
        <referenceTo>Street__c</referenceTo>
        <relationshipLabel>Zones</relationshipLabel>
        <relationshipName>Zones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ZoneID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Callejero External Zone ID</description>
        <externalId>true</externalId>
        <label>Callejero Zone ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ZoneType__c</fullName>
        <description>Zone Type / Tipo de Zona del Barrio</description>
        <label>Zone Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 URBANA</fullName>
                </value>
                <value>
                    <fullName>2 BARRIO MUNICIPAL</fullName>
                </value>
                <value>
                    <fullName>3 BARRIO PRIVADO</fullName>
                </value>
                <value>
                    <fullName>4 RURAL</fullName>
                </value>
                <value>
                    <fullName>5 ISLAS</fullName>
                </value>
                <value>
                    <fullName>6 PARQUE INDUSTRIAL</fullName>
                </value>
                <value>
                    <fullName>7 STANDARD</fullName>
                </value>
                <value>
                    <fullName>8 CASILLA DE CORREO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HandleCallejeroBasedAddressesTestv2.cls
@isTest 
private class HandleCallejeroBasedAddressesTestv2 {

      @testSetup static void setup() {
           //account,contact,zone,street,location,range
           List<Account> AccList = TestDataFactory.createAccounts(1);
           List<Contact> ConList = TestDataFactory.createContacts(1,AccList[0]);
           Location__c LOC = new Location__c(Name='TestLoc',StateCode__c='B', LocationCode__c='A000');
           insert LOC;
           Street__c Street = new Street__c(Location__c=LOC.id, Name='TestStreet', Postal_Code__c='1744', Range_From__c= 200.0, Range_To__c=250.0, StreetCode__c='B16030016');
           insert Street;
           Zones__c Zone = new Zones__c(AddressNumber__c=220.0, Location__c=LOC.id, Street__c=Street.id, ZoneID__c='54563', ZoneType__c='2');
           insert Zone;
           
      }
              
      static testMethod void UpsertToAddress2Test() {
      
          List<Account> AccList = [Select id from Account];
          List<Contact> ConList = [Select id from Contact];
          List<Location__c> Location = [Select id from Location__c]; 
          List<Street__c> Street = [Select id from Street__c]; 
          List<Zones__c> Zone = [Select id from Zones__c]; 
           
          Map<String,Object> testoptions = new Map<String,Object>();
          Map<String,Object> testinputmap = new Map<String,Object>();
          Map<String,Object> testoutputmap = new Map<String,Object>();
          
          testoptions.put('State', 'B');
          testoptions.put('LocationTypeAhead', Location[0].id);
          testoptions.put('StreetTypeAhead', Street[0].id);
          testoptions.put('ZoneTypeAhead', Zone[0].id);
          testoptions.put('TypeOfAddress', 'Billing Address');
          testoptions.put('AccountId', AccList[0].id);
          
          HandleCallejeroBasedAddresses ctrl = new HandleCallejeroBasedAddresses();
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
          
          testoptions = new Map<String,Object>();
          
          testoptions.put('State', 'B');
          testoptions.put('LocationName', 'Test Location');
          testoptions.put('StreetName', 'Test Street');
          testoptions.put('ZoneName', 'Test Zone');
          testoptions.put('TypeOfAddress', 'Legal Address');
          testoptions.put('AccountId', AccList[0].id);
          
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
          
          testoptions = new Map<String,Object>();
          
          testoptions.put('State', 'B');
          testoptions.put('LocationName', 'Test Location');
          testoptions.put('StreetName', 'Test Street');
          testoptions.put('ZoneName', 'Test Zone');
          testoptions.put('TypeOfAddress', 'Service Address');
          testoptions.put('AccountId', AccList[0].id);
          
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
          
          testoptions = new Map<String,Object>();
           
          testoptions.put('State', 'B');
          testoptions.put('LocationTypeAhead', Location[0].id);
          testoptions.put('StreetTypeAhead', Street[0].id);
          testoptions.put('ZoneTypeAhead', Zone[0].id);
          testoptions.put('TypeOfAddress', 'Mailing Address');
          testoptions.put('ContactId', ConList[0].id);
          
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
          
          testoptions = new Map<String,Object>();
          
          testoptions.put('State', 'B');
          testoptions.put('LocationName', 'Test Location');
          testoptions.put('StreetName', 'Test Street');
          testoptions.put('ZoneName', 'Test Zone');
          testoptions.put('TypeOfAddress', 'Billing Address');
          testoptions.put('ContactId', ConList[0].id);
          
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
           
      }
      
      static testMethod void DeleteAddress2Test() {
          List<Account> AccList = [Select id from Account];
          List<Contact> ConList = [Select id from Contact];
          List<Location__c> Location = [Select id from Location__c]; 
          List<Street__c> Street = [Select id from Street__c]; 
          List<Zones__c> Zone = [Select id from Zones__c]; 
           
          Map<String,Object> testoptions = new Map<String,Object>();
          Map<String,Object> testinputmap = new Map<String,Object>();
          Map<String,Object> testoutputmap = new Map<String,Object>();
          
          testoptions.put('State', 'B');
          testoptions.put('LocationTypeAhead', Location[0].id);
          testoptions.put('StreetTypeAhead', Street[0].id);
          testoptions.put('ZoneTypeAhead', Zone[0].id);
          testoptions.put('TypeOfAddress', 'Billing Address');
          testoptions.put('AccountId', AccList[0].id);
          
          HandleCallejeroBasedAddresses ctrl = new HandleCallejeroBasedAddresses();
          ctrl.invokemethod('UpsertToAddress2',testinputmap, testoutputmap, testoptions );
          
          testoptions = new Map<String,Object>();
          testoptions.put('Address2Id', testoutputmap.get('Address2Id'));
          ctrl.invokemethod('DeleteAddressfromAddress2',testinputmap, testoutputmap, testoptions );
          
      }
      
      static testMethod void UIAddressHelper_StreetTest() {
      
          List<Account> AccList = [Select id from Account];
          List<Contact> ConList = [Select id from Contact];
          List<Location__c> Location = [Select id from Location__c]; 
          List<Street__c> Street = [Select id from Street__c]; 
          List<Zones__c> Zone = [Select id from Zones__c]; 
           
          Map<String,Object> testoptions = new Map<String,Object>();
          Map<String,Object> testinputmap = new Map<String,Object>();
          Map<String,Object> testoutputmap = new Map<String,Object>();
          
          testoptions.put('LocationId', Location[0].id);
          testoptions.put('StreetName', 'Test');
          
          HandleCallejeroBasedAddresses ctrl = new HandleCallejeroBasedAddresses();
          ctrl.invokemethod('UIAddressHelper_street',testinputmap, testoutputmap, testoptions );
          
         
      
      
      }
      
      static testMethod void UIAddressHelper_ZoneTest() {
      
          List<Account> AccList = [Select id from Account];
          List<Contact> ConList = [Select id from Contact];
          List<Location__c> Location = [Select id from Location__c]; 
          List<Street__c> Street = [Select id from Street__c]; 
          List<Zones__c> Zone = [Select id from Zones__c]; 
           
          Map<String,Object> testoptions = new Map<String,Object>();
          Map<String,Object> testinputmap = new Map<String,Object>();
          Map<String,Object> testoutputmap = new Map<String,Object>();
          
          testoptions.put('LocationId', Location[0].id);
          testoptions.put('zonename', 'Test');
          
          HandleCallejeroBasedAddresses ctrl = new HandleCallejeroBasedAddresses();
          ctrl.invokemethod('UIAddressHelper_zone',testinputmap, testoutputmap, testoptions );
          
      }
    
    
    
 }