objects/LoyaltyTransaction__c.object
<CustomObject>
    <description>Object to capture all transactions related to Accounts and Assets for Loyalty Club Personal</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Loyalty Transactions</relationshipLabel>
        <relationshipName>LoyaltyTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsApprobed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Approbed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoyaltyAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Loyalty Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loyalty Transactions</relationshipLabel>
        <relationshipName>LoyaltyTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Process</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Reverted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Loyalty Transaction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loyalty Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Status__c.object
<CustomObject>
    <label>Estado</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estados</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MembershipStatusTest.cls
@isTest(seeAllData = false)
public with sharing class MembershipStatusTest {
    static testmethod void invoquedMethodTest(){
        Test.startTest();
        MembershipStatus ms = new MembershipStatus();
        ms.invokeMethod('NotExistantMethod', null, null, null);
        Test.stopTest();
    }
    
    static testmethod void getMembershipStatusTest(){
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        

        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Id billingRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Billing' AND SobjectType = 'Account' LIMIT 1].Id;

        
        Account aParent = new Account(Name = 'TestMSConsumer', RecordTypeId = consumerRecordTypeId);
        insert aParent;
        
        Account aBilling = new Account(Name = 'TestMSBilling', RecordTypeId = billingRecordTypeId, ParentId = aParent.Id);
		insert aBilling;
        
        List<Account> accs = [SELECT Id, ParentId, Name, RecordType.DeveloperName FROM Account WHERE Name IN ('TestMSConsumer','TestMSBilling')];
        system.debug('accs: ' + accs);
        
        Asset asst = new Asset(Name = 'Asset', AccountId = aBilling.Id);
        insert asst;
        
        LoyaltyTransaction__c lt = new LoyaltyTransaction__c(Status__c ='Approved',
                                                             IsApprobed__c = true, Points__c = 40,
                                                             LoyaltyAccount__c = aParent.Id,
                                                             Asset__c = asst.Id);
        
        insert lt;

        Test.startTest();
        
        Object contextId = aParent.Id;
        inputMap.put('ContextId', contextId);
        system.debug('inputMap: '+ inputMap);
        MembershipStatus ms = new MembershipStatus();
        ms.invokeMethod('getMembershipStatus', inputMap, outMap, null);
        Test.stopTest();
    }
    
    static testmethod void getTransactionsTest(){
        Map<String, Object> inputMap = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        

        Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
        Id billingRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Billing' AND SobjectType = 'Account' LIMIT 1].Id;

        
        Account aParent = new Account(Name = 'TestMSConsumer', RecordTypeId = consumerRecordTypeId);
        insert aParent;
        
        Account aBilling = new Account(Name = 'TestMSBilling', RecordTypeId = billingRecordTypeId, ParentId = aParent.Id);
		insert aBilling;
        
        List<Account> accs = [SELECT Id, ParentId, Name, RecordType.DeveloperName FROM Account WHERE Name IN ('TestMSConsumer','TestMSBilling')];
        system.debug('accs: ' + accs);
        
        Asset asst = new Asset(Name = 'Asset', AccountId = aBilling.Id);
        insert asst;
        
        LoyaltyTransaction__c lt = new LoyaltyTransaction__c(Status__c ='Approved',
                                                             IsApprobed__c = true, Points__c = 40,
                                                             LoyaltyAccount__c = aParent.Id,
                                                             Asset__c = asst.Id);
        
        insert lt;

        Test.startTest();
        
        Object contextId = aParent.Id;
        inputMap.put('ContextId', contextId);
        system.debug('inputMap: '+ inputMap);
        
        MembershipStatus ms = new MembershipStatus();
        ms.invokeMethod('getTransactions', inputMap, outMap, null);
        Test.stopTest();
    }
}