objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <description>Formula: Value of the AccountId field.</description>
        <formula>AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>AssociatedWarehouseDefault__c</fullName>
        <label>Associated Warehouse Default</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__CalculationMatrix__c.object
<CustomObject>
    <label>Vlocity Calculation Matrix</label>
    <nameField>
        <label>Calculation Matrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Calculation Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__CalculationMatrixRow__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__CalculationMatrixVersionId__c</fullName>
        <label>Vlocity Calculation Matrix Version</label>
        <referenceTo>vlocity_cmt__CalculationMatrixVersion__c</referenceTo>
        <relationshipName>Vlocity_Calculation_Table_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__InputData__c</fullName>
        <label>Input Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OutputData__c</fullName>
        <label>OutputData</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity Calculation Matrix Row</label>
    <nameField>
        <label>Input Data MD5 Hash</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Calculation Matrix Rows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__CalculationMatrixVersion__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__CalculationMatrixId__c</fullName>
        <label>Pricing Matrix</label>
        <referenceTo>vlocity_cmt__CalculationMatrix__c</referenceTo>
        <relationshipLabel>Vlocity Calculation Matrix Versions</relationshipLabel>
        <relationshipName>Vlocity_Calculation_Table_Versions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__VersionNumber__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vlocity Calculation Matrix Version</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Calculation Matrix Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentAdjustment__c.object
<CustomObject>
    <description>Payment adjustments allow a Customer Service Rep to request an adjustment to a customer&apos;s billing statement. For example, this could occur as the result of a case that was registered to dispute a prior billing or product issue. Once the adjustment is approved, it can then be fed to the client&apos;s billing system for processing. This object can also be used to register a client&apos;s payment independent of any dispute.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments/Adjustments</relationshipLabel>
        <relationshipName>PaymentAdjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>Security__c</fullName>
        <description>security code de la entidad bancaria</description>
        <label>SecurityCode</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__MethodType__c</fullName>
        <label>Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <default>true</default>
                    <label>Efectivo</label>
                </value>
                <value>
                    <fullName>1201</fullName>
                    <label>Debito a Proxima Factura</label>
                </value>
                <value>
                    <fullName>2001</fullName>
                    <label>Tarjeta de Credito</label>
                </value>
                <value>
                    <fullName>Transferencia Bancaria</fullName>
                </value>
                <value>
                    <fullName>4002</fullName>
                    <label>Tarjeta de Debito</label>
                </value>
                <value>
                    <fullName>9998</fullName>
                    <label>Descuento de Saldo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Físico</fullName>
    </customValue>
    <customValue>
        <fullName>MVNO</fullName>
    </customValue>
    <customValue>
        <fullName>Telefónico</fullName>
    </customValue>
    <description>Used to indicate the top level of the channels in the solution.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/ta_sales_paymentMethod_test.cls
@IsTest global with sharing class ta_sales_paymentMethod_test{

    @IsTest static void invoke_getPaymentMethods_ok(){
        String methodName = 'GetPaymentMethods';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        List<Account> AccList = TestDataFactory.createAccounts(1, 'Consumer');
        vlocity_cmt__BusinessSite__c StoreLocations = new vlocity_cmt__BusinessSite__c(vlocity_cmt__OrganizationId__c=AccList[0].id ,PointOfSaleId__c=1.0, AssociatedWarehouseDefault__c='Default', Channel_Type__c='Agentes' ,Channel_Type_3__c='Agentes' ,Channel_Type_2__c='Agentes' ,Channel__c='Físico');
        insert StoreLocations;

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Order ord = TestDataFactory.createOrders(1, TestDataFactory.createAccounts(1, 'Consumer')[0])[0];
        ord.Delivery_Method__c = 'Delivery';
        ord.vlocity_cmt__OriginatingChannel__c = 'Agentes';
        update ord;
        input.put('IdOrder', ord.Id);
        input.put('CreditDiscountPaymentMethod', null);

        vlocity_cmt__CalculationMatrix__c testMatrix = new vlocity_cmt__CalculationMatrix__c(name='PaymentDeliveryMethod');
        insert testMatrix;

        vlocity_cmt__CalculationMatrixVersion__c objVersion = new vlocity_cmt__CalculationMatrixVersion__c();
        objVersion.vlocity_cmt__VersionNumber__c = 1;
        objVersion.vlocity_cmt__IsEnabled__c = true;
        objVersion.Name = 'PaymentDeliveryMethod';
        objVersion.vlocity_cmt__CalculationMatrixId__c = testMatrix.id;
        insert objVersion;

        vlocity_cmt__CalculationMatrixRow__c objCalculation = new vlocity_cmt__CalculationMatrixRow__c();
        objCalculation.vlocity_cmt__InputData__c = '{"MetodoEntrega":"Delivery","Canal":"Oficinas Comerciales"}';
        objCalculation.vlocity_cmt__OutputData__c = '{"DescuentoSaldo":"true","DebitoProxFactura":"true","TarjetaDebito":"true","TarjetaCredito":"true","Efectivo":"true"}';
        objCalculation.vlocity_cmt__CalculationMatrixVersionId__c = objVersion.id;
        objCalculation.Name = 'si funciona';
        insert objCalculation;

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Map<String, String>> opts = (List<Map<String, String>>) outMap.get('options');

        system.assertEquals( opts.size() , opts.size());
    }
//
    @IsTest static void invoke_getPaymentMethods_discount(){
        String methodName = 'GetPaymentMethods';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Order ord = TestDataFactory.createOrders(1, TestDataFactory.createAccounts(1, 'Consumer')[0])[0];

        input.put('IdOrder', ord.Id);
        input.put('CreditDiscountPaymentMethod', true);

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Map<String, String>> opts = (List<Map<String, String>>) outMap.get('options');

        system.assertEquals(opts.size(), opts.size());
    }
//
     @IsTest static void UpdateBillingCycleAndCheckIfShow_test(){
        //<DA>
        String methodName = 'UpdateBillingCycleAndCheckIfShow';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
         ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();


        Order ord = TestDataFactory.createOrders(1, TestDataFactory.createAccounts(1, 'Consumer')[0])[0];

        options.put('IdOrder', ord.Id);
        input.put('billingCycleValue', '134');

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        System.debug('outMap: ' + outMap);
        //Map<String,Object> auxMap = (Map<String,Object>) outMap.get('params');
        system.assertEquals(null, outMap.get('error'));

    }
//
    @IsTest static void getLineNumberFromAssetId_test(){
        //<DA>
        String methodName = 'GetLineNumberFromAssetId';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
         ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        List<Account> accs = TestDataFactory.createAccounts(1);
        List<Asset> ass = TestDataFactory.createAssets(1,accs[0],'123123');

        options.put('assetId', ass[0].Id);

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        System.debug('outMap: ' + outMap);
        //Map<String,Object> auxMap = (Map<String,Object>) outMap.get('params');
        system.assertEquals(null, outMap.get('error'));

    }
    @IsTest static void invoke_getPaymentMethods_noOrder(){
        String methodName = 'GetPaymentMethods';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        //User u = TestDataFactory.createUser('TA - OFCOM Venta y Atencion a Clientes');

       // System.runAs(u) {

            TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
            //TestDataFactory.setTeamMember('Test', u, null);
            TestDataFactory.createPaymentMethodTypes();

            input.put('IdOrder', null);
            input.put('CreditDiscountPaymentMethod', null);

            Test.startTest();
            testedClass.invokeMethod(methodName, input, outMap, options);
            Test.stopTest();

            List<Map<String, String>> opts = (List<Map<String, String>>) outMap.get('options');

            System.debug('outMap: ' + outMap);
            system.assertEquals(opts.size(), opts.size());
       // }

    }
//
    @IsTest static void invoke_getExistingPaymentMethod_exception(){
        String methodName = 'getExistingPaymentMethod';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        system.assertNotEquals(null, outMap.get('error'));
    }

    @IsTest static void getExistingPaymentMethod_test(){
        //<DA>
        String methodName = 'getExistingPaymentMethod';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);

        options.put('AccountId', accs[0].Id);
        options.put('OrderId', orders[0].Id);

        Map<String, Object> selectedPaymentMethods = new Map<String, Object>();

        selectedPaymentMethods.put('PaymentMethodRadio', 'Efectivo');

        Map<String, Object> paymMethods = new Map<String, Object>();
        paymMethods.put('PaymentMethods', selectedPaymentMethods);
        input.put('SelectPaymentMethodsStep', paymMethods);

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Map<String, Object>> validPaymentMethods = (List<Map<String, Object>>) outMap.get('ValidPaymentMethods');

        system.assertEquals(1, validPaymentMethods.size());
    }

    @IsTest static void invoke_getExistingPaymentMethod_notexists(){
        String methodName = 'getExistingPaymentMethod';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);

        options.put('AccountId', accs[0].Id);
        options.put('OrderId', orders[0].Id);

        Map<String, Object> selectedPaymentMethods = new Map<String, Object>();

        selectedPaymentMethods.put('PaymentMethodRadio', 'Efectivo');

        Map<String, Object> paymMethods = new Map<String, Object>();
        paymMethods.put('PaymentMethods', selectedPaymentMethods);
        input.put('SelectPaymentMethodsStep', paymMethods);

        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();

        Test.startTest();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Map<String, Object>> validPaymentMethods = (List<Map<String, Object>>) outMap.get('ValidPaymentMethods');

        system.assertEquals(1, validPaymentMethods.size());
    }

    @IsTest static void invoke_getExistingPaymentMethod_noPM(){
        String methodName = 'getExistingPaymentMethod';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);

        options.put('AccountId', accs[0].Id);
        options.put('OrderId', orders[0].Id);

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Map<String, Object> paymentMethod = new Map<String, Object>();

        input.put('PaymentMethod', paymentMethod);

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        //system.assertEquals('Error al validar medios de pago: No se ingresaron los medios de pago', (String) outMap.get('error'));
    }

    @IsTest static void invoke_getExistingPaymentMethod_exists(){
        String methodName = 'getExistingPaymentMethod';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        options.put('AccountId', accs[0].Id);
        options.put('OrderId', orders[0].Id);

        Vlocity_cmt__PaymentMethod__c objPaymentMethod = new Vlocity_cmt__PaymentMethod__c();
        objPaymentMethod.vlocity_cmt__MethodType__c = '1001';
        objPaymentMethod.vlocity_cmt__AccountId__c = accs[0].Id;
        insert objPaymentMethod;

        List<Map<String, Object>> listSelectedPaymentMethods = new List<Map<String, Object>>();

        Map<String, Object> mapSelectedPaymentEf = new Map<String, Object>();
        mapSelectedPaymentEf.put('PaymentMethodRadio', 'Efectivo');
        mapSelectedPaymentEf.put('Amount', '100');

        Map<String, Object> mapSelectedPaymentDPF = new Map<String, Object>();
        mapSelectedPaymentDPF.put('PaymentMethodRadio', 'Debito a Proxima Factura');
        mapSelectedPaymentDPF.put('Amount', '100');

        Map<String, Object> mapSelectedPaymentTjt = new Map<String, Object>();
        mapSelectedPaymentTjt.put('PaymentMethodRadio', 'Tarjeta de Credito');
        mapSelectedPaymentTjt.put('Amount', '100');

        Map<String, Object> mapCreditCardData = new Map<String, Object>();
        mapCreditCardData.put('ExpirationMonth', '12');
        mapCreditCardData.put('ExpirationYear', '21');
        mapCreditCardData.put('CardNumber', '1241252151251251');

        mapSelectedPaymentTjt.put('CreditCardData', mapCreditCardData);

        listSelectedPaymentMethods.add(mapSelectedPaymentEf);
        listSelectedPaymentMethods.add(mapSelectedPaymentDPF);
        listSelectedPaymentMethods.add(mapSelectedPaymentTjt);

        Map<String, Object> paymMethods = new Map<String, Object>();
        paymMethods.put('PaymentMethods', listSelectedPaymentMethods);
        input.put('SelectPaymentMethodsStep', paymMethods);

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Map<String, Object>> validPaymentMethods = (List<Map<String, Object>>) outMap.get('ValidPaymentMethods');

        system.assertEquals(3, validPaymentMethods.size());
        system.assertEquals(objPaymentMethod.Id, (String) validPaymentMethods[0].get('Id'));
    }

    @IsTest static void invoke_getPaymentMethodFromOrder_OK(){
        String methodName = 'getPaymentMethodFromOrder';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();


        Vlocity_cmt__PaymentMethod__c objPaymentMethod = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '1001',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethod;

        Vlocity_cmt__PaymentMethod__c objPaymentMethodDesc = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '9999',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethodDesc;

        Vlocity_cmt__PaymentMethod__c objPaymentMethodTj = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '2001',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true,
            Security__c = 678);
        insert objPaymentMethodTj;

        Vlocity_cmt__PaymentMethod__c objPaymentMethodPdf = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '1201',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethodPdf;

        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], objPaymentMethodPdf, 1);
        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], objPaymentMethod, 0);
        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], objPaymentMethodDesc, 0);
        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], objPaymentMethodTj, 1);
        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], TestDataFactory.createPaymentMethod(1, accs[0])[0], 0);

        options.put('accountId', accs[0].Id);
        options.put('IdOrder', orders[0].Id);

        Map<String, Object> paymentMethod = new Map<String, Object>();

        input.put('PaymentMethod', paymentMethod);

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        Map<String, Object> retPayMeth = (Map<String, Object>) outMap.get('PaymentMethod');
        //List<Object> retPayMeths = (List<Object>) retPayMeth.get('PaymentMethods');

        //System.assertEquals(5, retPayMeths.size());
    }

    @IsTest static void invoke_getBillingCycleShow_OK(){
        String methodName = 'getBillingCycleShow';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();
        TestDataFactory.createOrderItem(2, orders[0]);

        options.put('IdOrder', orders[0].Id);
        input.put('BillingCycleValue', '0');

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        Boolean show = (Boolean) outMap.get('BillingCycleShow');

        System.assertEquals(true, show);
    }

    @IsTest static void invoke_deletePaymentAdjustmentsFromOrder_OK(){
        String methodName = 'deletePaymentAdjustmentsFromOrder';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Vlocity_cmt__PaymentMethod__c objPaymentMethod = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '1001',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethod;

        TestDataFactory.createPaymentAdjustments(1, accs[0], orders[0], objPaymentMethod, 0);

        options.put('IdOrder', orders[0].Id);

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<vlocity_cmt__PaymentAdjustment__c> lstPa = [SELECT ID FROM vlocity_cmt__PaymentAdjustment__c];

        System.assertEquals(0, lstPa.size());
    }

    @IsTest static void invoke_getPaymentMethodsByChannel_OK(){
        String methodName = 'getPaymentMethodsByChannel';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.createPaymentMethodTypes();

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        Map<String, Object> mediosMap = (Map<String, Object>) outMap.get('dependency');

        System.assertEquals(4, mediosMap.size());
    }

    @IsTest static void invoke_getPaymentMethodsWithCreditDiscount_OK(){
        String methodName = 'getPaymentMethodsWithCreditDiscount';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();


        User u = TestDataFactory.createUser('TA - OFCOM Venta y Atencion a Clientes');
        System.runAs(u) {

            TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
            TestDataFactory.createPaymentMethodTypes();
            Test.startTest();
            ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
            testedClass.invokeMethod(methodName, input, outMap, options);
            Test.stopTest();

            List<Object> mediosMap = (List<Object>) outMap.get('options');

            //System.assertEquals(4, mediosMap.size());
        }
    }

    @IsTest static void invoke_getPaymentTypes_OK(){
        String methodName = 'getPaymentTypes';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.createPaymentMethodTypes();

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<Object> mediosMap = (List<Object>) outMap.get('options');

        System.assertEquals(2, mediosMap.size());
    }

    @IsTest static void invoke_getPaymentMethodQuantity_OK(){
        String methodName = 'getPaymentMethodQuantity';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        options.put('channel', 'Agentes');

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        String mediosMap = (String) outMap.get('PaymentMethodQuantity');

        System.assertEquals('3', mediosMap);
    }

    @IsTest static void invoke_getPaymentMethodQuantity_Error(){
        String methodName = 'getPaymentMethodQuantity';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        options.put('channel', 'Roberto');

        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        System.assertEquals('No se obtuvo límite de medios de pagos posibles para combinación.', (String) outMap.get('error'));
    }

    @IsTest static void invoke_savePaymentAdjustments_Error(){
        String methodName = 'savePaymentAdjustments';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();

        List<Account> accs = TestDataFactory.createAccounts(1, 'Consumer');
        List<Order> orders = TestDataFactory.createOrders(1, accs[0]);
        TestDataFactory.setTeamMember('Test', userinfo.getUserId(), null);
        TestDataFactory.createPaymentMethodTypes();

        Vlocity_cmt__PaymentMethod__c objPaymentMethod = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '1001',
            vlocity_cmt__AccountId__c = accs[0].Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethod;

        Map<String, Object> testMap = new Map<String, Object>();
        testMap.put('TotalInstallments', '1');
        testMap.put('Amount', '100');
        testMap.put('AmountInstallments', '100');
        testMap.put('AccountId', accs[0].Id);
        testMap.put('OrderId', orders[0].Id);
        testMap.put('Id', objPaymentMethod.Id);

        options.put('ValidPaymentMethods', testMap);

        Test.startTest();
        ta_sales_paymentMethod testedClass = new ta_sales_paymentMethod();
        testedClass.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

        List<vlocity_cmt__PaymentAdjustment__c> padj = [SELECT Id FROM vlocity_cmt__PaymentAdjustment__c];

        System.assertEquals(1, padj.size());
    }
 }