objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

classes/taOrderBillingUpdateProcess.cls
global with sharing class taOrderBillingUpdateProcess {//implements vlocity_cmt.VlocityOpenInterface{
    
    global static void BillUpdateOrder(String id)
    {
        System.debug('taOrderBillingUpdateProcess.BillUpdateOrder');
        try
        {
            //PFTA-7438 - Store Pickup - Flujo de Derivacion - INI
            System.debug('IdOrder: ' + id);
            Order order = [SELECT OriginStoreLocation__c, Delivery_Method__c FROM Order where Id =: id];

            System.debug('OriginStoreLocation: ' + order.OriginStoreLocation__c);
            vlocity_cmt__BusinessSite__c store = [SELECT Channel_Type__c FROM vlocity_cmt__BusinessSite__c WHERE Id =: order.OriginStoreLocation__c];

            System.debug('ChannelType: ' + store.Channel_Type__c);
            if(store.Channel_Type__c == 'Oficinas Comerciales')
            {
                taOrderController.UpdateOrderStatus(id, 'Preparar pedido');
                taOrderController.CreateStateTask(id, taOrderController.PENDIENTE_ARMADO_NOTIFICATION);
            }
            else if(store.Channel_Type__c == 'Agentes')
            {
                if(order.Delivery_Method__c == 'Presencial' || order.Delivery_Method__c == 'Delivery')
                {
                    taOrderController.UpdateOrderStatus(id, 'Entregado');
                }
                if(order.Delivery_Method__c == 'Store Pick Up')
                {
                    taOrderController.UpdateOrderStatus(id, 'Preparar pedido');
                    taOrderController.CreateStateTask(id, taOrderController.PENDIENTE_ARMADO_NOTIFICATION);
                }
            }
            /*
            System.debug(order.Delivery_Method__c);
            if(order.Delivery_Method__c == 'Presencial' || order.Delivery_Method__c == 'Store Pick Up' )
            {
                String codDeposito = '';
                Map<string, Object> response = TaMatrixUtils.getStockMovementOperation('VTAN','FACTURA', order.Delivery_Method__c);
                String codOperation =  (String) response.get('StockMovementOperation__OperationCode');
                String destinationDepositCode = (String) response.get('StockMovementOperation__DestinationDepositCode');
                System.debug('FACTURA -> Codigo operacion: ' + codOperation + ' Codigo deposito: ' + destinationDepositCode );
                if(destinationDepositCode == 'VICLIE')
                    codDeposito = 'VICLIE0001';

                if (String.isNotBlank(codOperation) && String.isNotBlank(codDeposito))
                    StockUtils.StockMovement(id, codOperation, codDeposito);
                }
            if (taOrderController.ValidateTangibleExistence(id))
            {
                taOrderController.UpdateOrderStatus(id,'Preparar Pedido');
                taOrderController.CreateStateTask(id,taOrderController.PENDIENTE_ARMADO_NOTIFICATION);
            }
            else taOrderController.UpdateOrderStatus(id,'Cobrado');
            */
            //PFTA-7438 - Store Pickup - Flujo de Derivacion - FIN
        }
        catch(Exception e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            System.debug(e.getMessage());
        }
    }
/*
    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;
        try
        {
            if (methodName.equals('DeliverStorePickUp'))
            {
                DeliverStorePickUp(inputMap, outMap);
            }
            result = false;  
        } 
        catch(Exception e)
        {
            System.debug('taOrderBillingUpdateProcess:invokeMethod -> exception: '+e);
            result = false;
        }
        return result;
    }

    void DeliverStorePickUp(Map<String,Object> inputMap, Map<String,Object> outMap)
    {
        System.debug('DeliverStorePickUp');
        try
        {
            Map<String, Object> order = (Map<String, Object>) inputMap.get('BillingOrder');
            String orderId = (String) order.get('Id');
            StockUtils.StockMovement(orderId, 'FVOC', 'VICLIE0001');
        }
        catch(Exception e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            System.debug(e.getMessage());
        }
    }
    */
}