objects/Order.object
<CustomObject>
    <fields>
        <fullName>Delivery_Method__c</fullName>
        <label>Delivery Method</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>vlocity_cmt__OriginatingChannel__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Delivery_Methods</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gestion__c</fullName>
        <label>Gestion</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cambio de SIM</fullName>
                </value>
                <value>
                    <fullName>Cambio de SIM por siniestro</fullName>
                </value>
                <value>
                    <fullName>Cambio de número</fullName>
                </value>
                <value>
                    <fullName>Cambio de titularidad</fullName>
                </value>
                <value>
                    <fullName>Desconexión</fullName>
                </value>
                <value>
                    <fullName>Nominacion</fullName>
                </value>
                <value>
                    <fullName>Cambio de Plan</fullName>
                </value>
                <value>
                    <fullName>Alta Baja Servicios</fullName>
                </value>
                <value>
                    <fullName>Compra de Pack</fullName>
                </value>
                <value>
                    <fullName>Venta</fullName>
                </value>
                <value>
                    <fullName>Alta</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Preactivacion Repro</fullName>
                </value>
                <value>
                    <fullName>Alta o Baja SVA</fullName>
                </value>
                <value>
                    <fullName>Conciliador</fullName>
                </value>
                <value>
                    <fullName>Conciliate</fullName>
                </value>
                <value>
                    <fullName>Suspension</fullName>
                </value>
                <value>
                    <fullName>Resume</fullName>
                </value>
                <value>
                    <fullName>Numero Gratis</fullName>
                </value>
                <value>
                    <fullName>Alta producto genérico</fullName>
                </value>
                <value>
                    <fullName>Cambio de Terminal</fullName>
                </value>
                <value>
                    <fullName>Cambio en Garantia</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentMethodType__c</fullName>
        <label>Payment Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PaymentMethodType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>FromStock__c</fullName>
        <description>It is saved from which inventory the reservation was made and then the sale. This can be paid for dismissal according to the type of inventory and if it is tangible or not, if you have to send it to invoice or not.</description>
        <label>From Stock</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Location is set here, when the orderItem belongs to a Simcard and has a LineNumber associated to identify the location where the line is assigned</description>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/StockMovementConfiguration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configurations for the stock movement process</description>
    <fields>
        <fullName>Codigo_Deposito__c</fullName>
        <description>Client deposit code</description>
        <label>Codigo Deposito</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_del_Cliente__c</fullName>
        <description>Client Material config value</description>
        <label>Material del Cliente</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Stock Movement Configuration</label>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>Channel_Type_2__c</fullName>
        <description>Stores the level 2 of the type of channels.</description>
        <label>Channel Type 2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_3__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType2</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type_3__c</fullName>
        <description>Stores the level 3 of the type of channels.</description>
        <label>Channel Type 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ChannelType3</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <description>Stores the first level of the type of channels.</description>
        <label>Channel Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type_2__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>ChannelType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>Used to indicate the top level of the channels in the solution based in the value selected in the Channel_Type__c field.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Channel_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Channel</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Store the region that the store location belongs to.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used to indicate the status of the point of sales or agency.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Dado de baja</fullName>
                </value>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Pendiente activación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__State__c</fullName>
        <label>State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WarrantyTimeLimit__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Time limit for warranty replacement process based on channel, location and other parameters</description>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationCode__c</fullName>
        <label>LocationCode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeLimit__c</fullName>
        <label>TimeLimit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WarrantyTimeLimit</label>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Channel.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Físico</fullName>
    </customValue>
    <customValue>
        <fullName>MVNO</fullName>
    </customValue>
    <customValue>
        <fullName>Telefónico</fullName>
    </customValue>
    <description>Used to indicate the top level of the channels in the solution.</description>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Call Center</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mayorista</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the first level of the type of channels.</description>
    <masterLabel>ChannelType</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/ChannelType2.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>OC</fullName>
    </customValue>
    <customValue>
        <fullName>OC TP</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Redes Sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
    </customValue>
    <description>Stores the level 2 of the type of channels.</description>
    <masterLabel>ChannelType2</masterLabel>
</GlobalValueSet>

globalValueSets/ChannelType3.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Administración de Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Agentes</fullName>
    </customValue>
    <customValue>
        <fullName>APP</fullName>
    </customValue>
    <customValue>
        <fullName>Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Caring</fullName>
    </customValue>
    <customValue>
        <fullName>Chat Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Cooperativas</fullName>
    </customValue>
    <customValue>
        <fullName>E-Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Ejecutivos</fullName>
    </customValue>
    <customValue>
        <fullName>Emprendimientos</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Google+</fullName>
    </customValue>
    <customValue>
        <fullName>Google-Hangout</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>ISP</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>LinkedIN</fullName>
    </customValue>
    <customValue>
        <fullName>Mail</fullName>
    </customValue>
    <customValue>
        <fullName>Oficinas Comerciales</fullName>
    </customValue>
    <customValue>
        <fullName>Retails Nacionales</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>SnapChat</fullName>
    </customValue>
    <customValue>
        <fullName>Telegram</fullName>
    </customValue>
    <customValue>
        <fullName>Totem</fullName>
    </customValue>
    <customValue>
        <fullName>Twitter</fullName>
    </customValue>
    <customValue>
        <fullName>USSD</fullName>
    </customValue>
    <customValue>
        <fullName>Ventas</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <description>Stores the level 3 of the type of channels.</description>
    <masterLabel>ChannelType3</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Delivery_Methods.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Presencial</fullName>
    </customValue>
    <customValue>
        <fullName>Store Pick Up</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <description>Métodos de entrega para el proceso de venta</description>
    <masterLabel>Delivery Methods</masterLabel>
</GlobalValueSet>

globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AMBA</fullName>
    </customValue>
    <customValue>
        <fullName>LITO</fullName>
        <label>Litoral</label>
    </customValue>
    <customValue>
        <fullName>MEDI</fullName>
        <label>Mediterranea</label>
    </customValue>
    <customValue>
        <fullName>SUR</fullName>
        <label>Sur</label>
    </customValue>
    <customValue>
        <fullName>LISU</fullName>
        <isActive>false</isActive>
        <label>LISU</label>
    </customValue>
    <customValue>
        <fullName>NOA</fullName>
        <isActive>false</isActive>
        <label>NOA</label>
    </customValue>
    <customValue>
        <fullName>LINO</fullName>
        <isActive>false</isActive>
        <label>LINO</label>
    </customValue>
    <description>Store the region division used in Telecom Argentina</description>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/taSalesChangeTerminalInWarrantyTest.cls
@isTest
public with sharing class taSalesChangeTerminalInWarrantyTest
{
  public static testmethod void test1()
 {
   List<Account> lstAccount = TestDataFactory.createAccounts(1, 'Consumer');
   List<Product2> lstProduct2 = TestDataFactory.createProduct(1);
   Map<String,String> serialNumbers = new Map<String,String>();
               serialNumbers.put('99999777799999', 'MTPL');
               serialNumbers.put('77776676767666', 'MCVM');
   Asset assetTest = new Asset();
   assetTest.Name = 'Test Asset';
   assetTest.AccountId = lstAccount[0].Id;
   assetTest.Product2Id =  lstProduct2[0].Id;
   //assetTest.SerialNumber = '99999777799999';
   assetTest.SerialNumber = serialNumbers.get('99999777799999');
   lstProduct2[0].productCode = 'CHIPPRUEBA';
   update lstProduct2;
   insert assetTest;
   vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
     Name = 'Barrio Norte',
     vlocity_cmt__OrganizationId__c = lstAccount[0].Id,
     Status__c = 'Activo',
     Type__c = 'POS',
     Channel__c = 'Físico',
     Channel_Type__c = 'Agentes',
     Channel_Type_2__c = 'Agentes',
     Channel_Type_3__c = 'Agentes',
     vlocity_cmt__State__c = 'C',
     Region__c='AMBA');
   insert storeLocation;

       WorkTeam__c workTeamParent = new WorkTeam__c(
     Team_Name__c = 'Test Parent',
     Name = 'Test Parent');
       insert workTeamParent;

   StockMovementConfiguration__c stockConf = new StockMovementConfiguration__c();
   stockConf.Codigo_Deposito__c = 'VICLIE001';
   stockConf.Material_del_Cliente__c = 'MCTL';
   insert stockConf;



   WarrantyTimeLimit__c objTimeAnnul = new WarrantyTimeLimit__c();
   objTimeAnnul.Channel__c = 'Físico';
   objTimeAnnul.LocationCode__c = 'C';
   objTimeAnnul.Name = 'CABA_Fisico';
   objTimeAnnul.TimeLimit__c = 30.0;
   insert objTimeAnnul;

   User usernew = new user(ID = UserInfo.getUserID());
       String strIdUser = UserInfo.getUserID();

       String manager = UserInfo.getUserId();
       String parent = workTeamParent.Id;
       WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
   Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);
   List<Order>OrdList = TestDataFactory.createOrders(2,lstAccount[0]);
   OrdList[0].OriginStoreLocation__c = storeLocation.Id;
   OrdList[0].PaymentMethodType__c ='1001';
   OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
   OrdList[0].Gestion__c = 'Venta';
   OrdList[0].Delivery_Method__c='Presencial';
   OrdList[1].OriginStoreLocation__c = storeLocation.Id;
   OrdList[1].PaymentMethodType__c ='1001';
   OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
   OrdList[1].Gestion__c = 'Venta';
   OrdList[1].Delivery_Method__c='Presencial';
   update OrdList;
   List<OrderItem>OIList =TestDataFactory.createOrderItem(1,OrdList[0]);
   OIList[0].FromStock__c = 'MTPL';
   update OIList;
   List<OrderItem>OIList1 =TestDataFactory.createOrderItem(1,OrdList[1]);
   OIList1[0].FromStock__c = 'MTPL';
   //update OIList1;
   assetTest.vlocity_cmt__OrderProductId__c = OIList[0].Id;
   update assetTest;
   Map<String, Object> inputMap = new Map<String, Object>();
   Map<String, Object> outputMap = new Map<String, Object>();
   Map<String, Object> options = new Map<String, Object>();
   options.put('assetId', assetTest.Id);
   inputMap.put('assetId', assetTest.Id);
   String mockResponse = '{"listaNumeroSeries":[{"codNMU":"codNMU","imsi":"imsi","aduanaIngreso":"aduanaIngreso","paisOrigen":"paisOrigen","codOrdenDespacho":"codOrdenDespacho","codDeposito":"codDeposito","stockProducto":"stockProducto","numeroSerie":"serial"},{"codNMU":"codNMU","imsi":"imsi","aduanaIngreso":"aduanaIngreso","paisOrigen":"paisOrigen","codOrdenDespacho":"codOrdenDespacho","codDeposito":"codDeposito","stockProducto":"stockProducto","numeroSerie":"serial2"}]}';
  VlocityIntegrationProcedureTestUtility.mockIntegrationProcedure('IFS_S095', mockResponse);
   Test.startTest();
     taSalesChangeTerminalInWarrantyHandler.invokeMethod('ValidateRazonSocial', inputMap, outputMap, options);
     taSalesChangeTerminalInWarrantyHandler.invokeMethod('ValidateTangibleConsignado', inputMap, outputMap, options);
     taSalesChangeTerminalInWarrantyHandler.invokeMethod('validationTimeDefenseConsumer', inputMap, outputMap, options);
     taSalesChangeTerminalInWarrantyHandler.invokeMethod('GetTypesChangeTerminal', inputMap, outputMap, options);
     taSalesChangeTerminalInWarrantyHandler.invokeMethod('ValidateClientMaterial', inputMap, outputMap, options);
     //tsctiw.invokeMethod('ValidateSTEnElPais', inputMap, outputMap, options);
   Test.stopTest();
 }

public static testmethod void test2()
  {
    List<Account> lstAccount = TestDataFactory.createAccounts(1, 'Consumer');
    List<Product2> lstProduct2 = TestDataFactory.createProduct(1);
    Asset assetTest = new Asset();
    assetTest.Name = 'Test Asset';
    assetTest.AccountId = lstAccount[0].Id;
    assetTest.Product2Id =  lstProduct2[0].Id;
    lstProduct2[0].productCode = 'CHIPPRUEBA';
    update lstProduct2;
    insert assetTest;
    vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
      Name = 'Barrio Norte',
      vlocity_cmt__OrganizationId__c = lstAccount[0].Id,
      Status__c = 'Activo',
      Type__c = 'POS',
      Channel__c = 'Físico',
      Channel_Type__c = 'Agentes',
      Channel_Type_2__c = 'Agentes',
      Channel_Type_3__c = 'Agentes',
      vlocity_cmt__State__c = 'C',
      Region__c='AMBA');
    insert storeLocation;

        WorkTeam__c workTeamParent = new WorkTeam__c(
      Team_Name__c = 'Test Parent',
      Name = 'Test Parent');
        insert workTeamParent;

    WarrantyTimeLimit__c objTimeAnnul = new WarrantyTimeLimit__c();
    objTimeAnnul.LocationCode__c = 'C';
    objTimeAnnul.Name = 'CABA_Fisico';
    objTimeAnnul.TimeLimit__c = 30.0;
    insert objTimeAnnul;

    User usernew = new user(ID = UserInfo.getUserID());
        String strIdUser = UserInfo.getUserID();

        String manager = UserInfo.getUserId();
        String parent = workTeamParent.Id;
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
    Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);
    List<Order>OrdList = TestDataFactory.createOrders(2,lstAccount[0]);
    OrdList[0].OriginStoreLocation__c = storeLocation.Id;
    OrdList[0].PaymentMethodType__c ='1001';
    OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[0].Gestion__c = 'Venta';
    OrdList[0].Delivery_Method__c='Presencial';
    OrdList[1].OriginStoreLocation__c = storeLocation.Id;
    OrdList[1].PaymentMethodType__c ='1001';
    OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[1].Gestion__c = 'Venta';
    OrdList[1].Delivery_Method__c='Presencial';
    // OrdList[1].SubGestion__c = '';
    update OrdList;
    List<OrderItem>OIList =TestDataFactory.createOrderItem(1,OrdList[0]);
    OIList[0].FromStock__c = 'MTPL';
    update OIList;
    List<OrderItem>OIList1 =TestDataFactory.createOrderItem(1,OrdList[1]);
    OIList1[0].FromStock__c = 'MTPL';
    update OIList1;
    assetTest.vlocity_cmt__OrderProductId__c = OIList[0].Id;
    update assetTest;
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outputMap = new Map<String, Object>();
    Map<String, Object> options = new Map<String, Object>();
    options.put('assetId', assetTest.Id);
    Test.startTest();
      taSalesChangeTerminalInWarrantyHandler.invokeMethod('validationTimeDefenseConsumer', inputMap, outputMap, options);
    Test.stopTest();
  }

  public static testmethod void test3()
  {
    List<Account> lstAccount = TestDataFactory.createAccounts(1, 'Consumer');
    List<Product2> lstProduct2 = TestDataFactory.createProduct(1);
    Asset assetTest = new Asset();
    assetTest.Name = 'Test Asset';
    assetTest.AccountId = lstAccount[0].Id;
    assetTest.Product2Id =  lstProduct2[0].Id;
    lstProduct2[0].productCode = 'CHIPPRUEBA';
    update lstProduct2;
    insert assetTest;
    vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
      Name = 'Barrio Norte',
      vlocity_cmt__OrganizationId__c = lstAccount[0].Id,
      Status__c = 'Activo',
      Type__c = 'POS',
      Channel__c = 'Físico',
      Channel_Type__c = 'Agentes',
      Channel_Type_2__c = 'Agentes',
      Channel_Type_3__c = 'Agentes',
      vlocity_cmt__State__c = 'C',
      Region__c='AMBA');
    insert storeLocation;

        WorkTeam__c workTeamParent = new WorkTeam__c(
      Team_Name__c = 'Test Parent',
      Name = 'Test Parent');
        insert workTeamParent;

    WarrantyTimeLimit__c objTimeAnnul = new WarrantyTimeLimit__c();
    objTimeAnnul.Name = 'CABA_Fisico';
    objTimeAnnul.TimeLimit__c = 30.0;
    insert objTimeAnnul;

    User usernew = new user(ID = UserInfo.getUserID());
        String strIdUser = UserInfo.getUserID();

        String manager = UserInfo.getUserId();
        String parent = workTeamParent.Id;
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
    Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);
    List<Order>OrdList = TestDataFactory.createOrders(2,lstAccount[0]);
    OrdList[0].OriginStoreLocation__c = storeLocation.Id;
    OrdList[0].PaymentMethodType__c ='1001';
    OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[0].Gestion__c = 'Venta';
    OrdList[0].Delivery_Method__c='Presencial';
    OrdList[1].OriginStoreLocation__c = storeLocation.Id;
    OrdList[1].PaymentMethodType__c ='1001';
    OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[1].Gestion__c = 'Venta';
    OrdList[1].Delivery_Method__c='Presencial';
    update OrdList;
    List<OrderItem>OIList =TestDataFactory.createOrderItem(1,OrdList[0]);
    OIList[0].FromStock__c = 'MTPL';
    update OIList;
    List<OrderItem>OIList1 =TestDataFactory.createOrderItem(1,OrdList[1]);
    OIList1[0].FromStock__c = 'MTPL';
    update OIList1;
    assetTest.vlocity_cmt__OrderProductId__c = OIList[0].Id;
    update assetTest;
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outputMap = new Map<String, Object>();
    Map<String, Object> options = new Map<String, Object>();
    options.put('assetId', assetTest.Id);
    Test.startTest();
      taSalesChangeTerminalInWarrantyHandler.invokeMethod('validationTimeDefenseConsumer', inputMap, outputMap, options);
    Test.stopTest();
  }

   public static testmethod void test4()
  {
    List<Account> lstAccount = TestDataFactory.createAccounts(1, 'Consumer');
    List<Product2> lstProduct2 = TestDataFactory.createProduct(1);
    Asset assetTest = new Asset();
    assetTest.Name = 'Test Asset';
    assetTest.AccountId = lstAccount[0].Id;
    assetTest.Product2Id =  lstProduct2[0].Id;
    lstProduct2[0].productCode = 'CHIPPRUEBA';
    update lstProduct2;
    insert assetTest;
    vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(
      Name = 'Barrio Norte',
      vlocity_cmt__OrganizationId__c = lstAccount[0].Id,
      Status__c = 'Activo',
      Type__c = 'POS',
      Channel__c = 'Físico',
      Channel_Type__c = 'Agentes',
      Channel_Type_2__c = 'Agentes',
      Channel_Type_3__c = 'Agentes',
      vlocity_cmt__State__c = 'C',
      Region__c='AMBA');
    insert storeLocation;

        WorkTeam__c workTeamParent = new WorkTeam__c(
      Team_Name__c = 'Test Parent',
      Name = 'Test Parent');
        insert workTeamParent;

    WarrantyTimeLimit__c objTimeAnnul = new WarrantyTimeLimit__c();
    objTimeAnnul.Channel__c = 'Físico';
    objTimeAnnul.LocationCode__c = 'C';
    objTimeAnnul.Name = 'CABA_Fisico';
    objTimeAnnul.TimeLimit__c = 30.0;
    insert objTimeAnnul;

    User usernew = new user(ID = UserInfo.getUserID());
        String strIdUser = UserInfo.getUserID();

        String manager = UserInfo.getUserId();
        String parent = workTeamParent.Id;
        WorkTeam__c workTeam = new WorkTeam__c(Team_Name__c = 'Test', Name = 'Test');
    Team_Member__c tm = TestDataFactory.setTeamMember('Call Center', UserInfo.getUserId(), null);
    List<Order>OrdList = TestDataFactory.createOrders(2,lstAccount[0]);
    OrdList[0].OriginStoreLocation__c = storeLocation.Id;
    OrdList[0].PaymentMethodType__c ='1001';
    OrdList[0].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[0].Gestion__c = 'Venta';
    OrdList[0].Delivery_Method__c='Store Pick Up';
    OrdList[0].DeliveryDate__c  = System.today();
    OrdList[1].OriginStoreLocation__c = storeLocation.Id;
    OrdList[1].PaymentMethodType__c ='1001';
    OrdList[1].vlocity_cmt__OriginatingChannel__c ='Agentes';
    OrdList[1].Gestion__c = 'Venta';
    OrdList[1].Delivery_Method__c='Store Pick Up';
    OrdList[1].DeliveryDate__c  = System.today();
    update OrdList;
    List<OrderItem>OIList =TestDataFactory.createOrderItem(1,OrdList[0]);
    OIList[0].FromStock__c = 'MTPL';
    update OIList;
    List<OrderItem>OIList1 =TestDataFactory.createOrderItem(1,OrdList[1]);
    OIList1[0].FromStock__c = 'MTPL';
    update OIList1;
    assetTest.vlocity_cmt__OrderProductId__c = OIList[0].Id;
    update assetTest;
    Map<String, Object> inputMap = new Map<String, Object>();
    Map<String, Object> outputMap = new Map<String, Object>();
    Map<String, Object> options = new Map<String, Object>();
    options.put('assetId', assetTest.Id);
    Test.startTest();
      taSalesChangeTerminalInWarrantyHandler.invokeMethod('validationTimeDefenseConsumer', inputMap, outputMap, options);

    Test.stopTest();
  }
}