objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__PriceListId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>vlocity_cmt__PriceList__c</referenceTo>
        <relationshipLabel>Orders Using This Price List</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PriceList__c.object
<CustomObject>
    <description>A price list represents the pricing for the products and services that your company offers. A base price list defines the baseline pricing for your products and services. A child price list inherits all the pricing from the base price list and contains exceptions to the baseline pricing.</description>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OVStepperControllerTest.cls
@isTest
private class OVStepperControllerTest {

  static testMethod void OVStepperController() {
  
      List<Account> accounts = TestDataFactory.createAccounts(1,'Consumer');
      vlocity_cmt__PriceList__c taPriceList = TestDataFactory.createPriceList('Telecom Price List');
      test.starttest();
      Order Ord = new order(Name='TestOrder',
                            AccountId=accounts[0].id,
                            EffectiveDate=Date.today(),
                            Status='Draft',
                            Pricebook2Id =Test.getStandardPricebookId(),
                            vlocity_cmt__PriceListId__c=taPriceList.Id);
      insert Ord ;
      ApexPages.StandardController sc = new ApexPages.StandardController(Ord);
      OVStepperController OVS = new OVStepperController(sc);
       test.stoptest();
       }
 }