objects/OrderManagerIntegrationProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EndpointGet__c</fullName>
        <label>Endpoint Get</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointLoginUrl__c</fullName>
        <label>Endpoint Login Url</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order Manager Integration Properties</label>
</CustomObject>

classes/OrderControllerTest.cls
@isTest
private class OrderControllerTest {

    @isTest
    private static void TestGetOrderConciliateOM() {
        OrderManagerIntegrationProperties__c conProp = new OrderManagerIntegrationProperties__c();
        conProp.EndpointGet__c = 'https://api.dev.ta.xom.vloc-dev.com/ordermanagement/v1/orderMilestoneInfo/';
        conProp.EndpointLoginUrl__c = 'https://ui.dev.ta.xom.vloc-dev.com/security/v1/login';
        conProp.Password__c = 'vlocity';
        conProp.User__c = 'admin';
        conProp.Name = 'Milestones';
        insert conProp;

        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorOrderController());
            OrderController testOrderController = new OrderController();
        Test.stopTest();
    }
}