objects/Order.object
<CustomObject>
    <fields>
        <fullName>OriginStoreLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Origin Store Location</label>
        <referenceTo>vlocity_cmt__BusinessSite__c</referenceTo>
        <relationshipLabel>Orders (Origin Store Location)</relationshipLabel>
        <relationshipName>OriginOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OriginatingChannel__c</fullName>
        <description>Channel can be used to drive Eligibility/Compatibility/Recommendations/Pricing/Other implementations, e.g. Certain Product Bundles are only available on the Web or Call Center channel but not via the Retail and Dealer channels OR A product may have a different price when sold via the Web than sold via the Retail channel, etc.</description>
        <label>Originating Channel</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>WEB</fullName>
                </value>
                <value>
                    <fullName>Call Center</fullName>
                </value>
                <value>
                    <fullName>Retails</fullName>
                </value>
                <value>
                    <fullName>Mayorista</fullName>
                </value>
                <value>
                    <fullName>Agentes</fullName>
                </value>
                <value>
                    <fullName>Oficinas Comerciales</fullName>
                </value>
                <value>
                    <fullName>E-Commerce</fullName>
                </value>
                <value>
                    <fullName>Administración de Ventas</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                </value>
                <value>
                    <fullName>Cooperativas</fullName>
                </value>
                <value>
                    <fullName>Ejecutivos</fullName>
                </value>
                <value>
                    <fullName>Emprendimientos</fullName>
                </value>
                <value>
                    <fullName>IVR</fullName>
                </value>
                <value>
                    <fullName>SMS</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>USSD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>PointOfSaleAddressNumber__c</fullName>
        <description>Point Of Sale Address Number</description>
        <inlineHelpText>Point Of Sale Address Number</inlineHelpText>
        <label>Address Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PointOfSaleStorePickupEnabled__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Point Of Sale Store Pickup Enabled</description>
        <inlineHelpText>Point Of Sale Store Pickup Enabled</inlineHelpText>
        <label>Point Of Sale Store Pickup Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PointOfSaleType__c</fullName>
        <description>PFTA-8812 - Stores the type of facility that the store location has.</description>
        <label>Type of facility</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>PointOfSaleTypesSet</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>PostOfficeEndDate__c</fullName>
        <description>Post Office End Date</description>
        <inlineHelpText>Fin de actividad de Oficina Postal</inlineHelpText>
        <label>Post Office End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>POS</fullName>
                </value>
                <value>
                    <fullName>PostOffice</fullName>
                    <label>Post Office</label>
                </value>
                <value>
                    <fullName>Agente</fullName>
                </value>
                <value>
                    <fullName>Proveedor</fullName>
                </value>
                <value>
                    <fullName>Oficina Comercial</fullName>
                </value>
                <value>
                    <fullName>Deposito Central TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__StreetAddress__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/taSalesSearchBusinessSitesTest.cls
@isTest(seeAllData=false)
public with sharing class taSalesSearchBusinessSitesTest {
    
	public static testmethod void getBusinessSitesByCityTest(){
		Account acc = new Account(Name = 'test');
		insert acc;
		Map<String, Object> outMap = new Map<String, Object>();
        vlocity_cmt__BusinessSite__c bussite = new vlocity_cmt__BusinessSite__c (vlocity_cmt__City__c = 'Tigre', PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE');
		insert bussite;
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getBusinessSitesByCity', null, outMap, null);
		Test.stopTest();
	}

	public static testmethod void getStorePickUpBusinessSitesByCityTest(){
		Account acc = new Account(Name = 'test');
		insert acc;
		Map<String, Object> outMap = new Map<String, Object>();
		insert new vlocity_cmt__BusinessSite__c (vlocity_cmt__City__c = 'Tigre', PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE', Type__c = 'POS', PointOfSaleStorePickupEnabled__c = true);
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getStorePickUpBusinessSitesByCity', null, outMap, null);
		Test.stopTest();
	}
    
	public static testmethod void getPostOfficesByCityTest(){
		Account acc = new Account(Name = 'test');
		insert acc;
		Map<String, Object> outMap = new Map<String, Object>();
		insert new vlocity_cmt__BusinessSite__c (vlocity_cmt__City__c = 'Tigre', PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE', Type__c = 'PostOffice', PostOfficeEndDate__c = null);
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getPostOfficesByCity', null, outMap, null);
		Test.stopTest();
	}
    
	public static testmethod void getStorePickUpBusinessSitesByCityLookupTest(){
        MockupFactory.generate();
        String city = 'Tigre';
        
		Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
		vlocity_cmt__BusinessSite__c busSite = new vlocity_cmt__BusinessSite__c(vlocity_cmt__City__c = city, PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE', Type__c = 'POS', PointOfSaleStorePickupEnabled__c = true);
        insert busSite;
        
        ord.OriginStoreLocation__c = busSite.Id;
        ord.vlocity_cmt__OriginatingChannel__c = 'Presencial Agente';
        update ord;
        
		Map<String, Object> inputMap = new Map<String, Object>();
		Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> auxMap = new Map<String, Object>();
        auxMap.put('City', city);
        inputMap.put('orderId', ord.Id);
        inputMap.put('SalesChannelConfiguration', auxMap);
        
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getStorePickUpBusinessSitesByCityLookup', inputMap, outMap, null);
		Test.stopTest();
	}
    public static testmethod void getStorePickUpBusinessSitesByCityLookupTest2(){
        MockupFactory.generate();
        String city = 'Tigre';
        
		Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
        ord.vlocity_cmt__OriginatingChannel__c = '';
        update ord;
		vlocity_cmt__BusinessSite__c busSite = new vlocity_cmt__BusinessSite__c(vlocity_cmt__City__c = city, PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE', Type__c = 'POS', PointOfSaleStorePickupEnabled__c = true);
        insert busSite;
        
        ord.OriginStoreLocation__c = busSite.Id;
        ord.vlocity_cmt__OriginatingChannel__c = 'Presencial Agente';
        update ord;
        
		Map<String, Object> inputMap = new Map<String, Object>();
		Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> auxMap = new Map<String, Object>();
        auxMap.put('City', city);
        inputMap.put('orderId', ord.Id);
        inputMap.put('SalesChannelConfiguration', auxMap);
        
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getStorePickUpBusinessSitesByCityLookup', inputMap, outMap, null);
		Test.stopTest();
	}
        public static testmethod void getStorePickUpBusinessSitesByCityLookupTestNull(){
        MockupFactory.generate();
        String city = 'Tigre';
        
		Account acc = [SELECT Id FROM Account LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
		vlocity_cmt__BusinessSite__c busSite = new vlocity_cmt__BusinessSite__c(vlocity_cmt__City__c = city, PointOfSaleId__c = 1, vlocity_cmt__StreetAddress__c = 'Test', PointOfSaleAddressNumber__c = '1', vlocity_cmt__OrganizationId__c = acc.Id, PointOfSaleType__c = 'LE', Type__c = 'POS', PointOfSaleStorePickupEnabled__c = true);
        insert busSite;
        
        ord.OriginStoreLocation__c = busSite.Id;
        ord.vlocity_cmt__OriginatingChannel__c = 'Presencial Agente';
        update ord;
        
		Map<String, Object> inputMap = new Map<String, Object>();
		Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> auxMap = new Map<String, Object>();
        auxMap.put('City', city);
        inputMap.put('orderId', '');
        inputMap.put('SalesChannelConfiguration', auxMap);
        
		Test.startTest();
		taSalesSearchBusinessSites tsl = new taSalesSearchBusinessSites();
		tsl.invokeMethod('getStorePickUpBusinessSitesByCityLookup', inputMap, outMap, null);
		Test.stopTest();
	}
}