objects/Order.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <description>Formula: Value of the AccountId field.</description>
        <formula>AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentAdjustment__c.object
<CustomObject>
    <description>Payment adjustments allow a Customer Service Rep to request an adjustment to a customer&apos;s billing statement. For example, this could occur as the result of a case that was registered to dispute a prior billing or product issue. Once the adjustment is approved, it can then be fed to the client&apos;s billing system for processing. This object can also be used to register a client&apos;s payment independent of any dispute.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payments/Adjustments</relationshipLabel>
        <relationshipName>PaymentAdjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Adjustment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Payment Adjustments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__MethodType__c</fullName>
        <label>Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <default>true</default>
                    <label>Efectivo</label>
                </value>
                <value>
                    <fullName>1201</fullName>
                    <label>Debito a Proxima Factura</label>
                </value>
                <value>
                    <fullName>2001</fullName>
                    <label>Tarjeta de Credito</label>
                </value>
                <value>
                    <fullName>Transferencia Bancaria</fullName>
                </value>
                <value>
                    <fullName>4002</fullName>
                    <label>Tarjeta de Debito</label>
                </value>
                <value>
                    <fullName>9998</fullName>
                    <label>Descuento de Saldo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/taSalesPaymentMethodsExtensionTest.cls
@isTest
global with sharing class taSalesPaymentMethodsExtensionTest {

  @isTest static void constructorTest(){
    Account acc = TestDataFactory.createAccounts(1)[0];
    Order ord = TestDataFactory.createOrders(1, acc)[0];

        Vlocity_cmt__PaymentMethod__c objPaymentMethod = new Vlocity_cmt__PaymentMethod__c(
            vlocity_cmt__MethodType__c = '1001',
            vlocity_cmt__AccountId__c = acc.Id,
            vlocity_cmt__IsActive__c = true);
        insert objPaymentMethod;

    List<vlocity_cmt__PaymentAdjustment__c> paymAdj = TestDataFactory.createPaymentAdjustments(1, acc, ord, objPaymentMethod, 0);

    ApexPages.currentPage().getParameters().put('lc',ord.id);
    ApexPages.StandardController stdLead = new ApexPages.StandardController(ord);

    taSalesPaymentMethodsExtension testClass = new taSalesPaymentMethodsExtension(stdLead);

    System.assertEquals(testClass.paymentMethods[0].Id, paymAdj[0].Id);
  }
}