objects/Product2.object
<CustomObject>
    <fields>
        <fullName>NMU__c</fullName>
        <description>Unique product identifier for TA</description>
        <externalId>true</externalId>
        <label>NMU</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Bien_de_Uso__c</fullName>
        <label>Tipo de Bien de Uso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
                <value>
                    <fullName>Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_sales_productSearch.cls
global with sharing class ta_sales_productSearch implements vlocity_cmt.VlocityOpenInterface {

    public Boolean invokeMethod(String methodName, Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options) {
        if(methodName.equals('PopulateProductsTypeAhead')){
            PopulateProductsTypeAhead(input, outMap, options);
        }
        return true;
    }

    public void PopulateProductsTypeAhead(Map<String, Object> input, Map<String, Object> outMap, Map<String, Object> options){
        try{
            List<Product2> products = [SELECT Id, Name, ProductCode, NMU__c FROM Product2 WHERE Product2.Tipo_de_Bien_de_Uso__c = 'Tangible' ORDER BY Name];

            outMap.put('products', products);
        }catch (Exception e){}
    }
}