objects/Product2.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__JSONAttribute__c</fullName>
        <description>JSON body containing a denormalized representation of the product&apos;s Vlocity Attribute values and configuration metadata.</description>
        <label>JSONAttribute</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__Attribute__c.object
<CustomObject>
    <description>Represents the definition of an attribute which can be used for profiling, describing or configuring
        items tracked in the database. More specifically:
        1) Attributes are used to profile accounts and contacts to describe their interests, preferences and any other
        information that users desire to track. The same attributes can be used on products, documents and other content
        to describe the target profile of customers who might be interested in them.
        2) Attributes can allow users to filter a list of available and eligible products shown on an opportunity, quote
        or order to those matching some criteria.
        3) Attributes can be used to configure individual characteristics of a product on an opportunity, quote or
        order. For example, the operator may select one of three speeds available on a specific modem.</description>
    <fields>
        <fullName>vlocity_cmt__AttributeCategoryId__c</fullName>
        <description>Parent attribute category. Used for organizing the attributes into groupings.</description>
        <label>Attribute Category</label>
        <referenceTo>vlocity_cmt__AttributeCategory__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Description__c</fullName>
        <description>Description of this attribute.</description>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PicklistId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Picklist that provides the valid values for this attribute.</description>
        <label>Picklist</label>
        <referenceTo>vlocity_cmt__Picklist__c</referenceTo>
        <relationshipLabel>Vlocity Attributes</relationshipLabel>
        <relationshipName>Vlocity_Attributes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Value__c</fullName>
        <description>Default value for this attribute when assigned to an object.</description>
        <label>Default Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an Attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>vlocity_cmt__AttributeCategoryId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute Category copied from the attribute at the time the attribute was assigned.</description>
        <label>Attribute Category</label>
        <referenceTo>vlocity_cmt__AttributeCategory__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AttributeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute assigned to the parent object.</description>
        <label>Attribute</label>
        <referenceTo>vlocity_cmt__Attribute__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DefaultPicklistValueId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID identifying the default value for this attribute from the governing Vlocity Picklist.</description>
        <label>Default Picklist Value</label>
        <referenceTo>vlocity_cmt__PicklistValue__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsReadOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this attribute is read-only for the assigned parent object (usually a product).</description>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a value for this attribute is required for the assigned parent object (usually a product).</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectId__c</fullName>
        <description>ID of the parent object to which the attribute is assigned.</description>
        <externalId>true</externalId>
        <label>Assigned To Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PicklistId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id of the Vlocity Picklist that provides the valid values for this attribute on this parent object. Overrides any Vlocity Picklist defined at the attribute level.</description>
        <label>Picklist</label>
        <referenceTo>vlocity_cmt__Picklist__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ValueDataType__c</fullName>
        <description>Data type of this attribute such as text, number, percent or checkbox. Overrides the Value Type field on the assigned Vlocity Attribute.</description>
        <label>Value Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Datetime</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Multi Picklist</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Value__c</fullName>
        <description>Value of this attribute. For example, attribute strength (0-5), or a text value &quot;Jimmy&quot;.</description>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Attribute Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__AttributeCategory__c.object
<CustomObject>
    <description>Vlocity Attribute Categories allow Attributes to be assigned to admin-defined groupings. The Category also identifies some characteristics of the profiling attributes in that grouping.</description>
    <fields>
        <fullName>vlocity_cmt__Description__c</fullName>
        <description>Description of this attribute category.</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Vlocity Attribute Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attribute Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__Picklist__c.object
<CustomObject>
    <description>Vlocity Picklists are reusable lists of values used for validating attributes or custom UI pick list controls.</description>
    <fields>
        <fullName>vlocity_cmt__Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity Picklist</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Picklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__PicklistValue__c.object
<CustomObject>
    <description>Represents a value defined for a Vlocity Picklist.</description>
    <fields>
        <fullName>vlocity_cmt__PicklistId__c</fullName>
        <label>Vlocity Picklist</label>
        <referenceTo>vlocity_cmt__Picklist__c</referenceTo>
        <relationshipName>PicklistValues</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Value__c</fullName>
        <formula>IF(  ISPICKVAL(vlocity_cmt__PicklistId__r.vlocity_cmt__DataType__c, &apos;Date Time&apos;) ,  TEXT(vlocity_cmt__DateTimeValue__c) ,
    IF( ISPICKVAL(vlocity_cmt__PicklistId__r.vlocity_cmt__DataType__c, &apos;Date&apos;) ,  TEXT(vlocity_cmt__DateValue__c) ,
        IF( ISPICKVAL(vlocity_cmt__PicklistId__r.vlocity_cmt__DataType__c, &apos;Text&apos;),  vlocity_cmt__TextValue__c ,
            IF( ISPICKVAL(vlocity_cmt__PicklistId__r.vlocity_cmt__DataType__c, &apos;Number&apos;) ,  (TEXT(vlocity_cmt__NumberValue__c) &amp; vlocity_cmt__UnitOfMeasureName__c) ,
                IF( ISPICKVAL(vlocity_cmt__PicklistId__r.vlocity_cmt__DataType__c, &apos;Boolean&apos;)  ,  IF( vlocity_cmt__BooleanValue__c = true  ,  &apos;true&apos; , &apos;false&apos; ), null )))))</formula>
        <label>Value</label>
        <type>Text</type>
    </fields>
    <label>Vlocity Picklist Value</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Picklist Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AttributesListController.cls
public class AttributesListController 
{
    public List<AttributeAssignment> attrAssigns;
    public Map<Id,List<AttributeAssignment>> prod2attrAssigns;
    private Map<Id,String> attr2DefPLValue;
    
    public class AttributeAssignment
    {
        public vlocity_cmt__AttributeAssignment__c attrAssign { get; set; }
        public Product2 product { get; set; }
        public List<String> pickListValues { get; set; }
        public String defaultPLValue { get; set; }
        public String isReadonly { get; set; }
        public String isRequired { get; set; }
        
        AttributeAssignment(vlocity_cmt__AttributeAssignment__c attrAssign)
        {
            this.attrAssign = attrAssign;
            this.isReadonly = attrAssign.vlocity_cmt__IsReadOnly__c ? 'yes' : 'no';
            this.isRequired = attrAssign.vlocity_cmt__IsRequired__c ? 'yes' : 'no';
        }
        
    }
    
    public List<AttributeAssignment> getAssignments() 
    {
        //Get list of all atrribute assignments
        List<vlocity_cmt__AttributeAssignment__c> results = [select 
                                                             Id, 
                                                             vlocity_cmt__ObjectId__c, 
                                                             vlocity_cmt__AttributeCategoryId__r.Name, 
                                                             vlocity_cmt__AttributeId__r.Name, 
                                                             vlocity_cmt__AttributeId__c,
                                                             vlocity_cmt__AttributeId__r.vlocity_cmt__Description__c, 
                                                             vlocity_cmt__ValueDataType__c, 
                                                             vlocity_cmt__PicklistId__r.Name,  
                                                             vlocity_cmt__Value__c, 
                                                             vlocity_cmt__DefaultPicklistValueId__r.Name, 
                                                             vlocity_cmt__IsReadOnly__c, 
                                                             vlocity_cmt__IsRequired__c  
                                                             from vlocity_cmt__AttributeAssignment__c
                                                            ];
        
        prod2attrAssigns = new Map<Id,List<AttributeAssignment>>();
        
        //Store results into Map (productID - AttributeAssignments)
        Iterator<vlocity_cmt__AttributeAssignment__c> it=results.iterator();
        System.debug('\n\nStart reading the results');
        while(it.hasNext())
        {
            vlocity_cmt__AttributeAssignment__c attrAssign = (vlocity_cmt__AttributeAssignment__c)it.next();
            System.debug('\n\nattrAssign.Id='+attrAssign.Id+'; ProductId='+attrAssign.vlocity_cmt__ObjectId__c);
            Id productId = Id.valueOf(attrAssign.vlocity_cmt__ObjectId__c);
            System.debug('real ProductId='+productId);
            
            List<AttributeAssignment> attrAssgnTmp = prod2attrAssigns.get(productId);
            if (attrAssgnTmp==null) attrAssgnTmp = new List<AttributeAssignment>();
            attrAssgnTmp.add(new AttributeAssignment(attrAssign));
            
            prod2attrAssigns.put(productId, attrAssgnTmp);
        }
        System.debug('\n\nResults processed');
        
        //Now for each AttributeAssignment we need to resolve ProductId into Product2 record
        resolveProducts();
        
        //get all values from the map(ProductId - AttributeAssignments) and store them into the new List
        attrAssigns = new List<AttributeAssignment>();
        Iterator<Id> productsItr = prod2attrAssigns.keySet().iterator();
        while (productsItr.hasNext())
        {
            Id productId = productsItr.next();
            List<AttributeAssignment> attrAssignTmp = prod2attrAssigns.get(productId);
            if (attrAssignTmp==null || attrAssignTmp.size()==0 || attrAssignTmp.get(0)==null || attrAssignTmp.get(0).product==null) continue;
            attrAssigns.addAll(attrAssignTmp);
        }
        
        return attrAssigns;
        
    }
    
    private void resolveProducts()
    {
        List<Product2> products = [select Id, Name, ProductCode, vlocity_cmt__JSONAttribute__c from Product2 where Id=:prod2attrAssigns.keySet()];
        Iterator<Product2> productsItr = products.iterator();
        while (productsItr.hasNext())
        {
            Product2 product = productsItr.next();
            if (product.ProductCode==null || !product.ProductCode.startsWith('XOM'))
            {
                prod2attrAssigns.remove(product.Id);
                continue;
            }
            //Parse JSON Attribute and store all picklist values in a map (attribute Id - list of values)
            //            Map<Id,List<String>> attr2pickListValues = new Map<Id,List<String>>();
            Map<Id,List<String>> attr2pickListValues = new Map<Id,List<String>>();
            attr2DefPLValue = new Map<Id,String>();
            String json = product.vlocity_cmt__JSONAttribute__c;
            if (json!=null) attr2pickListValues = parseJSONAttribute(json);
            
            //Populate AttributeAssignment objects with Product and picklist values
            List<AttributeAssignment> attrAssgnLst = prod2attrAssigns.get(product.Id);
            Iterator<AttributeAssignment> attrAssItr = attrAssgnLst.iterator();
            while (attrAssItr.hasNext())
            {
                //get AttributeAssignment object
                AttributeAssignment attrAssgn = attrAssItr.next();
                
                //populate product
                attrAssgn.product = product;
                
                //populate picklist values (if needed)
                attrAssgn.pickListValues = attr2pickListValues.get(attrAssgn.attrAssign.vlocity_cmt__AttributeId__c);
                
                //populate default picklist value (if needed)
                attrAssgn.defaultPLValue = attr2DefPLValue.get(attrAssgn.attrAssign.vlocity_cmt__AttributeId__c);
            }
        }
    }
    
    /**
* the method parses JSONAttribute field to get pick list values and default pick list value 
* (if an attribute is a lick list).
* Logic assumes certain format of the corresponding JSON:
* {   <--each attribute starts with an Array
*   "$$AttributeDefinitionStart$$" <-- and this tag in the beginning
*   ...
*   "attributeid__c": ...    <--attribute id
*   ...
*   "valuedatatype__c": "Picklist",    <-- indication that a particular attribute is a picklist
*   ...
*   "displayText": ...   <-- picklist value will be taken from here
*   ...
*	"default"  <--start of the section for the dafult pick list value
*	...
*	"displayText": ...   <-- default picklist value will be taken from here
*   ...
*   "$$AttributeDefinitionEnd$$"
* }
* */
    
    private Map<Id,List<String>> parseJSONAttribute(String json)
    {
        Map<Id,List<String>> attr2pickListValues = new Map<Id,List<String>>();
        
        System.debug('START JSON PARSER. json is: '+json);
        
        Map<String,Object> attrCats = (Map<String,Object>)System.JSON.deserializeUntyped(json);
        List<Object> attrs = attrCats.values();
        System.debug('Attributes are: '+attrs);
        
        for (Object attrListObj : attrs)
        {
            List<Object> attrList = (List<Object>)attrListObj;
                
            for (Object attr : attrList)
            {
                
                
                System.debug('==Attribute is: '+attr);
                Map<String, Object> attrMap = (Map<String,Object>)attr;
                System.debug('==Attribute is converted to Map: '+attrMap);
                
                String attrIdasString = (String)attrMap.get('attributeid__c');
                System.debug('==Attribute Id is: '+attrIdasString);
                Id attrId = attrIdasString==null ? null : Id.valueOf(attrIdasString);
                
                String attrType = (String)attrMap.get('valuedatatype__c');
                System.debug('==Attribute type is: '+attrType);
                
                if ('Picklist'.equals(attrType))
                {
                    List<String> pickListValues = new List<String>();
                    
                    Map<String,Object> attrRunTime = (Map<String,Object>)attrMap.get('attributeRunTimeInfo');
                    System.debug('==Attribute run time is: '+attrRunTime);
                    
                    List<Object> values = (List<Object>)attrRunTime.get('values');
                    System.debug('==Picklist values are: '+values);
                    
                    for (Object value : values)
                    {
                        System.debug('===Picklist value block is: '+value);
                        Map<String, Object> valueMap = (Map<String, Object>)value;
                        System.debug('===Picklist value block as Map is: '+valueMap);
                        
                        String pickList = (String)valueMap.get('displayText');
                        System.debug('===Picklist value is: '+pickList);
                        
                        pickListValues.add(pickList);
                    }
                    
                    List<Object> defaultPLBlock = (List<Object>)attrRunTime.get('default');
                    System.debug('==Default PL block is: '+defaultPLBlock);
                    
                    Map<String,Object> defaultPLBlockMap = new Map<String,Object>();
                    System.debug('==Default PL block Map is: '+defaultPLBlockMap);
                    
                    if (defaultPLBlock.size()>0) defaultPLBlockMap = (Map<String,Object>)defaultPLBlock.get(0);
                    
                    if (attrId != null) 
                    {
                        attr2DefPLValue.put(attrID, (String)defaultPLBlockMap.get('displayText'));
                        attr2pickListValues.put(attrId, pickListValues);
                        System.debug('==Default PL value and all PL values are saved');
                    }
                }
            }
        }
        
        return attr2pickListValues;
    }
}