objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Marca__c</fullName>
        <description>Marca</description>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TELECOM Personal</fullName>
                </value>
                <value>
                    <fullName>Gemalto</fullName>
                </value>
                <value>
                    <fullName>Samsung</fullName>
                </value>
                <value>
                    <fullName>LG</fullName>
                </value>
                <value>
                    <fullName>Motorola</fullName>
                </value>
                <value>
                    <fullName>Google</fullName>
                </value>
                <value>
                    <fullName>Telecom</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
                <value>
                    <fullName>Arnet</fullName>
                </value>
                <value>
                    <fullName>MarcaPrueba1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NMU__c</fullName>
        <description>Unique product identifier for TA</description>
        <externalId>true</externalId>
        <label>NMU</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Bien_de_Uso__c</fullName>
        <label>Tipo de Bien de Uso</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
                <value>
                    <fullName>Servicio</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__HelpText__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <description>Product Type can be used to drive eligibility/compatibility/recommendations/other implementations</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan</fullName>
                </value>
                <value>
                    <fullName>Gemalto</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>TELECOM PERSONAL</fullName>
                </value>
                <value>
                    <fullName>Bundle</fullName>
                </value>
                <value>
                    <fullName>FixedLine</fullName>
                    <label>Línea Fija</label>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                    <label>Línea Móvil</label>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Servicio Valor Agregado</fullName>
                </value>
                <value>
                    <fullName>Plan Prepago</fullName>
                </value>
                <value>
                    <fullName>Plan Pospago</fullName>
                </value>
                <value>
                    <fullName>Plan Hibrido</fullName>
                </value>
                <value>
                    <fullName>Servicio GSM</fullName>
                </value>
                <value>
                    <fullName>Numeros Amigos</fullName>
                </value>
                <value>
                    <fullName>Pack</fullName>
                </value>
                <value>
                    <fullName>Reseteo de Cuota</fullName>
                </value>
                <value>
                    <fullName>Control Cuota Datos</fullName>
                </value>
                <value>
                    <fullName>Simcard</fullName>
                </value>
                <value>
                    <fullName>Recarga</fullName>
                </value>
                <value>
                    <fullName>Credito Adicional</fullName>
                </value>
                <value>
                    <fullName>Roaming</fullName>
                </value>
                <value>
                    <fullName>Dispositivo</fullName>
                </value>
                <value>
                    <fullName>Prestamo</fullName>
                </value>
                <value>
                    <fullName>Proteccion</fullName>
                </value>
                <value>
                    <fullName>Captura</fullName>
                </value>
                <value>
                    <fullName>Pack LDI</fullName>
                </value>
                <value>
                    <fullName>Pack Roaming</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__BusinessSite__c.object
<CustomObject>
    <description>Store Locations track the retail and customer service locations where customers may obtain products or services from your organization or your partner organizations. This information can be used to provide a Store Locator feature on a customer website. A store location advertises its location by address and geolocation as well as its hours of operation. Store locations are operated by a company brand or an authorized dealer which must be defined as a partner account or an internal organization account.</description>
    <fields>
        <fullName>AssociatedWarehouseId__c</fullName>
        <description>Associated Warehouse Code</description>
        <inlineHelpText>Associated Warehouse Code</inlineHelpText>
        <label>Associated Warehouse</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PointOfSaleId__c</fullName>
        <description>Point of Sale Code (VMI-NET service ID)</description>
        <inlineHelpText>Point of Sale Code (VMI-NET service ID)</inlineHelpText>
        <label>Point Of Sale</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OrganizationId__c</fullName>
        <description>Defines the internal brand or authorized dealer that operates this store or customer service location.</description>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Store Locations</relationshipLabel>
        <relationshipName>OrganizationSites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Store Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TaCpqAppHandlerInputMapFactoryTest.cls
@isTest
public class TaCpqAppHandlerInputMapFactoryTest {
    
    public static String createPrefeasibilityJson() {
        Map<String, Object> prefeMap = new Map<String, Object>();
        List<Object> tecnologiasAccesoList = new List<Object>();
        Map<String, Object> technologyMap = new Map<String, Object>();
        List<Object> servicesList = new List<Object>();
        Map<String, Object> serviceTypeInternetMap = new Map<String, Object>();
        Map<String, Object> serviceTypeVozMap = new Map<String, Object>();
        List<Object> technicalStandardsList = new List<Object>();
        Map<String, Object> techStandardMap = new Map<String, Object>();
        techStandardMap.put('disponibilidad', 'SI');
        techStandardMap.put('medicionDeBajada', '12345');
        technicalStandardsList.add(techStandardMap);
        serviceTypeInternetMap.put('standardsTecnico', technicalStandardsList);
        serviceTypeInternetMap.put('servicio', 'Internet');
        serviceTypeVozMap.put('standardsTecnico', technicalStandardsList);
        serviceTypeVozMap.put('servicio', 'Voz');
        servicesList.add(serviceTypeInternetMap);
        servicesList.add(serviceTypeVozMap);
        technologyMap.put('servicios', servicesList);
        tecnologiasAccesoList.add(technologyMap);
        prefeMap.put('tecnologiasAcceso', tecnologiasAccesoList);
        return JSON.serialize(prefeMap);
    }

    public static Map<String, Object> generateInputMap() {
        Map<String, Object> inputMap = new Map<String, Object>();

        inputMap.put('pagesize', 10);
        inputMap.put('fields', 'IsActive,Id,Name,UnitPrice,ProductCode,vlocity_cmt__RecurringPrice__c,product2.description,product2.Tipo_de_Bien_de_Uso__c,Product2.Marca__c,Product2.vlocity_cmt__HelpText__c,Product2.NMU__c,Product2.vlocity_cmt__Type__c,Product2.Family');

        Map<String, Object> billingOrderMap = new Map<String, Object>();
        Decimal pickUpStore = 21;

        Account acc = [SELECT Id FROM Account LIMIT 1];
        vlocity_cmt__BusinessSite__c storeLocation = new vlocity_cmt__BusinessSite__c(vlocity_cmt__OrganizationId__c = acc.Id);
        storeLocation.PointOfSaleId__c = pickUpStore;
        storeLocation.AssociatedWarehouseId__c = 'DFMULT001';
        insert storeLocation;

        billingOrderMap.put('PickUpStore', String.valueOf(pickUpStore));
        inputMap.put('BillingOrder', billingOrderMap);
        return inputMap;
    }
}