objects/Repro_Loader_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Repro Loader Settings</label>
</CustomObject>

objects/XOMBatchLineJob__c.object
<CustomObject>
    <description>Represents a single line to be processed via batch job</description>
    <fields>
        <fullName>JSON__c</fullName>
        <description>JSON object with the fields/attributes needed for this job/line.</description>
        <label>JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OrderCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag that says if the Order record for this job/line has been created.</description>
        <label>Order Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order record created for provisioning this job/line.</description>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Batch Line Jobs</relationshipLabel>
        <relationshipName>XOMBatchLineJobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>1</defaultValue>
        <description>The priority with which the job/line should be processed. Highest number = highest priority.</description>
        <label>Priority</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of job to be done for this line.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repro</fullName>
                </value>
                <value>
                    <fullName>Dormant</fullName>
                </value>
                <value>
                    <fullName>Nominatividad</fullName>
                </value>
                <value>
                    <fullName>Rehabilitacion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Batch Line Job</label>
    <nameField>
        <displayFormat>BLJ-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>BatchLineJob Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Line Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/xOMCreateOrdersForReproBulkJobs.cls
global class xOMCreateOrdersForReproBulkJobs implements Database.Batchable<sObject>, Schedulable {
    String query = 'Select Id, JSON__c, Order__c From XOMBatchLineJob__c Where Type__c = \'Repro\' and OrderCreated__c = false and order by Priority__c desc, CreatedDate asc limit 10';
    
    global void execute(SchedulableContext SC) {
        xOMCreateOrdersForReproBulkJobs batchCLass = new xOMCreateOrdersForReproBulkJobs();
        Database.executebatch(batchCLass, 1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        try {
            Repro_Loader_Settings__c settings = Repro_Loader_Settings__c.getOrgDefaults();
            boolean result = xOMReproLoader.createOrdersFromBulkJob((List<XOMBatchLineJob__c>) scope, settings);
            xOMReproLoader.ResultObj res;
            if(result) {
                res.resultCode = 1;
                update scope;
            }
        }
        catch(Exception ex) {
            finish(BC);
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        // report progress back to BeFAN
    }
    
}