objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__VlocityTrackingEntry__c.object
<CustomObject>
    <fields>
        <fullName>TrackedAction__c</fullName>
        <label>TrackedAction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Data__c</fullName>
        <label>Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Vlocity Tracking Entry</label>
    <nameField>
        <label>Vlocity Tracking Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Tracking Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrackingEntryClass.cls
public with sharing class TrackingEntryClass {
    
    public static void updateTrackingEntry(List<vlocity_cmt__VlocityTrackingEntry__c> triggerNew){

       List<Id> ownersID = new List<Id>();
        
        for(vlocity_cmt__VlocityTrackingEntry__c t : triggerNew)
        {
            if(t.TrackedAction__c == 'Consulta de Comprobante')
                ownersID.add(t.OwnerId);
        }
            
        List<Team_Member__c> workTeamUser = [SELECT Work_Team__c, User_member__c FROM Team_Member__c WHERE User_member__c IN :ownersID];
        system.debug('workTeamUser'+ workTeamUser);
        List<vlocity_cmt__VlocityTrackingEntry__c> trackinListUpdate = new List<vlocity_cmt__VlocityTrackingEntry__c>();
        system.debug('trackingListUpdate'+ trackinListUpdate);
        
        for(vlocity_cmt__VlocityTrackingEntry__c ta : triggerNew)
        {
            if(ta.TrackedAction__c == 'Consulta de Comprobante'){
                for(Integer w=0; w < workTeamUser.size(); w++){
                    if(ta.OwnerId == workTeamUser[w].User_member__c){
                        ta.vlocity_cmt__Data__c = ta.vlocity_cmt__Data__c+',workTeamUser: '+workTeamUser[w].Work_Team__c;
                    }
                }
            }
        }
           
    }

/*ta_helper.getWorkTeamUserInfo(userId);
public class ta_helper{
public static List<Team_Member__c> getWorkTeamUserInfo(Id userId)
{
   List<Team_Member__c> workTeamUser = [SELECT Work_Team__c, User_member__c FROM Team_Member__c WHERE User_member__c = :userId]; 
   return workTeamUser;
}
}*/

}