objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserRoleAPIName__c</fullName>
        <description>It is used to store the API name of the Salesfor Role assigned to the user based in the roles available for the work team in Work team permissions.</description>
        <externalId>true</externalId>
        <label>User Role API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the manager of the workplace</description>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_security_wmassignment_test.cls
@isTest
public class ta_security_wmassignment_test {
    static testMethod void myUnitTest(){
            
            List<workteam__c> workteams = new List<workteam__c>();
        workteam__c workTeam1 = new workteam__c(Name='Test1' ,team_Name__c='Test1',is_Active__c = true, Manager__c = UserInfo.getUserId());
        workteam__c workTeam2 = new workteam__c(Name='Test2' ,team_Name__c='Test2',is_Active__c = true, Manager__c = UserInfo.getUserId());
            workteams.add(workTeam1);
            workteams.add(workTeam2);
            insert workteams;

            team_member__c member = new team_member__c(user_member__c = UserInfo.getUserId(), UserRoleAPIName__c='Test', is_Active__c = true, work_team__c = workTeam1.Id);
            insert member;            

        Test.StartTest();
        PageReference pageRef1 = Page.ta_security_workmemberassignment;
        Ta_security_wmassignment_controller cont1 = new ta_security_wmassignment_Controller();
        Ta_security_wmassignment_controller.feedTree();
            cont1.selectedId = workTeam1.Id;
            cont1.view();
            cont1.saveId = workTeam2.Id;
            cont1.save();
            cont1.foreignMember.user_member__c = UserInfo.getUserId();
            cont1.selectedId = workTeam1.Id;
            cont1.viewTeam();
            cont1.foreignMember.UserRoleAPIName__c='Test';
            cont1.assign();
            cont1.getRoleAPINames();
            Test.StopTest();
   }
    
    static testMethod void myUnitTest2(){
            
        List<workteam__c> workteams = new List<workteam__c>();
        workteam__c workTeam1 = new workteam__c(Name='Test1' ,team_Name__c='Test1',is_Active__c = true, Manager__c = UserInfo.getUserId());
        workteams.add(workTeam1);
        insert workteams;  

        Test.StartTest();
        PageReference pageRef1 = Page.ta_security_workmemberassignment;
        Ta_security_wmassignment_controller cont1 = new ta_security_wmassignment_Controller();
        cont1.foreignMember = new team_member__c(user_member__c = UserInfo.getUserId(), UserRoleAPIName__c='Test2', is_Active__c = true, work_team__c = workTeam1.Id);
        cont1.saveMember();
        Test.StopTest();
   }
}