objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Work_Team_Permission__c.object
<CustomObject>
    <description>Store the permission set, queues and user roles assigned to a work team, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the permission is active or not for the work team.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_API_Name__c</fullName>
        <description>It is used to store the API name of the queue related to the work team.</description>
        <externalId>true</externalId>
        <label>Queue API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a permission with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Permissions</relationshipLabel>
        <relationshipName>Work_Team_Permissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Permission</label>
    <nameField>
        <displayFormat>WTP-{0000}</displayFormat>
        <label>Work Team Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PublicGroupAPIName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>It is used to store the API name of the public group created as a mirror of the work team.
Used to control the synchronization between this 2 objects.</description>
        <externalId>true</externalId>
        <label>Public Group API Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkTeamPermissionHelper.cls
/**
* @author       Norwill Gutiérrez href=<ngutierrez@aconcaguabs.com>
* Project:      Telecom Security
* Description:  WorkTeamPermissionTrigger Helper
*
* Changes (Version)
* -------------------------------------
*      No.    Date          Author                 Description
*      -----  ----------    --------------------   ---------------
*      1.0    2018-03-09    Norwill Gutiérrez      Class creation.
*      2.0    2018-04-27    Norwill Gutiérrez      To process queue.
*************************************************************************************************************/
public with sharing class WorkTeamPermissionHelper {

    @future
    public static void processGroupQueue(String[] wtpIDs){
        try {
            Set<String> wtQueueNames = new Set<String>();
            Set<String> wtpQueueNames = new Set<String>();
            Map<String, Id> grpPublicMap = new Map<String, Id>();
            Map<String, Id> grpQueueMap = new Map<String, Id>();
            List<GroupMember> grpMemberToInsert = new List<GroupMember>();
            List<GroupMember> grpMemberToDelete = new List<GroupMember>();
            
            system.debug('wtpIDs: '+ wtpIDs);

            List<Work_Team_Permission__c> wtpLst = [SELECT Id, Work_Team__c, Work_Team__r.PublicGroupAPIName__c, 
                                                    Queue_API_Name__c, Is_Active__c
                                                    FROM Work_Team_Permission__c WHERE Id IN :wtpIDs];
            
            system.debug('Work_Team_Permission__c: '+ wtpLst);

            for(Work_Team_Permission__c wtP :wtpLst ){
                wtpQueueNames.add(wtP.Queue_API_Name__c);
                wtQueueNames.add(wtP.Work_Team__r.PublicGroupAPIName__c);
            }

            List<Group> grpPublic = [SELECT Id,Name FROM Group 
                                    WHERE Type = 'Regular' AND Name IN :wtQueueNames];
            for(Group grpP : grpPublic){
                grpPublicMap.put(grpP.Name, grpP.Id);
            }

            List<Group> grpList = [SELECT Id,Name FROM Group 
                                WHERE Type = 'Queue' AND Name IN :wtpQueueNames];        
            for(Group grpQ : grpList){
                grpQueueMap.put(grpQ.Name, grpQ.Id);
            }

            for(Work_Team_Permission__c wtP :wtpLst ){
                if(wtP.Is_Active__c){               
                    GroupMember grpMember = new GroupMember();
                    grpMember.GroupId = grpQueueMap.get(wtP.Queue_API_Name__c);
                    grpMember.UserOrGroupId = grpPublicMap.get(wtP.Work_Team__r.PublicGroupAPIName__c);
                    grpMemberToInsert.add(grpMember);
                }else{
                    grpMemberToDelete.add([SELECT GroupId,Id,UserOrGroupId FROM GroupMember 
                                        WHERE GroupId =: grpQueueMap.get(wtP.Queue_API_Name__c)
                                        AND UserOrGroupId =: grpPublicMap.get(wtP.Work_Team__r.PublicGroupAPIName__c)]);
                }
            }
            if(grpMemberToInsert.size() > 0){
                system.debug('grpMemberToInsert: '+ grpMemberToInsert);
                insert grpMemberToInsert;
            }
            if(grpMemberToDelete.size() > 0){
                system.debug('grpMemberToDelete: '+ grpMemberToDelete);
                delete grpMemberToDelete;
            } 
        }catch(Exception ex){
            system.debug('EX: ' + ex );
        }              
    }

    @future
    public static void grantPermissionToUser(String[] permissionSet, String[]  wtpIds) {
        try {
            List<Team_Member__c> tm = [SELECT Id, User_Member__c FROM Team_Member__c WHERE Is_Active__c = true AND Work_Team__c IN :wtpIds AND User_Member__c != NULL];
            List<PermissionSet> permSet = [SELECT Id FROM PermissionSet WHERE Name IN :permissionSet];
            List<PermissionSetAssignment> psa = new List<PermissionSetAssignment>();
            for (Team_Member__c tmember : tm) {
                for (PermissionSet idPerm : permSet) {
                    PermissionSetAssignment newPermissionSetA = new PermissionSetAssignment(PermissionSetId = idPerm.Id, AssigneeId = tmember.User_Member__c);
                    psa.add(newPermissionSetA);
                }
            }
            system.debug('grantPermissionToUser: ' + tm + ' - ' + permSet + ' - ' + psa);
            insert psa;
        }catch(Exception ex){
            system.debug('EX: ' + ex );
        }
    }

    @future
    public static void deleteUserPermission(String[] permissionSet, String[] wtpIds) {
        try {
            system.debug('deleteUserPermission: ' + permissionSet.size() + ' wtpIds: ' + wtpIds.size());
            Set<Id> tmIds = new Set<Id>();
            List<Team_Member__c> lstTM = [SELECT Id, User_Member__c FROM Team_Member__c WHERE Is_Active__c = true AND Work_Team__c IN :wtpIds AND User_Member__c != null];
            system.debug('lstTM: ' + lstTM);
            for(Team_Member__c tm : lstTM){
                tmIds.add(tm.User_Member__c);
            }

            Set<Id> permSet = (new Map<Id, SObject>([SELECT Id FROM PermissionSet WHERE Name IN :permissionSet])).keySet();
            List<PermissionSetAssignment> psa = new List<PermissionSetAssignment>();
            system.debug('tmIds: ' + tmIds);
            system.debug('permSet: ' + permSet);
            List<PermissionSetAssignment> psaResult = [SELECT Id FROM PermissionSetAssignment WHERE PermissionSetId IN :permSet AND AssigneeId IN :tmIds]; 
            system.debug('psaResult: ' + psaResult);
            for (PermissionSetAssignment psaItem : psaResult) {
                psa.add(psaItem);
            }
            system.debug('deleteUserPermission: ' + psa.size() + ' - ' + tmIds.size() + ' - ' + permSet.size()); 
            delete psa;
        }catch(Exception ex){
            system.debug('EX: ' + ex );
        }
    }
}