objects/Team_Member__c.object
<CustomObject>
    <description>Store the user assigned by work team in TA, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the assignation is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserRoleAPIName__c</fullName>
        <description>It is used to store the API name of the Salesfor Role assigned to the user based in the roles available for the work team in Work team permissions.</description>
        <externalId>true</externalId>
        <label>User Role API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is used to relate a user with the work team that it belongs to. Used in the security design done for TA.</description>
        <label>User member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a team member (user) with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Members</relationshipLabel>
        <relationshipName>Team_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Member</label>
    <nameField>
        <displayFormat>T-{00000000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>Stores the name of the work team that the user belongs to. It is loaded by development to control the vlocity actions available for a user.</description>
        <externalId>true</externalId>
        <label>Work Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WorkTeamTriggersTest.cls
/**
* @Author: Julia Carranza
* @Description: This test tests the AttributesUsage Class for the Account Object.
*/
@isTest
public class WorkTeamTriggersTest {
	
	@isTest static void workTeamAndTeamMeberSync(){

		List<User> userList = new List<User>([SELECT Id FROM User LIMIT 1]);
		User user1 = userList[0];
		WorkTeam__c wt1 = new WorkTeam__c(Name = 'wt1 Name', Is_Active__c = true, Team_Name__c = 'wt1 Name');

		Test.startTest();

		Database.Insert(wt1);
		Team_Member__c tm1 = new Team_Member__c(Is_Active__c = true, User_member__c = user1.Id, Work_Team__c = wt1.Id, UserRoleAPIName__c = 'FAN_Director');
		Database.Insert(tm1);
		tm1.Is_Active__c = false;
		Database.Update(tm1);
		tm1.Is_Active__c = true;
		Database.Update(tm1);
		Database.Delete(tm1);
		wt1.Is_Active__c = false;
		Database.Update(wt1);
		Database.Delete(wt1);

		Test.stopTest();
	}
}