objects/Transaction_History__c.object
<CustomObject>
    <description>The purpose of this object is mainly to track the differents transactions that occurs over Assets object However Could be used as generic transaction object</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>Transaction History Entries</relationshipLabel>
        <relationshipName>Transaction_History_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Descripción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Status__c</fullName>
        <label>New Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscribe_Date__c</fullName>
        <description>Used in Subscription History Record Type (by TechCare)</description>
        <label>Fecha de Alta</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Campo utilizado para identificar si es una suspensión de siniestro o administrativa</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Siniestro</fullName>
                </value>
                <value>
                    <fullName>Administrativa</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction History Entry</label>
    <nameField>
        <label>Transaction_History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction History Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TransactionsHistory.cls
public class TransactionsHistory extends ApplicationDomain {
    public TransactionsHistory(List<Transaction_History__c> transactionsHistory) {
        Super(transactionsHistory);
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain Construct(List<SObject> sObjectList) {
            return new TransactionsHistory(sObjectList);
        } 
    }

    public override void OnApplyDefaults() {
        for (Transaction_History__c transactionHistory : (List<Transaction_History__c>) this.Records) {
            this.ApplyDefaultSubscribeDate(transactionHistory);
        }
    }

    public override void OnAfterInsert() {
        fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.NewInstance();
        Set<Id> suspendedSiniestroIds = new Set<Id>();
        Set<Id> suspendedAdministrativaIds = new Set<Id>();

        for (Transaction_History__c transactionEntry : (List<Transaction_History__c>) this.Records)
            if (transactionEntry.Description__c == 'Reconexión') {
                if (transactionEntry.Type__c == 'Siniestro')
                    suspendedSiniestroIds.Add(transactionEntry.Asset__c);
                else if (transactionEntry.Type__c == 'Administrativa')
                    suspendedAdministrativaIds.Add(transactionEntry.Asset__c);
            }
        
        if (!suspendedSiniestroIds.IsEmpty() || !suspendedAdministrativaIds.IsEmpty())
            this.DeactivateCurrentSuspension(unitOfWork, suspendedSiniestroIds, suspendedAdministrativaIds);
        
        unitOfWork.CommitWork();
    }

    private void ApplyDefaultSubscribeDate(Transaction_History__c transactionHistory) {
        if (transactionHistory.Subscribe_Date__c == null)
            transactionHistory.Subscribe_Date__c = DateTime.Now();
    }

    private void DeactivateCurrentSuspension(fflib_ISObjectUnitOfWork unitOfWork, Set<Id> suspendedSiniestroIds, Set<Id> suspendedAdministrativaIds) {
        Set<Id> suspendedAssetIds = new Set<Id>();
        suspendedAssetIds.AddAll(suspendedSiniestroIds);
        suspendedAssetIds.AddAll(suspendedAdministrativaIds);

        List<Transaction_History__c> activeSuspensions =
            new TransactionsHistorySelector().SelectByAssetIdAndStatus(suspendedAssetIds, 'Active');

        for (Transaction_History__c assetActiveSuspension : activeSuspensions) {
            if (assetActiveSuspension.Type__c == 'Siniestro' && suspendedSiniestroIds.Contains(assetActiveSuspension.Asset__c)) {
                assetActiveSuspension.New_Status__c = 'Inactive';
                unitOfWork.RegisterDirty(assetActiveSuspension);
            }
            else if (assetActiveSuspension.Type__c == 'Administrativa' && suspendedAdministrativaIds.Contains(assetActiveSuspension.Asset__c)) {
                assetActiveSuspension.New_Status__c = 'Inactive';
                unitOfWork.RegisterDirty(assetActiveSuspension);
            }
        }
    }
}