objects/vlocity_cmt__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an Attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>vlocity_cmt__ObjectId__c</fullName>
        <description>ID of the parent object to which the attribute is assigned.</description>
        <externalId>true</externalId>
        <label>Assigned To Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Attribute Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProfileTagsHandlerTest.cls
@isTest
public class ProfileTagsHandlerTest {
	
	@testSetup static void createDataTest() {
		List<vlocity_cmt__AttributeAssignment__c> attributeAssignments = new List<vlocity_cmt__AttributeAssignment__c>();
		vlocity_cmt__AttributeAssignment__c attributeAssignment1 = new vlocity_cmt__AttributeAssignment__c(
			vlocity_cmt__ObjectId__c = '0016C000008eeAoQAI'
		);
		vlocity_cmt__AttributeAssignment__c attributeAssignment2 = new vlocity_cmt__AttributeAssignment__c(
			vlocity_cmt__ObjectId__c = '0016C000008eeAoQAI'
		);
		attributeAssignments.add(attributeAssignment1);
		attributeAssignments.add(attributeAssignment2);
		insert attributeAssignments;
	}

    @isTest static void GetProfileTagsTest() {
        //GIVEN
        String nameMethod = 'GetProfileTags';
        
        Map<String,Object> input = new Map<String,Object>();
        Map<String,Object> output = new Map<String,Object>();
        Map<String,Object> options = new Map<String,Object>();
        
        ProfileTagsHandler ProfileTagsHandler = new ProfileTagsHandler();
        
        //WHEN
        Test.startTest();
        ProfileTagsHandler.invokeMethod(nameMethod, input, output, options);
        Test.stopTest();
        
        //THEN
        System.assertEquals(true,output.containsKey('Categories'));
        List<Map<String,String>> categoriesList = (List<Map<String,String>>) output.get('Categories'); 
        System.assertEquals(false,categoriesList.isEmpty());
    }
}