objects/vlocity_cmt__Attribute__c.object
<CustomObject>
    <description>Represents the definition of an attribute which can be used for profiling, describing or configuring
        items tracked in the database. More specifically:
        1) Attributes are used to profile accounts and contacts to describe their interests, preferences and any other
        information that users desire to track. The same attributes can be used on products, documents and other content
        to describe the target profile of customers who might be interested in them.
        2) Attributes can allow users to filter a list of available and eligible products shown on an opportunity, quote
        or order to those matching some criteria.
        3) Attributes can be used to configure individual characteristics of a product on an opportunity, quote or
        order. For example, the operator may select one of three speeds available on a specific modem.</description>
    <fields>
        <fullName>vlocity_cmt__AttributeCategoryId__c</fullName>
        <description>Parent attribute category. Used for organizing the attributes into groupings.</description>
        <label>Attribute Category</label>
        <referenceTo>vlocity_cmt__AttributeCategory__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <description>Unique code for this attribute.</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DisplaySequence__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Display sequence for this attribute within pick lists.</description>
        <label>Display Sequence</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vlocity Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an Attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>isParentMark__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo para indicar si la marca es a nivel de Cuit / Dni</description>
        <label>isParentMark</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AttributeCategoryId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute Category copied from the attribute at the time the attribute was assigned.</description>
        <label>Attribute Category</label>
        <referenceTo>vlocity_cmt__AttributeCategory__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__AttributeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute assigned to the parent object.</description>
        <label>Attribute</label>
        <referenceTo>vlocity_cmt__Attribute__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Data__c</fullName>
        <description>Additional Data attached to the attribute.</description>
        <label>Data</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DisplaySequence__c</fullName>
        <description>Category display sequence copied from the attribute category at the time the attribute was assigned.</description>
        <label>Category Display Sequence</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectId__c</fullName>
        <description>ID of the parent object to which the attribute is assigned.</description>
        <externalId>true</externalId>
        <label>Assigned To Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RemoveDate__c</fullName>
        <description>Date when the attribute was removed from the account, contact, product or other object.</description>
        <label>Date Removed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__RemovedFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this assignment has been removed from the object.</description>
        <label>Attribute Has Been Removed</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Attribute Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__AttributeCategory__c.object
<CustomObject>
    <description>Vlocity Attribute Categories allow Attributes to be assigned to admin-defined groupings. The Category also identifies some characteristics of the profiling attributes in that grouping.</description>
    <fields>
        <fullName>vlocity_cmt__Code__c</fullName>
        <description>Unique code for this attribute category.</description>
        <label>Code</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DisplaySequence__c</fullName>
        <description>Display sequence of this category in the profile details section.</description>
        <label>Display Sequence</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Vlocity Attribute Category</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attribute Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ta_care_MarksManagement_test.cls
@IsTest
public class ta_care_MarksManagement_test {
	
    @testSetup static void setup() {
        vlocity_cmt__AttributeCategory__c attCategory = new vlocity_cmt__AttributeCategory__c();
		attCategory.name = 'Marks';
		attCategory.vlocity_cmt__Code__c = 'Marks';
		attCategory.vlocity_cmt__DisplaySequence__c = 999;
		insert attCategory;
		
		vlocity_cmt__Attribute__c vAttribute = new vlocity_cmt__Attribute__c();
		vAttribute.name = 'test mark';
		vAttribute.vlocity_cmt__AttributeCategoryId__c = attCategory.id;
		insert vAttribute;
		
		//Id consumerRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Consumer' AND SobjectType = 'Account' LIMIT 1].Id;
		//Id businessRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Business' AND SobjectType = 'Account' LIMIT 1].Id;
		Id consumerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Consumer').getRecordTypeId();
        Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business').getRecordTypeId();
        Account parentAcc = new Account (Name='New Test Parent Account', RecordTypeId = consumerRecordTypeId);
		insert parentAcc;
		Account childAcc = new Account (Name='New Test Child Account', RecordTypeId = businessRecordTypeId, ParentId = parentAcc.Id);
		insert childAcc;
		
		vlocity_cmt__AttributeAssignment__c attrAssignment = new vlocity_cmt__AttributeAssignment__c ();
		attrAssignment.vlocity_cmt__ObjectId__c= childAcc.Id;
		attrAssignment.isParentMark__c = true;
		attrAssignment.vlocity_cmt__AttributeCategoryId__c= attCategory.Id;
        attrAssignment.vlocity_cmt__AttributeId__c = vAttribute.Id;
		attrAssignment.vlocity_cmt__Data__c = 'test att';
		insert attrAssignment;
		
    }
    
    @IsTest static void invoke_getMarks(){
        String methodName = 'getMarks';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
		
        ta_care_MarksManagement marks = new ta_care_MarksManagement();
        
		Test.startTest();
        marks.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();
        
		system.assertNotEquals(null, outMap.get('options'));
    }
	
	@IsTest static void invoke_upsertClientAttributeAssignments(){
		String methodName = 'upsertClientAttributeAssignments';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
		
        ta_care_MarksManagement marks = new ta_care_MarksManagement();
		
		
		vlocity_cmt__Attribute__c Attr = [SELECT id,name FROM vlocity_cmt__Attribute__c WHERE name='test mark'];
		Account accTest = [SELECT Id,name FROM Account WHERE name='New Test Parent Account'];
		Account childAcc = [SELECT Id,name FROM Account WHERE name='New Test Child Account'];
		vlocity_cmt__AttributeCategory__c category = [SELECT Id,name FROM vlocity_cmt__AttributeCategory__c WHERE name='Marks'];
		
		options.put('ContextId',accTest.id);
		
		String body = '{"AttributeId": "'+Attr.id+'","StartDate": "2018-02-14T03:00:00.000Z","EndDate": "2018-02-16T03:00:00.000Z","isParentMark": true,"hasBeenRemoved": false,"CategoryId": "'+category.Id+'","ContextId": "'+accTest.id+'","DaysOfGrace": "","Id": ""}';
		Map<String, Object> responseNode = (Map<String, Object>) JSON.deserializeUntyped(body);
        options.put('AttrAssignment', responseNode);
		

        Test.startTest();
        marks.invokeMethod(methodName, input, outMap, options);
		Test.stopTest();
				
		vlocity_cmt__AttributeAssignment__c attAssig = [SELECT Id,name,vlocity_cmt__ObjectId__c,vlocity_cmt__Data__c FROM vlocity_cmt__AttributeAssignment__c WHERE vlocity_cmt__ObjectId__c =: childAcc.Id AND vlocity_cmt__Data__c !='test att'];
		
        system.assertNotEquals(null,attAssig);
		
	}
	
	@IsTest static void invoke_updateClientAttributeAssignments_update(){
		String methodName = 'updateClientAttributeAssignments';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
		
        ta_care_MarksManagement marks = new ta_care_MarksManagement();
		
		Account accTest = [SELECT Id,name FROM Account WHERE name='New Test Parent Account'];
		vlocity_cmt__Attribute__c Attr = [SELECT id,name FROM vlocity_cmt__Attribute__c WHERE name='test mark'];
		
		options.put('contextId',accTest.id);
		options.put('endDate','2018-02-21T03:00:00.000Z');
		options.put('isDeleted',false);
		options.put('markID',Attr.id);
		
		
		Test.startTest();
        marks.invokeMethod(methodName, input, outMap, options);
		Test.stopTest();
		
        vlocity_cmt__AttributeAssignment__c attAssig = [SELECT id,name,isParentMark__c,vlocity_cmt__ObjectId__c,vlocity_cmt__AttributeId__c,vlocity_cmt__Data__c,vlocity_cmt__RemoveDate__c FROM vlocity_cmt__AttributeAssignment__c WHERE vlocity_cmt__Data__c='test att'];
		
        string s = string.valueOfGmt(attAssig.vlocity_cmt__RemoveDate__c);

		system.assertEquals('2018-02-21 00:00:00',string.valueOfGmt(attAssig.vlocity_cmt__RemoveDate__c));
	}
    
    @IsTest static void invoke_updateClientAttributeAssignments_delete(){
    	String methodName = 'updateClientAttributeAssignments';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
		
        ta_care_MarksManagement marks = new ta_care_MarksManagement();
		
		Account accTest = [SELECT Id,name FROM Account WHERE name='New Test Parent Account'];
		vlocity_cmt__Attribute__c Attr = [SELECT id,name FROM vlocity_cmt__Attribute__c WHERE name='test mark'];
		
		options.put('contextId',accTest.id);
		options.put('isDeleted',true);
		options.put('markID',Attr.id);
		
		Test.startTest();
        marks.invokeMethod(methodName, input, outMap, options);
		Test.stopTest();
        
        vlocity_cmt__AttributeAssignment__c attAssig = [SELECT id,name,isParentMark__c,vlocity_cmt__ObjectId__c,vlocity_cmt__AttributeId__c,vlocity_cmt__Data__c,vlocity_cmt__RemoveDate__c,vlocity_cmt__RemovedFlag__c FROM vlocity_cmt__AttributeAssignment__c WHERE vlocity_cmt__Data__c='test att'];
        
        system.assertEquals(true,attAssig.vlocity_cmt__RemovedFlag__c);
    }
    
    @IsTest static void invoke_setFraudAndValidAssetForContextIdAndAccountID(){
    	String methodName = 'setFraudAndValidAssetForContextIdAndAccountID';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
		
        ta_care_MarksManagement marks = new ta_care_MarksManagement();
		
		Account childAcc = [SELECT Id,name FROM Account WHERE name='New Test Child Account'];
        
        String body = '{"Marks":{"Name": "Dias de Gracia"},"ActiveAssets": false,"Name": "test account 1","AccountId": "'+childAcc.Id+'","Fraud": false}';
		List<Map<String, Object>> responseNode = new List<Map<String, Object>>();
        responseNode.add((Map<String, Object>)JSON.deserializeUntyped(body));
        
        options.put('BillingAccounts', responseNode);
		options.put('accountId',childAcc.Id);
		options.put('numberArray',2);

        Test.startTest();
        marks.invokeMethod(methodName, input, outMap, options);
		Test.stopTest();
        
        system.assertEquals(true,outMap.get('AccountIdExist'));
    }
}