objects/vlocity_cmt__Attribute__c.object
<CustomObject>
    <description>Represents the definition of an attribute which can be used for profiling, describing or configuring
        items tracked in the database. More specifically:
        1) Attributes are used to profile accounts and contacts to describe their interests, preferences and any other
        information that users desire to track. The same attributes can be used on products, documents and other content
        to describe the target profile of customers who might be interested in them.
        2) Attributes can allow users to filter a list of available and eligible products shown on an opportunity, quote
        or order to those matching some criteria.
        3) Attributes can be used to configure individual characteristics of a product on an opportunity, quote or
        order. For example, the operator may select one of three speeds available on a specific modem.</description>
    <fields>
        <fullName>vlocity_cmt__ActiveFlg__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the attribute is active. Only active attributes can be assigned.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Vlocity Attribute</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an Attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>vlocity_cmt__AttributeId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the Vlocity Attribute assigned to the parent object.</description>
        <label>Attribute</label>
        <referenceTo>vlocity_cmt__Attribute__c</referenceTo>
        <relationshipLabel>Attribute Assignments</relationshipLabel>
        <relationshipName>AttributeAssignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsActiveAssignment__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates if the attribute assignment is active.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Attribute Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AttributeTriggers.cls
public class AttributeTriggers {

	public static void ValidateAssignments(){

		Set<Id> deleted = new Set<Id>();

		if(trigger.isDelete){
            deleted = Trigger.NewMap.keySet();
            
		}else{
			for(vlocity_cmt__Attribute__c attributeNew : (List<vlocity_cmt__Attribute__c>)Trigger.New){
                vlocity_cmt__Attribute__c attributeOld = (vlocity_cmt__Attribute__c)Trigger.OldMap.get(attributeNew.Id);
                if(attributeOld.vlocity_cmt__ActiveFlg__c && !attributeNew.vlocity_cmt__ActiveFlg__c){
                    deleted.add(attributeNew.Id);
                }
			}	
		}
		List<vlocity_cmt__attributeAssignment__c> assignments = [SELECT Id, vlocity_cmt__AttributeId__c FROM vlocity_cmt__attributeAssignment__c
																  WHERE vlocity_cmt__AttributeId__c IN :deleted
																  	AND vlocity_cmt__IsActiveAssignment__c = true];
		
        for(vlocity_cmt__attributeAssignment__c assignment : assignments){
            Trigger.NewMap.get(assignment.vlocity_cmt__AttributeId__c).addError(Label.ErrorAttributeDeleted);
        }
        
	}
}