objects/vlocity_cmt__PaymentMethod__c.object
<CustomObject>
    <description>Payment Method stores credit card or other payment processing information for an account.</description>
    <fields>
        <fullName>vlocity_cmt__AccountId__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__MethodType__c</fullName>
        <label>Method Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1001</fullName>
                    <default>true</default>
                    <label>Efectivo</label>
                </value>
                <value>
                    <fullName>1201</fullName>
                    <label>Debito a Proxima Factura</label>
                </value>
                <value>
                    <fullName>2001</fullName>
                    <label>Tarjeta de Credito</label>
                </value>
                <value>
                    <fullName>Transferencia Bancaria</fullName>
                </value>
                <value>
                    <fullName>4002</fullName>
                    <label>Tarjeta de Debito</label>
                </value>
                <value>
                    <fullName>9998</fullName>
                    <label>Descuento de Saldo</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Method Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ManagePaymentMethods_test.cls
@isTest
public class ManagePaymentMethods_test {
    
    @isTest
    static void testUpdateStatusCard(){
        String methodName = 'updateStatusCard';

        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        
        Account acc = new Account(Name = 'test');
		insert acc;
		vlocity_cmt__PaymentMethod__c paymentMethodForTest = 
            new vlocity_cmt__PaymentMethod__c(vlocity_cmt__AccountId__c = acc.Id,
                                             vlocity_cmt__MethodType__c = 'Tarjeta de Credito');
        insert paymentMethodForTest;
        input.put('PaymentId', paymentMethodForTest.Id);
        
        Test.startTest();
        ManagePaymentMethods classToBeTested = new ManagePaymentMethods();
        classToBeTested.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();

    }
    
    @isTest
    static void testGetAccountIdUpdate(){
        String methodName = 'getAccountId';
        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        Map<String, Object> automaticDebitAction = new Map<String, Object>();
        automaticDebitAction.put('SelectedAutomaticDebitAction', 'Update');
        input.put('AutomaticDebitAction', automaticDebitAction);
        Account acc = new Account(Name = 'test');
		insert acc;
        
        input.put('BillingAccountToResponse', acc.Id);

        ManagePaymentMethods classToBeTested = new ManagePaymentMethods();

        Test.startTest();
        classToBeTested.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();
    }
    
    @isTest
    static void testGetAccountId(){
        String methodName = 'getAccountId';
        Map<String, Object> input = new Map<String, Object>();
        Map<String, Object> outMap = new Map<String, Object>();
        Map<String, Object> options = new Map<String, Object>();
        Map<String, Object> automaticDebitAction = new Map<String, Object>();
        automaticDebitAction.put('SelectedAutomaticDebitAction', '');
        input.put('AutomaticDebitAction', automaticDebitAction);
        Account acc = new Account(Name = 'test');
		insert acc;
		Map<String, Object> BillingAccounts = new Map<String, Object>();
		BillingAccounts.put('1', acc);
        
        input.put('BillingAccounts', BillingAccounts);

        ManagePaymentMethods classToBeTested = new ManagePaymentMethods();

        Test.startTest();
        classToBeTested.invokeMethod(methodName, input, outMap, options);
        Test.stopTest();
    }

}