objects/vlocity_cmt__AttributeAssignment__c.object
<CustomObject>
    <description>The assignment of an Attribute to an object such as an Account, Contact or Product. Product attributes define the default configuration for the product to which they are assigned.</description>
    <fields>
        <fullName>vlocity_cmt__AttributeName__c</fullName>
        <description>DEPRECATED. Formula: Value of the Name field from the assigned attribute.</description>
        <formula>vlocity_cmt__AttributeId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__CategoryName__c</fullName>
        <description>Formula: Value of the Attribute Category Name field based on the copied Attribute Category ID.</description>
        <formula>vlocity_cmt__AttributeCategoryId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribute Category Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ObjectId__c</fullName>
        <description>ID of the parent object to which the attribute is assigned.</description>
        <externalId>true</externalId>
        <label>Assigned To Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Attribute Assignment</label>
    <nameField>
        <label>Attribute Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProfileTagsHandler.cls
global with sharing class ProfileTagsHandler implements vlocity_cmt.VlocityOpenInterface {

    global Boolean invokeMethod(String methodName, Map<String,Object> inputMap, Map<String,Object> outMap, Map<String,Object> options) {
        Boolean result = true;

        try {
            if (methodName.equals('GetProfileTags')) {
                GetProfileTags(inputMap, outMap);
            }
            result = false;  
        } 
        catch (Exception e) {
            System.debug('ProfileTagsHandler:invokeMethod -> exception: ' + e);
            result = false;
        }

        return result;
    }

    void GetProfileTags(Map<String,Object> inputMap, Map<String, Object> outMap) {
        String accountId = (String) inputMap.get('id');

        String query = 'SELECT Id, vlocity_cmt__AttributeName__c, vlocity_cmt__CategoryName__c FROM vlocity_cmt__AttributeAssignment__c WHERE (vlocity_cmt__ObjectId__c = \'0016C000008eeAoQAI\') ORDER BY vlocity_cmt__CategoryName__c';

        List<vlocity_cmt__AttributeAssignment__c> profileTags = Database.query(query);

        List<Map<String, String>> categoriesList = new List<Map<String, String>>();
        List<Map<String, String>> attributesList = new List<Map<String, String>>();

        Boolean firstTime = true;
        String categoryName;

        for (vlocity_cmt__AttributeAssignment__c profileTag : profileTags) {
            Map<String, String> categoryTempMap = new Map<String, String>();

            if (firstTime) {
                firstTime = false;
                categoryTempMap.put('Name', profileTag.vlocity_cmt__CategoryName__c);
                categoriesList.add(categoryTempMap);
                categoryName = profileTag.vlocity_cmt__CategoryName__c; 
            }

            if (categoryName != profileTag.vlocity_cmt__CategoryName__c) {
                categoryTempMap.put('Name', profileTag.vlocity_cmt__CategoryName__c);
                categoriesList.add(categoryTempMap);
                categoryName = profileTag.vlocity_cmt__CategoryName__c;
            }
        }

        outMap.put('Categories', categoriesList);
    }  
}