objects/vlocity_cmt__OrchestrationItem__c.object
<CustomObject>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Orchestration Item</label>
    <nameField>
        <label>Orchestration Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orchestration Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LoggingSystemInterface.cls
global virtual class LoggingSystemInterface extends vlocity_cmt.DefaultSystemInterface
{    
    global virtual override String generatePayload(vlocity_cmt__OrchestrationItem__c item, vlocity_cmt.XOMOrderDomainObject orderObj)
    {
        System.debug('item: '+item + 'orderOBJ' + orderObj);
        String request = super.generatePayload(item, orderObj);
        System.debug('request: ' + request);
        if (request != null)
        {
          item.request__c = JSON.serializePretty(JSON.deserializeUntyped(request));
        }
        System.debug('item.request__C' + item.request__c);
        return request;
    }
    
    global virtual override void processResponse(vlocity_cmt__OrchestrationItem__c item, String url, String path, vlocity_cmt.XOMOrderDomainObject orderObj, HttpResponse res)
    {
        String response = res.getBody();
        System.debug('processResponse - response' + response);
        if (response != null)
        {
          item.response__c = JSON.serializePretty(JSON.deserializeUntyped(response));
        }
        
        super.processResponse(item, url, path, orderObj, res);
    }    
}