objects/vlocity_cmt__VlocityAction__c.object
<CustomObject>
    <label>Vlocity Action</label>
    <nameField>
        <label>Vlocity Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Work_Team_Permission__c.object
<CustomObject>
    <description>Store the permission set, queues and user roles assigned to a work team, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the permission is active or not for the work team.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_Set_API_Name__c</fullName>
        <description>Used to store the API Name of a permission set assigned to a work team.</description>
        <externalId>true</externalId>
        <label>Permission Set API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a permission with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Permissions</relationshipLabel>
        <relationshipName>Work_Team_Permissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Permission</label>
    <nameField>
        <displayFormat>WTP-{0000}</displayFormat>
        <label>Work Team Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkteamLevel__c</fullName>
        <label>Workteam Level</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/taSecurityMamageCrossedTeamMembersCtrl.cls
public with sharing class taSecurityMamageCrossedTeamMembersCtrl {
    Public  Id vlcActionId {get; set;}
    Public String vlcActionName {get; set;}
    Public Id permissionId {get; set;}
    Public Id workTeamId {get; set;}
    Public String workTeamName {get; set;}

    @RemoteAction
    public static String getWorkTeamsByParentId(String rootFlag, String vlocityAction, String teamId){
    	String jsonChilds;
    	List<workTeamWrapper> tmrList = new List<workTeamWrapper>();
    	Set<Id> workTeamsSet = new Set<Id>();
    	String parent;
    	//Id parentId = Id.valueOf(teamId);

    	system.debug('vlocityAction: '+vlocityAction);
    	system.debug('rootFlag: '+rootFlag);
    	system.debug('teamId: '+teamId);

    	if(rootFlag == '#'){
	        List<vlocity_cmt__VlocityAction__c> lstQueryVlcName = [SELECT Id, ApplicablePermissionSet__c  
	                                                               FROM vlocity_cmt__VlocityAction__c
	                                                               WHERE Id = :vlocityAction
	                                                               LIMIT 1 ];


	        system.debug('lstQueryVlcName: ' + lstQueryVlcName);

			List<workteam__c> workTeams = [SELECT Id, Team_name__c FROM Workteam__c WHERE Parent_Team__c  = :teamId AND Is_Active__c = true AND WorkteamLevel__c != null];

			for(workteam__c w : workTeams){
				workTeamsSet.add(w.Id);
			}

			system.debug('workTeamsSet: ' + workTeamsSet);

	        List<Work_Team_Permission__c> wtpResult = [SELECT Id, Work_Team__c, RecordTypeId, Permission_Set_API_Name__c, Is_Active__c
	                                                   FROM  Work_Team_Permission__c 
	                                                   WHERE Work_Team__c IN :workTeamsSet 
	                                                   AND Permission_Set_API_Name__c = :lstQueryVlcName[0].ApplicablePermissionSet__c ]; 

	        system.debug('wtpResult: ' + wtpResult);

			for(workteam__c wt : workTeams){
				for(Work_Team_Permission__c wtp : wtpResult){
					if(workTeamsSet.contains(wtp.Work_Team__c)){
						if(wtp.Work_team__c == wt.Id){
				            workTeamWrapper wtr = new workTeamWrapper();
				            wtr.id = wt.id;
				            wtr.text = wt.Team_name__c;
				            wtr.parent = '#';
				            wtr.children = true;
				            if(wtp.Is_Active__c){
				            	Map<String, boolean> workTeamState = new Map<String, boolean>();
				            	workTeamState.put('selected', true);
				            	wtr.state = workTeamState;
				            }
				            tmrList.add(wtr);
						}
					}else{
		            	workTeamWrapper wtr = new workTeamWrapper();
			            wtr.id = wt.id;
			            wtr.text = wt.Team_name__c;
			            wtr.parent = '#';
			            wtr.children = true;
		            	Map<String, boolean> workTeamState = new Map<String, boolean>();
		            	workTeamState.put('selected', false);
		            	wtr.state = workTeamState;
			            tmrList.add(wtr);						
					}
				}
			}
    	}else{
        	List<vlocity_cmt__VlocityAction__c> lstQueryVlcName = [SELECT Id, ApplicablePermissionSet__c  
	                                                               FROM vlocity_cmt__VlocityAction__c
	                                                               WHERE Id = :vlocityAction
	                                                               LIMIT 1 ];


	        system.debug('lstQueryVlcName: ' + lstQueryVlcName);

			List<workteam__c> workTeams = [SELECT Id, Team_name__c FROM Workteam__c WHERE Parent_Team__c  = :rootFlag AND Is_Active__c = true AND WorkteamLevel__c != null];

			for(workteam__c w : workTeams){
				workTeamsSet.add(w.Id);
			}

			system.debug('workTeamsSet: ' + workTeamsSet);

	        List<Work_Team_Permission__c> wtpResult = [SELECT Id, Work_Team__c, RecordTypeId, Permission_Set_API_Name__c, Is_Active__c
	                                                   FROM  Work_Team_Permission__c 
	                                                   WHERE Work_Team__c IN :workTeamsSet 
	                                                   AND Permission_Set_API_Name__c = :lstQueryVlcName[0].ApplicablePermissionSet__c ]; 

	        system.debug('wtpResult: ' + wtpResult);

			for(workteam__c wt : workTeams){
				for(Work_Team_Permission__c wtp : wtpResult){
					if(workTeamsSet.contains(wtp.Work_Team__c)){
						if(wtp.Work_team__c == wt.Id){
				            workTeamWrapper wtr = new workTeamWrapper();
				            wtr.id = wt.id;
				            wtr.text = wt.Team_name__c;
				            wtr.parent = rootFlag;
				            wtr.children = true;
				            if(wtp.Is_Active__c){
				            	Map<String, boolean> workTeamState = new Map<String, boolean>();
				            	workTeamState.put('selected', true);
				            	wtr.state = workTeamState;
				            }
				            tmrList.add(wtr);
						}
					}else{
			            workTeamWrapper wtr = new workTeamWrapper();
			            wtr.id = wt.id;
			            wtr.text = wt.Team_name__c;
			            wtr.parent = rootFlag;
			            wtr.children = true;
		            	Map<String, boolean> workTeamState = new Map<String, boolean>();
		            	workTeamState.put('selected', false);
		            	wtr.state = workTeamState;

			            tmrList.add(wtr);				
					}
				}
			}
    	}

		system.debug(JSON.serialize(tmrList));
		return JSON.serialize(tmrList);
	}

    public class workTeamWrapper{
        public id id {get;set;}
        public String text {get;set;}
        public String parent {get;set;}
        public boolean children {get;set;}
        public Map<String, boolean> state {get;set;}
    }
}