objects/vlocity_cmt__VlocityTrackingEntry__c.object
<CustomObject>
    <fields>
        <fullName>TrackedAction__c</fullName>
        <label>TrackedAction</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity Tracking Entry</label>
    <nameField>
        <label>Vlocity Tracking Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Tracking Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TrackingEntryClassTest.cls
@IsTest
public class TrackingEntryClassTest {
   @IsTest static void trakingEntrys(){
        
       Id ownerIdTest = UserInfo.getUserId(); 
       Test.startTest();
        vlocity_cmt__VlocityTrackingEntry__c TrackingEntry = new vlocity_cmt__VlocityTrackingEntry__c(Name = 'Test Campaign ',TrackedAction__c = 'Consulta de Comprobante',OwnerId = ownerIdTest);
        insert TrackingEntry;
		Test.stopTest();
		
		system.assertEquals('Consulta de Comprobante', TrackingEntry.TrackedAction__c);
		
   }
}