objects/vlocity_cmt__VlocityAction__c.object
<CustomObject>
    <fields>
        <fullName>vlocity_cmt__DisplayLabel__c</fullName>
        <label>Display Label</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vlocity Action</label>
    <nameField>
        <label>Vlocity Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Work_Team_Permission__c.object
<CustomObject>
    <description>Store the permission set, queues and user roles assigned to a work team, this object is used to handle the security.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to indicate if the permission is active or not for the work team.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Permission_Set_API_Name__c</fullName>
        <description>Used to store the API Name of a permission set assigned to a work team.</description>
        <externalId>true</externalId>
        <label>Permission Set API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Team__c</fullName>
        <description>This field is used to store the assignation of a permission with a work team that it belongs to.</description>
        <label>Work Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Work Team Permissions</relationshipLabel>
        <relationshipName>Work_Team_Permissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Team Permission</label>
    <nameField>
        <displayFormat>WTP-{0000}</displayFormat>
        <label>Work Team Permission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Team Permissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PFTA-8791 - Used to indicate if the work team is active or not.</description>
        <label>Is Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <description>Stores the name of the division (team).</description>
        <externalId>true</externalId>
        <label>Team Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WorkteamLevel__c</fullName>
        <label>Workteam Level</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/assignmentSecurityProcessTest.cls
@isTest(SeeAllData=true)
private class assignmentSecurityProcessTest {	
    @isTest 
    static void testGetHierarchyWorkTeam() {        
        WorkTeam__c[] teams = [SELECT 
                                Id, Team_Name__c, Parent_Team__c, WorkTeamLevel__c                                         
                                FROM WorkTeam__c 
                                WHERE Is_Active__c = true AND WorkteamLevel__c = 1 AND Team_Name__c = 'Aegis'
                                LIMIT 1] ;

		List<vlocity_cmt__VlocityAction__c> lstQueryName = [SELECT Id, vlocity_cmt__DisplayLabel__c 
														  	FROM vlocity_cmt__VlocityAction__c
                                                            WHERE vlocity_cmt__DisplayLabel__c = 'Anulación de Ordenes'
															LIMIT 1 ];

        Set<Id> teamSetIds = WorkTeamHierarchyNode.getSetWorkTeamIds(teams);

        List<Work_Team_Permission__c> wtpResult = [SELECT 
                                                        Id, Work_Team__c, RecordTypeId, Permission_Set_API_Name__c, Is_Active__c
                                                    FROM 
                                                        Work_Team_Permission__c 
                                                    WHERE 
                                                        Work_Team__c IN :teamSetIds 
                                                        AND Permission_Set_API_Name__c = :lstQueryName[0].ApplicablePermissionSet__c ];                                

        Id vlcActionId = lstQueryName[0].Id;
        String vlcActionName = lstQueryName[0].vlocity_cmt__DisplayLabel__c;
        Id workTeamId = teams[0].Id;
        String workTeamName = teams[0].Team_Name__c;

        List<WorkTeamHierarchyNode> lstResult = assignmentProcessByWorkTeamController.getHierarchyWorkTeam(String.valueOf(workTeamId), String.valueOf(vlcActionId), lstQueryName[0].ApplicablePermissionSet__c);
        system.assert(true, lstResult.size() > 0);
    }

    @isTest
    static void testGetPermissionAsigmentResult() {
        WorkTeam__c[] teams = [SELECT 
                                Id, Team_Name__c, Parent_Team__c, WorkTeamLevel__c                                         
                                FROM WorkTeam__c 
                                WHERE Is_Active__c = true AND WorkteamLevel__c = 1 AND Team_Name__c = 'Aegis'
                                LIMIT 1] ;
        
		List<vlocity_cmt__VlocityAction__c> lstQueryName = [SELECT Id, vlocity_cmt__DisplayLabel__c 
														  	FROM vlocity_cmt__VlocityAction__c
                                                            WHERE vlocity_cmt__DisplayLabel__c = 'Anulación de Ordenes'
															LIMIT 1 ];
                                    
        Id vlcActionId = lstQueryName[0].Id;
        String vlcActionName = lstQueryName[0].vlocity_cmt__DisplayLabel__c;
        Id workTeamId = teams[0].Id;
        String workTeamName = teams[0].Team_Name__c;
        List<String> selectedTeams = new List<String>();
        selectedTeams.add(workTeamId);
        selectedTeams.add(workTeamId);

        Boolean result = assignmentProcessByWorkTeamController.getPermissionAsigmentResult((String)workTeamId, (String)vlcActionId, vlcActionName, selectedTeams); 

        system.assert(true, result);
    }
    
    @isTest
    static void testGetPermissionAsigmentExistResult() {
        WorkTeam__c[] teams = [SELECT 
                                Id, Team_Name__c, Parent_Team__c, WorkTeamLevel__c                                         
                                FROM WorkTeam__c 
                                WHERE Is_Active__c = true AND WorkteamLevel__c = 1 AND Team_Name__c = 'Aegis'
                                LIMIT 1] ;
        
		List<vlocity_cmt__VlocityAction__c> lstQueryName = [SELECT Id, vlocity_cmt__DisplayLabel__c 
														  	FROM vlocity_cmt__VlocityAction__c
                                                            WHERE vlocity_cmt__DisplayLabel__c = 'Anulación de Ordenes'
															LIMIT 1 ];
                                    
        Id vlcActionId = lstQueryName[0].Id;
        String vlcActionName = lstQueryName[0].vlocity_cmt__DisplayLabel__c;
        Id workTeamId = teams[0].Id;
        String workTeamName = teams[0].Team_Name__c;
        List<String> selectedTeams = new List<String>();
        selectedTeams.add(workTeamId);
        selectedTeams.add(workTeamId);

        Boolean result = assignmentProcessByWorkTeamController.getPermissionAsigmentResult((String)workTeamId, (String)vlcActionId, vlcActionName, selectedTeams); 

        system.assert(true, result);
    }    
}