objects/vlocity_cmt__DRMapItem__c.object
<CustomObject>
    <description>The Vlocity DataRaptor mapping item describes the transformation of one attribute from the source interface to a target attribute in the target interface or data object.</description>
    <fields>
        <fullName>vlocity_cmt__DomainObjectAPIName__c</fullName>
        <label>Domain Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DomainObjectCreationOrder__c</fullName>
        <label>Domain Object Creation Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__DomainObjectFieldAPIName__c</fullName>
        <label>Domain Object Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__InterfaceFieldAPIName__c</fullName>
        <label>Interface Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__InterfaceObjectName__c</fullName>
        <label>Interface Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vlocity DataRaptor Map Item</label>
    <nameField>
        <label>Map Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity DataRaptor Map Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/vlocity_cmt__Element__c.object
<CustomObject>
    <description>Vlocity OmniScript Elements are the components which make up an OmniScript.</description>
    <fields>
        <fullName>vlocity_cmt__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__OmniScriptId__c</fullName>
        <label>OmniScript</label>
        <referenceTo>vlocity_cmt__OmniScript__c</referenceTo>
        <relationshipName>Elements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ParentElementId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Element</label>
        <referenceTo>vlocity_cmt__Element__c</referenceTo>
        <relationshipName>Elements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PropertySet__c</fullName>
        <label>Property Set</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aggregate</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Calculation Action</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>DataRaptor Extract Action</fullName>
                </value>
                <value>
                    <fullName>DataRaptor Post Action</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Date/Time (Local)</fullName>
                </value>
                <value>
                    <fullName>Disclosure</fullName>
                </value>
                <value>
                    <fullName>DocuSign Envelope Action</fullName>
                </value>
                <value>
                    <fullName>DocuSign Signature Action</fullName>
                </value>
                <value>
                    <fullName>Done Action</fullName>
                </value>
                <value>
                    <fullName>Email Action</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>File</fullName>
                </value>
                <value>
                    <fullName>Filter</fullName>
                </value>
                <value>
                    <fullName>Filter Block</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Geolocation</fullName>
                </value>
                <value>
                    <fullName>Headline</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Input Block</fullName>
                </value>
                <value>
                    <fullName>Line Break</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Multi-select</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>OmniScript</fullName>
                </value>
                <value>
                    <fullName>Password</fullName>
                </value>
                <value>
                    <fullName>PDF Action</fullName>
                </value>
                <value>
                    <fullName>Remote Action</fullName>
                </value>
                <value>
                    <fullName>Integration Procedure Action</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Vlocity OmniScript Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity OmniScript Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/vlocity_cmt__OmniScript__c.object
<CustomObject>
    <description>Represents a Vlocity OmniScript. Each Vlocity OmniScript is a declarative script that defines a task-based, guided user process enabling users to get work done efficiently and effectively. OmniScripts can be configured to pull data from Salesforce or any other data source via business services and can execute any business service to launch and interact with server-side business process engines.</description>
    <fields>
        <fullName>vlocity_cmt__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please do not manually modify this field.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__IsProcedure__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsProcedure</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__ProcedureKey__c</fullName>
        <externalId>true</externalId>
        <label>Procedure Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__PropertySet__c</fullName>
        <label>Property Set</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Licensing &amp; Permitting</fullName>
                </value>
                <value>
                    <fullName>Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_cmt__Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Vlocity OmniScript</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vlocity OmniScript</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Components.cls
global with sharing class Components {
    
    private static Map<String, List<DRInfo>> drExtract;
    private static Map<String, List<DRInfo>> drLoad;
    private static Map<String, Id> classesMap;
    
    @AuraEnabled
    public static List<vlocity_cmt__OmniScript__c> OSList(){
        List<vlocity_cmt__OmniScript__c> omniscriptList = [SELECT Id, Name, vlocity_cmt__Version__c, vlocity_cmt__IsProcedure__c
                                                           FROM vlocity_cmt__OmniScript__c 
                                                           ORDER BY Name, vlocity_cmt__Version__c DESC];
        return omniscriptList;
    }
    
    @AuraEnabled
    public static List<Element> OSElement(String omniscriptId){
        classesMap = getClass();
        drExtract = dataRaptorExtract();
        drLoad = dataRaptorLoad();
        Map<String, List<Element>> IPElementsMap = IPElement();
        List<Element> elementList = new List<Element>();
        for (vlocity_cmt__Element__c e : [SELECT 
                                          	Id, Name, vlocity_cmt__Type__c, vlocity_cmt__ParentElementId__c, vlocity_cmt__PropertySet__c, 
                                          	vlocity_cmt__Active__c, vlocity_cmt__OmniScriptId__r.Name 
                                          FROM vlocity_cmt__Element__c 
                                          WHERE vlocity_cmt__OmniScriptId__c = :omniscriptId
                                          ORDER BY vlocity_cmt__Order__c]) {
            Element el = new Element();
            el.elementId = e.Id;
            el.elementName = e.Name;
            el.elementType = e.vlocity_cmt__Type__c;
            el.parentElementId = e.vlocity_cmt__ParentElementId__c;
            el.elementStatus = e.vlocity_cmt__Active__c;
            Map<String, Object> propertyMap = (Map<String, Object>)JSON.deserializeUntyped(e.vlocity_cmt__PropertySet__c);
            if(e.vlocity_cmt__Type__c.equalsIgnoreCase('DataRaptor Extract Action')) {
                if (drExtract.containsKey(String.valueOf(propertyMap.get('bundle')))) {
                    el.elementDR = drExtract.get(String.valueOf(propertyMap.get('bundle')));
                }
            } else if (e.vlocity_cmt__Type__c.equalsIgnoreCase('DataRaptor Post Action')) {
                if (drLoad.containsKey(String.valueOf(propertyMap.get('bundle')))) {
                    el.elementDR = drLoad.get(String.valueOf(propertyMap.get('bundle')));
                }
            }
            if (e.vlocity_cmt__Type__c.contains('Remote Action')) {
                String className = String.valueOf(propertyMap.get('remoteClass'));
                if(className.contains('vlocity_cmt.')) className = className.remove('vlocity_cmt.');
                if (classesMap.containsKey(className)) {
                    el.className = className;
                    el.classId = classesMap.get(className);
                }
            }
            if (e.vlocity_cmt__Type__c == 'Integration Procedure Action') {
                if (IPElementsMap.containsKey(String.valueOf(propertyMap.get('integrationProcedureKey')))) {
                    List<Element> elementIP = IPElementsMap.get(String.valueOf(propertyMap.get('integrationProcedureKey')));
                    for (Element IPel : elementIP) {
                        IPel.elementName += ' ( Integration Procedure ) > ' + propertyMap.get('integrationProcedureKey') ;
                        elementList.add(IPel);
                    }
                }
            }
            elementList.add(el);
        }
        return elementList;
    }
    
    @AuraEnabled
    public static Map<String, List<DRInfo>> dataRaptorExtract(){
        Map<String, List<DRInfo>> drElements = new Map<String, List<DRInfo>>();
        for (vlocity_cmt__DRMapItem__c drItemList : [SELECT vlocity_cmt__InterfaceFieldAPIName__c, vlocity_cmt__InterfaceObjectName__c, Name 
                                                     FROM vlocity_cmt__DRMapItem__c 
                                                     ORDER BY vlocity_cmt__DomainObjectCreationOrder__c]){
			DRInfo info = new DRInfo();
            info.fieldName = drItemList.vlocity_cmt__InterfaceFieldAPIName__c;
            info.objectName = drItemList.vlocity_cmt__InterfaceObjectName__c;
            if (drElements.containsKey(drItemList.Name)) {
                drElements.get(drItemList.Name).add(info);
            } else {
                List<DRInfo> infoList = new List<DRInfo>();
                infoList.add(info);
                drElements.put(drItemList.Name, infoList);
            }
                                                         
		}
        return drElements;
    }
    
    @AuraEnabled
    public static Map<String, List<DRInfo>> dataRaptorLoad(){
        Map<String, List<DRInfo>> drElements = new Map<String, List<DRInfo>>();
        for (vlocity_cmt__DRMapItem__c drItemList : [SELECT vlocity_cmt__DomainObjectAPIName__c,vlocity_cmt__DomainObjectFieldAPIName__c,Name 
                                                     FROM vlocity_cmt__DRMapItem__c]){
            DRInfo info = new DRInfo();
            info.fieldName = drItemList.vlocity_cmt__DomainObjectFieldAPIName__c;
            info.objectName = drItemList.vlocity_cmt__DomainObjectAPIName__c;
            if (drElements.containsKey(drItemList.Name)) {
                drElements.get(drItemList.Name).add(info);
            } else {
                List<DRInfo> infoList = new List<DRInfo>();
                infoList.add(info);
                drElements.put(drItemList.Name, infoList);
            }
        }
        return drElements;
    }
    
    private static Set<Id> IPSet(){
        Set<Id> idIPSet = new Set<Id>();
        for (vlocity_cmt__OmniScript__c os : [SELECT Id, Name, vlocity_cmt__Version__c 
                                              FROM vlocity_cmt__OmniScript__c 
                                              WHERE vlocity_cmt__IsActive__c = true 
                                              	AND vlocity_cmt__IsProcedure__c = true 
                                              ORDER BY Name, vlocity_cmt__Version__c DESC]) {
            idIPSet.add(os.Id);
        }
        return idIPSet;
    }
    
    private static Map<String, List<Element>> IPElement(){
        Set<Id> idIPSet = IPSet();
        Map<String, List<Element>> elementMap = new Map<String, List<Element>>();
        for (vlocity_cmt__Element__c e : [SELECT 
                                          	Id, Name, vlocity_cmt__Type__c, vlocity_cmt__ParentElementId__c, vlocity_cmt__PropertySet__c, 
                                          	vlocity_cmt__Active__c, vlocity_cmt__OmniScriptId__c, vlocity_cmt__OmniScriptId__r.vlocity_cmt__ProcedureKey__c 
                                          FROM vlocity_cmt__Element__c 
                                          WHERE vlocity_cmt__OmniScriptId__c IN :idIPSet 
                                          ORDER BY vlocity_cmt__Order__c]) {
            Element el = new Element();
            el.elementId = e.Id;
            el.elementName = e.Name;
            el.elementType = e.vlocity_cmt__Type__c;
            el.parentElementId = e.vlocity_cmt__ParentElementId__c;
            el.elementStatus = e.vlocity_cmt__Active__c;
            Map<String, Object> propertyMap = (Map<String, Object>)JSON.deserializeUntyped(e.vlocity_cmt__PropertySet__c);
            if(e.vlocity_cmt__Type__c.equalsIgnoreCase('DataRaptor Extract Action')) {
                if (drExtract.containsKey(String.valueOf(propertyMap.get('bundle')))) {
                    el.elementDR = drExtract.get(String.valueOf(propertyMap.get('bundle')));
                }
            } else if (e.vlocity_cmt__Type__c.equalsIgnoreCase('DataRaptor Post Action')) {
                if (drLoad.containsKey(String.valueOf(propertyMap.get('bundle')))) {
                    el.elementDR = drLoad.get(String.valueOf(propertyMap.get('bundle')));
                }
            }
            if (e.vlocity_cmt__Type__c.contains('Remote Action')) {
                String className = String.valueOf(propertyMap.get('remoteClass'));
                if(className.contains('vlocity_cmt.')) className = className.remove('vlocity_cmt.');
                if (classesMap.containsKey(className)) {
                    el.className = className;
                    el.classId = classesMap.get(className);
                }
            }
            if (elementMap.containsKey(e.vlocity_cmt__OmniScriptId__r.vlocity_cmt__ProcedureKey__c)) {
                elementMap.get(e.vlocity_cmt__OmniScriptId__r.vlocity_cmt__ProcedureKey__c).add(el);
            } else {
                List<Element> elementList = new List<Element>();
                elementList.add(el);
                elementMap.put(e.vlocity_cmt__OmniScriptId__r.vlocity_cmt__ProcedureKey__c, elementList);
            }
        }
        return elementMap;
    }
    
    private static Map<String, Id> getClass() {
        Map<String, Id> classMap = new Map<String, Id>();
        for (ApexClass ac : [SELECT Id,Name,NamespacePrefix 
                             FROM ApexClass]){
            classMap.put(ac.Name, ac.Id);
        }
        return classMap;
    }

    global class Element {
        @AuraEnabled global String elementId;
        @AuraEnabled global String elementName;
        @AuraEnabled global String elementType;
        @AuraEnabled global String parentElementId;
        @AuraEnabled global List<DRInfo> elementDR;
        @AuraEnabled global String className;
        @AuraEnabled global String classId;
        @AuraEnabled global Boolean elementStatus;
    }
    
    global class DRInfo {
        @AuraEnabled global String fieldName;
        @AuraEnabled global String objectName;
    }
}