objects/WorkTeam__c.object
<CustomObject>
    <description>Custom Object used to store the work teams hierarchy used to handle the security at Business Process level.</description>
    <fields>
        <fullName>Parent_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field used to handle the hierarchy relationship between the Work Teams.</description>
        <label>Parent Team</label>
        <referenceTo>WorkTeam__c</referenceTo>
        <relationshipLabel>Child Work Teams</relationshipLabel>
        <relationshipName>Workplaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WorkteamLevel__c</fullName>
        <label>Workteam Level</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Team</label>
    <nameField>
        <label>Work Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateWorkTeamLevelsBatchable.cls
global class UpdateWorkTeamLevelsBatchable implements Database.Batchable<sObject> {
	
	String query = '[SELECT Id, Parent_Team__c, WorkTeamLevel__c  FROM WorkTeam__c WHERE Parent_Team__c = null]';
	Integer wtLevel = 1;

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Id, Parent_Team__c, WorkTeamLevel__c  FROM WorkTeam__c WHERE Parent_Team__c = null]);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<WorkTeam__c> lstTopParents = new List<WorkTeam__c>();
		Set<Id> lstTopParentsIds = new Set<Id>();
		
		//Level 1
        for (WorkTeam__c wt : (List<WorkTeam__c>) scope) 
        {
			wt.WorkTeamLevel__c = wtLevel;
			lstTopParents.add(wt); 
			lstTopParentsIds.add(wt.Id);              
        }

		update lstTopParents;

		setChildrensLevel(lstTopParentsIds, wtLevel);	
	}
	
	public void setChildrensLevel(Set<Id> lstTopParentsIds, Integer wtLevel){
		wtLevel  = wtLevel + 1;

		List<WorkTeam__c> lstChildrens = [SELECT Id, Parent_Team__c, WorkTeamLevel__c  
										  FROM WorkTeam__c 
										  WHERE Parent_Team__c IN :lstTopParentsIds];
		
		Set<Id> lstChildrensIds = new Set<Id>();

		for (WorkTeam__c wt : lstChildrens) 
        {
			wt.WorkTeamLevel__c = wtLevel;
			lstChildrensIds.add(wt.Id);              
        }

		update lstChildrens	;

		if(!lstChildrens.isEmpty()){
			setChildrensLevel(lstTopParentsIds, wtLevel);
		}
	}

	global void finish(Database.BatchableContext BC) {
		
	}	
}